### ISSUE TITLE
Modpack Loading Time

### ISSUE THREAD

**Issue by SebSub** [The-1-7-10-Pack/The-1.7.10-Pack#10]
This modpack takes at least 15 minutes for it to load and 5 minutes to join a server, I have Java 8 installed but it just takes forever to play this modpack,

**Comment by CKrisman** [comment]
When i started the pack it didnt start the game im using java 8 fyi

**Comment by BlackJackAres** [comment]
Whats your RAM? It's pretty irrelevant I am just asking out of curiosity at this point.

A simple solution (Generally) is to just go into %appdata% and completely uninstall .technic, or just uninstall the 1.7.10 entirely. Then download a fresh copy and try again to get it to load. If that doesn't work then you should just try re-installing a fresh version of the tekkit launcher. I recommend doing that first because it is super small and simpler to try than to delete the 1.7.10 pack twice and download it twice.

Also you might try running a check on Java 8 to make sure it installed properly and that it also uninstalled all the other versions of Java, which can sometimes cause issues in java related programs. 

You can do the java check here: https://www.java.com/en/download/installed.jsp

**Comment by SebSub** [comment]
Yeah I did all of that already and I did install java 8 correctly. Also I
have 4 gigs of RAM.

**Comment by BlackJackAres** [comment]
4 gigs you can dedicate to the game? Or 4 gigs total. If you only have 4 total and you can only dedicate 2-3 this might explain why the mod pack takes 3 times longer to load than is usual, and therefore can only really be fixed by upgrading the RAM in your personal laptop or PC, if at all possible.

**Comment by The-1-7-10-Pack** [comment]
Also, please provide the latest log so we can be sure.

**Comment by chrisps89** [comment]
My girlfriends cousin who plays with us only has 3GB dedicated to hers and doesn't have a great CPU either but she still loads in around 3 minutes so not sure RAM is the issue, could be CPU related, could be a faulty install without logs it's hard to tell.

**Comment by The-1-7-10-Pack** [comment]
If someone with the problem can give me his latest log it can really help.

**Comment by chrisps89** [comment]
It could be an idea to have a sticky type thread(if you can do them on github) called "How to report a Bug/Error", and tell people all the things they need to post if they want to get help quickly and effectively. Seems like a lot of people are going to have issues like this, which are likely not even to do with your pack but the install or computer, and if people drop their Java version, computer specs and RAM they are making available for Technic, we can obviously answer them straight away.

**Comment by The-1-7-10-Pack** [comment]
I wrote it on the README file, when you enter the GitHub page.

**Comment by chrisps89** [comment]
Ahh so you have, one problem with that, is your link from the technicpack website takes you straight to the issues page, so people won't even see it.

**Comment by The-1-7-10-Pack** [comment]
It's not a mistake. some people can have trouble getting into the issues section from there. there's nothing I can do about it.

**Comment by chrisps89** [comment]
I know it's not a mistake, it's just one of them unfortunate things, maybe you can link to the README on the technic pack post where you link to here and tell people to read that before posting about errors.

**Comment by Flukethoughts** [comment]
Closed due to missing Information please paste logs with your post thank you.

**Comment by The-1-7-10-Pack** [comment]
Please provide more information as I see it critical.
Latest log.

**Comment by BlackJackAres** [comment]
If you're having trouble finding .roaming then copy paste this

C:\Users\YOUR COMPUTER USER NAME HERE\AppData\Roaming.technic\modpacks\the-1710-pack\crash-reports

into your windows location bar, and switch out "YOUR COMPUTER USER NAME HERE" with your computer user name, which can be found by bringing up the task bar (windows XP, Vista, and 7) and looking in the top right of that, or bringing up the windows screen (Windows 8, 8.1) and looking in the top right.

Example of the folder logs are in:
![image](https://cloud.githubusercontent.com/assets/10352736/5595611/77bf5d76-922c-11e4-88bc-4e02fc3b3eae.png)

**Comment by Flukethoughts** [comment]
please post dxdiag for any loading issues thank you.

**Comment by The-1-7-10-Pack** [comment]
Information is missing.
If anyone has this bug, please provide your latest log.

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information, 7 days passed.
