### ISSUE TITLE
Mekanism: electrolytic separator energy usage issue

### ISSUE THREAD

**Issue by Ceruleann** [The-1-7-10-Pack/The-1.7.10-Pack#100]
Hello,

I noticed after playing in a new world that the electrolytic separator from Mekanism has a base usage that is ten times what it should be. It requires 1600 RF/t when it should be 160 RF/t. From the Mekanism wiki page I could see that it should require 400 J/t, the Joule being the Mekanism base power unit. It looks like that are some mishaps in the energy values conversions. Since it was working in my previous worlds with this modpack I wonder if something has changed recently.

I tried to play with the configuration file of Mekanism, Mekanism.cfg but had little luck of getting anywhere:

    # THIS DETERMINES ELECTROLYTIC SEPARATOR USAGE
    D:HydrogenEnergyDensity=2000.0
    D:JoulesToEU=10.0
    D:JoulesToMJ=25.0
    D:JoulesToRF=2.5
    B:LogPackets=false
    D:MJToJoules=0.04
    B:MachineEffects=true
    I:ObsidianTNTBlastRadius=12
    I:ObsidianTNTDelay=100
    I:OsmiumPerChunk=10
    D:RFToJoules=0.4

Changing "D:JoulesToRF=2.5" had no effect. Changing "D:RFToJoules=0.4" to D:RFToJoules=4.0" bumped the energy usage to 16000 RF/t (no good), and changing the value to 0.4 reduced it to 160 RF/t (thought I got it). Unfortunately I could not see any difference in the way the machine was pumping the energy from the energy cells. Also I could see that the generators such as the gas burning generator were producing ten times less energy as well. From 800 RF/t to 80 RF/t...

Thanks for looking into this.

Ceruleann.

PS: I love this modpack :).

**Comment by Flukethoughts** [comment]
Could simply be an issue with the mod itself have you reported this to the mod dev? Or checked to see if the mod devs ticket reporting system already has this report. Sometimes us coders forget to carry a zero other times we carry to many.

**Comment by The-1-7-10-Pack** [comment]
Should be reported to Mekanism, Nothing I can do about it.

**Comment by Ceruleann** [comment]
No worries, it's not a bug. I contacted the guys from the Mekanism mod. This energy usage is what they coded.

**Comment by Ceruleann** [comment]
I forgot to add that they mod owners told me that the follow config parameter could be changed to a value of 200 (10 times less) and that would change the electrolytic separator and the gas burner both usage / energy production by a 10 order : 
D:HydrogenEnergyDensity=2000.0

**Comment by T-Grave** [comment]
@The-1-7-10-Pack this is still an issue on a fresh install.

The `D:HydrogenEnergyDensity=2000.0` needs to be changed to `D:HydrogenEnergyDensity=200.0` as per instructed by the mod creator to have normal energy consumption rates.

**Comment by xJon** [comment]
@T-Grave Thank you for reporting. This has been fixed and pushed to v0.9.8d.
