### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by jeanropke** [The-1-7-10-Pack/The-1.7.10-Pack#105]
I'm having trouble using a world generated in update 0.6.9 in the update 0.7.0

Latest log:
http://paste.ubuntu.com/9862103/

- Thank you and sorry for my bad english.

**Comment by The-1-7-10-Pack** [comment]
That's very unfortunate. Please report this bug in the Tinkers' Constructs GitHub page: https://github.com/SlimeKnights/TinkersConstruct/issues
Update me here.

**Comment by jeanropke** [comment]
The modpack has auto backup, and I used a backup and it worked. Weird.

**Comment by The-1-7-10-Pack** [comment]
Indeed weird. Glad you found a fix for it!
