### ISSUE TITLE
Want to downgrade from 0.70 to 0.61

### ISSUE THREAD

**Issue by Thegremlin599** [The-1-7-10-Pack/The-1.7.10-Pack#107]
I accidentally updated my pack, and now it is not compatible with the my server.
I need to downgrade my pack, so is there somewhere still a download for 0.61?

**Comment by thebalck** [comment]
Update your server, the 0.7 is working fine in my server

**Comment by The-1-7-10-Pack** [comment]
Why would you want to play without the new HQM quests, with outdated mods, and bugs?
Just update your own server.
