### ISSUE TITLE
Block Breaker [1.7.10] Crash

### ISSUE THREAD

**Issue by Rc-Admin** [The-1-7-10-Pack/The-1.7.10-Pack#108]
Was setting up our new 1.7.10 server and while testing for by passable items we tried the Block Breaker, you add a block into the block breaker and it will destroy that block around it, what we didnt know is this permanently crashes your server we need a fix ASAP or everything we done was wasted

**Comment by Flukethoughts** [comment]
okay just a heads up if ur running the server yourself did u disable the mod it'self if u need a fix asap then this is your solution

**Comment by Rc-Admin** [comment]
I dont physcially run it i do in game staff, test by passes etc but i'll get them to remove the mod.

**Comment by Flukethoughts** [comment]
also now adays for fixes we need the owner to contact fluke via skype
not_just_a_fluke this is because he runs and maintains the dedicated server and can be of help to any server.

**Comment by Rc-Admin** [comment]
Okay thankyou for the response.

**Comment by The-1-7-10-Pack** [comment]
Block Breaker from which mod?
I need to confirm this first

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information.
