### ISSUE TITLE
Setting Up

### ISSUE THREAD

**Issue by CKrisman** [The-1-7-10-Pack/The-1.7.10-Pack#11]
When I start the the game it just refreshes the technic pack

**Comment by chrisps89** [comment]
How much RAM are you assigning to the Technic Launcher? And how much RAM do you have overall? You can check the Technic Launcher RAM by going into the Launcher Options in the top right if the Technic Launcher and going to the Java Options tab.

**Comment by BlackJackAres** [comment]
Additionally you might provide your version of Java.

**Comment by CKrisman** [comment]
The highest ram technic can go to for me it is 1 gb and 6gb installed ram in my pc

**Comment by The-1-7-10-Pack** [comment]
Please provide the latest.log file from .technic/modpacks/the-1710-pack/logs.

**Comment by chrisps89** [comment]
Are you running 64 or 32 bit windows?

**Comment by Shalashalska** [comment]
If technic only allows you to allocate 1GB, then you have 32 bit java installed. Install 64 bit java, then allocate 4-5 gigs.

**Comment by chrisps89** [comment]
He would need to have a 64 Bit Windows installed though, if he only has 32 Bit Windows then he cannot install 64 Bit Java.

**Comment by Flukethoughts** [comment]
This is an issue when 64bit java is not installed. If your computer isn't 64bit then I can only say wow. Thank you for your submission Closed due to no log posted.
