### ISSUE TITLE
Mod sugestion Remain in Motion

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#110]
This mod is awesome plz try to add it 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104611-1-7-10-remain-in-motion-continuation-of-redstone

PS:. You need to add  Planet Guy Lib too i think to make the Remanin in Motion to work

**Comment by ValentinoDante** [comment]
there is a mod i think you should try called rotorycraft

**Comment by The-1-7-10-Pack** [comment]
This is why we have Funky Locomotion that does the same thing! :)
