### ISSUE TITLE
Crashes when searching on creative mode

### ISSUE THREAD

**Issue by inilz** [The-1-7-10-Pack/The-1.7.10-Pack#111]
I'm noticing the client crashing when I try and search for items using the vanilla search.

http://paste.ubuntu.com/9875299/

**Comment by Flukethoughts** [comment]
noticed same issue i wonder what he did to break it i didn't have this issue till i reinstalled computercraft

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/112
