### ISSUE TITLE
Game crashes on creative search tab use

### ISSUE THREAD

**Issue by paytengames** [The-1-7-10-Pack/The-1.7.10-Pack#112]
**You need to use a paste-tool: http://paste.ubuntu.com/9878452**

**Comment by Flukethoughts** [comment]
hey make this on a paste tool or i will close the issue sorry follow rules or receive no help

**Comment by The-1-7-10-Pack** [comment]
I was not  able to reproduce this, what item did you searched? when did it happen exactly?

**Comment by thebalck** [comment]
This happens to me too when im in creative if i click in the compass in inventory the game crashes

**Comment by The-1-7-10-Pack** [comment]
Can you provide information about systems?

**Comment by paytengames** [comment]
Systems like my computer? If so then: http://puu.sh/f3lY7/e56dbc5c29.png

Otherwise I'm not sure what you're asking for. And it occurs whenever I either: click the search tab or the navigate to the 13th tab of mods in the creative inventory.

**Comment by Flukethoughts** [comment]
no it's the modpack. modpack wont let anyone use creative while on the server

**Comment by The-1-7-10-Pack** [comment]
It's not a critical bug, lol.
Anyway, please report this issue there: https://github.com/BuildCraft/BuildCraft/issues
I'm pretty sure it's because of buildcraft. Be sure to mention there that it's client side only, and give them the crash report.

**Comment by The-1-7-10-Pack** [comment]
I'll keep it open until I update the pack, so I'll remember.

**Comment by thebalck** [comment]
Men i dont know what happen but i can use the search tab now : D

**Comment by The-1-7-10-Pack** [comment]
Black magic?

**Comment by thebalck** [comment]
Maybe xD
