### ISSUE TITLE
Some type of launcher crash | Please Help

### ISSUE THREAD

**Issue by TickleMaPickl3** [The-1-7-10-Pack/The-1.7.10-Pack#115]
when i press play on the launcher it loads up here:http://gyazo.com/0357e21e8db141c2382adc3930648e2c and then goes back to the launcher like some type of crash, this is probably happening because i replaced my mods file with my friend one so i can play on his server (since its an earlier version). iv given it 5GB i got one type of java...
p.s. when i re install normally it works but i cant get on server coz i dont have the mods file.
but i dotn know what up with this.

**Comment by The-1-7-10-Pack** [comment]
I'm sorry but I can't give support for additional mods, as you can see there are a lot of open issues here. Just ask your friend to play the modpack without any additional mods.
