### ISSUE TITLE
server keeps timing out

### ISSUE THREAD

**Issue by boromin** [The-1-7-10-Pack/The-1.7.10-Pack#116]
when i join the server i get to play for about ten minuetes and then it times out and everyone gets this its not just me i asked people when i  re joined

**Comment by Flukethoughts** [comment]
your talking about the official server im guessing?

**Comment by boromin** [comment]
i think so yh

**Comment by boromin** [comment]
yh i am and this could do with fixing fast
#ASAP

**Comment by Flukethoughts** [comment]
okay you understand all the work put into the server correct and the server is about to be upgraded again. So I would suggest maybe understanding what I put my self through each day for the server before making any demands.

**Comment by The-1-7-10-Pack** [comment]
As Fluke said, the server is coming to an upgrade soon.
There's no need to #ASAP.

**Comment by boromin** [comment]
i didnt mean to offend you just said asap andmeant as soon as you get to
