### ISSUE TITLE
OpenGL error, wat?

### ISSUE THREAD

**Issue by ZeroX8** [The-1-7-10-Pack/The-1.7.10-Pack#117]
No crash log, just pops up with a OpenGL error and closes the game, I am using an nvidia gpu. the strange part is that i can run every other modpack except this one, but this one likes to randomly pop that up. and if you're wondering no, the GPU is NOT overclocked at all.

- Growlith1223

**Comment by ZeroX8** [comment]
Ok, there does seem to apparently be a "Crash log", but it just literally has the line:

Negative index in crash report handler(0/19)

**Comment by Flukethoughts** [comment]
is your computer plugged in? 


j/p double check your drivers and then make sure sli is disabled nvidia also make sure settings are change on the modpack through your nvidia settings

**Comment by ZeroX8** [comment]
Alright i have tested even further, it seems to only happen when i am in windowed full. sli is indeed disabled, settings are the same as i usually have it, as i have said it seems to only happen with this pack. i have also checked drivers

**Comment by The-1-7-10-Pack** [comment]
Do you have any additional mods?

**Comment by ZeroX8** [comment]
No  additional mods whatsoever, I downloaded it, and went straight to playing on a little server i am hosting. I have not tested to see if this happens on singleplayer however, i will try it out now and tell you if it does happen

**Comment by The-1-7-10-Pack** [comment]
Also provide the system information (OS etc).

**Comment by ZeroX8** [comment]
Alright im testing it now on singleplayer and nothing has happened so far, this is also being ran on Windows 8.1(was running it on win10 as well but it was doing the same thing lol)

Specs are:
I5 4690k overclocked to 4.7GHz
Zotac AMP! edition GTX 760
8GBs Crucial Ballistix sports 1366MHz ram

Hopefully that was what you were wanting? lol

**Comment by The-1-7-10-Pack** [comment]
Can you please post a picture of the error and also the full crash log? it won't harm anything, it can help.

**Comment by pgudge** [comment]
I also get this error regularly with Minecraft, both on FTB and Technic packs. I used to get Error 8, then from about Novemeber last year it upgraded to Error 9 :) and now its back to error 8.

![NVidia OpenGL Error 8](https://dl.dropboxusercontent.com/u/15633346/screenshots/NVidiaOpenGLErrorCode8.png)
 
I have toggle Advanced OpenGL, Fullscreen, windows, resource pack, no resource pack, nothing is consistent. This error about happened when I was in a ravine and a teleport creeper blew up and sent me to the surface, as the screen was wobbling it crashed.

![Another Error 1](https://dl.dropboxusercontent.com/u/15633346/screenshots/Capture-nvidia-too-many-errors.PNG)

Hope this helps.

/paul

**Comment by ZeroX8** [comment]
forgot about that, sorry lol

http://pastebin.com/iE5vTSaL

and the error is just nvidia saying that there was an openGL error and the program had to close because of it. now the game is trying to make me look like a fool and not produce the error again lol

**Comment by ZeroX8** [comment]
Alright, it seems to have happened again... lol

http://i.gyazo.com/e679f99a94bcb47f7584401015b549d1.png

I'm really not sure why this is happening. this is with a fresh install of the driver too btw.

**Comment by The-1-7-10-Pack** [comment]
Well this problem is relared to the driver of the GPU of course, you can try to reinstall it. Be sure to do it as you need, read some guides on the internet.

**Comment by Flukethoughts** [comment]
this is not a modpack issue but rather an issue with your pc thank you have a nice day.
