### ISSUE TITLE
[Mod Suggestion] InfusionCraft

### ISSUE THREAD

**Issue by James4007** [The-1-7-10-Pack/The-1.7.10-Pack#118]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294954-infusioncraft-v-2-45-combine-ingots
It is a very cool mod that allows you to infuse certain items into material to craft staffs and other awesome things. The crafting recipes are very balanced and it is a little magical. I tried it out before and it is very good.

**Comment by The-1-7-10-Pack** [comment]
I am sorry but the mod does not fit the modpack. Also adding new mods is a bit overkill at this point.
Anyway you're welcome to add it yourself manually, I just won't be able to give you support with it :)
