### ISSUE TITLE
Client disconnects from Cauldron server due to ColorChat

### ISSUE THREAD

**Issue by daytimepanther** [The-1-7-10-Pack/The-1.7.10-Pack#119]
I found an issue where the client disconnects from a server when you attempt to chat and ColorChat is installed on the server. In the client console it shows "java.io.ioexception: connection reset by peer" and in the server console "Internal Exception: java.lang.ArrayIndexOutOfBoundsException: -1". The server was running cauldron-1.7.10-1.1236.05.212. When the server is running Forge everything works fine so its more of a cauldron/ColorChat issue however, it is something to note incase someone wonders why they are disconnecting whenever they chat on their cauldron server. Removing ColorChat from the server mods fixes the issue.

**Comment by The-1-7-10-Pack** [comment]
I can't give support to Cauldron due to the simple fact that it does not update anymore.
Also the mod can be easily replaced by a plugin, I have it on the server files just because it's cool and people can't use plugins.
Good to know though, thank you for the report.

**Comment by LoseThePlot** [comment]
I had this issue as well. Removing colourchat solved. Try updating Cauldron to 1307 using mayanies emergency downloads...

**Comment by trismegistis** [comment]
Hi I have a modpack that doesnt use Colourchat... And this is cocuring. Help?

**Comment by daytimepanther** [comment]
This is not a help forum. You will not receive help for anything not related to the 1.7.10 pack. Try asking on the technic forums.
