### ISSUE TITLE
Can't go back to 0.6.0 :(

### ISSUE THREAD

**Issue by SMY12** [The-1-7-10-Pack/The-1.7.10-Pack#12]
Hey, sorry to bother you, but you requested to create an account on here to seek help.. so I did.
Anyways, my question is simply "How do I make my launcher back to 0.6.0" because I have a server with my friends which I really need to go on, and it won't let me log in with the newer version, and in the "modpack options" when choosing my selected version.. the old one isn't there...

-yours sincerely, SMY12

**Comment by The-1-7-10-Pack** [comment]
Good that you made an account.
Anyway I gave you an answer also in the platform:
"It won't destroy any save. updates are good. fixing bugs and adding new features. You just need to keep the "world" folder. switch all the other folders with the new ones.
Also make a backup to the server folder, so if you'll do any mistake you can try again."
