### ISSUE TITLE
Crash when loading world with pre made stuff in 

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#121]
hi all, 

i hope someone can help when i load up my world i am using for my series i get this error in the link, some says its galaticcraft some say its buildcraft if i start a new world it loads fine. i hope there is a fix since rebuilding everything for my series is going to take weeks 

http://pastebin.com/69bLqkNq

**Comment by The-1-7-10-Pack** [comment]
When did you last played the world and in what version did it brake?

**Comment by darktrek** [comment]
i last played the world on friday i updated to 0.7.0 on monday and everytime i try and load the world i get that error, i can start a new world no problem

**Comment by darktrek** [comment]
20 added mods i did try a clean install of 0.7.0 without my mods and i still got the error

**Comment by The-1-7-10-Pack** [comment]
Because you have the mods information in your world.
It is because some of your mods use an old BC APIs, with MJ power.
I'm sorry but there's nothing I can do about it, I can only recommend you trying to delete the ticking block entity with NBTExplorer. See some guides how on youtube.
