### ISSUE TITLE
'1.7.10 Pack' Modpack not launching.

### ISSUE THREAD

**Issue by PopeDarien** [The-1-7-10-Pack/The-1.7.10-Pack#123]
When I try to launch the 1.7.10 Pack Modpack the launcher will say it is starting and then the launcher closes for a second and then comes back. I have tried re-installing the Modpack, re-installing my Java, and even re-installing the launcher but nothing has worked!
 
I'm running on a Windows 7 32-bit Operating system with 4 GB of RAM and the only Java I have installed is Java 7 update 75.
and the Anti-virus I'm running is McAfee but I disabled it to run Technic.
 
Here is my log: http://pastebin.com/TKeyNRUQ
 
 
Thanks in advance for those who decide to help.   :)

**Comment by The-1-7-10-Pack** [comment]
I'm sorry but The 1.7.10 Pack does not support 32-bit Operating systems, due to the fact that they can allocate only up to 1GB of RAM.
