### ISSUE TITLE
Pack Failing to Launch

### ISSUE THREAD

**Issue by DuskWolfGH** [The-1-7-10-Pack/The-1.7.10-Pack#124]
This is a client issue, if you couldn't already tell.
Hello! Also, thanks for the help in advance!
I've been having issues regarding actually launching the pack. I've been searching over all of the old issue reports to see if I could fix the issue without having to create a report myself for assistance, but alas.
I have indeed reinstalled java 7 (update 75, I can't find 71 because they don't support it anymore) 64 and 32 bit multiple times, after removing 8... That didn't work. I also made sure that it was running the 64 bit, with 4 GB of memory. - http://imgur.com/7QzzvoW
I reinstalled the pack each time I reinstalled java. I even once completely deleted the launcher and tried again, that didn't work either.
Before installing this pack I was able to launch modpacks with MCForge (which I'm guessing is the cause of this along with Java) like TPPI (Test Pack Please Ignore) and now cannot. 
At that point in time I had Java 7 and Java 8 installed at the same time.

If you need any more information just ask, I've included some pastebins with the log reports, one from the actual Technic Launcher and one from the pack. 
(You will see my computer's name, please ignore it.)
There are also some images (screenshots) for proof of things.

(*Warning*) I only now just learned this myself, but if you just normally click on the links it will open in this tab, open in new tab to keep this page and view the links without using the back button... But I'm sure you already knew that, with you people using this to look at reports and such.

All Images Album for Issue Report on Imgur (Easiest to View All Images): http://imgur.com/a/ffbxb
Or if you want to see them all individually... 
Technic Launcher Java Settings: http://imgur.com/7QzzvoW
Technic Launcher Freezing (At Assets 0%) Image: http://imgur.com/t0wd0XT
System Specs: http://imgur.com/gm21SuA

Technic Launcher Logs Folder Image: http://imgur.com/1lHsEtZ
Latest Technic LAUNCHER Log from [CpuName]>AppData>Roaming>.technic>logs
http://pastebin.com/v92eD6rn

The 1.7.10 Pack Logs Folder Image: http://imgur.com/ygUi8GT
Latest Log from AppData>Roaming>.technic>modpacks>the-1710-pack>logs:
http://pastebin.com/GBANKKvD

Thanks for reading! I hope I/we can get this sorted out soon (possibly today even?)!
If I get this fixed before anyone responds, I'll close the thread.

**Comment by Flukethoughts** [comment]
Just want to go ahead and say thank you for doing all this

**Comment by Flukethoughts** [comment]
but jon will have to help you with it sorry i can't be of any help today

**Comment by DuskWolfGH** [comment]
You're welcome, I thought if I was going to report something, I may as well give you all the information I thought you guys might of needed. I even had to look up some things to just learn how to find some information too... Why report something if you don't give everything you possibly could about it? Again, thanks for at least looking at this, hopefully Jon will see this sometime soon.

(If you people want you can go and explore around a little on my Imgur, http://duskwolfir.imgur.com/all/ there are only I think three other photos that are not about this report and they're minecraft screenshots from...servers and places I've been. I've been thinking about adding more but time has escaped me with that.)

**Comment by The-1-7-10-Pack** [comment]
Corrupted files probably.
Instead of reinstalling the modpack through the launcher, completely delete "the-1710-pack" folder, and try to download & launch again.

**Comment by DuskWolfGH** [comment]
Just deleted the folder, starting re-download in just a moment, let's see how this goes!

**Comment by DuskWolfGH** [comment]
Nope, still doesn't work. Same issue.

**Comment by The-1-7-10-Pack** [comment]
Can you give me the new log from the latest try?

**Comment by DuskWolfGH** [comment]
I will as soon as I get the chance. (Which will be around 6pm CST)
I'll post both the pack's log and the launcher's.

**Comment by The-1-7-10-Pack** [comment]
Okay.

**Comment by DuskWolfGH** [comment]
I was not feeling well yesterday, when I get the chance then I'll post them, be that today or in three. I hate flu season and allergies.

**Comment by DuskWolfGH** [comment]
Alright then, here are the logs from the attempt a few days ago, note that I've not tried it again since.
Launcher Log: http://pastebin.com/jq6Y8e4M

Pack Log: http://pastebin.com/KsDN7gUv

**Comment by DuskWolfGH** [comment]
I'm also going to re-install Java 8 as with seeing how many things require it, and considering that it *shouldn't* conflict with the pack because I can set what version of Java is run in the Java args..

**Comment by The-1-7-10-Pack** [comment]
Never saw such error, you're challenging me.
Anyway, the logs you provide are good information.
This error shows about corrupted jar files. You told me you deleted the whole modpack folder and downloaded it again, and it didn't help. Where is the .technic folder located on your computer?

**Comment by DuskWolfGH** [comment]
The .technic folder is in the same place the .minecraft is. (Of course it isn't in .minecraft though.)
The folder is located in AppData>Roaming aka in the run window, %appdata%.

**Comment by The-1-7-10-Pack** [comment]
"java.util.zip.ZipException: invalid LOC header (bad signature)"
What the actual fuck.
I'll give you direct link download and you try to install the modpack yourself. Tell me if it works.
http://1drv.ms/1D1F8MS

**Comment by DuskWolfGH** [comment]
Guessing that I just need to replace the folder with that file... right?
Downloading the pack right now, I'll tell you how it goes unless I have no idea what to do.

**Comment by The-1-7-10-Pack** [comment]
Replace the inside of the "the-1710-pack" solder with the direct download

**Comment by DuskWolfGH** [comment]
Well, I did that. And guess what.
Nope! Still failed, then I updated it and it failed as well.
Assembling all of the logs... (What the heck is going on here?)

**Comment by DuskWolfGH** [comment]
Here are the logs.
Pack Logs:
Before Direct Download (I believe you've already seen this one): http://pastebin.com/wGXt8m5G
Direct Download You Sent: http://pastebin.com/dADNVZZA
Direct Download + Update: http://pastebin.com/jaGGWD2b

Launcher:
Yesterday's Log: http://pastebin.com/BrCq6FQ9
Today's Log: http://pastebin.com/3Pz24kwH

Fun, right?

**Comment by DuskWolfGH** [comment]
Fun, right? I'm not sure how to separate the launcher logs by per attempted launch, it looks like they are given per day. I just hope I we/you can fix this and I can play.

Want to hear some other great news?
A friend says he's having issues too. (He says its the same issue, but I've never told him the details of mine so I just hope he'll make an error report too. There is no way he could tell it was the same issue when he never learned mine.)
We both initially downloaded this pack on the same day, after downloading the Tolkincraft one.
(Can modpacks interfere with each other? I remember SacredLabyrinth didn't get along with another... I forget what it was.)

**Comment by The-1-7-10-Pack** [comment]
It's all the same error: *"java.util.zip.ZipException: invalid LOC header (bad signature)"*

**Comment by DuskWolfGH** [comment]
I'm not really sure what to do...
Back to binge watching InuYasha I guess for now.

**Comment by DuskWolfGH** [comment]
I'm not really sure what to do...
Back to binge watching InuYasha I guess for now.

**Comment by The-1-7-10-Pack** [comment]
Try to delete all 6 parts of the ProjectRed mod and also the MrTJPCore mod

**Comment by DuskWolfGH** [comment]
I will when I get the chance.
I have to leave for a while, as soon as I get back I shall.

**Comment by DuskWolfGH** [comment]
I will when I get the chance.
I have to leave for a while, as soon as I get back I shall.

**Comment by DuskWolfGH** [comment]
Deleted all six parts of ProjectRed, I cannot find MrTJPCore.
Testing to see if it will run.

**Comment by The-1-7-10-Pack** [comment]
MrTJPCore is located in mods/1.7.10 folder

**Comment by The-1-7-10-Pack** [comment]
Closing it due to inactivity.
