### ISSUE TITLE
(Bug Report) Lush River Biome in Nether

### ISSUE THREAD

**Issue by walrusgumbo** [The-1-7-10-Pack/The-1.7.10-Pack#125]
The Lush River Biome spawns in the Nether, I'm not sure why.

On the side: it is virtually impossible to find jungle and snow biomes. In previous versions of Biome's O'Plenty, there was biome essence, usable with a biome radar to find a biome, is this just not in this version?

**Comment by The-1-7-10-Pack** [comment]
About the world gen: can you provide a picture?
About the biome essence, read there: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1409854-biomes-o-plenty-biome-essence?comment=5

**Comment by walrusgumbo** [comment]
![2015-01-28_12 46 11](https://cloud.githubusercontent.com/assets/10465957/5943283/a6c16ba4-a6eb-11e4-88c8-e485adaab461.png)

**Comment by The-1-7-10-Pack** [comment]
Lush River should generate only in the overworld. Nothing I can do about this bug unfortunately.
Should be reported there: https://github.com/Glitchfiend/BiomesOPlenty/issues
