### ISSUE TITLE
Auto Workbench (BC Factory) seams to be broken

### ISSUE THREAD

**Issue by Snarvitlaus** [The-1-7-10-Pack/The-1.7.10-Pack#126]
So i have a few of em making compressed cobblestone and the first compression is fine (i use hoppers), is when i try to compress em further that things start to brake(double) . They seam to just gather up in the inventory and they don't start building even if all slots are full, i need to manualy pick em up and drop em back in for it to start its progress. Same thing happens on the next level (triple compressed).

**Comment by The-1-7-10-Pack** [comment]
You need a pipe, you can't use a hopper, it's not vanilla minecraft!

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information.
