### ISSUE TITLE
Fatally Missing Blocks and Textures

### ISSUE THREAD

**Issue by MarrTiin** [The-1-7-10-Pack/The-1.7.10-Pack#127]
So, I went on the pack to make a server, the pack and server are both up to date, however; when I try to test log in to the server, it kicks me out, and says that I am fatally missing blocks and textures. Not sure what I did wrong, just ran the server, both of them are in the same update, and it kicks me out. 

Please write me back

**Comment by The-1-7-10-Pack** [comment]
Did you read how to report a bug? I guess not.
Please read how there: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md

**Comment by MarrTiin** [comment]
Not sure if you were being a dick, and being sarcastic. I did read it, but
I felt putting it on the bug area, someone who had the same problem might
be able to help me...

**Comment by The-1-7-10-Pack** [comment]
Why would you use such language to someone who tries to help you? deleted the comment.
Anyway, one of your server files probably got deleted, maybe through the update.
Keep your world and redownload the server files, then try again. Everything should work.

**Comment by MarrTiin** [comment]
:/ It sort of sounded like you were treating me like an infant, hard to detect sarcasm over the internet...

**Comment by Flukethoughts** [comment]
ok listen this is what u can do do save ur world reupload the modpack

**Comment by The-1-7-10-Pack** [comment]
Did you manage to fix your problem?

**Comment by MarrTiin** [comment]
Umm yes, I did. I tried to delete the chisel blocks because of interference
and somewhere along the lines it corrupted. So i redownloaded the pack and
now it works. Thanks :p
