### ISSUE TITLE
Server crash when launch

### ISSUE THREAD

**Issue by Liverkiller14** [The-1-7-10-Pack/The-1.7.10-Pack#13]
Anytime i try launch my server for my friends to play on it crashes (Im using 0.6.1)

**Comment by The-1-7-10-Pack** [comment]
It started since the update?
Please provide a crash report and more information.
Post the crash report link through http://pastebin.com

**Comment by chrisps89** [comment]
I'm having the same issue launching the 0.6.1 server. Was fine yesterday on the 0.6.0.

http://pastebin.com/81541w25

**Comment by Liverkiller14** [comment]
I fixed mine try setting the EULA.txt to true then restart it 2 times should fix it

**Comment by The-1-7-10-Pack** [comment]
Good. for @chrisps89, open a new issue for you.
Also what did you provide isn't a crash report, so notice that.

**Comment by chrisps89** [comment]
What's the directory for the crash logs?

**Comment by The-1-7-10-Pack** [comment]
it's called "crash-reports".

**Comment by chrisps89** [comment]
I don't have such a folder, but I managed to sort out my problem anyway, so I never bothered making a new issue.
