### ISSUE TITLE
Server's down?

### ISSUE THREAD

**Issue by boromin** [The-1-7-10-Pack/The-1.7.10-Pack#130]
i waited over 60 mins and the sever is still down pls can you look in to this

**Comment by boromin** [comment]
pls can this get fixed soon i want to play on the server cos its great

**Comment by The-1-7-10-Pack** [comment]
You should read news: http://magitechworld.com/?p=53
But it's just came back online. What are you waiting for and reading this text? go play!

**Comment by boromin** [comment]
its not up

**Comment by The-1-7-10-Pack** [comment]
Okay. well anyway it should be up soon.

**Comment by Flukethoughts** [comment]
anytime the server is down don't post here look at the website it tells u everything
