### ISSUE TITLE
Game crash at launch

### ISSUE THREAD

**Issue by Goqedu** [The-1-7-10-Pack/The-1.7.10-Pack#131]
Hello, i post my problem, because i want badly play with this mod.

PC:

Windows 7 x64
Java 7 71 64 bits
8Go RAM

Technic launcher:

Already tried to reinstall the modpack (i deleted all the directory)
Already tried to reinstall technic launcher (With registry cleaning)
Already tried to allocate 4gb+ RAM

My log file: 

http://pastebin.com/GyCgG8yX

I noticed the "Picked up _JAVA_OPTIONS: -Xmx512M", i tried this fix: http://forums.technicpack.net/topic/70759-cannot-allocate-more-ram-to-minecraft/?p=531689
But it don't work...

If you have any ideas, i thanks you !

**Comment by The-1-7-10-Pack** [comment]
What version of Java do you have installed on your computer?

**Comment by Goqedu** [comment]
Its ok, i deleted the _JAVA_OPTIONS: -Xmx512M and did REBOOT, and it worked, for the peoples who have the same problem, don't forget to delete two times the _JAVA_OPTIONS and reboot the computer ! You can close the thread

**Comment by The-1-7-10-Pack** [comment]
So basically your computer had already Java settings that blocked the amount of RAM the modpack needed. Good to know.

**Comment by Asmodeus95** [comment]
Where is the _JAVA_OPTIONS: -Xmx512M found? i have the same problem

**Comment by The-1-7-10-Pack** [comment]
@Asmodeus95: http://www.reddit.com/r/Minecraft/comments/2iqoqj/ram_wont_properly_allocate_anymore_help/cl4mc5x
