### ISSUE TITLE
Server update from 0.6.1 to 0.7.0

### ISSUE THREAD

**Issue by jacesilverleaf** [The-1-7-10-Pack/The-1.7.10-Pack#132]
Greetings,
I have been browsing the site here trying to find someone else who has had the same problem, but haven't quite seen it.
I recently downloaded the new 0.7.0 server, and attempted to update my server with it, and now it refuses to boot. It appears to be missing mods, but the console complains of other issues as well, such as how the world was made with different versions of the mod.
I am currently in the process of uploading the mods that seem to be missing (QuarryPlus and Equivalent Exchange), but are they supposed to be missing?
If not, then perhaps I should re-download the server pack and reupload it. But as it stands, my server won't boot, so I want to see if I am the only person experiencing these issues.
I deleted all the old files other than my world folder, uploaded the new server files, and started it, but it won't boot up completely. I want to ensure that uploading these mods that appear to be removed won't cause a problem with the mod pack.
Thank you for your time, and I apologize if I have posted incorrectly.

**Comment by jacesilverleaf** [comment]
To add more:   adding equivalent exchange and quarryplus back into the mods allowed the server to boot, although I had to enter '/fml confirm' into the server console to allow it to continue booting.
I have also successfully logged into the server, although we'll have to see if adding in the mods that were removed will cause any problems.
I am attempting to remove the few equivalent exchange items that were made to play around with to see if I can remove the mod or not, but I know there were not any quarryplus items ever created, so I am confused as to why the booting process complained of missing information from that mod after I updated.
Thank you again for your time.

**Comment by The-1-7-10-Pack** [comment]
You probably just missed something with the files. Delete everything except your world and use a fresh server files.

**Comment by jacesilverleaf** [comment]
I mentioned in my original post that I deleted all the old files except for the world folder.
I believe the problem with EE3 was due to there being existing EE3 items in our base, but the QuarryPlus problem has me vexed.

**Comment by jacesilverleaf** [comment]
I removed the EE3 items, but it is still giving me the same issue - it will just hang after spitting this out rather than exiting or stopping or restarting the server - I've waitied up to 15 minutes for it to move on:
30.01 00:29:20 [Server] ic2-poolthread-1/INFO [IC2]: UU graph built with 10084 nodes after 35157 ms.
30.01 00:29:20 [Multicraft] Skipped 45 lines due to rate limit (100/s)
30.01 00:29:14 [Server] INFO EE3:alchemicalChest
30.01 00:29:14 [Server] INFO EE3:researchStation
30.01 00:29:14 [Server] INFO EE3:chalkBlock
30.01 00:29:14 [Server] INFO EE3:aludel
30.01 00:29:14 [Server] INFO EE3:dummyArray
30.01 00:29:14 [Server] INFO Missing Blocks/Items:
30.01 00:29:14 [Server] INFO A world backup will be automatically created in your saves directory.
30.01 00:29:14 [Server] INFO If you continue the missing blocks/items will get removed.
30.01 00:29:14 [Server] Server thread/WARN [FML]: Forge Mod Loader detected missing blocks/items.
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: RefinedRelocation:sortingAlchemicalChest, id 2143
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: RefinedRelocation:sortingAlchemicalChest, id 2143
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:shearsDarkMatter, id 5230
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:chalkBlock, id 1402
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:guide, id 5221
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemicalDust, id 5211
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:bowDarkMatter, id 5231
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:arrowDarkMatter, id 5232
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:dummyArray, id 1395
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:stonePhilosophers, id 5216
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:augmentationTable, id 1400
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemicalFuelBlock, id 1403
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:hammerDarkMatter, id 5226
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:fishingRodDarkMatter, id 5229
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:swordDarkMatter, id 5233
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemicalUpgrade, id 5218
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:chalk, id 5217
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:stoneMinium, id 5215
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:shardMinium, id 5214
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:axeDarkMatter, id 5227
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:stoneInert, id 5213
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:pickAxeDarkMatter, id 5225
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemyArray, id 1404
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:hoeDarkMatter, id 5228
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:diviningRod, id 5219
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:matter, id 5222
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemicalFuel, id 5212
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemicalChest, id 1401
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:calcinator, id 1396
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:shovelDarkMatter, id 5224
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemicalBag, id 5210
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:researchStation, id 1399
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:alchemicalTome, id 5220
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:gem, id 5223
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:aludel, id 1397
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified item: EE3:glassBell, id 1398
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:alchemicalFuelBlock, id 1403
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:augmentationTable, id 1400
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:calcinator, id 1396
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:glassBell, id 1398
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:alchemyArray, id 1404
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:alchemicalChest, id 1401
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:researchStation, id 1399
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:chalkBlock, id 1402
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:aludel, id 1397
30.01 00:29:14 [Server] Server thread/ERROR [FML]: Unidentified block: EE3:dummyArray, id 1395
30.01 00:29:14 [Server] Server thread/ERROR [FML]: There are unidentified mappings in this world - we are going to attempt to process anyway
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:shearsDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:chalkBlock
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:guide
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalDust
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:bowDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:arrowDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:dummyArray
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:stonePhilosophers
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:augmentationTable
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalFuelBlock
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:hammerDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:fishingRodDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:swordDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalUpgrade
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world RefinedRelocation:sortingAlchemicalChest
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:chalk
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:stoneMinium
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:shardMinium
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:axeDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:stoneInert
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:pickAxeDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemyArray
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:hoeDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:diviningRod
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:matter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalFuel
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalChest
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:calcinator
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:shovelDarkMatter
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalBag
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:researchStation
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalTome
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:gem
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:aludel
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:glassBell
30.01 00:29:14 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalFuelBlock
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:augmentationTable
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:calcinator
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:glassBell
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemyArray
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:alchemicalChest
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:researchStation
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world RefinedRelocation:sortingAlchemicalChest
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:chalkBlock
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:aludel
30.01 00:29:13 [Server] Server thread/INFO [FML]: Found a missing id from the world EE3:dummyArray
30.01 00:29:13 [Server] Server thread/INFO [FML]: Injecting existing block and item data into this server instance
30.01 00:29:13 [Server] Server thread/ERROR [fml.ModTracker]: This world was saved with mod EE3 which appears to be missing, things may not work well
30.01 00:29:13 [Server] Server thread/INFO Preparing level "world"

**Comment by jacesilverleaf** [comment]
Okay, so apparently I needed to '/fml confirm' on those hangups, but the console wasn't stating that (apparently in the skipped lines).
Did anybody else have to do this when they updated from 0.6.1 to 0.7.0?

**Comment by Flukethoughts** [comment]
lmfao yes but i now auto do it

**Comment by The-1-7-10-Pack** [comment]
Probably you didn't update the launch file, it should do it automatically. :)
