### ISSUE TITLE
Mod Request - Resonant Induction and Electrodynamics

### ISSUE THREAD

**Issue by dedbbs1** [The-1-7-10-Pack/The-1.7.10-Pack#134]
I'm not sure if these are in the process of unifying into one mod or not, but from what I read they seem to be, hence why they're being requested together. I already know there are ways to make massive amounts of power but I think this would be fun for those of us who are power mad and like generating massive amounts of power. 

Just a request, thought it would be fun both as a server owner and a player! Either way, thanks for putting together this great modpack, my users and I all thank you for the great work you've put into getting everything running smoothly together!

**Comment by The-1-7-10-Pack** [comment]
Uh huh.
![image](https://cloud.githubusercontent.com/assets/10350644/5975880/9db508cc-a88f-11e4-8f70-3c449be3d06b.png)
![image](https://cloud.githubusercontent.com/assets/10350644/5975882/9fbf014a-a88f-11e4-8271-6f312d7eb749.png)
![image](https://cloud.githubusercontent.com/assets/10350644/5975883/a1a65de6-a88f-11e4-877a-d6fa0a55b3d8.png)

**Comment by The-1-7-10-Pack** [comment]
Both mods are really cool, but most of the stuff they are able to to, other mods can do.
I'll keep it open for now to see more comments :)

**Comment by The-1-7-10-Pack** [comment]
Well thanks anyway

**Comment by da404lewzer** [comment]
I for one welcome our multi-mod overlords. I thinking having multiple mods that do the same thing is actually really liberating. I am constantly experimenting with various machines and depending on the situation I have different machines processing different items. It's easy to connect one mod to itself, but to 4 others? Challenge Accepted! Lag is my only concern because the second we get these giant windmill things everyone will make 10 of them :P

**Comment by The-1-7-10-Pack** [comment]
You answered your own question: also woth to note that making a lot of power in a cool way can be already made with more than one mod through the modpack

**Comment by da404lewzer** [comment]
I'm interested in more machines, power is not a problem in this pack and I set out to prove it...

Last night I started building a 32x32x48 BigReactor in survival. I currently have it 32x32x5 and it outputs 130KiRF/t and can replenish 10M RF in about 20 seconds. How much more power does one need? lol

WIP: http://imgur.com/a/90aJg
