### ISSUE TITLE
Mod Suggestion Zelda Sword Skills

### ISSUE THREAD

**Issue by ssjyasai** [The-1-7-10-Pack/The-1.7.10-Pack#136]
Not sure how Practical it would be to add it in but would love to see it if possible

It would definitly fit in great with more focus on sword abilities and fantasy aspects of Zelda

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293190-zelda-sword-skills-1-7-10-v0-2-1-updated-1-19-2015

**Comment by The-1-7-10-Pack** [comment]
With so much tools in the modpack, adding more is just ridicules. Thank you anyway.
