### ISSUE TITLE
Mekanism Universal Cables Don't Seem to Work Properly

### ISSUE THREAD

**Issue by dedbbs1** [The-1-7-10-Pack/The-1.7.10-Pack#138]
We've been having an issue on our server (stock settings, stock server, a few clients with optifine but otherwise stock clients) where Mekanism Universal Cables basically do not transfer power except with other Mekanism blocks. IE, a Mekanism Windmill will connect and power a Mekanism Digital Miner, but whereas before these cables would transfer power between IC2 and ThermalExpansion/RF/Buildcraft powered blocks/engines/storage devices seamlessly, they've become apparently worthless for that purpose.

**Comment by The-1-7-10-Pack** [comment]
Uh huh.
![image](https://cloud.githubusercontent.com/assets/10350644/5975880/9db508cc-a88f-11e4-8f70-3c449be3d06b.png)
![image](https://cloud.githubusercontent.com/assets/10350644/5975882/9fbf014a-a88f-11e4-8271-6f312d7eb749.png)
![image](https://cloud.githubusercontent.com/assets/10350644/5975883/a1a65de6-a88f-11e4-877a-d6fa0a55b3d8.png)

**Comment by Flukethoughts** [comment]
Cant reproduce either closing

**Comment by Wharblar** [comment]
I'm having this same issue. Can't connect an MV-transformer to a quarry with a universal cable. The connection is there, the MV-Transformer has power, but the Quarry isn't running.

**Comment by xJon** [comment]
@Wharblar Can you manage to reproduce the issue in a different world?
