### ISSUE TITLE
Witchery Quest Bugged?

### ISSUE THREAD

**Issue by poetofsilence** [The-1-7-10-Pack/The-1.7.10-Pack#139]
Hey guys. I have been working through the quests and the Witchery quest wont acknowledge that I have a witches hand in my inventory. The book says I only need one, but for some reason its not accepting it. Any ideas?

**Comment by The-1-7-10-Pack** [comment]
This is a crafting task, and can't craft the hand - you find it.
Thanks for the report :)

**Comment by poetofsilence** [comment]
:)
