### ISSUE TITLE
Additional mods

### ISSUE THREAD

**Issue by Davografie** [The-1-7-10-Pack/The-1.7.10-Pack#140]
Hi,

Ethos has really attracted me to play Minecraft again and then with mods. There are a few mods he's used in his series I would really like to use. Would you suggest me to put the mods in the mod-folder myself (and would this be challenging?) or would you rather check them out and see if they can get a spot in the 1.7.10-pack? Up until now the main mods I'm interested in are:
AppleCore - API for hunger
Hunger overhaul - Extensive tweaks to hunger and related mechanics (uses AppleCore)
The Spice of Life - Encourages dietary variety through diminishing returns (uses AppleCore)
Archimedes' Ships - features self-designed ships that can actually sail the seven seas
Custom NPCs - create NPCs and change their health/strenght/weapons/skin and AI
Mariculture - improves oceans and rivers in minecraft beyond their usual bland selves
DrZhark's MoCreatures - adds more creatures to the game
Random Things - a compilation of different blocks and items

So the question really is: is it easy to implement these mods as an extra on top of your modpack or would you be willing to include them in the modpack?

Hope to hear from you soon,

Dave

**Comment by The-1-7-10-Pack** [comment]
Worth to note that I do watch Etho's let's play myself, I know the mods that he play with.
- Hunger overhaul & The Spice of Life: As optional mods are not a thing in the Technic Platform, and a lot of people does not like this system, I didn't add them both.
- Archimedes' Ships: This mod is not so big and it may be fun for a while but with Space Ships, Planes and FunkyLocomotion to move stuff this is just not needed.
- Custom NPCs: People can abuse this mod too easily. Still a very cool MC mod and I'd recommend people to add it themselfs manually.
- DrZhark's MoCreatures: Permissions blocked to all public modpacks.
- Random Things: Most of the features included in this mod are already given by other mods.
Thanks anyway for the suggestions!

**Comment by Trahloc** [comment]
One advantage of Archimedes' Ships mod that might not be obvious at first glance is it lets you build mobile bases.  Me and a buddy would use it to create flying quarries and flying storage organizers which was very handy.
