### ISSUE TITLE
Mod Suggestion - Ars Magica 2

### ISSUE THREAD

**Issue by Slushyz2237** [The-1-7-10-Pack/The-1.7.10-Pack#142]
I think adding Ars Magica 2 would be great for the magic aspect of this modpack.

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/73
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/59
