### ISSUE TITLE
Mod Suggestion - Thaumcraft addons (read comment)

### ISSUE THREAD

**Issue by bLANKMOD** [The-1-7-10-Pack/The-1.7.10-Pack#143]
I would love to be a master thaumaturge, and your mod pack is the best place for that to happen, so could you add:
-Advanced Thaumaturgy
-Forbidden Magic
-Thaumic Exploration
-Thaumcraft Extras
-Thaumic Tinkering
-Electro-Magic Tools
-Magistics
-Thaumic Warden
-Thaumic Darkness
-Thaumic Infusion
-Automagy
-And maybe keep an eye out for future addons to add???
here's a link to help you out: http://thaumcraft-4.wikia.com/wiki/Add-ons
![image](https://cloud.githubusercontent.com/assets/10787409/5988745/ac61e104-a93b-11e4-9913-be5af83a57dd.png)
![image](https://cloud.githubusercontent.com/assets/10787409/5988748/b4a55bac-a93b-11e4-80da-f2d57eb9964e.png)
![image](https://cloud.githubusercontent.com/assets/10787409/5988751/c07c028c-a93b-11e4-99c2-94bb3025fc00.png)
![image](https://cloud.githubusercontent.com/assets/10787409/5988754/ca189e4a-a93b-11e4-9d21-e3202b2b4dc3.png)
![image](https://cloud.githubusercontent.com/assets/10787409/5988755/cecd2776-a93b-11e4-8897-44187f1d88b0.png)

**Comment by The-1-7-10-Pack** [comment]
Thaumic Exploration is already in the pack.
Anyway, all of those addons are cool and everything, but not so stable and the modpack doesn't focus only in Thaumcraft & Magic. Feel free to add them yourself manually though, thanks anyway.
