### ISSUE TITLE
HQM Tutorial Quests - Botania Mod n' more

### ISSUE THREAD

**Issue by Mythalinear** [The-1-7-10-Pack/The-1.7.10-Pack#144]
I created a line of tutorial quests for the Botanica Mod so that players unfamiliar with the system can get acquainted with it. The first ones are very basic and I tried to keep the rewards small until larger quests at the end.

I'm not sure how to attach zip files in Github, so here's a link to the zip from dropbox
https://www.dropbox.com/s/8jumhc4mg94t8vp/hqm.zip?dl=0

![botania quests 3](https://cloud.githubusercontent.com/assets/10788511/5989185/6dd2800c-a944-11e4-929f-6662869dd33c.png)
![botania quests 1](https://cloud.githubusercontent.com/assets/10788511/5989186/6dd65998-a944-11e4-9580-c65c801f2ca7.png)
![botania quests 2](https://cloud.githubusercontent.com/assets/10788511/5989187/6dd90d0a-a944-11e4-96e5-cdd5d230daad.png)

**Comment by The-1-7-10-Pack** [comment]
Very cool! What do you think guys?

**Comment by darktrek** [comment]
seems cool ive reading wiki about this mod trying to get a head on it a set of quests would be great :)

**Comment by poetofsilence** [comment]
Botania quests would be great.

**Comment by The-1-7-10-Pack** [comment]
My only problem with this is the fact that it doesn't fit the rest of the quests.
They focus high-end stuff, this is a set of quests focusing on one mod.
What do you think? @Mythalinear

**Comment by Mythalinear** [comment]
I think it would be fantastic if we had both types of quests. Maybe the 'mod specific' quest chains can have a special designation to separate them from the other quests. Maybe something like this:

1. Becoming a Geek!
2. Are you a Wizard?
3. Adventures of Columbus
4. NPC Village of AWESOME
5. [Tutorials: Botania]
6. [Tutorials: BuildCraft]
7. [Tutorials: Witchery]
Etc.

I think it would be awesome if other community members were able to create and submit quest chains for review as well.

**Comment by The-1-7-10-Pack** [comment]
I won't add it next patch but if you would be able to create a set of quests that make sense it'll be wonderful.
Maybe you can add some order to them and use help the of the community.
I'm leaving this one open as the projectHQM

**Comment by Mythalinear** [comment]
I'm not sure I understand what you are saying.

Are you saying that I should proceed with making more Tutorial Quests?

What sort of order should I add to them?

**Comment by The-1-7-10-Pack** [comment]
I'm saying that having 3 sets of quests that focus on high-end stuff and one that focus a specific mod does not make sense. If you can think about how it can make sense, it would be wonderful :)

**Comment by Mythalinear** [comment]
Would 3 sets of quests that focus on high-end stuff and 3 that focus on teaching the basics of 3 different mods make sense?

**Comment by The-1-7-10-Pack** [comment]
It's a problem with The 1.7.10 Pack as it doesn't focus any specific way to play.

**Comment by Mythalinear** [comment]
Well I don't know how I can make tutorial quest chains make sense then. The purpose of a tutorial is to teach new players how to do something specific (in this case it was the Botania system). My idea was to make lots of tutorials, each for specific mods. 1 tutorial quest chain for Botania, 1 for IC2 + BuildCraft, 1 for Steve's Carts, 1 for Thaumcraft, 1 for Archimedes Ships, and so on. I need to know if this makes sense because I don't want to spend weeks building quests that don't fit within your vision of how the pack is supposed to work.

**Comment by The-1-7-10-Pack** [comment]
That's understandable.
For now I'll have to say no: The quests idea was supposed to be optional fun rewards to be aware to all the cool high-end stuff that the mods provide within the modpack. Tutorials are really cool for new players but they doesn't fit it. It can be optional in a separate download maybe.

**Comment by Mythalinear** [comment]
If you wanted to offer it as an optional separate download on the 1.7.10 pack site then I would continue making tutorials.

**Comment by Mythalinear** [comment]
I could also just make a separate website for you to link to, that way you won't need to update the download as I build.

**Comment by The-1-7-10-Pack** [comment]
Yes this is an awesome idea. I can put in the description the link to the "bonus tutorial quests file", that will link to a seperate website. You can include there download links and how to install.

**Comment by xJon** [comment]
Now that you can export quests into `.json` files, I'd look how can we implement your effort. Thanks.
