### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Ninja1951** [The-1-7-10-Pack/The-1.7.10-Pack#145]
Whenever I try to launch the game it gets to initializing and crashes. It is a client side crash and I am running the latest version of the modpack and have java 8
http://paste.ubuntu.com/9982493/

**Comment by The-1-7-10-Pack** [comment]
First time you installed the modpack?

**Comment by Ninja1951** [comment]
No, I have installed it once before and it worked, but when I tried to reopen it it crashed.

**Comment by The-1-7-10-Pack** [comment]
Please go to the folder you got the pack installed on, configs, and delete "ChickenChunks.cfg"

**Comment by Ninja1951** [comment]
I did that and it crashed again. Here is the crash report http://paste.ubuntu.com/9982999/

**Comment by Ninja1951** [comment]
I tired launching it again and it worked. Then I closed out of it and tried it again and it crashed again.

**Comment by Ninja1951** [comment]
Okay, so got it to launch every so often but when I try to start a world it gives me a server crash instead of client. Here is the crash http://paste.ubuntu.com/9983415/

**Comment by The-1-7-10-Pack** [comment]
So try to delete this config now: "C:\Users\User\Desktop\tekkit\saves\New World\NEI\server.cfg"
Anyway it's not a problem with the modpack itself, just some computer weirdness, closing this one.
