### ISSUE TITLE
Four Hearts...

### ISSUE THREAD

**Issue by poetofsilence** [The-1-7-10-Pack/The-1.7.10-Pack#146]
Any idea when I loaded my game up this morning I only had 4 hearts of health instead of the ten. I am not in morph, and have nothing in my inventory. 

![2015-01-31_15 19 22](https://cloud.githubusercontent.com/assets/10660522/5989882/b8947dc6-a95c-11e4-8d10-3b259eecc43f.png)

![2015-01-31_15 19 06](https://cloud.githubusercontent.com/assets/10660522/5989885/bf9ac9d6-a95c-11e4-8490-2b90a12e0911.png)

**Comment by Flukethoughts** [comment]
No telling with so many different mods it could be a wide range of things.

**Comment by The-1-7-10-Pack** [comment]
Just try to die and respawn, this is an old Morph bug
