### ISSUE TITLE
[Mod Suggestion] Dungeon Pack /or/ Doomlike Dungeons

### ISSUE THREAD

**Issue by Spellkaze** [The-1-7-10-Pack/The-1.7.10-Pack#148]
Dungeon Pack: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284476-1-7-10-smp-bukkit-forge-dungeonpack-24-dungeons-3

Doomlike Dungeons: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293843-doomlike-dungeons-1-6-2

Hi, the few new structures that are around the world are very little and make the land look a bit cheerful, but for players that likes exploring, thery are... little? :c (Roguelike dungeons it is an exception)
So I suggest two mods that can make the modpack a bit more exciting about exploring the world:
"Dungeon Pack" and "Doomlike Dungenos", only one of them should be fine, here are some pros and cons
~Le pros
✔ Compatible with Biome O' Plenty
✔ Dungeons spawn rate, size and difficulty can be configured, example: for singleplayer  and private servers, normal spawn rate; for public servers, can be very limited or disabled so the server memory doesn't "explode".
✔ More items, mobs and bosses to fight (Dungeon Pack only)
✔ Both mods have permissions that let them be added in modpacks.
✔ Adding them would probably make me and my frieds happy (Wait, what?)

~Le cons
 ✖ There is a little problem (not confirmed by myself), apparently, there is a possibility that in dungeon created by a mod... can spawn another dungeon from another mod
✖ In case of a chunk corruption, when minecraft re-create that chunk, a part of a dungeon can spawn on it.
✖ When a very huge dungeon appears, it causes a spike of memory that can freeze minecraft or server for 3 seconds or less (tested by me in Dungeon Pack) (depends on the computer)
✖ Since some dungeons have a lot of mob spawners (thing that can be configurated), it may cause lag for people that don't have a good computer.
✖ The dugeon pack mod page have doesn't have any pics, just videos (I don't know if that is considerated a cons)

Well, that's it, I like the Doomlike mod more than Dungeon Pack because it is less problematic in servers, probably there are a lot of mods that can make dungeons, but this ones are my favorites. I think It would be nice to add them in the modpack, I think it can get along with the other mods (especially with ender zoo). What do you think? :)

**Comment by The-1-7-10-Pack** [comment]
I know both mods very good and they are nice, but fit more adventure modpacks.
The 1.7.10 Shouldn't focus on anything specific: We have dungeon mods, but we shouldn't have too much of them.
Thanks anyway :)
