### ISSUE TITLE
Outdated Java

### ISSUE THREAD

**Issue by James4007** [The-1-7-10-Pack/The-1.7.10-Pack#15]
I have Java 8 update 25, but when I start the pack, a message comes up saying one of the mods requires version 1.7 or newer, and that I have 1.6.0_65. I deleted and reinstalled Java multiple times, and it still doesn't work. Please Help!

**Comment by The-1-7-10-Pack** [comment]
Your Java 8 is up to date?

**Comment by The-1-7-10-Pack** [comment]
Did you try to install Java 7 and it worked?
Also, is it the first time you install the pack?

**Comment by chrisps89** [comment]
Are you downloading the offline Java or the online Java? You can download the offline version here https://java.com/en/download/manual.jsp

**Comment by Flukethoughts** [comment]
Please post crash-report or screen shot of issue thank you.

**Comment by James4007** [comment]
This started happening when the launcher updated.
Here is a screenshot: 
![screen shot 2015-01-01 at 9 45 59 pm](https://cloud.githubusercontent.com/assets/10367273/5593964/a9b9c136-91ff-11e4-8b85-b342009ac69e.png)

**Comment by BlackJackAres** [comment]
I'd say run through the usual list of suspects, like completely uninstalling the .technic loader and the 1.7.10 pack to make sure it isn't a faulty download error, then try installing a fresh copy of Java 7 or 8 and see if that fixes your problem.

**Comment by James4007** [comment]
I deleted the technic launcher (but saved my worlds), deleted my Java and reinstalled it, and downloaded  the launcher of the website. Its the one with the ![screen shot 2015-01-01 at 10 37 12 pm](https://cloud.githubusercontent.com/assets/10367273/5594080/cc8e9130-9206-11e4-9929-ae2bbd27c892.png)picture on the front. Now the launcher doesn't open. I'm going to try to reinstall it.

**Comment by James4007** [comment]
Wait, i got the launcher to open.

**Comment by James4007** [comment]
and it still doesn't work.

**Comment by BlackJackAres** [comment]
Whats your java type? 32 or 64? Additionally how much ram do you have able to allocate? Also take a look in the .technic folder, select the mods folder (It is in %appdata% which you can just type into your search bar on windows and press enter, itll bring it up automatically) look for the 1.7.10 pack and go into that, and go into crash reports and send us your latest crash report.

PLEASE do not copy paste it into here, but instead send it to us via http://paste.ubuntu.com which makes it much easier to manage the report.

**Comment by James4007** [comment]
(I have a Mac, but I still found it) There is no crash report, and now after getting the new download for the launcher, I can only play packs I installed.

**Comment by James4007** [comment]
I think I can open any of the default packs is because of the new launcher. I haven't used them since the update.

**Comment by James4007** [comment]
Never mind, I can use the default ones, now

**Comment by chrisps89** [comment]
Is your problem sorted out now ? Can you get the Modpack going ?

**Comment by Silphsy** [comment]
Got this issue as well: http://i.imgur.com/FGHZqmc.png
This doesn't happen with any of my other installed modpacks, just only with this one.
(Tekkit, Vanilla, DETS II, Crafting Dead, Ultra-modded survival 2, Oh Gaming's Medieval Times, etc)
I had already and un-installed & installed Java, Technic and the pack itself and this issue still occurs.
I'm starting to think that this might be a mac problem.

**Comment by Silphsy** [comment]
Java7Checker seemed to be the cause of the problem for me, give me a minute to see if i can run the pack without it.

**Comment by Silphsy** [comment]
Fixed it! I honestly didn't think it was my Mac's problem, oh well.
http://download.oracle.com/otn-pub/java/jdk/7u71-b14/jdk-7u71-macosx-x64.dmg (1.7 Mac Download)
Now, time to play some damn Minecraft!

**Comment by chrisps89** [comment]
Congrats mate, glad you got it sorted. http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html will work for anyone else with the problem, you can scroll down and select the download for your operating system.

Seems odd that you need the Java Development Kit to play it though, but if it works, it works!

**Comment by The-1-7-10-Pack** [comment]
:)

**Comment by James4007** [comment]
Thank you so much!!!!

**Comment by Silphsy** [comment]
Just like to comment that you should probably remove 'Mac' from the title. 
Other OS users might also receive this problem and think that the title will be irrelevant to them.

**Comment by The-1-7-10-Pack** [comment]
Other OS should open their own issue :)

**Comment by James4007** [comment]
I didn’t change the title, and I don’t see it anymore

**Comment by teigur1** [comment]
Thanks guys! this is why I love GOOGLE
