### ISSUE TITLE
Falling through map / horrible latency

### ISSUE THREAD

**Issue by drschplatt** [The-1-7-10-Pack/The-1.7.10-Pack#150]
Hey there, when trying to play on a private, multiplayer map making use of the technic launcher and 1.7.10 pack, I am experiencing horrible lag and latency issues.  When I log in, I will often fall through the map into blackness for several minutes before the world finally loads.  Other times I cannot move more than 4 or 5 blocks away from where I am standing without rubber banding back to the start. I will often break blocks with no result, get killed by enemies I cannot see or attack, and generally lose the ability to interact with anyone in the map. 

When I go into the multiplayer launcher, the ping is never higher than 300ms.  I'm the only one having this issue with the server, the people who play together are able to log in and play without much trouble. 

So, I'm wondering if there's a problem on my end.  I have no lag/latency problems with any other online game that I play, only this one.  I'm not sure what information people will need to help trouble shoot this, but I'll be more than happy to provide whatever information and logs are needed if someone will point me in the right direction. 

Cheers!

**Comment by Flukethoughts** [comment]
where is the mulitplayer map hosted in location and where is your location?

**Comment by drschplatt** [comment]
The server is located in Australia. I live in Taiwan but am on vacation in the US.  I get the same result in both locations.  When I'm in Taiwan I'm able to play other games on US, European and Australian servers without this kind of latency issues.  One of the guys who plays on the server is in Canada and isn't having these issues. 

My Taiwan bandwidth is 100 down 50 up, so no speed issues there.

**Comment by Flukethoughts** [comment]
Australia there is your issue

**Comment by drschplatt** [comment]
Except for the fact, like I just pointed out, that other people outside of Australia aren't having the same issues.  If anyone who has helpful advice would like to chime in I'd appreciate it. I haven't gotten any yet.

**Comment by Flukethoughts** [comment]
ok this is closed Australia has a horrible upload rate if you didn't know so yea there you go again. There internet Prob can't hold you and all the other users so when you get the chance to learn before you speak that would be wonderful.

**Comment by drschplatt** [comment]
If you aren't interested in reading or being helpful then don't take on an issue.   I don't need smart ass remarks. If you don't know how to help, admit you don't know and move on.  I stated very clearly that people outside of Australia are able to use the server just fine and that I am able to ping the server with an acceptable latency but once the game goes active things start hanging up.  When I am the only person on the server I still get issues.  I guess I'll have to start a new thread seeing as Fluke doesn't know enough to help and decided to close this before anyone knowledgeable could help.

**Comment by The-1-7-10-Pack** [comment]
No need to be mad, at anything, ever.
Anyway, this is not the modpack's issue so this is why this one closed.
Maybe we can still help you though. How is your connection to the official server?
