### ISSUE TITLE
Problemw ith my server

### ISSUE THREAD

**Issue by sprout18** [The-1-7-10-Pack/The-1.7.10-Pack#151]
On my server that i have made i cannot do anythign with mods if i try to spawn something in it doesnt come and says id wrong or something like that and when i break a block of a mod it just disappears

**Comment by Flukethoughts** [comment]
my skype info is not_just_a_fluke add me on there and I will look into your issue.

**Comment by thebalck** [comment]
You need to open this jar so the server works
forge-1.7.10-10.13.2.1291-universal.jar

Not the other one

**Comment by sprout18** [comment]
i opened the 1.7.10-10.13.2.1291-universal file it worked like a normal server it looked the same it just didnt open up the server i renamed 1.7.10-10.13.2.1291-universal.jar but the exzact same thing happened

**Comment by sprout18** [comment]
So i still need help on my first comment and a fix on my most recent comment

**Comment by sprout18** [comment]
last thing can some one link me to spahx for the texture pack 64x

**Comment by The-1-7-10-Pack** [comment]
To launch the server you need to double-click the LaunchServer.bat file.
ResourcePack: http://bit.ly/The-1-7-10-Pack-Sphax

**Comment by sprout18** [comment]
Ihave dont that and on the launch server.bat file when i start it up it says error unable to acces jar file forge1.7.10 and so on and i have the forge universal file opened at the exzact same time as the launch server .bat

**Comment by sprout18** [comment]
also a mod sugestion is MCA or minecraft comes alive

**Comment by sprout18** [comment]
PLease some body i really need help

**Comment by sprout18** [comment]
---- Minecraft Crash Report ----
// There are four lights!

Time: 3/02/15 5:49 PM
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 912006312 bytes (869 MB) / 1167589376 bytes (1113 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xmx3G -XX:PermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 189 mods loaded, 189 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{7.10.85.1230} [Forge Mod Loader] (forge.jar) Unloaded
	Forge{10.13.2.1230} [Minecraft Forge] (forge.jar) Unloaded
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded
	NotEnoughItems{1.0.3.78} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.78-universal.jar) Unloaded
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded
	RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) Unloaded
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded
	AdvancedMachines{1.1.2} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) Unloaded
	aobd{2.3.6} [Another One Bites The Dust] (AOBD-2.3.6.jar) Unloaded
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded
	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) Unloaded
	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded
	asielib{0.3.8} [asielib] (AsieLib-1.7.10-0.3.8.jar) Unloaded
	Grinder{4.0.0} [Grinder] (AttachableGrinder-4.0.0.jar) Unloaded
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded
	bdlib{1.6.0.35} [BD Lib] (bdlib-mc1710-1.6.0.35.jar) Unloaded
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded
	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) Unloaded
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1057-universal.jar) Unloaded
	AWWayofTime{v1.3.0b} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0b-3.jar) Unloaded
	Botania{r1.3-153} [Botania] (Botania r1.3-153.jar) Unloaded
	BuildCraft|Silicon{6.3.3} [BC Silicon] (buildcraft-6.3.3.jar) Unloaded
	BuildCraft|Core{6.3.3} [BuildCraft] (buildcraft-6.3.3.jar) Unloaded
	BuildCraft|Transport{6.3.3} [BC Transport] (buildcraft-6.3.3.jar) Unloaded
	BuildCraft|Builders{6.3.3} [BC Builders] (buildcraft-6.3.3.jar) Unloaded
	BuildCraft|Energy{6.3.3} [BC Energy] (buildcraft-6.3.3.jar) Unloaded
	BuildCraft|Factory{6.3.3} [BC Factory] (buildcraft-6.3.3.jar) Unloaded
	BuildCraft|Compat{6.3.0} [BuildCraft Compat] (buildcraft-compat-6.3.1.jar) Unloaded
	CarpentersBlocks{3.3.4.4} [Carpenter's Blocks] (Carpenter's Blocks v3.3.4.4 - MC 1.7.10.jar) Unloaded
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded
	chisel{2.3.3.28} [Chisel 2] (Chisel2-2.3.3.28.jar) Unloaded
	ChiselFacades{1.7.10-2.9-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.9-cricket.jar) Unloaded
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded
	colorchat{1.7.2-0.1.0} [ColorChat] (colorchat-1.7.10-0.1.0-22.jar) Unloaded
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded
	computronics{1.3.4} [Computronics] (Computronics-1.7.10-1.3.4.jar) Unloaded
	DeathCounter{4.0.0} [DeathCounter] (DeathCounter-4.0.0.jar) Unloaded
	debug{1.0} [debug] (denseores-1.5.jar) Unloaded
	denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded
	Doge{0.5.2} [Doge] (DogeMod_0.5.2_[1.7.10].jar) Unloaded
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded
	EnderIO{1.7.10-2.2.7.325} [Ender IO] (EnderIO-1.7.10-2.2.7.325.jar) Unloaded
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded
	EnderZoo{1.7.10-1.0.9.18} [Ender Zoo] (EnderZoo-1.7.10-1.0.9.18.jar) Unloaded
	extracells{2.2.46} [ExtraCells] (ExtraCells-1.7.10-2.2.46b72.jar) Unloaded
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded
	factorization.misc{1.7.10-0.8.88.7} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.88.7.jar) Unloaded
	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.88.7.jar) Unloaded
	factorization{1.7.10-0.8.88.7} [Factorization] (Factorization-1.7.10-0.8.88.7.jar) Unloaded
	FastCraft{1.16} [FastCraft] (fastcraft-1.16.jar) Unloaded
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded
	Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded
	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-4.jar) Unloaded
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.257.jar) Unloaded
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.257.jar) Unloaded
	gendustry{1.4.4.52} [GenDustry] (gendustry-mc1710-1.4.4.52.jar) Unloaded
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded
	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) Unloaded
	HelpFixer{1.0.5} [HelpFixer] (HelpFixer-1.0.5.jar) Unloaded
	HardcoreQuesting{The Journey (4.2.2)} [Hardcore Questing Mode] (HQM-The Journey (4.2.2).jar) Unloaded
	IC2NuclearControl{2.1.2a} [Nuclear Control 2] (IC2NuclearControl-2.1.2a.jar) Unloaded
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded
	IC2{2.2.663-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.663-experimental.jar) Unloaded
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded
	JABBA{1.2.0a} [JABBA] (Jabba-1.2.0a_1.7.10.jar) Unloaded
	LogisticsPipes{0.8.3.92} [Logistics Pipes] (logisticspipes-0.8.3.92.jar) Unloaded
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded
	MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.145.jar) Unloaded
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.145.jar) Unloaded
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.145.jar) Unloaded
	MFFS{4.1.1} [Modular Force Field System] (mffs-4.1.1.61-core.jar) Unloaded
	MineFactoryReloaded{1.7.10R2.8.0RC6} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatMagicalCrops{1.0beta} [MFR Compat: MagicalCrops] (MineFactoryReloaded-CompatMagicalCrops.jar) Unloaded
	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal.jar) Unloaded
	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.6.jar) Unloaded
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded
	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded
	necromancy{1.7.1} [Necromancy] (Necromancy-1.7.10.jar) Unloaded
	NEIAddons{1.12.3.13} [NEI Addons] (neiaddons-mc1710-1.12.3.13.jar) Unloaded
	NEIAddons|Botany{1.12.3.13} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.13.jar) Unloaded
	NEIAddons|Forestry{1.12.3.13} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.13.jar) Unloaded
	NEIAddons|CraftingTables{1.12.3.13} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.13.jar) Unloaded
	NEIAddons|ExNihilo{1.12.3.13} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.13.jar) Unloaded
	neiintegration{1.0.5} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.5.jar) Unloaded
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded
	recipemod{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) Unloaded
	neresources{0.1.0.55} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.55.jar) Unloaded
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded
	OpenComputers{1.4.6.30} [OpenComputers] (OpenComputers-MC1.7.10-1.4.6.30-universal.jar) Unloaded
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded
	OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded
	OpenPeripheralCore{0.5.0} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded
	OpenPeripheral{0.2.0} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-1.jar) Unloaded
	harvestcraft{1.7.10d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10f.jar) Unloaded
	PneumaticCraft{1.5.3 - err} [PneumaticCraft] (PneumaticCraft-1.7.10-1.5.3-universal.jar) Unloaded
	progressiveautomation{1.5.6} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.5.6.jar) Unloaded
	ProjRed|Core{4.5.8.59} [ProjectRed] (ProjectRed-1.7.10-4.5.8.59-Base.jar) Unloaded
	ProjRed|Compatibility{4.5.8.59} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.8.59-Compat.jar) Unloaded
	ProjRed|Integration{4.5.8.59} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded
	ProjRed|Transmission{4.5.8.59} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded
	ProjRed|Illumination{4.5.8.59} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.8.59-Lighting.jar) Unloaded
	ProjRed|Expansion{4.5.8.59} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded
	ProjRed|Transportation{4.5.8.59} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded
	ProjRed|Exploration{4.5.8.59} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.8.59-World.jar) Unloaded
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded
	RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded
	RefinedRelocation{1.0.7d} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.7d.jar) Unloaded
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) Unloaded
	ResonantEngine{3.3.0} [Resonant Engine] (resonant-engine-3.3.0.393-core.jar) Unloaded
	Roguelike{1.3.5} [Roguelike Dungeons] (roguelike-1.7.10-1.3.5.jar) Unloaded
	AS_Ruins{14.2} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded
	simplyjetpacks{1.3.2} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.3.2.jar) Unloaded
	squidless{0.6.0} [Squidless] (squidless-1.7.10-0.6.0.jar) Unloaded
	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) Unloaded
	StevesAddons{0.6.8} [Steve's Addons] (StevesAddons-1.7.10-0.6.8.jar) Unloaded
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded
	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) Unloaded
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded
	Thaumcraft{4.2.3.3} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.3.jar) Unloaded
	thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.6a.jar) Unloaded
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-34.jar) Unloaded
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded
	ttCore{MC1.7.10-0.1.0-55} [ttCore] (ttCore-MC1.7.10-0.1.0-55.jar) Unloaded
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded
	Waila{1.5.7} [Waila] (Waila-1.5.7a_1.7.10.jar) Unloaded
	wailaplugins{MC1.7.10-0.0.1-10} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-10.jar) Unloaded
	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) Unloaded
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	yampst{1.3.3} [YAMPST] (Yampst-The 1.7.10 Pack-0.7.0.jar) Unloaded
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by sprout18** [comment]
thats my crash report

**Comment by The-1-7-10-Pack** [comment]
You did basically everything wrong.
Redownload the server files and double click LaunchServer.bat.
After that make sure you set eula.txt to true, then double click LaunchServer.bat again and you're done.

**Comment by sprout18** [comment]
the launch server .bat doesnt make the eula fules because it has the forge error

**Comment by The-1-7-10-Pack** [comment]
but you don't need to touch anything, " i have the forge universal file opened at the exzact": Just download the server files, don't touch anything and double click the launch file. Closing this one.
