### ISSUE TITLE
is this anything to be worried about 

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#152]
every time i load into my world i get this bit of code i was just wondering is it anything i should be worried about it as of yet does not seem to stop me doing anything. i'm just being careful

[12:42:57] [NEI Item Loading/ERROR]: Removing item: net.minecraft.item.ItemBlock@3be17334 from list.
[B#256]  java.lang.NullPointerException
[B#256]  	at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73) ~[alc.class:?]
[B#256]  	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181) ~[abh.class:?]
[B#256]  	at codechicken.nei.ItemList$1.execute(ItemList.java:202) [ItemList$1.class:?]
[B#256]  	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]

**Comment by The-1-7-10-Pack** [comment]
You should be careful from being too careful
