### ISSUE TITLE
HQM Quest cannot be completed - Promise Lands Removed from recent version.

### ISSUE THREAD

**Issue by da404lewzer** [The-1-7-10-Pack/The-1.7.10-Pack#153]
As cited from the wiki below: "As of Biomes o' Plenty version 717, the Promised Land is no longer in game, and many of the blocks contained there have been completely removed."

This means that the quest cannot be completed because you cannot currently craft the required item.

http://biomesoplenty.wikia.com/wiki/Promised_Land

Thanks :)
-404

**Comment by The-1-7-10-Pack** [comment]
Thanks for the report, fixed (:

**Comment by da404lewzer** [comment]
No problem. I plan on keeping this pack for a while so I'm going to try to be a lot more active with fixing it.
