### ISSUE TITLE
Migrate mod configs to Solder

### ISSUE THREAD

**Issue by spacemonkey** [The-1-7-10-Pack/The-1.7.10-Pack#155]
First thanks for such an awesome modpack!

Migrating this pack to [Solder](https://github.com/TechnicPack/TechnicSolder) means you no longer will have to manually update the list of mods and versions on the Technic website, and it will also allow you to link to the original downloads - making it possible to include stuff like JourneyMap and many others.

I'm happy to help with this, would really show how mature and well-managed this pack is, and has grown. I'm a server-side guy and have a strong PHP background ([Joomla!](http://www.joomla.org/) founder) and can set this up in minutes.

**Comment by The-1-7-10-Pack** [comment]
First of all, Solder is indeed cool. We have plans though, don't you worry.
Second of all, thank you for offering help. Anybody, at any time, can use help.
I understand you have a very technical background, but hosting Solder requires a dedicated server you know. If you have anything more you say you are welcome to send me a private message on the MC forums, here is not really the place for this kind of suggestions. :)
