### ISSUE TITLE
NEI Cheat mode bug

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#156]
When i give myself items in cheat mode from NEI but my inventory is full the game crashes

http://paste.ubuntu.com/10017682/

**Comment by The-1-7-10-Pack** [comment]
This is why you should never cheat.

**Comment by thebalck** [comment]
Haha My server my rules xD

Ty for the info

**Comment by bochen415** [comment]
@thebalck What item was it? From which mod?

**Comment by The-1-7-10-Pack** [comment]
@bochen415 It doesn't matter which item.

**Comment by pchard** [comment]
This has been fixed in the latest version of BuildCraft:

http://www.mod-buildcraft.com/download/

**Comment by The-1-7-10-Pack** [comment]
@pchard How BuildCraft related to this bug?

**Comment by pchard** [comment]
I updated my buildcraft and the issue is gone. So, updating this pack,
solves the creative bug issue.
4. feb. 2015 16:56 skrev "Jon" <notifications@github.com>:

**Comment by The-1-7-10-Pack** [comment]
@pchard This issue is not about the creative tab issue. Also it's not news, I actually reported the creative tab issue myself to the BC issue tracker.
