### ISSUE TITLE
[Mod Suggestion] Electrodynamics

### ISSUE THREAD

**Issue by imaFlippingAsian** [The-1-7-10-Pack/The-1.7.10-Pack#158]
http://calclavia.com/electrodynamics/
Could you add this mod? There are many things I could do in this mod that I really enjoyed. And it coexisted pretty well with the other tech mods like Mekanism and IC2. The power generation in this mod is challenging to achieve early on, but in the long run. Out scales almost every other power generation in any other mod. 
Everything in this mod is compatible with IC2, Thermal Expansion and Universal Electricity. There are many other things I haven't explored but there are a lot of things to do with this mod and it just incorporates well with all of the tech mods that already exist in this pack. Tech Junkies would love this mod. I would appreciate it if this mod is added in a future update.

**Comment by AWESOMEDUCKMAN1** [comment]
I took a look at the mod and I thought it looked really awesome it's something I would also wanna see in the modpack. I hope the creator of the 1.7.10 pack (Jon I think?) sees this and considers it. Of course only if it's compatible.

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/134
