### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by TreePuncher9501** [The-1-7-10-Pack/The-1.7.10-Pack#159]
The game crashes whenever it loads up my world.

Scenario: Created a large automated farm using Minefactory and Magical Crops. Here's the error report: http://paste.ubuntu.com/10044852/

Edit for new info: I fixed the crashing problem, but now the world does not load PERIOD. When trying to load, it brings me back to the main menu. If I try loading it again, it goes straight to shutting down internal server and will not leave that screen or crash out. It will just freeze on that screen. I am very confused about this. Screenshot: http://i.imgur.com/VC3FUu7.png

Edit 2: Was able to load up world, but sky blinks very fast and I fall through blocks on attempt to move.

**Comment by The-1-7-10-Pack** [comment]
Nothing I can do about this problem, MFR & MagicalCrops doesn't connect too good on 1.7 as they both didn't add any official support for each other.
Are you able to load your world?
