### ISSUE TITLE
Issue with the modpack not launching what so ever

### ISSUE THREAD

**Issue by jaketheman99** [The-1-7-10-Pack/The-1.7.10-Pack#16]
Whenever I launch the mod pack it almost instantly returns me to the screen I have looked at all the recommendations and none of them seem to work for me. I have the correct version of java and everything and also a few of my friends are having the same issue.

**Comment by The-1-7-10-Pack** [comment]
Please provide the latest.log from .technic/modpacks/the-1710-pack/logs.

**Comment by jaketheman99** [comment]
Ok and also how come the server files have problems with uploading crucible for bukkit plugins?

**Comment by The-1-7-10-Pack** [comment]
The server does not support any plugins.

**Comment by Flukethoughts** [comment]
This is a forge server not a bukkit or cauldron sever. Plugins are not something you can just add on a forge server sorry. I think before you start a server you should read more into it.

**Comment by Flukethoughts** [comment]
Closed this Is not a Bukkit or Cauldron Server. Next time you post please post with logs thank you.
