### ISSUE TITLE
Crashing when trying to make Floating Tallow Candles

### ISSUE THREAD

**Issue by Slushyz2237** [The-1-7-10-Pack/The-1.7.10-Pack#160]
It seems whenever I try to make Floating Tallow Candles my game crashes as soon as I place the air shard in the Arcane Worktable while the three candles are already in there.

**Comment by The-1-7-10-Pack** [comment]
Did you read how to report a bug?

**Comment by Slushyz2237** [comment]
http://pastebin.com/KxpShDLb

**Comment by The-1-7-10-Pack** [comment]
A mod bug. Already have been reported (https://github.com/Flaxbeard/Thaumic_Exploration/issues/20)
Nothing I can do about it until it get fixed there.
