### ISSUE TITLE
[Custom Recipe] Packed Ice

### ISSUE THREAD

**Issue by da404lewzer** [The-1-7-10-Pack/The-1.7.10-Pack#162]
Some vanilla things like packed ice don't have crafting recipes. It's really unfortunate too because it's such a simple block, ice that doesn't melt.. genius! With Biomes o Plenty adding so many new biomes it's hard to find any packed ice and the twilight forest requires leveling up. That's when I remembered MineTweaker! 

I suggest we add a recipe that consists of a ring of ice with a snow block in the middle yielding 4 packed ice.

MineTweaker3 will give us the ability to do this and the author has stated on his website (in the footer) that it can be used as long as the pack is free. I can make the config if needed, I've done these before. This would also give us the ability to add (or remove) any other crafting recipes we can think of. http://minetweaker3.powerofbytes.com/

**Comment by The-1-7-10-Pack** [comment]
A big part of the fun of pached ice is to find it. Currently I won't add a custom recipe for it.
Thanks anyway for the suggestion.

**Comment by da404lewzer** [comment]
I believe the "fun" in finding packed ice is more of a vanilla experience. I hope you reconsider, we have machines that will make regular ice, whats the harm. If you want to go find it, nobody is twisting your arm go find it. I chose this pack because it's a "huge tech/magic pack" not because I want to explore, I can do that on any server/pack.

**Comment by The-1-7-10-Pack** [comment]
Although you can say the same thing about Diamonds or other rare ores. Exploring is a part of Minecraft that we can't kill.
