### ISSUE TITLE
Botania update

### ISSUE THREAD

**Issue by Justcorry** [The-1-7-10-Pack/The-1.7.10-Pack#163]
Hello the botana mod seems to be missing a few functional and generating flowers. 
Unless there is some compadability issues I would appreciate if the pack was updated to R1.4 156

If there is a reason why it can't be updated then that's fine however I really enjoy this mod and want to try all the new things.

**Comment by The-1-7-10-Pack** [comment]
What functionals and flowers?

**Comment by Justcorry** [comment]
The changelog on the botania site shows the spectrolus, narslimmus, marimorphosis, medumone and spectranthemum.

Perhaps they are also hidden in the elven knowledge section. I thought the orechid and thermalilly were removed but the changelog tells me they were moved there and they don't show up in the lexica botania book.

Regards,

Corry Hopkins

**Comment by The-1-7-10-Pack** [comment]
Next update of the modpack botania will update too but you'll have to wait a bit, there are some issues.
