### ISSUE TITLE
Can't upgrade to 0.7.1 - Launcher throwing FileNotFoundException

### ISSUE THREAD

**Issue by da404lewzer** [The-1-7-10-Pack/The-1.7.10-Pack#165]
**Error unzipping a file for the following pack: The 1.7.10 Pack
Attempting to extract file the-1710-pack-0.7.1.zip, but it did not exist.
Please consult the modpack author.**

![image](https://cloud.githubusercontent.com/assets/1009346/6069813/4c46a48a-ad3c-11e4-919f-32be7d4365ca.png)

Steps to reproduce:
1) Close Launcher
2) Open Launcher
3) Select Pack and click Play
4) Confirm that you want to upgrade
5) Resulting Error (from console):

[B#265] Expected MD5: 94a9d4cbcb9ceaa25000fa303fa81acc Calculated MD5: 94a9d4cbcb9ceaa25000fa303fa81acc
[B#265] Expected MD5: b62087eb4b11746987c800c0512890ef Calculated MD5: b62087eb4b11746987c800c0512890ef
[B#265] Starting download of http://www.gravatar.com/avatar/417979e451a4ed37c22f5340a9c3cd4a?s=60&d=retro, with 3 tries remaining
[B#265] Starting download of http://www.gravatar.com/avatar/2a29f323eddf3410fb1b531b10f7df6f?s=60&d=retro, with 3 tries remaining
[B#265] Starting download of http://www.gravatar.com/avatar/d9730e2e0c38231a9acaaeca38baf069?s=60&d=retro, with 3 tries remaining
[B#265] Starting download of http://www.gravatar.com/avatar/2b162da4b79c29cb9acd8691252a5417?s=60&d=retro, with 3 tries remaining
[B#265] Starting download of http://www.gravatar.com/avatar/658cdc5b875ea573a0016824e0959e1d?s=60&d=retro, with 3 tries remaining
[B#265] Starting download of http://crafatar.com/avatars/b6cf4c57a5d54d47949ebf69ba999a00?size=100&helm, with 3 tries remaining
[B#265] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://magitechworld.com/TechnicSolder/public/api/modpack/]
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:109)
[B#265] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#265] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#265] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#265] 	at java.lang.Thread.run(Unknown Source)
[B#265] Caused by: java.io.FileNotFoundException: http://magitechworld.com/api/modpack
[B#265] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:89)
[B#265] 	... 7 more
[B#265] Starting download of http://www.gravatar.com/avatar/d593acb99c078196c657559168b57a6e?s=60&d=retro, with 3 tries remaining
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-logos/453902.png?1423171660, with 3 tries remaining
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-backgrounds/453902.jpg?1423171660, with 3 tries remaining
[B#265] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://magitechworld.com/TechnicSolder/public/api/modpack/]
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:109)
[B#265] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#265] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#265] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#265] 	at java.lang.Thread.run(Unknown Source)
[B#265] Caused by: java.io.FileNotFoundException: http://magitechworld.com/api/modpack
[B#265] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:89)
[B#265] 	... 7 more
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1423171660, with 3 tries remaining
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1423171660, with 3 tries remaining
[B#265] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://magitechworld.com/TechnicSolder/public/api/modpack/]
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:109)
[B#265] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#265] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#265] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#265] 	at java.lang.Thread.run(Unknown Source)
[B#265] Caused by: java.io.FileNotFoundException: http://magitechworld.com/api/modpack
[B#265] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:89)
[B#265] 	... 7 more
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1423171660, with 3 tries remaining
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1423171660, with 3 tries remaining
[B#265] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://magitechworld.com/TechnicSolder/public/api/modpack/]
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:109)
[B#265] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#265] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#265] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#265] 	at java.lang.Thread.run(Unknown Source)
[B#265] Caused by: java.io.FileNotFoundException: http://magitechworld.com/api/modpack
[B#265] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:89)
[B#265] 	... 7 more
[B#265] net.technicpack.rest.RestfulAPIException: Error accessing URL [http://magitechworld.com/TechnicSolder/public/api/modpack/]
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:109)
[B#265] 	at net.technicpack.solder.http.HttpSolderApi.getMirrorUrl(HttpSolderApi.java:59)
[B#265] 	at net.technicpack.solder.cache.CachedSolderApi.getMirrorUrl(CachedSolderApi.java:134)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getInfoFromPlatformInfo(PlatformPackInfoRepository.java:72)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:60)
[B#265] 	at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
[B#265] 	at net.technicpack.launchercore.modpacks.PackLoadJob$6.run(PackLoadJob.java:195)
[B#265] 	at java.lang.Thread.run(Unknown Source)
[B#265] Caused by: java.io.FileNotFoundException: http://magitechworld.com/api/modpack
[B#265] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#265] 	at net.technicpack.rest.RestObject.getRestObject(RestObject.java:89)
[B#265] 	... 7 more
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1423171660, with 3 tries remaining
[B#265] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1423171660, with 3 tries remaining

**Comment by da404lewzer** [comment]
I should note that the server download is fine and has no issues.

**Comment by da404lewzer** [comment]
So, this time around I said "NO" to the update and now 0.7.0 doesn't work either. Every person on my server who has attempted to upgrade can no longer play.

http://i.imgur.com/t7nwSAS.png

**Comment by da404lewzer** [comment]
Also the older versions have been removed, this means none of can now install the current version installed on the server and play until this gets resolved. Please put the older versions back up, this is one of the reasons we left Yogscast Complete, they forced updates and new players (or issues like this) keep us from playing.

![image](https://cloud.githubusercontent.com/assets/1009346/6070035/2f078af4-ad3e-11e4-99f3-13f6ba71b502.png)

**Comment by GreatHolyCow** [comment]
I cant play either im stuck now to. Cant play previous or new version.

**Comment by tetsuraryuuken** [comment]
I tried updating and couldn't. Then when I tried to play 0.7.0 I couldn't. I really like this pack, please fix it when you get a chance!

I'm gonna try restoring old versions with Windows...

**Comment by Jakorosin** [comment]
Just a quick heads-up, guys-- modpack author attempted Solder integration, and something went derpy. He's working on it and says it should be fixed soon. http://www.technicpack.net/status/63987

**Comment by GreatHolyCow** [comment]
Should just roll back to zip file and then figure out solder integration later

**Comment by da404lewzer** [comment]
The older versions shouldn't have been removed in the first place. If they were still there we would have been playing 2 hours ago and not sitting here talking about it. Good thing I tried upgrading my client before I did the server lol

**Comment by Flukethoughts** [comment]
sometimes it's best to check the website hint hint hint

**Comment by tetsuraryuuken** [comment]
I kept updating the website to learn when 0.7.1 first came out. This issue was reported about an hour after the pack update.

**Comment by The-1-7-10-Pack** [comment]
http://www.technicpack.net/status/64422

**Comment by da404lewzer** [comment]
Thank you for putting the old version back up but 0.7.0 shows as being down too. Also, can we not remove old versions in the past? I feel like everyone could be playing right now if that wasn't the case.

![image](https://cloud.githubusercontent.com/assets/1009346/6088120/1455b71a-ae08-11e4-8db2-f4ec5fd45304.png)

**Comment by The-1-7-10-Pack** [comment]
@da404lewzer I am aware, it's the technic platform's problem though. I'm afraid that it'll take a bit more waiting but everyone will win.
