### ISSUE TITLE
a 3gb memory ram limit on this modpack while tekkit modpack/launcher set to 15gb?

### ISSUE THREAD

**Issue by mariodk** [The-1-7-10-Pack/The-1.7.10-Pack#166]
what is up with this? 
i set the tekkit launcher to 15gb ram(16gb ram on the computers)
tried on 3 computers
same result ingame: can only use 3gb memory ram
i kinda fixed it by moving config/forge/mods folders to replace a modpack from Atlauncher
but still weird its only this modpack that use 3gb while the others use what i can set on tekkit launcher

ps. 
also i see on world gen. there is 2 types of Tin from 2 mods instead only 1
and 2 types of copper: from thermal expansion & foresty 
we only needing 1 tin and 1 copper not 2 on world gen. (as in basically what other modpacks do with world gen. & ores)

**Comment by A3K** [comment]
Sounds like you've got both 32bit and 64bit Java installed and that the pack is launching under the 32bit java

**Comment by Flukethoughts** [comment]
sometimes it's best to check the website for official server hint hint hint

**Comment by The-1-7-10-Pack** [comment]
The modpack automatically allocates RAM and this is why you can't control it.
You don't need to set up more than 3, it's just using your computer RAM for nothin'.
About the wold gen: Maybe when you moved the configs you changed them, but in the default pack we have only one type of each ore, others disabled through the configs.

**Comment by mariodk** [comment]
ok i see but the ore thing
i saw in the mining world on a server it has ores from thermal expansion & foresty 
but 3gb ram is under 30 FPS most of the time even in a complete new world
8gb is perfect for modpacks and if i wanted texture pack it also needs more

**Comment by The-1-7-10-Pack** [comment]
Ore: That's the server problem.
RAM: The RAM doesn't matter for fps most of the time, how much you're actually using in-game?
