### ISSUE TITLE
[mod suggestion] ICBM

### ISSUE THREAD

**Issue by Egobooster** [The-1-7-10-Pack/The-1.7.10-Pack#167]
Adds ICBM´s to minecraft would be very nice because Universal Electricity is already in the pack and it would be very funny to blow up some friends or make some sort of war :)

**Comment by The-1-7-10-Pack** [comment]
I may add ICBM when it'll be more stable, and out of Alpha stage :)
Thanks for the suggestion!

**Comment by da404lewzer** [comment]
Is there a place we could post suggestions without them getting closed immediately? I know you make the final say so but it would be nice to get a vote on some of these suggestions...

**Comment by The-1-7-10-Pack** [comment]
You can still vote and say your opinion.
I'll tell you a secret: when you close issues on GitHub - you can still open them after!

**Comment by da404lewzer** [comment]
You don't have to be a jerk about it. Simply stating people might not just randomly look up suggestions and that keeping them up a little longer, perhaps two days, wouldn't hurt.

**Comment by The-1-7-10-Pack** [comment]
![image](https://cloud.githubusercontent.com/assets/10350644/6098773/59d07db2-aff1-11e4-8a12-425f99baaafc.png)
