### ISSUE TITLE
My game crashes every time i load it

### ISSUE THREAD

**Issue by string55** [The-1-7-10-Pack/The-1.7.10-Pack#168]
I believe it is because you removed the chunk loader and i had a chunk loader and that is causing the crash. I am obviously pretty new to mod packs and i am curious as to what i can do to get my world back.

Any help is appreciated!

Edited: Please use pastebin next time.
http://pastebin.com/QPaSUFSV

**Comment by The-1-7-10-Pack** [comment]
You deleted the ChunkLoader and it fixed it?

**Comment by string55** [comment]
No how would i do that?

**Comment by The-1-7-10-Pack** [comment]
Leave it.
When does actually the game crashes? when you load up the client? or your save? (or anything else)

**Comment by string55** [comment]
when i load my save

**Comment by The-1-7-10-Pack** [comment]
"I believe it is because you removed the chunk loader and i had a chunk loader"
How can I remove a chunk loader from your world?

**Comment by string55** [comment]
lol i thought i saw somewhere that the chunk loader was removed from the pack

**Comment by string55** [comment]
and on the crash report it said that the chunk loader was the problem i believe.

**Comment by string55** [comment]
could my save be corrupted?

**Comment by The-1-7-10-Pack** [comment]
It is corrupted but maybe you can save it. You should report it there: http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820

**Comment by string55** [comment]
alright will do thanks do you have any clue what causes a save to be corrupted so that i could prevent it from happening again?

**Comment by Varzoh** [comment]
I created a server for my friends and I but every time my friends and I try to join, it crashes??? Help PLEASE!!

**Comment by The-1-7-10-Pack** [comment]
@Varzoh You should open your own issue and provide a crash report.

**Comment by string55** [comment]
i tried reinstalling the pack and now i can't even install it

**Comment by The-1-7-10-Pack** [comment]
Moving to solder, you need to wait a bit. Anyway you don't need to reinstall the entire modpack if one save fot corrupted, you should know for the next time :)

**Comment by string55** [comment]
okay lol what should i do for a corrupted save??

**Comment by The-1-7-10-Pack** [comment]
Nothing I can do, it's a mod bug, but you should ask for help there: You should report it there: http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820
Also the new update is out. Are you able to download it?

**Comment by liquid-metal** [comment]
try this dude : http://minecraft.gamepedia.com/Tutorials/Recover_corrupted_saved_world_data
i try it couple times a while back when playing other modpack (which is unstable as crap), and always prove success, but beware, everything that in your character inventory will disappear and your spawn point will be reset at random area

**Comment by string55** [comment]
okay dope ill try it thanks for the info

**Comment by The-1-7-10-Pack** [comment]
Closing it.
