### ISSUE TITLE
Cannot Install Modpack

### ISSUE THREAD

**Issue by gimble49** [The-1-7-10-Pack/The-1.7.10-Pack#169]
Upon attempting to install i get this message, http://imgur.com/wGXFCqk so here i am! please help

**Comment by The-1-7-10-Pack** [comment]
I'm aware, we're using a temp host until I get solder up and running.
Please wait a bit more and everything will be better :)

**Comment by TheIceballLP** [comment]
same problem :(

**Comment by The-1-7-10-Pack** [comment]
@TheIceballLP Don't worry guys, just a bit more of than "waiting" thingy and everything will be perfect.

**Comment by jorrdy12** [comment]
Having the same problem =( i cant wait to play this modpack

**Comment by The-1-7-10-Pack** [comment]
@jorrdy12 Just couple of hours :)

**Comment by poetofsilence** [comment]
The modpack is great guys. Worth the wait, I promise.

**Comment by gimble49** [comment]
Excellent, thank you :), cant wait to get back on my server!

**Comment by The-1-7-10-Pack** [comment]
Well the new version, with solder and unlimited bandwidth will have to wait a bit more.
Although, the modpack download of the 0.7.0 version is available again.

**Comment by mcmeaties** [comment]
Still can't download it!

**Comment by The-1-7-10-Pack** [comment]
@mcmeaties Restart your launcher and try again? I was able to.

**Comment by mcmeaties** [comment]
Okay, finally it is working.  Thank you.

**Comment by TardMonkey585** [comment]
@The-1-7-10-Pack It still wont download for me any suggestions?

**Comment by jorrdy12** [comment]
@The-1-7-10-Pack still having the same problem

**Comment by The-1-7-10-Pack** [comment]
@jorrdy12 @TardMonkey585 Just wait a bit so we'll move to the new host, then download problems will not be a thing anymore :)

**Comment by TardMonkey585** [comment]
When should we expect the new host change..?

**Comment by The-1-7-10-Pack** [comment]
@TardMonkey585 **Yes**.

**Comment by TardMonkey585** [comment]
When should we be able to download it?

**Comment by The-1-7-10-Pack** [comment]
I hope that today.

**Comment by The-1-7-10-Pack** [comment]
@TheIceballLP, @jorrdy12, @poetofsilence, @mcmeaties, @TardMonkey585:
It's out.
