### ISSUE TITLE
Crashing to Technic Launcher when creating Piston

### ISSUE THREAD

**Issue by Anicena** [The-1-7-10-Pack/The-1.7.10-Pack#17]
No crash report is created, just crashes all the way back to Technic Launcher. Item number 33. When created on crafting table and you attempt to remove created item from crafting table game immediately crashes. :(

**Comment by Anicena** [comment]
Correction, is whenever you attempt to make 2 at a time, one at a time does not cause the issue.

**Comment by Flukethoughts** [comment]
I can not duplicate this can you post a log check crash-reports

**Comment by Anicena** [comment]
Removed ignorant user from computer, obtained crash report. User was backhanded. http://paste.ubuntu.com/9657163/

**Comment by bmd1000** [comment]
delete java 8 and download java 7. Problem solved. (went through the same problem with all the modpacks i played, i researched it and that is what i found the problem was)

**Comment by Anicena** [comment]
Trying the java theory

**Comment by The-1-7-10-Pack** [comment]
Any update?

**Comment by The-1-7-10-Pack** [comment]
It's NotEnoughResources.

**Comment by Anicena** [comment]
Could not play the game without java 8. :(

**Comment by bmd1000** [comment]
Use the .jar version of the launcher

**Comment by The-1-7-10-Pack** [comment]
Why can't you play the game without java 8?
Please provide more information.

**Comment by Anicena** [comment]
Would press play on the Technic launcher and it would just sit at the
launcher.

**Comment by The-1-7-10-Pack** [comment]
Be sure that you have the currect version of Java.

**Comment by Anicena** [comment]
He did. 64 bit.

**Comment by The-1-7-10-Pack** [comment]
Who is "He"?
Alsom it's a completely new issue so please open a new one.

**Comment by Anicena** [comment]
My husband who i play with. We use the same build but i host to lan. He
tends so find game errors quite fast. Still can't create more than one
piston at a time without it crashing.

**Comment by The-1-7-10-Pack** [comment]
As The label says, It will fix in *next* update :)

**Comment by Anicena** [comment]
Ok.

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/101#issuecomment-71331180
