### ISSUE TITLE
Problem With hqm

### ISSUE THREAD

**Issue by jk484** [The-1-7-10-Pack/The-1.7.10-Pack#171]
It seems some quest items don't register such as the 4k storage drives which never go past 0%, or the crafting of the big backpack

**Comment by The-1-7-10-Pack** [comment]
It checked and it does register. You just need to have the amount needed :)

**Comment by Dommain** [comment]
I was able to reproduce it some how.  
http://i.imgur.com/nUCUDXm.png
http://i.imgur.com/DOi9MdF.png
And now it is bugged and I am not 100% sure what caused it

**Comment by The-1-7-10-Pack** [comment]
@Dommain And you have four of them?

**Comment by Dommain** [comment]
I tried all the way up to 16......  they don't stack and the manual detect doesn't work either.

**Comment by The-1-7-10-Pack** [comment]
I'll see what can I do, it will probably fix next update.
Thanks for reporting!

**Comment by Dommain** [comment]
I am happy to report the 4k drive issue is fixed but the 16348k is not being detected. I had the storage component and cell combined in my inventory with no success.

**Comment by The-1-7-10-Pack** [comment]
@Dommain Seriously? HQM does not like AE2 id's. Can you open a new issue, and also check some other items on the way? Thanks!

**Comment by Dommain** [comment]
I play legit so it may take me a while to test everything.

**Comment by The-1-7-10-Pack** [comment]
@Dommain Understandable, but for now can you just open a new issue about that other AE drive? Thanks.
