### ISSUE TITLE
Crash on World Loadup

### ISSUE THREAD

**Issue by TreePuncher9501** [The-1-7-10-Pack/The-1.7.10-Pack#172]
My world crashes on loadup after I enchanted something in a thaumcraft Osmotic Enchanter. Help? Here's the logs:
http://pastebin.com/uKm1Ev5g#

**Comment by The-1-7-10-Pack** [comment]
A bug of Thaumic Tinkerer. You should report it there, there's nothing I can do: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues
For now, to save your world, you should delete the Ticking block entity with NBT explorer, you can use this tutorial: https://www.youtube.com/watch?v=fWUUsdp3pJ8
