### ISSUE TITLE
Crashes in creative when opening search

### ISSUE THREAD

**Issue by Givemeyourgits** [The-1-7-10-Pack/The-1.7.10-Pack#174]
I see this mentioned a few times with other 1.7.10 packs, but I haven't found something that looks like a similar crash message.

Here is the exception I get when it crashes:
http://hastebin.com/odigocedij.avrasm

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/112
