### ISSUE TITLE
How to delete waypoints? 

### ISSUE THREAD

**Issue by MistyFires** [The-1-7-10-Pack/The-1.7.10-Pack#175]
So I started a brand new world but my old waypoints from my previous world are still showing up and I can't figure out how to get rid of them! Help!!

**Comment by The-1-7-10-Pack** [comment]
Set up in the controls the map menu, there you can delete and change all the minimaps :)

**Comment by MistyFires** [comment]
How do u do that?

**Comment by The-1-7-10-Pack** [comment]
You press Escape, then controls, then you scroll down until you find the key to the map menu, then you set it to something that is free (not red), then you press that key, you open the menu, go to the waypoints, select the waypoint and delete it :)

**Comment by The-1-7-10-Pack** [comment]
Closing this one as it's not an issue, if you need more details I'll give you.
