### ISSUE TITLE
Applied energestics

### ISSUE THREAD

**Issue by MistyFires** [The-1-7-10-Pack/The-1.7.10-Pack#176]
Can we please have this mod with the me access terminal etc?

**Comment by The-1-7-10-Pack** [comment]
We have it already =P

**Comment by MistyFires** [comment]
The second one yeah but I cannot find anything to do with the first one

**Comment by The-1-7-10-Pack** [comment]
There's only Applied Evergystics 2 for MC 1.7.10.

**Comment by MistyFires** [comment]
I'm on about the one with the me network! There is a first one, this mod pack is amazing but storage is so much better with the me network in applied energistics

**Comment by The-1-7-10-Pack** [comment]
There's an ME Network on the modpack as a part of Applied Energistics :)
