### ISSUE TITLE
build 0.7.0 can't be started anymore

### ISSUE THREAD

**Issue by shadowstrike114** [The-1-7-10-Pack/The-1.7.10-Pack#179]
The 0.7.0 version number seems to have been removed from the launcher. If i try to start it, it gives me the error: Error in response: Build does not exist.
Could the 0.7.0 version number please be added again so we can at least start the old version(at least for a few days, so we have time to update)

**Comment by The-1-7-10-Pack** [comment]
Why would you want to play in the old version?

**Comment by GreatHolyCow** [comment]
Well perhaps we would like to be able to play 0.7.0 untill our server is upgraded

**Comment by The-1-7-10-Pack** [comment]
I'll copy my comment on the platform:
> I didn't remove the old version, we just moved to Solder, and a diffrent host, so you can't access that stuff anymore. Anyway the build had it's bugs and with the new build everything is fixed. Update is very recommended. Not to note the new quests and mods..I can promise you though that from this point the builds will stay available after we moved to solder!

**Comment by GreatHolyCow** [comment]
Have you just tried to add the previous version to Solder to allow us to be able to launch?

**Comment by The-1-7-10-Pack** [comment]
@GreatHolyCow Building the 0.7.0 build from nothing will take me more time than you guys updating your servers, sorry. I'll note again that it won't happen again from this point. :)

**Comment by shadowstrike114** [comment]
can't you just put an empty folder or sth. as a dummy and call it v0.7.0 so the launcher won't get the error and the pack can be launched?

**Comment by The-1-7-10-Pack** [comment]
@shadowstrike114 No, because as I said, we're on a diffrent host now.
