### ISSUE TITLE
Can't play with the latest version of the mod pack .

### ISSUE THREAD

**Issue by HKEI** [The-1-7-10-Pack/The-1.7.10-Pack#18]
http://paste.ubuntu.com/9658686

**Comment by The-1-7-10-Pack** [comment]
You have an additional mod named "DQMNext", also with it's core.
It's not the modpack or the latest update.

**Comment by HKEI** [comment]
Thank you for the reply .

**Comment by The-1-7-10-Pack** [comment]
No problem

**Comment by HKEI** [comment]
Removed both DQMNext and PotionExtension but the mod pack is still crashing while creating world .

**Comment by The-1-7-10-Pack** [comment]
Did you remove all additional mods?
Please provide a crash report.

**Comment by BlackJackAres** [comment]
Crash report can be found by following this:

C:\Users\YOUR COMPUTER USERNAME HERE\AppData\Roaming.technic\modpacks\the-1710-pack\logs

Remember to replace the "YOUR COMPUTER USERNAME HERE" with your actual username.
And please paste it using (http://paste.ubuntu.com/)

**Comment by HKEI** [comment]
" Did you remove all additional mods? "

I only removed DQMNext and PotionExtension .

Crash report : http://paste.ubuntu.com/9659086

**Comment by The-1-7-10-Pack** [comment]
Try to remove all additional mods, if it works you'll know that one of them can't support the modpack.
