### ISSUE TITLE
Menu Music

### ISSUE THREAD

**Issue by mart804m** [The-1-7-10-Pack/The-1.7.10-Pack#180]
Can someone please put a link to the main menu songs or tell me which folder i can find em in. Thanks. BTW i love the modpack, not just the music :+1:

**Comment by The-1-7-10-Pack** [comment]
You can find the songs in the mods zip called "thevoxelmenumusic" or something like that.
In the zip enter assets\voxelmenu\sounds and you'll find the 4 songs. :)

**Comment by mart804m** [comment]
Thanks :D

**Comment by mart804m** [comment]
But can you give me the exact fil location. I have checked all the zip files and the closest thing i got to the songs was a LITEMOD file named "mod_voxelmenu_4.1.4_mc1.7.1.0.litemod" btw i was looking in the C:\Users\MyPC\AppData\Roaming\.technic\modpacks\the-1710-pack\cache. Is it not in the "%appdata%" file?

**Comment by The-1-7-10-Pack** [comment]
> res_voxelmenumusic_v_mc1.7.10.litemod\assets\voxelmenu\sounds

**Comment by mart804m** [comment]
Thanks mate. Found it :)

**Comment by The-1-7-10-Pack** [comment]
You should also thanks the creator of this music :)
> https://www.youtube.com/user/Extaticus

**Comment by fruitypigy** [comment]
I couldnt find that folder where is it?

**Comment by fruitypigy** [comment]
I found it but now i dont know how to get the music
Its a .litemod file correct?

**Comment by xJon** [comment]
@fruitypigy You need to open that file with Winrar or something similar to extract the tracks.

**Comment by unknowntrojan** [comment]
Well then whoever made the music stole the track menu3 from the nds game "spectrobes".

**Comment by xJon** [comment]
@unknowntrojan Or maybe he helped making it? I doubt that an artist would steal an entire piece

**Comment by unknowntrojan** [comment]
@xJon may I ask how any third party would be able to participate in a nintendo game?

**Comment by xJon** [comment]
@unknowntrojan What do you mean?
