### ISSUE TITLE
Server and Client versions don't agree

### ISSUE THREAD

**Issue by da404lewzer** [The-1-7-10-Pack/The-1.7.10-Pack#181]
After restarting their launcher, several of my players have been forced to a version that is incompatible with the server download.

The Server build obtained from http://bit.ly/The-1-7-10-Pack-Server-D-0-7-1 does not work with the recommended client build 0.7.1a

Is there an updated URL that maybe isn't on the Technic Launcher site yet? My server is officially offline due to conflicting versions, and offline if I rollback due to people not being able to reinstall plain 0.7.0

![image](https://cloud.githubusercontent.com/assets/1009346/6114742/0f930864-b055-11e4-9a1b-db27478b99ce.png)

Almost there...

**Comment by GreatHolyCow** [comment]
I also cant connect and I have even tried 0.7.1 and 0.7.1a neither will connect.

**Comment by The-1-7-10-Pack** [comment]
Well as it seems you're using the 0.7.0 server files, did I upload the wrong thing? let me check.

**Comment by da404lewzer** [comment]
The current download URL for http://www.technicpack.net/modpack/the-1710-pack.453902 is http://bit.ly/The-1-7-10-Pack-Server-D-0-7-1

If you have a direct link I can try it in case it's just the technicpack site lagging behind.

**Comment by The-1-7-10-Pack** [comment]
I just downloaded fresh server files from this URL and tried to enter with 0.7.1a, not a singel problem:
![image](https://cloud.githubusercontent.com/assets/10350644/6115024/363dda7e-b0ab-11e4-9b4e-78b26fca6061.png)

**Comment by da404lewzer** [comment]
Downloaded server and tried again. Whats strange is this time instead of complaining about block IDs, it successfully updated them. Either way, this can be probably closed as it was probably just a caching issue.
