### ISSUE TITLE
Launch Fail from Tech Launcher

### ISSUE THREAD

**Issue by JGBoon** [The-1-7-10-Pack/The-1.7.10-Pack#182]
After installing pack with no problems I push play only to see the green status bar loading but then flashes and never brings up the game,  I'm still at Tech launcher. I tried re installing pack many times  and even tried deleting folder then re installing it with no success. I thought I was having a similar issue as the previous update fixed but no luck. Please help.

**Comment by JGBoon** [comment]
Never mind I figured  it out. I had 32 bit java installed which only let me allot 1G of ram, I installed the 64 bit and it loads fine.

**Comment by The-1-7-10-Pack** [comment]
:+1:
