### ISSUE TITLE
The Old World are not Loading

### ISSUE THREAD

**Issue by D34DP5YCH0** [The-1-7-10-Pack/The-1.7.10-Pack#183]
Hello, 

my Englisch is Very Bad so sorry when you not understand me ;)

My Problem is, the Old World from the Version 0.7.0 is not working on the new Version :(

**Comment by The-1-7-10-Pack** [comment]
How is it not working? You game crash?

**Comment by D34DP5YCH0** [comment]
The Server want to Start and the Server Konsole Say ([Server thread/INFO]: Preparing level "world"
) and not more.....That is all....

**Comment by The-1-7-10-Pack** [comment]
Can you provide the WHOLE fml-server-latest.log file (from the logs folder) through this [paste tool](http://paste.ubuntu.com)?

**Comment by D34DP5YCH0** [comment]
fml-server-latest.log: http://paste.ubuntu.com/10159006/ 

I Can give you all log files when you want.

**Comment by D34DP5YCH0** [comment]
Server Console
With help of the debug-mode you can see the server console for e.g. detecting errors on startup. After activating the debug mode your server will be restarted.

Here are the log of this: http://paste.ubuntu.com/10159220/

**Comment by D34DP5YCH0** [comment]
When you want i can give you my Skype Name or the Login for Teamviewer and then you can see want happens.

**Comment by The-1-7-10-Pack** [comment]
What do you mean "the console freez"? You can't connect to the server?

**Comment by D34DP5YCH0** [comment]
Befor is Starting ??? The Console do noting... I Test it when the Server Start and After them...The Freez is by the self point. "[Server thread/INFO]: Preparing level "world"" I type "/fml confirm" but the Console give me noting Feedback.

**Comment by D34DP5YCH0** [comment]
Our formerly used world isnt loading in properly, so we try to start the server and nothing happens. it only runs on a clean save with a new world.

**Comment by D34DP5YCH0** [comment]
Thank you for your support, but we decided to start a new World please next time give the option to switch the Versions of the Pack, we could play if the pack would be aviable in the Version 0.7.0  can you make it aviable to change it to this older Version again, because the Launcher only Supports 0.7.1a and b which how i described the Server doesent run on.

**Comment by The-1-7-10-Pack** [comment]
As I already mentioned, it wasn't a possibility to do such before, but now it is, and it won't happen again! :)
