### ISSUE TITLE
Pneumatic craft assembly io unit

### ISSUE THREAD

**Issue by djandy** [The-1-7-10-Pack/The-1.7.10-Pack#184]
to create a working assembly setup you need an input and output but no matter what i try i cannot change a blue (input) to and orange (output) ive tryed it in my survival ive tryed it in my test world so i thought maybe im doing something wrong so i went to another modpack i was previously useing and it changed every time of course without this im stuck with pumping coal into an air compressor which isnt ideal and i cant cheat any advanced pressure tubes in because im in survival

**Comment by The-1-7-10-Pack** [comment]
So what exactly not working?

**Comment by djandy** [comment]
its the right click to change an input to an output you need to right click it with a wrench no matter how many times i click it nothing changes as i said i tested this with a creative world aswell as my survival and it never changes :(

**Comment by djandy** [comment]
sorry to drone on but i did change some of the buttons around to work with the jetpack mod reset all of those made sure button 2 was still only being used as it should and i am useing the correct tool so on so forth as i tested it on a different mod pack oh and i used a pneumatic craft wrench in my tests with charge in it and a creative pneumatic craft wrench in my creative world of which neither worked

**Comment by The-1-7-10-Pack** [comment]
I'm really not sure I fully understand what is the actual problem,

**Comment by djandy** [comment]
ok the io units of the assembily line you use a lazer and an io as an input and if you right click another io unit while it is on the ground it will turn into an output so will change from blue to orange i tell you what ill go on another modpack and show you

**Comment by djandy** [comment]
![2015-02-13_21 26 13](https://cloud.githubusercontent.com/assets/10949909/6195552/12c04540-b3c7-11e4-886b-dbd1901ce7df.png)

**Comment by djandy** [comment]
ok left we have an io unit middle we have a lazer right we have another io unit and then the controller to the far right now to change 1 of the blue io units to an export you need to right click it with the pneumatic drill on my hot bar this does not work i could click it all day and it will never change from blue to orange thus i can never complete this assembly line because they need an import and an export i assume its just my game as i say ive tryed exact same method on other modpacks and it will change to orange no problem at all useing the same tools and everything else works when i right click like bc or ae if its an easy fix brill if not can you tell me how to spawn 64 of them in on survival thanks :D

**Comment by djandy** [comment]
update has now solved it thanks close this thread please

**Comment by The-1-7-10-Pack** [comment]
:)
