### ISSUE TITLE
Advanced Enchantment Table bug /and/ Question 

### ISSUE THREAD

**Issue by Spellkaze** [The-1-7-10-Pack/The-1.7.10-Pack#185]
After the update, I was going to repair the enchanted obsidian armor set (Mekanism tools) that I enchanted before in the advanced enchantment table, but when I put any piece of armor, the game insta-crashed (losing the item), also,  some enchanted items from other mods also insta-crashed the game.

Here is the last crash report, I had 3 more changelogs, but they are almost the same.
http://paste.ubuntu.com/10166973/

The solution: Re-made the items and enchanted them as usual, I have tested, and repaired them, everything ok. Apparently someting is wrong with the enchantments of items that are not from vanilla and that were enchanted in the old version, but dunno.

Since I "fixed" it already, I just leave the crash report if anyone can check it and see what was causing the crash. 

==============================================================
PS: I have Cinema 4D and I can make some pictures Novaskin styled, but personalised (Skins with notable eyes, eyebrows, mouths) Here is a picture  that I made http://i38.servimg.com/u/f38/16/53/98/58/quirof10.png (Picture cropped and with a dropped quiality because it was intended for a facebook banner) . I doubt that I can make a modded styled picture (with machines and that) But If you want a new picture for another big update, you can ask me, you can even send me a vanilla world with a building of your alike :)

**Comment by The-1-7-10-Pack** [comment]
A bug with Enchanting Plus. Nothing I can do about it, but good that you're reporting it so I can be aware!
