### ISSUE TITLE
[Mod suggestion] QuarryPlus

### ISSUE THREAD

**Issue by liquid-metal** [The-1-7-10-Pack/The-1.7.10-Pack#186]
i'm big fan of BC quarry, it's leave ugly hole indeed, but its not a problem with the new aroma dimension
theres some problem that vanilla quarry can't handle, like flowing underground water/lava etc that can cause lag
with this mod theres lot of new stuff that usefull for building and such, and can fix basic problem vanilla quarry had 
i really hope you can add it into next update xD 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288467-active-1-7-10-ssp-smp-forge-yogpstops-mods

**Comment by The-1-7-10-Pack** [comment]
You should read changelogs :)
I removed QuarryPlus with v0.7.0 as it had some bugs and it was outdated for BC 6.3.
I should mention that an upgrade for a quarry can be the EnderQuarry. :)

**Comment by liquid-metal** [comment]
oh yeah...i'm a lazy bump :(
