### ISSUE TITLE
server upgrade 0.6.1 to 0.7.1 problem

### ISSUE THREAD

**Issue by killory** [The-1-7-10-Pack/The-1.7.10-Pack#187]
Hi I've been running the 0.6.1 version of the 1.7.10 pack for a month now and have been using the Minecraftserver.com.au's hosting services and have not had a problem thus far.
 
I'd be gratefull for any help I can get in regards to the matter.
when trying to update the server recently I haven't been able to keep it running, I seems to go this far

Edited: **Please post the FULL log and use a [paste-tool](http://paste.ubuntu.com/).**

**Comment by The-1-7-10-Pack** [comment]
Please update

**Comment by killory** [comment]
fml-server-latest
http://paste.ubuntu.com/10180411/

**Comment by The-1-7-10-Pack** [comment]
Do you have any additional mods?

**Comment by killory** [comment]
nothing, all is original
I even reverted back to the 0.6.1 server version and it works fine but the 0.6.1 client wont work

**Comment by The-1-7-10-Pack** [comment]
When you updated from v0.6.1 you updated the launch file too?

**Comment by killory** [comment]
yes
at one point I ran a clean install without importing world data

**Comment by The-1-7-10-Pack** [comment]
So you basically says that you're able to launch the server without your old world?

**Comment by killory** [comment]
sorry I didn't clarify enough.

**Comment by The-1-7-10-Pack** [comment]
So am I right?

**Comment by killory** [comment]
no
nothing with version 0.7.1

**Comment by The-1-7-10-Pack** [comment]
Try to launch the server files clean, without any singel file from your old server. Tell me what you get.

**Comment by killory** [comment]
that's what ive already said the error is still the same.

**Comment by killory** [comment]
that includes unpacking remotely and locally

**Comment by The-1-7-10-Pack** [comment]
With what do you launch the server?

**Comment by The-1-7-10-Pack** [comment]
It has fixed in the last version of Galacticraft, now it tells you exactly what are you missing.
