### ISSUE TITLE
golden chipset

### ISSUE THREAD

**Issue by Glassgod** [The-1-7-10-Pack/The-1.7.10-Pack#188]
the requirements for golden chipset changed fron one redstone and one gold to one redstone and 16 gold. Was this intentional

**Comment by The-1-7-10-Pack** [comment]
Huh?
![image](https://cloud.githubusercontent.com/assets/10350644/6154841/6576a6ee-b237-11e4-9f5a-0b1ba65abb4d.png)

**Comment by Glassgod** [comment]
it corrected itself after i reloaded thanks for replying however

**Comment by The-1-7-10-Pack** [comment]
:)
