### ISSUE TITLE
FML isnt loading so i cant play

### ISSUE THREAD

**Issue by DragonMaster260** [The-1-7-10-Pack/The-1.7.10-Pack#189]
i cant seem to get any mods on so i cant log on to the server PLZ HELP IVE BEEN WANTING TO PLAY ALL DAY

**Comment by The-1-7-10-Pack** [comment]
Just download the whole server package and click "LaunchServer.bat".

**Comment by DragonMaster260** [comment]
uuuhhh im kinda new to this so how do i do that?

**Comment by DragonMaster260** [comment]
PLZ AWNSER ME

**Comment by DragonMaster260** [comment]
how does one download the whole server package and click launchserver.bat

**Comment by The-1-7-10-Pack** [comment]
Do you know from where to download the server files?
After you download them, you unzip them to a folder and launch.

**Comment by DragonMaster260** [comment]
no i dont know where to download the server files will you tell me?

**Comment by GreatHolyCow** [comment]
http://www.technicpack.net/modpack/the-1710-pack.453902 on the right says Server Download

**Comment by DragonMaster260** [comment]
ok i downloaded it and clicked launchserver.bat and it says 

OS is 64
Error: missing `server' JVM at `C:\Program Files (x86)\Java\jre1.8.0_31\bin\serv
er\jvm.dll'.
Please install or use the JRE or JDK that contains these missing components.
Press any key to continue . . .

and when i press a key it does absolutely nothing to the server

**Comment by GreatHolyCow** [comment]
Well it clearly tells you... U need the java runtime environment hence u
should use google

**Comment by DragonMaster260** [comment]
ok i feel so dumb for saying this but look it up on google you mean?

**Comment by da404lewzer** [comment]
Are you submitting a bug or asking to learn to setup servers? The issue described doesn't seem to be directly related to the pack but I think GreatHolyCow has put you on the correct path for fixing your Java issue, but as far as minecraft servers go you literally download the zip, extract the contents and run 'LaunchServer.bat'. I can't imagine what steps you are asking for unless you need help forwarding ports or setting up a vpn, in which case Google it :)

You can find the pack's page here: http://www.technicpack.net/modpack/the-1710-pack.453902
You can download the current server version here: http://bit.ly/The-1-7-10-Pack-Server-D-0-7-1
You can find information on how to setup windows servers here: https://www.google.com/search?q=How+to+setup+a+technic+server+on+windows

This thread can probably be closed...

**Comment by DragonMaster260** [comment]
wait no dont close it!!!!! my problem isnt solved im not trying to make a server im trying to connect to the main one!!! in my screenshot i posted i htought you guys would get that it was the mai nserver i was talking about so if you could help me with that it would be very appreciated because no matter what i try, FML will not let the server load

**Comment by GreatHolyCow** [comment]
So now your not asking about server files but want a client so u can connect to the official server?!?!?!
the launchserver.bat runs a server not connect you to a server... get the technic launcher and choose it from the list of mods

**Comment by DragonMaster260** [comment]
excuse me but get what from the list of mods? i have changed my name so that might be the problem

**Comment by GreatHolyCow** [comment]
to be honest the way you figure things out and read sentences, I wouldn't want you near any of my modded servers. But since you can't go to http://www.technicpack.net/download and login with ur minecraft id and under the mods tab at the top search The 1.7.10 Pack download/install and play

**Comment by DragonMaster260** [comment]
i already have the technic launcher all i need to find out is why the servers arent working for some reason

**Comment by GreatHolyCow** [comment]
apparently not if your trying to run launchaserver.bat instead of the technic launcher

**Comment by DragonMaster260** [comment]
well the owner was the one who told me to run it so i guess he caused this thread to go so out of focus

ans no i dont blame him

**Comment by GreatHolyCow** [comment]
your screenshots clearly are telling you your mods are different versions. either the server is testing a update or hasn't updated and your not at the same version

**Comment by DragonMaster260** [comment]
ahhh so should i update the pack in the modpack sections tab of the pack and switch it to the "lates version" or just keep it at recommended version

**Comment by da404lewzer** [comment]
I suggest reinstalling the pack.

You can do this by clicking on the modpack in the launcher, clicking Modpack Options in the top right. 

Verify 'Recommended Version' is selected and clicking 'Reinstall Pack'

**Comment by GreatHolyCow** [comment]
try either version till you find what the server is running

**Comment by DragonMaster260** [comment]
kk thank you i will do that now

**Comment by DragonMaster260** [comment]
ok reinstalling the pack did not work im gonna try switching it to latest version now

**Comment by DragonMaster260** [comment]
well......... f**king fantastic neither of those suggestions worked @_@ idk what to do

**Comment by GreatHolyCow** [comment]
Perhaps you need to find out from the server owner what version of the mudpack you need....

**Comment by DragonMaster260** [comment]
how can i get his attention?

**Comment by GreatHolyCow** [comment]
well this is a site if you have problems with the mod itself not connecting to peoples servers...

**Comment by DragonMaster260** [comment]
well where else am i supposed to go if i cant connect to ther server and have no idea what to do?

**Comment by GreatHolyCow** [comment]
whats the servers ip:port your connecting to?

**Comment by da404lewzer** [comment]
I have verified the public server is on a different version than the recommended build. I guess you'll need to wait for the author to respond. If you absolutely can't wait try installing older versions starting with 0.7.0

**Comment by DragonMaster260** [comment]
when will it be to the reccomended build again?

**Comment by The-1-7-10-Pack** [comment]
Can you please be more clear? What is the actually problem at the moment?

**Comment by GreatHolyCow** [comment]
He essentially is complaining the official server is not running the latest or recommended and he cant play on it because of that.

**Comment by The-1-7-10-Pack** [comment]
@GreatHolyCow The current server download is for v0.7.1. As v0.7.1a & v0.7.1b are client changes only, he probably just have the wrong version of the modpack installed.

**Comment by da404lewzer** [comment]
As stated by me a couple messages ago... "I have verified the public server is on a different version than the recommended build. I guess you'll need to wait for the author to respond. If you absolutely can't wait try installing older versions starting with 0.7.0"

**Comment by GreatHolyCow** [comment]
no hes trying to play ON THE OFFICIAL SERVER not start a server.... and its running old mods

**Comment by da404lewzer** [comment]
As you can see, I have 0.7.1 and the server at "Magitechworld.com" is complaining. You can also see my server in the list which is up-to-date.

![image](https://cloud.githubusercontent.com/assets/1009346/6200842/6b7737f2-b43f-11e4-882d-92bd0455f46c.png)

![image](https://cloud.githubusercontent.com/assets/1009346/6200843/72682738-b43f-11e4-960e-3d1b19b7a8a3.png)

![image](https://cloud.githubusercontent.com/assets/1009346/6200844/7be90d04-b43f-11e4-8855-3318c9d06a34.png)

**Comment by da404lewzer** [comment]
However I do notice I need to update my MOTD because it says 0.7.0 whoops!

**Comment by The-1-7-10-Pack** [comment]
The MagiTech server does not support The 1.7.10 Pack anymore.

**Comment by da404lewzer** [comment]
It's claiming to be the official server. Did you switch hosts or do you not have an official server?

**Comment by The-1-7-10-Pack** [comment]
Well I can talk to Fluke and tell him to update the MOTD but it is not the official server anymore. There is no official server to the pack at this point. It's just too hard to make any official modded server without Cauldron or Forge Essentials support. This is why the MagiTech server has it's own modpack now.

**Comment by DragonMaster260** [comment]
whats the modpack for it then?

**Comment by GreatHolyCow** [comment]
dude go to magitechs website not here he just told u thats not the official server

**Comment by DragonMaster260** [comment]
whats the website?

**Comment by GreatHolyCow** [comment]
GOOGLE IT. NOT OUR JOB TO PROMOTE ANOTHER PERSONS MODPACK HERE

**Comment by DragonMaster260** [comment]
jeez

**Comment by tetsuraryuuken** [comment]
Amazing the answers you can find to questions you didn't have when you use Google...

**Comment by GreatHolyCow** [comment]
might want to read some of the last few posts.... because its up in the previous posts....
http://tinyurl.com/ogerrph

**Comment by Aninhafofa77** [comment]
what is the address of the public server? Please answer me as soon as possible .

**Comment by GreatHolyCow** [comment]
Aninhafofa77 did you read this post at all thats a public server to another modpack not this one...
