### ISSUE TITLE
can't craft MFR stuff?

### ISSUE THREAD

**Issue by Plasmatique** [The-1-7-10-Pack/The-1.7.10-Pack#19]
Hi,

for some reason when using this modpack I can't craft MFR items like the auto-spawner, blockbreaker, planter, etc. Did you change any configs to disable these or did I mess something up?

Cheers!

**Comment by chrisps89** [comment]
I had no problem creating the auto-spawner myself, Have you added anything to the modpack yourself or changed anything about it ? Are you using the new 0.6.1 version also ? And are you using the right recipes? I assume you are but worth double checking.

**Comment by Plasmatique** [comment]
Sorry for the late reply....it seems it had to do with the config file (common.cfg). Where it says RecipeSets, vannila-only was set on true and the enderIO/TE ones on false. I changed them all to true and that fixed it right up. I do have some issues with not being able to get certain items from certain mods (like the mekanism bronze shovel is impossible to get, even with only mekanism bronze...for the bronze paxel for example, which needs the 3 tools from the same mod to make it), but I'm looking into that.

Thanks for the quick response and once again sorry for the delay!

Dylan

**Comment by The-1-7-10-Pack** [comment]
The configs that you mention are not the default configs that come with the pack.
The modpack is using MFR's recipes with TE\EiO, and not vanilla.
Anyway, happy you were able to fix it yourself.
