### ISSUE TITLE
chocolate quest (aka better dungeons mod)

### ISSUE THREAD

**Issue by maartenblom** [The-1-7-10-Pack/The-1.7.10-Pack#190]
I know this mod has been asked to add before, but it was really short and i don't think it got the attention the mod deserves. Better dungeons mod adds new dungeons. The mod has got some dungeons, but i think they are really weak. By adding the better dungeons mod, you can attract a new group of mine crafters, the dungeon guys, the people that play hexxit and stuff. I think by doing this you enhance the modpack. I hope you will take this in serious consideration.
maarten, a loyal player of this modpack

**Comment by The-1-7-10-Pack** [comment]
Well now after there's a [proper release](http://minecraft.curseforge.com/mc-mods/60265-better-dungeons/files/2227053) I will consider this!

**Comment by DragonMaster260** [comment]
yes please i love this mod

**Comment by liquid-metal** [comment]
yes please!, i just watch the mod showcase, and its looks awesome :D

**Comment by ChinesePeanuts** [comment]
That would be so great :D

**Comment by DragonOfStendarr** [comment]
It really would be great! :D

**Comment by ChinesePeanuts** [comment]
Just a question !
I guess that we'll have to regen maps to gets the dungeons, but what if we already have a world, we will have to loose everything to get the dungeons ?
It's in fact the same question for the End extension !

**Comment by The-1-7-10-Pack** [comment]
@ChinesePeanuts No! You'll just need to generate new chunks and then the chance to have a "Chocolate Quest" dungeon will be available. About HEE: I'm not sure about this one.

**Comment by DragonOfStendarr** [comment]
If i'm not wrong you can actually use a item in creative from chocolate quest and spawn dungeons. i did do that on another modpack x)

**Comment by The-1-7-10-Pack** [comment]
@DragonOfStendarr You indeed can.

**Comment by Deathwater57** [comment]
Looks great

**Comment by NoGood4Me** [comment]
This mod has not been added? Version 1.7.10 is already there.

**Comment by The-1-7-10-Pack** [comment]
@NoGood4Me: No; the mod has not been added *yet*.

**Comment by NoGood4Me** [comment]
Is it worth it to wait for the next update?

**Comment by The-1-7-10-Pack** [comment]
@NoGood4Me What do you mean?

**Comment by NoGood4Me** [comment]
I mean, will it be added?

**Comment by The-1-7-10-Pack** [comment]
@NoGood4Me Not sure yet. It's a big mod and only one release for 1.7.10? I want to be sure it's stable.

**Comment by TreePuncher9501** [comment]
Honestly, with the new map GUI for Voxelmaps it shouldn't be hard finding new chunks. Sounds good to me!

**Comment by maartenblom** [comment]
yeah

**Comment by Gifftron** [comment]
This would be a real treat, I remember playing this mod in Hexxit a long time ago, I'm sure they've added new content since then

**Comment by CriticalRocket** [comment]
I want this! :D

**Comment by mandm635** [comment]
I think this would be a great addition to the pack!

**Comment by Smalfinn** [comment]
I am so ready for better dungeons to be added! :D

**Comment by skittishtrigger** [comment]
Just as an update to this convo: I had BetterDungeons/CQ on my server and in my modpack. There is a LOT of config that needs done, a LOT of know caveats, and 0 support that is not community based. Chocoltin is (the mod dev) fleeting at best and VERY RARELY does any sort of fixes or updates. There was a minor, forked, fix by someone else but there was still many issues. It is a fun mod for sure that adds a lot of elements to the game but I would add it at your own risk.

**Comment by The-1-7-10-Pack** [comment]
@skittishtrigger It is a shame. There was support for 1.6.4 but currently with about 4 updates only in 1.7.10 that just one of them is a release it won't be added. Maybe in the future.
