### ISSUE TITLE
16384k Storage not claimable... 

### ISSUE THREAD

**Issue by GreatHolyCow** [The-1-7-10-Pack/The-1.7.10-Pack#191]
After building every component for the 16384k Storage and manually crafting the final 4 stages of the 16384k drive. I still cant get credit for it. No a network did not auto craft the final things. I also tested in single player with crafting station vs crafting table. Still no luck.

![](http://i.imgur.com/mGioIDT.png)

**Comment by The-1-7-10-Pack** [comment]
Haha seriously? HQM PLZ. Let me test it.
If it's a bug it'll get fixed next update.

**Comment by The-1-7-10-Pack** [comment]
Derp.

**Comment by GreatHolyCow** [comment]
can we perhaps make it a manual detect so I and others don't have to waste another ton of supplies to do it again?

**Comment by The-1-7-10-Pack** [comment]
This is what I planned.
