### ISSUE TITLE
I got an problem login to the minecraft the 1.7.10 modpack

### ISSUE THREAD

**Issue by KLCHANJOHN** [The-1-7-10-Pack/The-1.7.10-Pack#192]
Hi sir/madam,

I currently playing a modpack the 1.7.10 in minecraft. It was first working fine at the beginning however now i have just have a problem of couldn't login to the game. Everytime I run the game I stucked in the logging in page or even if i could get in the game but i kept falling in the game to darkness until a message of "Time out or connection lost" come out. This problem is so annoying as i really like gaming in minecraft mod. Please kindly help me to solve out this problem. Much appreciate!

I attach below a link for my current Dxdiaglog
http://pastebin.com/b20Ep6d7

And link for my latest game log
http://pastebin.com/PpxqESnQ

Thanks a lot!!!!

**Comment by GreatHolyCow** [comment]
are you able to play vanilla minecraft just fine?

**Comment by KLCHANJOHN** [comment]
Hi greatholycow,

Yes I able to play vanilla on my computer just fine.

**Comment by The-1-7-10-Pack** [comment]
You should try reinstalling Java, also version 8 is recommended.

**Comment by KLCHANJOHN** [comment]
i tried reinstalling java 8 x64bit version but problem remain the same. I attached my latest game log and Dxdiaglog below much appreciate your help.

Latest game log:
http://pastebin.com/nCawDphX

Latest Dxdiaglog:
http://pastebin.com/MWAZci3p

Thanks a lot!!

**Comment by The-1-7-10-Pack** [comment]
When does this problem occur exactly?

**Comment by The-1-7-10-Pack** [comment]
Closed due inactivity.
