### ISSUE TITLE
Minecraft not loading

### ISSUE THREAD

**Issue by SJB-Joker** [The-1-7-10-Pack/The-1.7.10-Pack#193]
When I attempt to play the game it shows a loading menu then once the loading is done nothing happens, it simply repeats the process if I attempt it again

**Comment by The-1-7-10-Pack** [comment]
Did you read how to report a bug? Please do.

**Comment by Arganath** [comment]
that's happening to me too

**Comment by The-1-7-10-Pack** [comment]
Well I can't do anything when you don't know how to report a bug.

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information.
