### ISSUE TITLE
Server Automatically Shuts Down After 1-2 Seconds of Running

### ISSUE THREAD

**Issue by MurfsGaming** [The-1-7-10-Pack/The-1.7.10-Pack#194]
I am able to launch the server, and it even goes through all of the steps it needs to launch. However, once the server is live and able to be connected to, it crashes anytime someone connects.

Honestly have no clue what is causing this problem. It even happens after I've re-downloaded the server file and run everything as default. EULA is set to true, I've used "LaunchServer.bat" and the normal java server files included, and still no success.

-Wyatt Murphy

**Comment by GreatHolyCow** [comment]
any logs?

**Comment by da404lewzer** [comment]
How much ram does your server have and have you modified your LaunchServer.bat at all?

**Comment by MurfsGaming** [comment]
I think it has something to do with my world folder. Is there something that is no longer compatible from the old worlds? 

I only modified the server to have 8G of RAM, I didn't edit anything else.

**Comment by The-1-7-10-Pack** [comment]
Please provide the fml-server-latest.log file, we can't help you without it.

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information.
