### ISSUE TITLE
Ships mod suggestion

### ISSUE THREAD

**Issue by Justcorry** [The-1-7-10-Pack/The-1.7.10-Pack#195]
Stumbled across a mod that lets you make and sail custom made ships. It's a niche that I haven't seen filled by other available mods yet so it might make a nice addition.

http://www.planetminecraft.com/mod/beta-ships-mod---make-a-sailable-ship-out-of-blocks/

**Comment by The-1-7-10-Pack** [comment]
I don't see anyone using it. Just make a JetPack! It's a fast world!
