### ISSUE TITLE
Can't load previously made worlds.

### ISSUE THREAD

**Issue by Deathwater57** [The-1-7-10-Pack/The-1.7.10-Pack#199]
I've made 2 worlds now both have had at least 2 hours or work put into them and then i get off and load the world and as soon as it says building terrain goes back to the main menu with the choices like singleplayer and multiplayer and such, uninstalled the pack and reinstalled, changed my ram allocation, and restarted my computer to no avail i have no idea what else to try and don't feel like making another world and having to restart from the beginning again. So a solution would be much appreciated. 

http://paste.ubuntu.com/10231481/

Most recent log

**Comment by The-1-7-10-Pack** [comment]
And you can create and enter fresh-made worlds no problem?

**Comment by Deathwater57** [comment]
Yes but i assume that just like these two worlds that it will only work until i leave the world

**Comment by The-1-7-10-Pack** [comment]
Check it please, don't assume.

**Comment by Deathwater57** [comment]
now it's just saying insallling libraries and then the loading bar flashes on the launcher and the launcher just stays like it is.

**Comment by Deathwater57** [comment]
okay i fixed the launch issue now but as i stand corrected i can't even make a new world.

**Comment by The-1-7-10-Pack** [comment]
So it's a problem with your modpack installation. Try to go to .technic/modpacks and completely delete the folder named "the-1710-pack": **Just be sure to backup your saves folder before**.

**Comment by Deathwater57** [comment]
already did that and the problem persists.

**Comment by Deathwater57** [comment]
Okay bit of an update when curious i tried converting the world to a server and it crashed my minecraft entirely and took me back to the Technic Launcher. That was when i tried loading the server through the minecraftserver.jar instead of the ForgeUniversal.jar. I now loaded it through the forgeUniversal.jar and i'm able to access the world. Also even though i had already uninstalled it  and reinstalled it. i did it once more to fix my inability to make a world and then was able to. Although i'm still not able to play on my world in singleplayer i can still play it via online server.

**Comment by The-1-7-10-Pack** [comment]
Well, good thinking.
I have no idea why were you not able to play through singel player though.
