### ISSUE TITLE
HQM Quest - Mission: "I believe I can fly" Can't be completed / Suggestion

### ISSUE THREAD

**Issue by Spellkaze** [The-1-7-10-Pack/The-1.7.10-Pack#200]
Hi, in the HQM Quest there is a mission called "I believe I can fly", but it can't be completed because de quest mod don't accept the item, here are the proofs:
Picture of the mission: http://i.imgur.com/Sny7kFo.png
Picture of the item that I have but is not getting accepted: http://i.imgur.com/cYsocsm.png
(I crafted the Flux-Infused without any enchantments, so I don't think that would be the problem, also that the mission checks the inventory at any time)

The item is the same, so there is the problem, not a big one, but there it is.

----- Second part, the suggestion

Also, I think that there is something that can be changed in the mission, there are two types of this jetpack.
- Flux-Infused Jetpack
- Dark Soularium Jetpack

This Jetpacks have the same features, the only difference is that the Flux-Infused is crafted with Thermal Expansion items, and Dark Solarium Jetpack is made of Ender IO items.

I don't know if the mission can let make the players choose which items they prefer to make the jetpacks, in other words, the mission can be complether when you have the other Flux armor and the Flux-Infused Jetpack or the Dark Soularium Jetpack, since they are the same.

 I think that the mission could let the player choose what items from which mod it's going to use,  this is to let the players keep their preference. Like I said before, both items have the same features, so it's not unbalanced or anything.

I actually prefer the thermal expansion, but if you can make this mission to be completed with one of any of the two armors, I think it would be less of a pain for someone who likes using the Ender IO mod.

Well, the first part of this was a bug report, and the second part is most likely to be a suggestion, do what you like with the last part :)

**Comment by The-1-7-10-Pack** [comment]
I already thought about it but no, you can't let the player choose. Also, as the armor is made with Thermal Expansions, it'll make more sense to use Thermal Expansions JetPack. About the bug: let me see.
