### ISSUE TITLE
Optifine Issue 

### ISSUE THREAD

**Issue by ChinesePeanuts** [The-1-7-10-Pack/The-1.7.10-Pack#203]
First, thanks a lot for this awesome pack !
Now, the problem is, when using Optifine (as you recommend it) some blocks don't display, even without any resource pack
Optifine is definitely the problem, but I can't say why..
Without it, there is no problem

I don't know if you'll be able to help me, and even if it's the right place to ask 
But thanks in advance !

Keep doing this awesome pack & thanks for your help

**Comment by The-1-7-10-Pack** [comment]
It was a problem with an old version of Optifine, are you sure you're using the latest version?

**Comment by ChinesePeanuts** [comment]
Well, I was using the A4 Version, my bad, I'll try with the newest one !
Thanks
