### ISSUE TITLE
Suggestion Smartmoving?

### ISSUE THREAD

**Issue by Tanker24** [The-1-7-10-Pack/The-1.7.10-Pack#205]
Hello first I would like to thank you for your work on this great modpack and secondly I would like to suggest smart moving it may conflict with the mods already in but I wanted to suggest it so I know I am not crazy for not having it already in there. Its a great mod allowing different movements and just great fun. If its incompatible and its blatant sorry for wasting your time.

**Comment by The-1-7-10-Pack** [comment]
Smart Moving completely changes how you move in Minecraft.
Some players like it, some not, and it doesn't really fit the Magic-Tech modpack.
Thanks anyway!
