### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by CuseCose** [The-1-7-10-Pack/The-1.7.10-Pack#207]
There was an error updating the pack, I've tried re-installing it and deleting it and doing it again but I keep getting this error:

Failed to download http://solder.endermedia.com/repository/mods/factorization
![1 7 10](https://cloud.githubusercontent.com/assets/11051434/6237971/e4731264-b6bc-11e4-9976-978c478f6074.PNG)

**Comment by CuseCose** [comment]
yeah, please help, this is my favorite pack.

**Comment by CuseCose** [comment]
I just remembered i added mystcraft to the pack so is that is the problem please tell me how to fix it, I will try to remove it on my own though.

**Comment by CuseCose** [comment]
I deleted the 1.7.10 folder from technic and installed it again and still it hasn't worked, keep getting the same problem

**Comment by DetShaft** [comment]
I'm having the same problem, I believe its a problem with the repository that is setup for factorization to download from. I think he will have to (or technic) change the download site or something that is used. Just give it time.

**Comment by CuseCose** [comment]
D;

**Comment by kilps31** [comment]
I have this problem too.

**Comment by CptMcDoipe** [comment]
I got this problem as well on a mac.
![screen shot 2015-02-17 at 18 58 40](https://cloud.githubusercontent.com/assets/11052880/6240144/c7a87ed2-b6d8-11e4-9f81-7827a7309ca6.png)

**Comment by Rebelyrocks** [comment]
I have the same problem

**Comment by The-1-7-10-Pack** [comment]
@DetShaft @kilps31 @CptMcDoipe It was a stupid thing to do with the host that started to happen the second I got to sleep. After I woke up I fixed it, just one click - that simple.
