### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#209]
I dont know why my server wont start EULA  is set to true, its everything untouched.
and i cant type the /fml confirm 

http://paste.ubuntu.com/10291755/

**Comment by The-1-7-10-Pack** [comment]
You need to type /fml confirm, that's it.
Why can't you type that?

**Comment by thebalck** [comment]
Because when that line come on the screen the console wont accept any code

**Comment by The-1-7-10-Pack** [comment]
No way. Just click on the console, type the code and press enter.
