### ISSUE TITLE
whenever i make a Tconstruct crossbow (or whenever i put the bowstring in) my computer crashes

### ISSUE THREAD

**Issue by DragonMaster260** [The-1-7-10-Pack/The-1.7.10-Pack#21]
when i tried to make a crossbow i put the bowstring in and it crashes and i tried it with the fiery bowstring and the regular bowstring im not sure with the enchanted one

**Comment by DragonMaster260** [comment]
oh when i said computer in the title i meant the minecraft window

**Comment by chrisps89** [comment]
Hmm, worked fine for me with a fiery bowstring, can you post your crash log into http://pastebin.com .

Are you using the latest version of the modpack also ?

**Comment by DragonMaster260** [comment]
idk how to use pastebin and i am using the right version 0.6.1

**Comment by DragonMaster260** [comment]
but i did find my crash report

**Comment by DragonMaster260** [comment]
oh wait nvm it was because i was using a plastic base XD

**Comment by chrisps89** [comment]
Ahh hehe, Guess this can be closed now then,

**Comment by BlackJackAres** [comment]
Would you mind posting your crash report anyways for future reference?

**Comment by The-1-7-10-Pack** [comment]
Anyway you should report it for the mod itself.
