### ISSUE TITLE
World won't open.

### ISSUE THREAD

**Issue by TANGOjPANDA** [The-1-7-10-Pack/The-1.7.10-Pack#210]
So i downloaded the latest update and I try to open/create a world and it closes and returns to the title screen.
I am running with java 8 update 31.Any help will be appreciated.
The log shows me trying to open an existing world and trying to open one i just made.
Both have the same result.
I have tried fresh install of the modpack. (Also i never added any extra mods.)
Here is a log.

https://drive.google.com/file/d/0BxuUL_FVvnL9cGF1cGRsRXpkUUE/view?usp=sharing

Thanks in advance!  :-)
P.S. Any question i'll try to answer in a few hours.

**Comment by The-1-7-10-Pack** [comment]
That's weird..
Try to completely delete the modpack's folder (.technic/modpacks/the-1710-pack).
After that, try to do a fresh install, but before you launch, delete one specific mod named "colorchat" from the modpack's folder.

**Comment by TANGOjPANDA** [comment]
That seems to have worked and I have reopened and closed it a couple of times. So thanks again I'll let you know if I manage to break it again.

**Comment by The-1-7-10-Pack** [comment]
So the mod has a problem. I hope it won't happen again.
I'll consider removing this mod from client side if it happens again, be sure to let me know!
