### ISSUE TITLE
Game crashes when opening inventory/chests/etc.

### ISSUE THREAD

**Issue by cookiebeard** [The-1-7-10-Pack/The-1.7.10-Pack#211]
Every time i try to open my inventory/chests/etc. (both in survival and creative) when playing LAN (it works perfectly fine in single player) the game crashes. The person hosting the game does not have any problem at all. 

Tried to uninstall/reinstall the game several times. Also looked in the log, but did not understand much of it. Here it is http://paste.ubuntu.com/10306286/

Thanks in advance

**Comment by The-1-7-10-Pack** [comment]
Really? I got to admit I have no idea why does this happen, probably a mod bug of NEI.
Anyway you shouldn't run a LAN server with too much mods.
Setting up a normal server on LAN is 2 minutes aswell.
