### ISSUE TITLE
Adding advanced solar panels

### ISSUE THREAD

**Issue by Nemet01** [The-1-7-10-Pack/The-1.7.10-Pack#212]
Hello I would like to suggest Advanced solar panels for your modpack. 
It would fit with the modpack by adding the 4 or 5 new solar panels and some extra stuff.

**Comment by The-1-7-10-Pack** [comment]
I thought about it already but we got compact solar.
Do you think we should switch between the mods?

**Comment by Nemet01** [comment]
If I want to be honest it would be better

**Comment by The-1-7-10-Pack** [comment]
What is better in advanced solars than compact solars?

**Comment by Nemet01** [comment]
Well for me its makes more challenging to get and I'm kinda got used to them (thats why I add it back after every update), and also the extra machines whats comes with them, the molecular transformer for example.

**Comment by The-1-7-10-Pack** [comment]
Although it'll be a problem switching the mods. Who built the old solars will have to make them all over again.
I think that for now we'll keep it as is, I hope you'll understand.
Thanks for the suggestion!

**Comment by xJon** [comment]
Advanced Solar Panels has been added in version `0.10.5`!
