### ISSUE TITLE
Hardmode Questing Mod

### ISSUE THREAD

**Issue by joelou1** [The-1-7-10-Pack/The-1.7.10-Pack#213]
For some reason I can't seem to be able to open my Quest book on my friend's server. Leaving this weird comment in my log. Single-player freshly created do however open the book.
http://paste.ubuntu.com/10312622/

Issue:
- Can't open the questing book on Multi-Player.

I couldn't find any information about it on the web.

**Comment by The-1-7-10-Pack** [comment]
Your friend have old configs, tell him that when he updates the server he need to update the configs folder too.
