### ISSUE TITLE
Everything Changed

### ISSUE THREAD

**Issue by FirstWorldMatt** [The-1-7-10-Pack/The-1.7.10-Pack#214]
When i was updating to the 7.2 version i clicked cancel cause i needed to go do something. so when i came back i forgot to finish the update and tried to go back to the 7.1 version but when i came back there was only minecraft stuff. So i remenber that i needed to update it and i go back to the launcher and update it but when i come back all the blocks were turned into other blocks. Is there a way to access a load so i can reset it back to normal or do i need to do everything all over again?

**Comment by The-1-7-10-Pack** [comment]
You have backups. Use one, end of story :)
