### ISSUE TITLE
Mod suggestion: POWER!!!

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#215]
hi would mind adding Atomic Science Mod and Open Modular Turrets ,this pack deserves a bit of dark matter and defense to spice it up ,do you agree?

http://www.minecraftdl.com/atomic-science-mod/
[Atomic Science] this mod is an alternative to big reactors , you can build Hadron Collider to obtain anti matter, fission reactors...etc game mechanics as great as big reactors.

[Open modular turrets], as you may know modular turrets in voltz is out dated,
but one of the developers in the original team took the concept and created this new mod.
http://www.curse.com/mc-mods/minecraft/224663-openmodularturrets

**Comment by The-1-7-10-Pack** [comment]
- Atomic Science: We have Big Reactors, why would we want to have ANOTHER alternative for big power? This modpack has enough options to get power in a cool way!
- Open Modular Turrets: We got Flan's Mod for this kind of action!

Thank you anyway for the suggestions :)

**Comment by xJon** [comment]
Open Modular Turrets was added version `0.10.5`!
