### ISSUE TITLE
Mod Suggestion: Ars Magica 2

### ISSUE THREAD

**Issue by SAWMAN1337** [The-1-7-10-Pack/The-1.7.10-Pack#216]
A look into what Minecraft could become when you add a splash of magic...Ars Magica is a mod about casting powerful spells, fighting bosses, and having fun with magic! It features a unique spell creation system where you can create any spell you can imagine!

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292222-ars-magica-2-version-1-4-0-008-updated-february-6

**Comment by The-1-7-10-Pack** [comment]
#59, #73, #142
