### ISSUE TITLE
Server Doesnt Crash but client crashes when holding a riot shield

### ISSUE THREAD

**Issue by SwaginWagon101** [The-1-7-10-Pack/The-1.7.10-Pack#217]
My friend said he couldnt get on our server after he made a riot shield and crasehd. But after i removed the riotshield from his inventory, i still crashed. This is my client crash log

**Edited: please use a paste-tool.**
http://paste.ubuntu.com/10323784/

**Comment by The-1-7-10-Pack** [comment]
Well, Optifine has it up and downs.
Nothing I can do about it.
