### ISSUE TITLE
How to make a server

### ISSUE THREAD

**Issue by Tdoggy** [The-1-7-10-Pack/The-1.7.10-Pack#219]
I love the modpack but would really love to play it with my friends. but i am clueless on how to accomplish that. i know you download the server but from there im lost i dont know what goes where. i would really appreciate it if you helped me. Thank you.

**Comment by The-1-7-10-Pack** [comment]
Just unzip the server files and double click the "LaunchServer.bat" file.
Then some things will happen, the console will open and close. You'll see that a text file named "eula" has appeared. Enter it, and change the "false" to "true", be sure to read the whole document too.
After that, double click the "LaunchServer.bat" file again and you're off! To play with your friends you just need to open ports. Google will be your best friend for this second step.
