### ISSUE TITLE
NEI Bug

### ISSUE THREAD

**Issue by BlackJackAres** [The-1-7-10-Pack/The-1.7.10-Pack#22]
In the NEI screen when holding down shift to find item info, instead of displaying item info it changes all pathings and texts to "UNNAMED" but has no other known side effects. 

Example below.

Without Shift:

![image](https://cloud.githubusercontent.com/assets/10352736/5601260/6e8b6308-92a9-11e4-9ffb-fea48c20ac35.png)

With Shift:
![image](https://cloud.githubusercontent.com/assets/10352736/5601261/75984148-92a9-11e4-8d1b-242f5cacae6f.png)

**Comment by chrisps89** [comment]
I can't replicate that in singleplayer or on my server, shift for me just shows the energy exchange value or states "no exchange value". Couldn't replicate on public server either.

**Comment by BlackJackAres** [comment]
It seems to be player specific. I know of 2 other players with my bug and 1 player with a different sort of the same kind. For him EVERYTHING shows up as unnamed regardless of shift being pressed.

**Comment by The-1-7-10-Pack** [comment]
Really weird. it can be NEI, NEI Integration or NEI Addons. anyway, there's nothing I can do about it for now. If you wish, you should report it to all the mods I mentioned above.

**Comment by The-1-7-10-Pack** [comment]
Try to reset NEI, NEI Integration and NEI Addons config files.

**Comment by BlackJackAres** [comment]
How would I go about doing this?

**Comment by The-1-7-10-Pack** [comment]
Go to .technic/modpacks/the-1710-pack/config
there, search for NEI (Folder), NEIAddons, and neiintegration. delete all 3 files and try again. do both clietn and server, and update here.
