### ISSUE TITLE
Just updated to 0.7.2 launch issue, technic launcher

### ISSUE THREAD

**Issue by pie113** [The-1-7-10-Pack/The-1.7.10-Pack#220]
When I had updated the modpack, I tried launching but it wouldn't open minecraft. I've tried every other modpack I had and they worked. What could be done to potentially fix this.

**Comment by The-1-7-10-Pack** [comment]
Please read [how to report a bug](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by jwik01** [comment]
Different person, but same problem.

http://pastebin.com/xEr93HNy

**Comment by The-1-7-10-Pack** [comment]
You guys are a joke. Java 6? C'mon. Did you even read how to report a bug?
I'm closing this one.
