### ISSUE TITLE
How to get server after opening bat file and Eula. Don't know about port forwarding 

### ISSUE THREAD

**Issue by domcomrom** [The-1-7-10-Pack/The-1.7.10-Pack#221]
Need help really want to make a server for my friends. I'm stuck on the port forwarding part a little help would be appreciated thank you

**Comment by Tdoggy** [comment]
yeah im having a small amount of trouble with that to. Where do i put the 1.7.10 pack into the .technic modpacks or actually inside the 1.7.10 modpack file then what do i do i read something about entering localhost into the ip address and then port forward but it says it cannot find the server.

**Comment by The-1-7-10-Pack** [comment]
Guys after you got your console up and running after eula.txt is set to true just see a normal tutorial, I can't give that support because I need to focus about stuff that is about the modpack itself.
There are TONS of tutorials out there.
