### ISSUE TITLE
Power Generation stops

### ISSUE THREAD

**Issue by Gifftron** [The-1-7-10-Pack/The-1.7.10-Pack#223]
Hi,

Since updating to 0.72 magmatic dynamos and a couple other generators randomly stop producing RF.  The only thing that seems to start them up again is if I stop the server and restart.  Anyone else experiencing this?

**Comment by Gifftron** [comment]
By a couple other I mean Low voltage solar arrays and biomass generators

**Comment by The-1-7-10-Pack** [comment]
Are they chunk loaded?..

**Comment by Gifftron** [comment]
They should be, I was standing next to them, maybe the old server hardware I'm using is to blame.  Not keeping up when I come back from the moon

**Comment by Gifftron** [comment]
Its occurring currently on my low voltage solar panels if you want to come check it out I can email you server info

**Comment by The-1-7-10-Pack** [comment]
I have no way to confirm it, and they are too many reasons to explain this. I doubt it's a bug.
