### ISSUE TITLE
Thaumic Tinkerer - Osmotic Enchanter Crash on Startup

### ISSUE THREAD

**Issue by Jofkos** [The-1-7-10-Pack/The-1.7.10-Pack#224]
The ThaumicTinkerer Version in this ModPack is very old. [This issue was already fixed](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/632), but this ModPack is still using the 162 version. Newest ist [462](http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/469/).

Now i can't start my server because of this bug. (-> [crash-report](http://pastebin.com/ELRFHivw))

**Comment by The-1-7-10-Pack** [comment]
The mod has the dev vesrions that are on 462 now, but also a release versions that are on 162 (the latest).
Build 162 of the dev versions is not the same as build 162 from the release versions.
Anyway I think that I should update to the dev version anyway if it's more stable.

**Comment by Jofkos** [comment]
Developer version or not, i've updated it manually now, and it's working.
So a pack-side update would be nice :+1: 

Also i'm not sure if it's a developer version:
> [Nekosume (TT-Author)](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/632#issuecomment-69480614):
> Jenkins is our build server there will be a 163 as soon as I can get on a better connection, it takes multiple attempts just to push code to git uploading even a small binary to curse is currently out of my league I hate being stupid keyboard on mobile Internet at Edge of signal

It's probably only Nekosume's internet connection :)

**Comment by The-1-7-10-Pack** [comment]
As I noted, and update will be on the next version (0.7.3)
