### ISSUE TITLE
Somebody said ThermalDynamics?

### ISSUE THREAD

**Issue by The-1-7-10-Pack** [The-1-7-10-Pack/The-1.7.10-Pack#225]
No?
Well I'm going to add [it](http://minecraft.curseforge.com/mc-mods/227443) anyway.

**Comment by Jofkos** [comment]
Oh yeah, that would be nice :smile:

**Comment by joshosh34** [comment]
This sounds good.

**Comment by Rebelyrocks** [comment]
YES, I love it
