### ISSUE TITLE
Flan's mod- Crash on right clicking Modern weapons box.

### ISSUE THREAD

**Issue by joshosh34** [The-1-7-10-Pack/The-1.7.10-Pack#226]
I made a modern weapons box, placed it in the world, and when I right clicked on it, the game crashed. I tried to re-open that world again, but it immediately crashed before i could do anything. 

Here is the client side crash report:
**Edited: Please use a paste tool.**
http://paste.ubuntu.com/10368564/

**Comment by The-1-7-10-Pack** [comment]
Huh?
![image](https://cloud.githubusercontent.com/assets/10350644/6351387/df93ee94-bc43-11e4-8f55-030ebb5e1a6d.png)
Please give me more information as noted [there](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md), because I can't help you without it.

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information.
