### ISSUE TITLE
Suggest: AetherCraft ?

### ISSUE THREAD

**Issue by martinegui** [The-1-7-10-Pack/The-1.7.10-Pack#227]
No way to add AetherCraft to the modpack? 
Come I have so much junk that i want trade for other itens, this would be nice to solve this!

"With the tools AetherCraft gives you, you can both convert items into pure Aether and turn Aether into items. You can even use Aether to charge items of great power!"
( Mod link at forum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293204-aethercraft-1-4-5-aetheral-alchemy-turn-matter )

**Comment by The-1-7-10-Pack** [comment]
This mod doesn't really fit the pack and it changes the gameplay by A LOT.
Thanks anyway for suggesting!
