### ISSUE TITLE
OpenPeripheral terminal glasses receive nothing, code works in other packs

### ISSUE THREAD

**Issue by VintageMayo** [The-1-7-10-Pack/The-1.7.10-Pack#228]
Grabbed and edited some sample code for [a clock display on OpenPeripheral terminal glasses](http://pastebin.com/NVFayw1a), and tried to run it on a basic ComputerCraft computer with the terminal glasses bridge on the left side. Ran the code, nothing happened. Computer acted as if it was all running fine, but nothing shows up on the glasses. Tried running the same code on Tekkit and a couple other packs, code worked perfect and displayed the time on my HUD.

Glasses seems to pair to the bridge fine, with a key being successfully given to the glasses every time.
![2015-02-22_20 49 38](https://cloud.githubusercontent.com/assets/11154324/6322923/ce3f60a8-bad4-11e4-8f71-a95c4ba0ec6a.png)

Tried running basic terminal glasses functions (addBox, addText) from the Lua console with no success, but ran them successfully in other modpacks. No errors get returned on any functions in the console, just the usual table returns, but nothing shows up on the HUD.![2015-02-22_20 49 16](https://cloud.githubusercontent.com/assets/11154324/6322925/d7c0b42e-bad4-11e4-9d48-7a17433bbdaf.png)

Can't speak to if it's a version bug or mismatch, or a mod incompatibility or something, I'm no Java or mod expert.

**Comment by The-1-7-10-Pack** [comment]
Other OpenPeripheral features do work?

**Comment by VintageMayo** [comment]
To my knowledge, everything else from OpenPeripheral seems to work just fine. And yes, all the other packs I've tested on have been 1.7.10. Seems to be an issue unique to this pack so far, so if you have anything specific for me to do try to help locate the issue, just let me know.

**Comment by The-1-7-10-Pack** [comment]
What is the version of OpenPeripheral used in the packs you've tested it with?

**Comment by The-1-7-10-Pack** [comment]
Closed due inactivity.

**Comment by lesander** [comment]
Since OpenPeripheralAddons 0.2.0 you have to call `glass.sync()` to make changes visible. (https://docs.google.com/document/d/1YjFbIburoX3x-jIUUUEOkCCi8T29zgDuuQ97hpm8uxo/edit)

**Comment by The-1-7-10-Pack** [comment]
@lesander Thanks :)
