### ISSUE TITLE
Redstone Coil Crash

### ISSUE THREAD

**Issue by BlackJackAres** [The-1-7-10-Pack/The-1.7.10-Pack#23]
When attempting to craft the Redstone coil in the tinkers construct table it'll crash out my game. 

http://paste.ee/p/S5hiW

**Comment by chrisps89** [comment]
That one works okay for me in a Crafting Station or a Crafting Table.

**Comment by The-1-7-10-Pack** [comment]
You should report it to Tinkers' GitHub page.
https://github.com/SlimeKnights/TinkersConstruct/issues
