### ISSUE TITLE
World not loading can anyone help?

### ISSUE THREAD

**Issue by Zoidiicus** [The-1-7-10-Pack/The-1.7.10-Pack#230]
I've tried searching for a solution but unable to find one. My world when i click to load it starts to load but than just goes back to the start screen i have added mods but they haven't affected it because I've tried loading it without the mods and still don't work. I can pot the the launcher console logs if wanted, please help I've been unable to play for over a week.

it also says unable to play unknown sound event and some other stuff and its just for that world.

**Comment by Zoidiicus** [comment]
*some old worlds

**Comment by Zoidiicus** [comment]
and creating worlds

**Comment by The-1-7-10-Pack** [comment]
Please read [how to report a bug](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md)..

**Comment by Deathwater57** [comment]
I've experienced this issue before and although getting no solution Jon i did find a work around. just make a Server and it should run fine....if you experience lag because the server by default runs through java. I can give you a link to a .bat file that eliminates all lag.

**Comment by Zoidiicus** [comment]
why is the server 200mb?

and does the .bat file version run like the ATlauncher servers? Because i know they are .bat files

**Comment by Zoidiicus** [comment]
also iv'e had problems with optifine with the pack its making some blocks transperant

**Comment by Zoidiicus** [comment]
I'm trying the suggestion out and thank you vary much, much appreciated

**Comment by Deathwater57** [comment]
Np glad i could help...and i don't know how the ATlauncher works so i can't really answer that question but i do know it brings up a cmd which improved my servers performance dramatically. and thanks for mentioned that optifine thing i'm just now trying it. also are you on latest build or the one before?

**Comment by Zoidiicus** [comment]
im on the latest but i havn't tried the latest with optifine ill try it out, there is one world that i can load

could you give me the link to the .bat file

**Comment by Deathwater57** [comment]
Also here is the link to the .bat file https://www.dropbox.com/sh/gnxdnzimwy3mgua/AABFHkZGoXOIoSHlGKgQHrAea/Forge%20MCPC%201.7.10/ServerStart.bat?dl=0 you will have to open it and configure it because it's set to open a craftbukkit.jar not the forge-1.7.10-10.13.2.1291-universal.jar so you will need to open it and go to the bottom and scroll to the far right and you will see craftbukkit.jar twice. Simply replace both of those with forge-1.7.10-10.13.2.1291-universal or forge-1.7.10-10.13.2.1291-universal.jar if you delete the .jar part.

**Comment by Zoidiicus** [comment]
thanks

**Comment by Deathwater57** [comment]
no problem trust me it sucks made 2 worlds made lots of progress both did the same thing....so that's when i came here. got no help but made a solution.

**Comment by The-1-7-10-Pack** [comment]
> also iv'e had problems with optifine with the pack its making some blocks transperant
'Cause you were using an old version of Optifine.

**Comment by Zoidiicus** [comment]
ok thanks

**Comment by Zoidiicus** [comment]
i start the server and it says i have to rename *installer* installer.jar

**Comment by The-1-7-10-Pack** [comment]
Why did you change file's names?
Just keep the server files as they are and double click the LaunchServer.bat file. Remember to set eula.txt to true and you're good to go.

**Comment by Deathwater57** [comment]
Installer? and because with all the mods and it running in java causes lag....idk if it's caused my connection even if you are hosting the server. and you did change your craftbukkit.jar to forge-1.7.10-10.13.2.1291-universal.jar right?

**Comment by Zoidiicus** [comment]
im using the .bat file that Deathwater57 gave me a link to and its file name is ServerStarter, I lanched that and it does its thing and it says to rename at the start and it says minecraft server closed or crashed restarting, it continuously restarts.

**Comment by Deathwater57** [comment]
yeah open that .bat with notepad or notepad++ and change the craftbukkit.jar to forge-1.7.10-10.13.2.1291-universal.jar or whatever your forge server launcher says. you need to change both or it won't work.
![serverbat](https://cloud.githubusercontent.com/assets/11012047/6367987/0826ffcc-bc9e-11e4-97b0-8c9032a1d2bc.png)

**Comment by Deathwater57** [comment]
IT needs to look like that or your server won't launch it also will restart your server it ever crashes and has a script that does improve lag for your server.

**Comment by Zoidiicus** [comment]
i have now renamed them

**Comment by Zoidiicus** [comment]
how long usually does it take to start up the server?

**Comment by Deathwater57** [comment]
lmfao a while lol maybe like 1-2 minutes longer if you had used the .jar launcher trust me lol

**Comment by Zoidiicus** [comment]
ok

**Comment by Zoidiicus** [comment]
does it installl any files into the folder that you place it in or your desk top?

**Comment by Deathwater57** [comment]
I would recommend making a folder and then running the bat file. because it does install quite a few things.

**Comment by Deathwater57** [comment]
I'm pretty certain you did but just to be sure. You did go to the technicpack site where this and get the server file right?

**Comment by Zoidiicus** [comment]
nope

**Comment by Zoidiicus** [comment]
ive just downloaded the .bat file

**Comment by Deathwater57** [comment]
okay let me send you the link

**Comment by Zoidiicus** [comment]
thanks

**Comment by Deathwater57** [comment]
http://www.technicpack.net/modpack/the-1710-pack.453902  it's on the right should say server download. Wants it's done you will want to make a folder and drag and drop all of the server files into it along with the .bat file you downloaded. Also you will need to locate your 1.7.10 saves. Take all of those files and make a folder call world. and put that into the same folder with the server files.

**Comment by Deathwater57** [comment]
After you've done that find the forge-1.7.10-10.13.2.1291-universal.jar it probably look the same
once that's done go back to the .bat file open it again with notepad or notepad++ and do what i said earlier very bottom and turn the craftbukkit.jar to the forge-1.7.10-10.13.2.1291-universal.jar you will need to change both like i said. once all that's done you can then run the bat file and wait till it's done.

**Comment by Zoidiicus** [comment]
thanks so much

**Comment by Deathwater57** [comment]
np again if you need any of that better explained or run into any problems i'll be here.

**Comment by Zoidiicus** [comment]
the server's going to take a while to download because its 200 mb and i have really slow internet atm not to slow but its pretty dam slow

**Comment by Deathwater57** [comment]
dude i feel your pain i have bullshit hughes net only thing slower then that is dial up so i feel really bad if you have that.

**Comment by Zoidiicus** [comment]
do u know how to port forward and that so other people can join from different networks can join your server. ive created a server for skyfactory on the ATLauncher (using a .bat file). atm its only a lan server

**Comment by Deathwater57** [comment]
Yes but believe me it's not something that's easily explained you might want to look up a video tutorial because explaining it will take at least 30 minutes to an hour if i have to type it all
what kind of modem do you have?

**Comment by Zoidiicus** [comment]
yea i only get 30gb's a month and when i use all that i have really slow internet so i can still have internet

**Comment by Zoidiicus** [comment]
ok

**Comment by Deathwater57** [comment]
30gbs? hmm we only get 25 gbs so yeah not a lot of anything....and if you use that 25 you still have internet it's just 10x slower.

**Comment by Zoidiicus** [comment]
btw if you havnt already seen it check out the Microsoft Hololens it's pretty cool

and thanks

**Comment by Zoidiicus** [comment]
yea

**Comment by Deathwater57** [comment]
you either have the same thing i do or something similar and alright i will... but be sure to come back here if you have any more trouble  with the server it's self

**Comment by Zoidiicus** [comment]
alright, thanks so much

im with iinet

**Comment by Deathwater57** [comment]
iinet? is that your service provider or your modem brand?

**Comment by Zoidiicus** [comment]
service provider i have  a linkzys modem

**Comment by Zoidiicus** [comment]
the modem's about six years old

**Comment by Deathwater57** [comment]
i have the same thing okay well search on google how to port forward on linkzys modem and it should be able to take you from there.

**Comment by Zoidiicus** [comment]
ok thanks 

btw ive tryed that but you have to type some ip into the web browser than type in the username n password n i dont know it

**Comment by Deathwater57** [comment]
the username and password or or the url for the web browser

**Comment by The-1-7-10-Pack** [comment]
Guys I'm happy to see you're helping for each other!

**Comment by Zoidiicus** [comment]
dont worry ive found another way on the linkzys routers

**Comment by Deathwater57** [comment]
Alright great and np Hi it's me.

**Comment by Zoidiicus** [comment]
yes Deathwater57 has been vary nice and useful

**Comment by TANGOjPANDA** [comment]
Hey guys I had the same problem about a week ago.
Here is the link
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/210
The game works fine now (After deleting the mod 'colorchat')

**Comment by The-1-7-10-Pack** [comment]
@Zoidiicus Can you try @TANGOjPANDA's solution and tell me if it worked?
I need to know.

**Comment by Zoidiicus** [comment]
@The-1-7-10-Pack, @TANGOjPANDA's solution did work thankyou alot.

**Comment by Zoidiicus** [comment]
i havn't tried @deathwater57's solution due to my internet, the download keeps on failing to download but i will try his soluion because i would probably want it to run on a server as well.

**Comment by Zoidiicus** [comment]
ive also found another problem where if you were to place a skeleton spawner in the nether it turns into a wither skeletoon spawner, the problem with this is that your entity count risises dramitcally. When I first done this it raised up to abot 20,000 entities and i was strugling to get out of the nether, to get the entities down again is go back to the over world and come back to the nether without the spawner being in the ether e.g. picking it up before you leave.

**Comment by Zoidiicus** [comment]
your entity count keeps on rising

**Comment by The-1-7-10-Pack** [comment]
It's known, it's extra utilities due to the EnderPump.
