### ISSUE TITLE
The 1.7.10 modpack version 0.7.2 Server

### ISSUE THREAD

**Issue by Deathwater57** [The-1-7-10-Pack/The-1.7.10-Pack#232]
Just a question involving the latest server... does the server update the mods automatically or do you need redownload the server from the technicpack.net every time the server file get's updated?
and beside removing the ruin mod or there any other ones? minor or major?

**Comment by The-1-7-10-Pack** [comment]
Server will never update automaticaly. It's MINECRAFT. JAVA. Not an alien program.
To update the server just delete the mods folder, the configs folder, and the launch files if you see that they have been changed, also the forge version if it has been changed. Easy!

**Comment by Deathwater57** [comment]
This is my second time ever even asking about a modpack or server. if i've had trouble with a modpack in the past i would say screw it and give up. Ex. Attack of the B team, Ultra modded survival, many different flans modpacks and several others. So i'm sorry I liked you're modpack so much that i had to ask questions and wanted it to work to it's full potential. So there is no need to insult me.

**Comment by The-1-7-10-Pack** [comment]
No insulting buddy, sarcasm on the internet is fun :)

**Comment by Deathwater57** [comment]
oh lmfao you got me. also i have another problem to report possibly.

**Comment by The-1-7-10-Pack** [comment]
Open a new issue :)

**Comment by Deathwater57** [comment]
done fill free to close this one.
