### ISSUE TITLE
BC builder machines

### ISSUE THREAD

**Issue by Deathwater57** [The-1-7-10-Pack/The-1.7.10-Pack#233]
They just won't make the frame. or take any energy at all i've placed the landmarks i have 1 medium voltage solar array attached to 7 electrical engines going through diamond electrical pipes and attached to the filler/builder and it's not taking the energy let alone making the frame.

**Comment by Deathwater57** [comment]
I also seem to be missing an array of buidcraft blocks

**Comment by Deathwater57** [comment]
nvm idk what i fixed....it just wasn't working in 1 area

**Comment by The-1-7-10-Pack** [comment]
Weird! Anyway BC is going to update with a lot of bug fixes. Maybe it'll do it.
