### ISSUE TITLE
Binnie's Mods

### ISSUE THREAD

**Issue by nickjer** [The-1-7-10-Pack/The-1.7.10-Pack#234]
This is a suggested mod:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284348-1-7-10-1-6-4-forestry-binnies-mods-1-8-0-2-0-dev

Binnie's mods gives us more bees and trees to explore and breed. It also introduced more tools such as the Indexer for maintaining the different species. I remember using the Extra Bees mod quite a bit in Agrarian Skies when I was experimenting with bees.

**Comment by The-1-7-10-Pack** [comment]
What do you think guys?

**Comment by Rebelyrocks** [comment]
I haven't messed around with bee and tree breeding ever, but I think if enough people actually do that stuff, why not include it.

**Comment by alex2710xela** [comment]
I think you should add it, its just adding to a mod. It wont change the game play and if they don't like bees they don't have to use it.

**Comment by TANGOjPANDA** [comment]
I'm with Alex on this one I love bees I had assumed it was already in it to be honest. 
I like how overpowered it gets if you put the time in almost on par with magical crops.

**Comment by The-1-7-10-Pack** [comment]
Binnie's Mods add some stuff that people say "why not" but as I see them now they are on beta stage and not too stable. I won't add them at this point.
Thanks anyway.
