### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DragonOfStendarr** [The-1-7-10-Pack/The-1.7.10-Pack#236]
Will we have Fossils and Archeology Revival Build 7.0.1 - Dinosaurs in Minecraft! in the future? or is that something we don't want? :3

**Comment by Rebelyrocks** [comment]
I personally don't like this mod. I don't feel like the technology and dinosaur don't mix together, just like how I can't imagine the Random Mobs mod in this modpack.

**Comment by DragonOfStendarr** [comment]
I would love too see that mod in this modpack xD but not random mobs. as Fossils and archeology doesn't spawn dinosaur mobs. just fossils under ground etc. then you need to get the dinosaurs out xD

**Comment by Rebelyrocks** [comment]
After actually looking through the mod features, it actually looks pretty cool. I like that you have a choice to bring the dinosaurs to life or not. So if you don't want to use the mod, you don't have to. All I can think about is Jurassic Park!

**Comment by DragonOfStendarr** [comment]
Yup xD it's awesome xD

**Comment by The-1-7-10-Pack** [comment]
#73: Sorry but nothing changed - Magic, Tech, and...Dinosaurs?
Thanks anyway for suggesting (:
