### ISSUE TITLE
Fast Leaf Decay

### ISSUE THREAD

**Issue by The-1-7-10-Pack** [The-1-7-10-Pack/The-1.7.10-Pack#237]
[Fast Leaf Decay](https://github.com/Olafski/FastLeafDecay/releases)
'Cause we like things to be not annoying.

**Comment by alex2710xela** [comment]
:100:  
:+1:

**Comment by Deathwater57** [comment]
Not a bad idea i mean with treecapitator it shouldn't be an issue but now all axes work on all of the trees.

**Comment by Flukethoughts** [comment]
only issue i see is galatacraft oxygen setups
