### ISSUE TITLE
Adding Mariculture

### ISSUE THREAD

**Issue by alex2710xela** [The-1-7-10-Pack/The-1.7.10-Pack#238]
http://www.curse.com/mc-mods/minecraft/mariculture

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292346-mariculture-1-2-4d-updated-20-02-2015

Mariculture
I think it would be a great addition, it gives a whole new meaning to the water. As of now there are lots of tech, magic, and farm mods but there aren't any geared towards water and fishing. If people don't want to use it they don't have too, it wont affect them in any way if they choose not to use it. I think its a really fun mod and I think others will enjoy it too.      :)

**Comment by The-1-7-10-Pack** [comment]
The 1.7.10 Pack is full of cool mods, adding Mariculture is just too much.
Thanks anyway.
