### ISSUE TITLE
Nvidia Driver Crash

### ISSUE THREAD

**Issue by Givemeyourgits** [The-1-7-10-Pack/The-1.7.10-Pack#239]
I have been getting the following error since switching from Tekkit to 1.7.10 pack.

http://i.imgur.com/RvS5tJP.png

This initially only happened once in a while (every 2hrs or so, sometimes right away, but sometimes longer).

Now it seems to be happening a lot more often.
It does not create a crash log or any log entries.

Windows 8.1 x64 Pro
Nvidia 680 (latest drivers)
Java 8.0.31 x64
Sphax x64 

I am allocating 6GB to Java via Technic Launcher but was previously using 4GB and had the problem as well.

I get this error on my server when it happens, but I think this is just a result of being crashed out of the client abruptly.

http://hastebin.com/nuwasagufo.avrasm

**Comment by The-1-7-10-Pack** [comment]
Allocating RAM does not affect the modpack, it allocates RAM automatically.
Anyway, a quick question: do you use Optifine?

**Comment by Givemeyourgits** [comment]
I wasn't originally, but put it on recently.
Should I set technic launcher to default ram again, or does it not matter?

**Comment by The-1-7-10-Pack** [comment]
It does not matter.
Try to remove Optifine and see if it occurs again.

**Comment by Givemeyourgits** [comment]
Actually looks like it was removed when I did the update to 0.7.3 and it happened after the update.

**Comment by The-1-7-10-Pack** [comment]
Can you please provide a screen shot from [CPU-Z](http://www.cpuid.com/softwares/cpu-z.html)?

**Comment by Givemeyourgits** [comment]
https://db.tt/pXYyQRHE

**Comment by The-1-7-10-Pack** [comment]
Whoops, I meant [GPU-Z](http://www.techpowerup.com/gpuz/), of course. Nvidia, GPU.
Thanks.

**Comment by Givemeyourgits** [comment]
https://db.tt/YQIeri0m

**Comment by bochen415** [comment]
@Givemeyourgits 

![](http://i.imgur.com/q8XFD8l.png)

This indicates that you:
- are using 2 graphics cards in a SLI configuration (good)
or
- have the card placed in a x8 PCI-E slot (not so good)
or
- haven't installed the motherboard drivers right (that's bad)
or
- have hardware problems( that's very bad)

**Comment by Givemeyourgits** [comment]
The reason it shows up 8x is because I have a PCI-E sound card on the PCI bus, and any other card causes it to drop down to 8x.  But the performance difference between 8x and 16x is  usually below 2fps as cards can't saturate an x8 bus much less 16x.  

I've tested it in the past with and without the sound card and I saw no different with 3DMark.  I don't think that would cause this, and no other game (including Minecraft 1.6.4 running Tekkit) has caused this error.  But it is reoccuring with this pack.

**Comment by bochen415** [comment]
The only thing I can think of right now is high gpu temps and other apps using opengl in the same time (like Firefox's hardware acceleration).

**Comment by Givemeyourgits** [comment]
I'm seeing a load of 20-54% on the card (I got GPU-Z running on a second monitor watching the sensors) and the temp never goes above 46C (max for this board is 97C).

**Comment by TANGOjPANDA** [comment]
This sound like a dodgey drive to me.
Did the pack update at the same time as your gpu's drivers. If they did try down grading it.

Also this is a long shot but have you got an application running called raptor gaming. This caused my minecraft to crash repeatedly if I tabbed out it made my displayed driver crash.

**Comment by Givemeyourgits** [comment]
I just installed Fraps so I could see my frame rate (60fps, drops to 46fps briefly).

I updated the driver today and did a clean install option to see if it helps any. I normally install nvidia drivers within a day of their release once I get the popup, this drive was made on 2/10 so I likely installed it then, which would been a few days/week before I started using 1.7.10 Pack again.

I was using Tekkit and tried 1.7.10 but had lots of problems with slow performance.  Later I tried it again and found a bug that changing the mip map/anisotropic settings from 0 will cause the problems so I have them zeroed out now performance has been pretty stable.

I did just get a crash though as I was typing this, I didn't get the nvidia error 8 pop up, and I did get a crash log this time:

http://hastebin.com/yovucizeqo.coffee

Not sure if it is related, as I haven't had a crash in a while that didn't have the nvidia 8 error message.

**Comment by The-1-7-10-Pack** [comment]
So the issue is fixed, was GPU driver related?
(Please open a new issue for the crash).

**Comment by Givemeyourgits** [comment]
No, it was just a different crash not sure if it was related but the first crash I've had that wasn't the nvidia error 8.

**Comment by The-1-7-10-Pack** [comment]
I'm not too sure if so, can you sum the situation at the moment?

**Comment by Givemeyourgits** [comment]
I play, and randomly get nvidia opengl error 8.
it leaves no crash log and I can't see any pattern.

I tried adding the game to 3d programs  in nvidia panel and tried disabling cuda to see if that helps.  Not sure yet.

**Comment by The-1-7-10-Pack** [comment]
Did you try already the most simple solution to everything in the world that is to reinstall the modpack? (but in the professional way, to delete the whole folder and download everything again).

**Comment by Givemeyourgits** [comment]
I've had the problem before installing this time (prior I quit and gave up due to the errors).

I just deleted it again, but when I tried to reinstall I get this:
https://db.tt/IJApmWUj

**Comment by The-1-7-10-Pack** [comment]
@Givemeyourgits Fixed it, #SolderDerp

**Comment by Givemeyourgits** [comment]
Yes, I have in the past, but I just did it again.

**Comment by The-1-7-10-Pack** [comment]
@Givemeyourgits And did it help?

**Comment by Givemeyourgits** [comment]
Sorry no.  I am trying to test a theory on Nvidia CUDA which I have read causes similar issues (but they are really dated posts so may not be related).  It has been exclusive to 1.7.10 pack though, I don't have the problem with Tekkit, 1.8 or any other game.

**Comment by The-1-7-10-Pack** [comment]
Do you have a custom video settings?

**Comment by Givemeyourgits** [comment]
Just disabling mip maps as there seems to be a bug that causes massive FPS drops with that and anisotropic. I've tried setting Adv OpenGL to on and off but doesn't seem to affect anything.

**Comment by The-1-7-10-Pack** [comment]
Can you try resseting them to default? It's obviously something different that is on your system, we should try everything :)

**Comment by Givemeyourgits** [comment]
I'll give it a try, might be a day or two as I play mostly with my son.

**Comment by The-1-7-10-Pack** [comment]
Happy to see that I can help your quality time.

**Comment by Givemeyourgits** [comment]
I just tried it with default video settings and I got the crash about 4 minutes into a new world.

**Comment by The-1-7-10-Pack** [comment]
If you said that you tried already other 1.7.10 modpacks and they have worked no problem the only option at this moment is to just try to find what mod is causing that, I don't think that configuration changes can do such a thing. If you have the time, you can try to have a look what mods from The 1.7.10 Pack are not in the modpack that you was able to play in, and try removing them and see if it helps. It's the last option.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
If you have anything else to say, try, ask: You're always welcome, I can reopen this issue.

**Comment by The-1-7-10-Pack** [comment]
This error can be fixed by activating "Advanced OpenGL" in the video settings screen.

**Comment by Givemeyourgits** [comment]
I did try with and without AdvOpenGL.  (I was running with AdvOpenGL, but turned it off for testing)
But I haven't had the problem lately.  I played for a couple of hours the other day without the error.  
It seems to either work for long periods of time, or comes up really quickly and repeatedly.

It hasn't been happening for a bit now.  

Thanks for the follow up!

**Comment by The-1-7-10-Pack** [comment]
@Givemeyourgits I also read that it has something to do with Chrome being open at the same time.

**Comment by Givemeyourgits** [comment]
Interesting, I have chrome up 24/7.

**Comment by The-1-7-10-Pack** [comment]
@Givemeyourgits So here's our reason for the crashes, although in general you should blame Nvidia.

**Comment by bochen415** [comment]
> I also read that it has something to do with Chrome being open at the same time.

I basically said the same thing on Feb 27

> The only thing I can think of right now is high gpu temps and other apps using opengl in the same
> time (like Firefox's hardware acceleration). 

Why don't people listen to me? ;)

**Comment by The-1-7-10-Pack** [comment]
@bochen415 We are not smart enough to understand you );
Sorry!
