### ISSUE TITLE
Chunk Errors

### ISSUE THREAD

**Issue by Amir1205** [The-1-7-10-Pack/The-1.7.10-Pack#24]
When i start my world, everything works normally, I have no lag at all (Weird, because my laptop always lags normally), but, I see very big holes in the world, and I can't do anything or move anywhere. I have restarted my minecraft and it happens on all world types.

**Comment by Amir1205** [comment]
By the way, I also tried turning VSync off, it helped, but the holes appeared again when I restarted my Minecraft.

**Comment by chrisps89** [comment]
If there are large holes in the world then you are not loading everything, when you press F3, what FPS does it say you have in the top left. Also can you tell me your basic computer specs, CPU, RAM, Graphics Card. And what version of Java you have installed. Finally how much RAM are you giving to the game to use.

**Comment by The-1-7-10-Pack** [comment]
Yes, please provide more information as asked above.

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information. 7 days passed.

**Comment by Amir1205** [comment]
I have Windows 8.1, 6GB Ram, around 20-30 FPS (I normally run at 10-20, but this pack runs faster, because of some reason) and I have the newest Java version. I also play it on an external hard-drive.

**Comment by Amir1205** [comment]
Windows 8.1, I use a external hard-drive for Technic, and I run at 20-30 FPS with this pack, while I usually run at 10-20. I gave it 5GB (That's the maximum for my computer)

**Comment by The-1-7-10-Pack** [comment]
You can't gave the modpack RAM manually, it's automatic.
Anyway, you should try to ran the modpack without any other programs running. It may help.

**Comment by Amir1205** [comment]
Oh, I thought you meant how much GB I allowed the technic launcher to use.

**Comment by Amir1205** [comment]
And, it might be because of Java 8 and that 1.7.10 version packs aren't running well with it.

**Comment by Flukethoughts** [comment]
is this single player?
If so It's because your drive can't render the chunk correctly or fast enough..

**Comment by Amir1205** [comment]
Yes, it is Single Player, but it might be that the pack doesn't have Legacy Java Fixer and I'm running Java 8.

**Comment by The-1-7-10-Pack** [comment]
Legacy Java Fixer is required only for old versions of Forge
