### ISSUE TITLE
Buildcraft Additional pipes Add-on

### ISSUE THREAD

**Issue by Deathwater57** [The-1-7-10-Pack/The-1.7.10-Pack#242]
This is a suggestion

Just a simple Add-on to Buidcraft to add more pipes. I only know that it adds Teleport pipes but I just think it'd be nice for us Quarry users so we don't have to make a giant line of pipes forward in back
 
http://www.mod-buildcraft.com/addons/

Anyway tell me what y'all think and if there is are something that works similar to this already in the modpack please inform me.

**Comment by liquid-metal** [comment]
for teleporting item you can use ender chest though

**Comment by The-1-7-10-Pack** [comment]
There are so many thing that lets you teleport items that it just seems useless. Also I'll need to follow this addon everytime Buildcraft updates. No.
Thank you anyway.
