### ISSUE TITLE
Server Console Spammed With Message.

### ISSUE THREAD

**Issue by GamerMan7799** [The-1-7-10-Pack/The-1.7.10-Pack#243]
I know that this isn't really the fault of the modpack but I was hoping that someone might have run into this issue before and fixed it. What is happening is that every 10 seconds or so the server records a message saying something like:
```
[09:08:39] [Server thread/WARN]: Skipping BlockEntity with id
```

I just don't know what is causing this, I've tried to remove as many of the Block Entities in the chunks that  are usually loaded. But the thing is, this message only happens when no one is on the server, if someone is on it stops appearing. (This makes it even harder to find the cause). I am not blaming the modpack but as I do not know what mod is causing this I was wondering if anyone would know what it causing this.

This doesn't seem to be causing any significant issues other than causing really large log files.

**Comment by The-1-7-10-Pack** [comment]
Can you post the full log?

**Comment by GamerMan7799** [comment]
```
lasest.log
https://www.dropbox.com/s/uh1ikyylofql6ob/latest.log?dl=0
```
```
fml-server-lastest.log
https://www.dropbox.com/s/cgsfslu2xikm87m/fml-server-latest.log?dl=0
```

**Comment by The-1-7-10-Pack** [comment]
Can you try to do the thing I've said [there](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/241#issuecomment-76175321)? It might be the same problem.

**Comment by GamerMan7799** [comment]
I do have Server Tools (Core, Teleport, and Permissions) but this was an issue before I added that mod. 

I tried the version that you recommended but the server still sends the same error.

[Server start up log](https://www.dropbox.com/s/i3k56qm30tx4p9h/post-chisel-downgrade-server.log?dl=0)

**Comment by The-1-7-10-Pack** [comment]
Can you try without those additional mods?

**Comment by GamerMan7799** [comment]
The message still appears. 
[Start up Log](https://www.dropbox.com/s/bska4498yaowwkn/no-server-tools-log.log?dl=0)

Also something that might be worth saying is that this issue first appeared in the V0.7.1b (when I first made the server) and has continued through V0.7.2 and V0.7.3 (the current version).

**Comment by The-1-7-10-Pack** [comment]
- Try to generate a new world with the additional mods.
- Try to generate a new world without the additional mods.

Tell me what you get!

**Comment by GamerMan7799** [comment]
I loaded up both new worlds, and kept them up for a few minutes. Neither had the message appear after 10 minutes. This makes sense since I believe this is being caused by something in the world the issue is that I don't know what is causing it.

[Server Log Without additional mods](https://www.dropbox.com/s/octy33nu2e2fapj/New-World-No-Server-Tools.log?dl=0)
[Server Log With Additional Mods](https://www.dropbox.com/s/lquvj8inwvcmts4/server-log-with-server-tools.log?dl=0 )

**Comment by The-1-7-10-Pack** [comment]
This is a mod's problem for sure but I don't know exactly what mod and I don't have any good way to find out.
It's not critical, so I'll close this one.
