### ISSUE TITLE
server world wont load after update v0.7.3

### ISSUE THREAD

**Issue by xxxploder** [The-1-7-10-Pack/The-1.7.10-Pack#244]
When I load a new world with the update, it works just fine. Only when I load up my server's saved world does it break.

latest log file here:

https://www.dropbox.com/s/njncvnrwqapnf3n/fml-server-latest.log?dl=0

**Comment by The-1-7-10-Pack** [comment]
I'm pretty sure it's the same problem as #241.
Can you try the solution I've mentioned on [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/241#issuecomment-76175321) comment and tell me if it works?
If it does I'll update the pack.

**Comment by xxxploder** [comment]
I switched the files around..didn't seem to help
https://www.dropbox.com/s/1oongxpqaieajc3/fml-server-latest2.log?dl=0

**Comment by The-1-7-10-Pack** [comment]
It does seem to help because now you can just type /fml confirm in the console.

**Comment by The-1-7-10-Pack** [comment]
Closing this one, issue fixed.

**Comment by xxxploder** [comment]
I'm still on 0.7.2 .. I will try and get it updated again, ran outta time.
So adding that file and running that command should fix things?

**Comment by The-1-7-10-Pack** [comment]
Just do as you did, but run the command. :)

**Comment by xxxploder** [comment]
It wont stay up for me to put that command in. Keeps restarting.

**Comment by xxxploder** [comment]
ok, it worked. I got in. But I'm missing alot of blocks, lol their just not
there anymore. ?

**Comment by xxxploder** [comment]
like all my marble,granite,diorite,andesite ..

**Comment by The-1-7-10-Pack** [comment]
This is a problem with Chisel. Believe me I have nothing else to do.
I'll try to figure out more but at least your world is working :)

**Comment by xxxploder** [comment]
gotcha, yea its just wierd, those are default mc blocks, lol thanks for everything, love this pack.

**Comment by The-1-7-10-Pack** [comment]
:)

**Comment by xxxploder** [comment]
server is crashing randomly...
https://www.dropbox.com/s/njncvnrwqapnf3n/fml-server-latest.log?dl=0

**Comment by The-1-7-10-Pack** [comment]
> java.lang.OutOfMemoryError: PermGen space

Did you change your launch file? What version of Java do you have?

**Comment by xxxploder** [comment]
That's from the server console, I have no idea.. I did have to change the
forge jar file to "modded minecraft.jar" but that was never a problem before

**Comment by xxxploder** [comment]
I'm not sure what the server is running, I sent them a ticket. But, I know
I have 8gig ram on it. Seems to be fine until we get 3 people on the server
then crashes like every 30 min

**Comment by xxxploder** [comment]
I have java 7 update 67 on my pc, not sure what my friends are using

**Comment by The-1-7-10-Pack** [comment]
Why did you change the Forge name? You shouldn't touch anything there.
Anyway a quick and easy fix for it will be to update to Java 8.

**Comment by xxxploder** [comment]
update the server to java 8? not sure why I changed it, so it would fit in
the drop down for my host, to "optimized minecraft.jar" I think they
suggested it. not sure.

**Comment by The-1-7-10-Pack** [comment]
If it's dedicated and they know what they are doing it's not a problem I'd guess.
And yes, I'd recommend you to update to Java 8 if you have an "java.lang.OutOfMemoryError: PermGen space" Error.

**Comment by xxxploder** [comment]
Thanks.

**Comment by xxxploder** [comment]
It worked for around 4 hours, then I got this log.. hmm..

https://www.dropbox.com/s/p94582rnlzrufr0/crash-2015-03-02_10.14.02-server.txt?dl=0

**Comment by The-1-7-10-Pack** [comment]
God damn it Chisel 2 is unstable. You should give this crash report to the author.
You can just remove the mod if you're having too much trouble with it for now, I hope that more updates will be out for it soon.
