### ISSUE TITLE
SUGGESTION: PVP Improvement Mods

### ISSUE THREAD

**Issue by GamerMan7799** [The-1-7-10-Pack/The-1.7.10-Pack#246]
Add some mods to improve pvp such as 
[Better PVP](http://www.planetminecraft.com/mod/164-better-pvp-v10/)
and
 [PVP toggle](http://minecraft.curseforge.com/mc-mods/223394-pvptoggle)

Just two mods I thought would be interesting because I want better PVP control on my server.

**Comment by The-1-7-10-Pack** [comment]
Sorry but currently I currently won't add these.
Thanks anyway.
