### ISSUE TITLE
[Request] LanteaCraft

### ISSUE THREAD

**Issue by spannerman79** [The-1-7-10-Pack/The-1.7.10-Pack#248]
Is it at all possible that you can add LanteaCraft to this amazing pack?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292427-lanteacraft

**Comment by The-1-7-10-Pack** [comment]
Why do you think I should add this mod to the pack?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
