### ISSUE TITLE
Open Block Builders Guide

### ISSUE THREAD

**Issue by alex2710xela** [The-1-7-10-Pack/The-1.7.10-Pack#249]
When I place it in the world the ghost blocks don't appear and I don't know if its a config thing or what. I would like to fix it so I can use it. Any help is better than none.

**Comment by TANGOjPANDA** [comment]
You need to apply a Redstone signal for it to display the ghost blocks.

**Comment by alex2710xela** [comment]
Okay thank you, i havent used it in a while
