### ISSUE TITLE
Magical Crops' Osmium Seeds not craftable

### ISSUE THREAD

**Issue by BoWiWo** [The-1-7-10-Pack/The-1.7.10-Pack#25]
The Osmium seeds from Magical Crops cannot be crafted/no recipe was found using NEI. No message was displayed in the console when clicking the item in NEI. I tried crafting it anyways with weak, regular and strong essence and both ores and ingots, but did not succeed. I was not able to allocate a config setting for this, my best guess would be that Magical Crops doesn't recognize Mekanism. Client version is 0.6.1

**Comment by Silphsy** [comment]
This is something that should be reported on the mod's official site, not here.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287451-magical-crops-farm-your-resources-3-2-0-now-with

**Comment by The-1-7-10-Pack** [comment]
^

**Comment by martinegui** [comment]
There's a way to fiz the magical crops issues with some scripts with minetweaker look at top link some help.
