### ISSUE TITLE
Severe lag with Tesseract after 0.7.3 update

### ISSUE THREAD

**Issue by kkeith29** [The-1-7-10-Pack/The-1.7.10-Pack#250]
After this last update, turning on a tesseract causes extreme lag on my server. It only happens when a frequency is enabled. If the item is off, no lag occurs. The lag only shows itself only when the tesseract is in my characters view. I can stand next to it while it's on without issues as long as it isn't rendered.

Any ideas? I've tried grabbing some new ones in creative mode just to see if it was specific to the crafted items I had, but the same problem occurred.

**Comment by TANGOjPANDA** [comment]
It could be the sides of the block it has a really weird texture mechanic try turning of particles and any texture packs

**Comment by kkeith29** [comment]
I am no longer employed with Lifeboat Creative. If you need assistance please contact Colt Cox at colt@lifeboatcreative.com

Thanks!

**Comment by The-1-7-10-Pack** [comment]
We've updated Thermal Expansions in this update. Maybe it's because of this? Are you using Optifine or playing on server?

**Comment by kkeith29** [comment]
Playing on a server. Not using optfine.

I turned particles to minimal and the issue was still present.

**Comment by The-1-7-10-Pack** [comment]
Is the problem occures on Singel Player?

**Comment by kkeith29** [comment]
Yes, it does. The texture of the block starts acting weird once it is turned on so maybe it is causing the client side lag.

**Comment by The-1-7-10-Pack** [comment]
It may have something to do with your system of video settings because I've tested it myself now on two computers and everything is completely fine.
Closing this one :)
