### ISSUE TITLE
Mod Pack wont play

### ISSUE THREAD

**Issue by Curleytop** [The-1-7-10-Pack/The-1.7.10-Pack#251]
i have installed your mod pack really keen on playing it!! however when i hit the play button it try's to load and then it just stops loading. i have the log for you i've tried installing the latest java 1.8 and still doesn't help if you'd like the log let me know i'm really keen.  thanks for everything :)

**Comment by jwik01** [comment]
It's not my mod pack, but I had the same trouble until I figured out that simply installing java 8 doesn't tell Technic to actually use java 8 with this modpack.  You have to futz with Technic to get it to use the latest version of java.

**Comment by The-1-7-10-Pack** [comment]
You didn't provide your latest launcher\modpack log of course but I'd guess that your Java version is 32bit.

**Comment by Curleytop** [comment]
thanks for getting back to me ill try the java stuff u suggested and yeah i know its not your modpack that is the problem im still not good with problems so im really grateful for your help i think i did your pastbin thing not sure if not ill try again. Cheers :)

**Comment by Curleytop** [comment]
yeah so i've tried for about 2 hours on how to get the tehnic launcher to run on 7 and/or 8  but i cant get it to do either. i'm completely lost and according to what I've researched and what technic is telling me i'm still running on the generic 1.6.0_65 java 64bit so obviously yeah if i install 8 then technic doesn't run on it which i imagine is my problem ... i'm on a mac also :) which until i wanted to play on 1.7 MC and found your modpack which i was really looking forward too, my comp says no lol

**Comment by The-1-7-10-Pack** [comment]
So a wrong Java version is indeed the problem. Simply uninstall Java completely, then install the right Java 8 64bit version :)
Closing this one.
If you have more questions, feel free to ask.
