### ISSUE TITLE
Server problems

### ISSUE THREAD

**Issue by mattlad564** [The-1-7-10-Pack/The-1.7.10-Pack#252]
Im trying to make a hamchi server for this pack. Can i have some help please? :)

**Comment by alex2710xela** [comment]
what do you need?

**Comment by mattlad564** [comment]
Thank you for the reply. Have about five mins ago managed to get a hamchi server to work. What RAM would you recommend to allocate to the server?

Matthew Thomas

**Comment by The-1-7-10-Pack** [comment]
Just keep it as the default, 3GB.

**Comment by mattlad564** [comment]
Okay. Thank you. Great mod pack. Especially love the achievements 

Matthew Thomas

**Comment by alex2710xela** [comment]
Okay, im glad you got it.

**Comment by The-1-7-10-Pack** [comment]
If you have any other question open a new issue, have fun playing! (:
