### ISSUE TITLE
Thaumic Tinkerer Crash

### ISSUE THREAD

**Issue by dragonzero39** [The-1-7-10-Pack/The-1.7.10-Pack#253]
So, using the osmatic enchanter from Thaumic Tinkerer I crashed my server. Looking into the problem, the 1.7.10 pack currently uses build 162 of thaumic tinkerer. the latest build is build 469. A new and updated version would be great to fix problems that may be causing crashes!

Link to current builds of Thaumic Tinkerer
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

I can provide error reports if necessary.

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/224
