### ISSUE TITLE
How do you install Optifine with the 1.7.10 pack

### ISSUE THREAD

**Issue by Laeryc** [The-1-7-10-Pack/The-1.7.10-Pack#254]
I have tried previous methods of installing Optifine from adding to modpack folder or adding the contents of optifine Jar to the modpack jar  apperantly theres a new way by running the jar fil but it cant find the 1.7.10 core not sure how to find it with Technic pack? Anyone have a way to do it correctly?

**Comment by The-1-7-10-Pack** [comment]
You simply put the Optifine jar on the mods folder :)
