### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Byrnezz** [The-1-7-10-Pack/The-1.7.10-Pack#255]
my friend has made a server and he can get on it but i cannot?

**Comment by The-1-7-10-Pack** [comment]
I have no idea unfortunately.
But maybe..
Maybe you can give me a bit more information!
Yep, that's a good idea! :)
If you can provide the error picture or something similar It'd be good.

**Comment by alex2710xela** [comment]
@Byrnezz  Do you use Hamachi or did he port-forward or something?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
