### ISSUE TITLE
Falling into void when switching worlds

### ISSUE THREAD

**Issue by frieder** [The-1-7-10-Pack/The-1.7.10-Pack#257]
Hi everyone

I have set up this mod pack on a server of mine but people on the server reported that they are glitching through the blocks and falling into the void when switching worlds (overworld <-> nether). Has anybody else experienced this kind of problem yet? The minecraft server is running with 8GB heap space and 512MB perm space (Oracle Java 1.7.0_75) on a Xeon E2 3.4GHz with 3 cores assigned (KVM) so this should be enough I guess.

Any help is appreciated.

Cheers

**Comment by The-1-7-10-Pack** [comment]
How is their connection to the server?
It's probably an internet problem, the server sounds powerful.

**Comment by frieder** [comment]
Hi

I placed some admin world anchors there to make sure the worlds are loaded all the time but it did not help. As for the internet connection they have common internet connections (from DSL6000 up to 400MBit cable connections, also different countries/ISPs and medium to high end gaming PCs). I was just wondering if somebody else had seen this problem before. But if nobody else has this problem then I guess I will have to figure out what is going wrong here. Thx anyways.

**Comment by The-1-7-10-Pack** [comment]
No problem, have a nice day (:
