### ISSUE TITLE
Minecraft crashes instantly when I click the "Play" button

### ISSUE THREAD

**Issue by wavesurfer55** [The-1-7-10-Pack/The-1.7.10-Pack#259]

**Comment by The-1-7-10-Pack** [comment]
> No description provided.
Please read [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md) to understand how you should get help.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity and missing information.
If you would give me more information I'll help you.
