### ISSUE TITLE
Sever Crashes when I load it up

### ISSUE THREAD

**Issue by alex2710xela** [The-1-7-10-Pack/The-1.7.10-Pack#260]
**Edited, please use a paste tool next time.**
http://pastebin.com/9GzCWwwL

**Comment by The-1-7-10-Pack** [comment]
Never saw such a crash on my end, do you have any additional mods?

**Comment by alex2710xela** [comment]
no, I loaded the "minecraft_server.1.7.10" by accident and ever since that the batch file launch doesn't work.

**Comment by The-1-7-10-Pack** [comment]
Well launching the Minecraft server is cool and everything, don't understand me wrong, but if you want to play a modded server, AKA "The 1.7.10 Pack": You need to use the "LaunchServer.bat" file. Why didn't it work?

**Comment by alex2710xela** [comment]
Yea i know i need to launch the batch file but i clicked the wrong one and it like corrupted my world so i went back a save and it worked.

so lesson learned, never click the wrong one or else it breaks the world. thank you for the help though.

**Comment by The-1-7-10-Pack** [comment]
:+1:
