### ISSUE TITLE
What does it mean when a sever is X amount of ticks behind?

### ISSUE THREAD

**Issue by alex2710xela** [The-1-7-10-Pack/The-1.7.10-Pack#262]
I host a sever for two of  my friends and I and when I start it up its okay but after a while it starts to get really laggy and the console says "skipping 999 (for example) ticks" When the number starts to get pretty high the lag makes the game unplayable. So i would like to know what the ticks are and if there is a way to fix the lag.

**Comment by The-1-7-10-Pack** [comment]
It means that the server is overloaded. What is the system that you're running the server on?

**Comment by alex2710xela** [comment]
Windows 7 desktop  custom made for gaming

**Comment by The-1-7-10-Pack** [comment]
Can you give me a bit more details?

**Comment by Flukethoughts** [comment]
it means your cpu is not keeping up with the mods and the data traffic

**Comment by alex2710xela** [comment]
16 gb for ram and a Intel I5

**Comment by Flukethoughts** [comment]
i5 is to vague

**Comment by alex2710xela** [comment]
what do you need then

**Comment by The-1-7-10-Pack** [comment]
Can you give me your full latest log?

**Comment by alex2710xela** [comment]
can you tell me how to do that again?

**Comment by The-1-7-10-Pack** [comment]
Go to the server's folder -> logs folder, and post with a [paste-tool](http://paste.ubuntu.com/) the fml-latest-server.log file.

**Comment by alex2710xela** [comment]
http://paste.ubuntu.com/10543254/plain/

**Comment by The-1-7-10-Pack** [comment]
You're server is overloading due to the ""Silently" catching entity tracking error".
See there: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/161
You need to take out your EnderPump from the nether, it spawns massive amounts of Nether Skeletons.

**Comment by alex2710xela** [comment]
I dont have a pump in the nether

**Comment by The-1-7-10-Pack** [comment]
Do you use an EnderPump anywhere else in your world?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
