### ISSUE TITLE
VoxelCam settings reset when updating

### ISSUE THREAD

**Issue by Hirvox** [The-1-7-10-Pack/The-1.7.10-Pack#263]
When I updated to 0.7.3, my VoxelCam settings were reset and it started automatically uploading any screenshots to Imgur by default, even though I had disabled the auto-posting of screenshots before.

Also, is there a way to configure VoxelCam to automatically use my account when uploading pictures to  Imgur so that I can easily find them later?

**Comment by The-1-7-10-Pack** [comment]
It is a problem, because the mod uses the same file for the mod config and the information about accounts. What do you think I should do?

I'm not sure, I don't think so. If you want, you can suggest it (:

**Comment by Hirvox** [comment]
If you can't prevent the config files from getting reset, can you disable Imgur uploading by default?

Also, is it possible to configure the accounts from the Minecraft UI or do I have to edit the config files manually?

**Comment by The-1-7-10-Pack** [comment]
You know what, I'll just disable the config so it won't reset. I'll keep it as default, it's not too bad :)
Next update it won't reset to you, I promise!
