### ISSUE TITLE
Questing Mode problem

### ISSUE THREAD

**Issue by Sir-burnalot** [The-1-7-10-Pack/The-1.7.10-Pack#265]
Working through the quests include with this great mod pack and I have completed the Automation quest however the game does not recognise that I have made the Energetic Infuser , therefore it will not register 100% and I cannot collect the reward. Can this be fixed???

**Comment by The-1-7-10-Pack** [comment]
Let me confirm this first, but everything can be fixed - don't worry! :)

**Comment by Sir-burnalot** [comment]
Cheers Jon



-----Original Message-----
