### ISSUE TITLE
Millénaire

### ISSUE THREAD

**Issue by NoGood4Me** [The-1-7-10-Pack/The-1.7.10-Pack#266]
Is it possible to add mods Ruins and Millénaire? It seems to me that these mods are well suited to this pack.

**Comment by DragonOfStendarr** [comment]
Ruins was in the modpack.. but was replace with the mod RecurrentComplex :3

**Comment by NoGood4Me** [comment]
Okay. Actually, they could be replaced by BetterDungeons. This mod is very good :)

**Comment by DragonOfStendarr** [comment]
If you go longer down the issue list (suggestion) you will see that it might mod might come xD

**Comment by NoGood4Me** [comment]
Seen. I already wrote there :D I would very much like to see this mod.

**Comment by The-1-7-10-Pack** [comment]
> Millénaire

What is it? Give links, information, why do you think I should add it.

**Comment by NoGood4Me** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272755-millenaire-npc-village-new-villagers-in-players

**Comment by The-1-7-10-Pack** [comment]
It is a very intresting mod but as I didn't add CustomNPCs I won't add this mod too.
Doesn't fit.
Thanks anyway (:
