### ISSUE TITLE
Splash screen error And wont load to main menu screen turns up black

### ISSUE THREAD

**Issue by Unitedstatesofam** [The-1-7-10-Pack/The-1.7.10-Pack#267]
Please help me, Once the pack starts up it says not responding for a very long period of time And tries to reach the mojang splash screen but turns up all blank and black and once i try to move it, it wont budge I need answers please.

**Comment by Unitedstatesofam** [comment]
And it reaches it but does the same thing

**Comment by The-1-7-10-Pack** [comment]
Just let it load.
Can you give me information about your system? Maybe the modpack is too heavy for you.

**Comment by Unitedstatesofam** [comment]
My system is Windows 7 premium intel hd  hp pavilion slimline s51021 graphics are gma x4500 But the last time i played before another or 2 mods came in i was able to play

**Comment by Unitedstatesofam** [comment]
And 4g ddr system memory

**Comment by The-1-7-10-Pack** [comment]
When you run the modpack can you have a look on the task manager how many % are you using from both CPU and RAM?

**Comment by Unitedstatesofam** [comment]
Sure I will do that

**Comment by Unitedstatesofam** [comment]
52% to 80% and about 3.55gb ram of memory

**Comment by The-1-7-10-Pack** [comment]
Did you try to just give it time?

**Comment by Unitedstatesofam** [comment]
I tried but It seems to flash on the tool bar To let me know its ready but its not I think its on the start screen but its all black

**Comment by The-1-7-10-Pack** [comment]
Just let it load, it's okay. It may take more time to load on your system. :)

**Comment by Unitedstatesofam** [comment]
Okay.

**Comment by Unitedstatesofam** [comment]
Ok new problem it loads but the screen goes all the way to the bottom left corner how do i fix this ?

**Comment by Unitedstatesofam** [comment]
I think  i have to reinstall the modpack i'll tell you if it worked

**Comment by The-1-7-10-Pack** [comment]
@Unitedstatesofam :+1:

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
