### ISSUE TITLE
Frame Rate Issue

### ISSUE THREAD

**Issue by Aspeee** [The-1-7-10-Pack/The-1.7.10-Pack#269]
I keep getting random lag/FPS drop for a millisecond. I have 64 bit java thats up to date. I have optifine 1.7.10 HD U B5 and I have allocated from 3-8GB of RAM. I am playing on a Singleplayer world and i get usually around 200-300 FPS depending on rendering. When it says how much of the RAM I have allocated to it the usage goes up by one percent and keeps going until it gets to 91% and drops back down to around 50% which is when the framerate drop happens and it does it when I allocate different amounts of RAM. Please help as this is very frustrating as I am enjoying the pack sooo much :)

**Comment by The-1-7-10-Pack** [comment]
Can you provide the latest log?

**Comment by Aspeee** [comment]
https://www.dropbox.com/s/tdsqpkv269m0n29/fml-client-latest.log?dl=0 

This correct?

**Comment by The-1-7-10-Pack** [comment]
When you run the modpack can you have a look on the task manager how many % are you using from both CPU and RAM?

**Comment by The-1-7-10-Pack** [comment]
> [FastCraft-core/]: 18 / 18 applied

Can you have a look on the task manager while playing with the modpack how is the % usage of both CPU & RAM?

**Comment by Aspeee** [comment]
22% CPU and 43% when i dedicated 4GB to it.

**Comment by Aspeee** [comment]
it also seems to be worse the longer I play, but resenting the launcher and restarting the modpack dont work.

**Comment by The-1-7-10-Pack** [comment]
So basically you play at 200-300 fps but you have massive fps drops?
Can you try to link the fps drops to the RAM usage?

**Comment by Aspeee** [comment]
Basically it dosent matter how much ram I allocate to it, when pressed F3 it will usually says 50% of that RAM is being used. But when I experience the LAG/Framerate drop its goes from 50% and increases rapidly to 91% and then drops to either 50% or 70% depending on allocated memory. And it does this when I am not loading chunks either it does it all the time.

**Comment by Aspeee** [comment]
But its 100% worse when I have played the game for 2-3 hours.

**Comment by Aspeee** [comment]
Its also never done it on any other modpack from ftb, teckit or the ATL launcher on various versions of MC. Thats why I am confused.

**Comment by The-1-7-10-Pack** [comment]
Go to the modpack's folder, bin, and change the version.json file. You can see there that the modpack is allocating 3 Gigs, you can change it for more and see if anything changes. I doubt it though.

**Comment by Aspeee** [comment]
Thanks for the help, I increased the RAM to 5gb in the version.json file and ill see how it goes and report back. The modpack is great btw and if this issue is fixed it will be the best yet 100%!!!!!!

**Comment by The-1-7-10-Pack** [comment]
I need to know if it's a RAM issue, so I'll increace the maximum as default. If not I have more things I can investigate, be sure to update me.

**Comment by Aspeee** [comment]
Thanks Jon :)

**Comment by Aspeee** [comment]
"javaArguments": "-Xms2048M -Xmx3072M -XX:PermSize=256M -

I changed it to 

"javaArguments": "-Xms4096M -Xmx5120M -XX:PermSize=256M -

That correct

**Comment by The-1-7-10-Pack** [comment]
That basically increased your allocated RAM to the game.
Did it fix the fps drops, or not?

**Comment by Aspeee** [comment]
Not checked yet sorry just wanted to make sure I did it correctly, its not to bad but will report back if theres issues and if there isn't I will say. Busy at university today so ill report ASAP.

**Comment by Aspeee** [comment]
I changed it to what I said and in the top right it only says 3gb has been allocated?

**Comment by The-1-7-10-Pack** [comment]
You may need to change the same file again in the bin/modpack.jar/version.json file.

**Comment by Aspeee** [comment]
Seems to have worked and I don't get the frame rate drop so far and I played for 4+ hours thanks :)

**Comment by The-1-7-10-Pack** [comment]
Are you sure? Intresting.

**Comment by Aspeee** [comment]
https://www.dropbox.com/s/6n42x1460updmea/IMG_0979.JPG?dl=0

https://www.dropbox.com/s/fokn8eo4webbf3u/Photo%2005-03-2015%2009%2047%2022.jpg?n=52148397

**Comment by The-1-7-10-Pack** [comment]
It's funny that the frame drop stopped because the RAM increase didn't actually work, you probably did something wrong. Anyway that's my point: 3GB is ENOUGHT RAM to the modpack, and now I see again that I'm right. Increating the default RAM to above 3GB will make people with 4GB systems hard time.
