### ISSUE TITLE
Crashing!

### ISSUE THREAD

**Issue by DragonOfStendarr** [The-1-7-10-Pack/The-1.7.10-Pack#270]
could you find out what is making the crash?
I have no clue how to read it xD 

I have tried deleting player file but still crashing.. it's when i'm exploring.
http://www.filedropper.com/crash-2015-02-25204144-client

**Comment by The-1-7-10-Pack** [comment]
Can you use a paste tool for the log?
http://pastebin.com

**Comment by DragonOfStendarr** [comment]
http://pastebin.com/kw2q95yg

**Comment by The-1-7-10-Pack** [comment]
After what did this crash happened?

**Comment by DragonOfStendarr** [comment]
I'm exploring around the world.. and it have now started crashing me. didn't do that before. thought it was a corrupt chunk but every crash was in another location. that's what is happining.

**Comment by DragonOfStendarr** [comment]
Doesn't crash the server tho.. just the client.

**Comment by DragonOfStendarr** [comment]
here is the most recent crash report. http://pastebin.com/SG3r1ZLs 10min old crash report.

**Comment by DragonOfStendarr** [comment]
and! i have to delete my player file each time..

**Comment by The-1-7-10-Pack** [comment]
The first crash is really weird..We may have to blame Forge for it.
The second crash is Flan's Mod's fault. It shouldbe reported to them.
You're really unlucky to find all the mod's bugs! you should report the second crash to Flan's Mod's GitHub repository.

**Comment by DragonOfStendarr** [comment]
Atleast it stopped after the last time i deleted my player file. so i can play again x)

**Comment by The-1-7-10-Pack** [comment]
Good :)
