### ISSUE TITLE
Essence ore is not correctly inputted into ore dictionary

### ISSUE THREAD

**Issue by AgonGhast** [The-1-7-10-Pack/The-1.7.10-Pack#271]
I can't tell my digital miner to search for oreEssence because it isn't registered correctly with the ore dictionary.

It works if you place a Essence Ore in the miner directly, but those blocks aren't available in survival mode - even Silk Touch breaks those blocks into essence fragments.

**Comment by The-1-7-10-Pack** [comment]
That's a problem with Magical Crops. Anyway, you can't just put *ore* In it? It should work.
