### ISSUE TITLE
Modpack Quitting Help Needed

### ISSUE THREAD

**Issue by KingChoc** [The-1-7-10-Pack/The-1.7.10-Pack#273]
Whenever I click the play button on the technic launcher, the mod pack opens for about 4 seconds then quits. Please help!

**Comment by The-1-7-10-Pack** [comment]
So you probably have Java 6 or a 32bit of it.
Be sure to fix your Java version, you need 7 or 8 and 64bit version.

**Comment by KingChoc** [comment]
I'm on a mac and I just installed Java 8

**Comment by The-1-7-10-Pack** [comment]
Please give me your latest launcher log so I won't be guessing.

**Comment by KingChoc** [comment]
which one?
I'm not sure haven't done this before

**Comment by The-1-7-10-Pack** [comment]
.technic/logs and post the latest one on http://pastebin.com

**Comment by KingChoc** [comment]
http://pastebin.com/D5zFBDzV

**Comment by KingChoc** [comment]
i think thats it

**Comment by The-1-7-10-Pack** [comment]
You're Java version is 6. Uninstall it and install Java 7 or 8.
Closing this one.
