### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#275]
What you think about add this mod ?

http://www.tolkiencraft.com/draconic-evolution/

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/75.
This mod is super cool but it doesn't really fit this Main Magic-Tech modpack.
Thanks anyway.
