### ISSUE TITLE
Automation quest 

### ISSUE THREAD

**Issue by Snarvitlaus** [The-1-7-10-Pack/The-1.7.10-Pack#277]
like the title says im trying to do the Automation Quest but i cant find the recipe for Energetic Infuser (basic), all i can find is the resonant. All the other things i need for this quest are resonant and not basic. Is it ment to be this way?

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/265
