### ISSUE TITLE
Please add these mods 

### ISSUE THREAD

**Issue by MrKRONIC** [The-1-7-10-Pack/The-1.7.10-Pack#278]
Please can you add these mods to the mod pack in the next update, i use this modpack as a base modpack for my custom server as it is the best modpack to date. but i add a few other mods to make the experience a whole lote greater, i would appriciate it if you could add these mods to the pack asap, i also can confirm that there are no id conflictions or for that matter any problems caused by adding these mods both client and server side, as said before i run this on a server with added  mods. 

mods i would like you to add in the next update....
animationAPI    latest version        (needed for arsmagicka 2)
AM2 1.4.0.008  latest version        (otherwise known as arsmagicka 2)
chococraft 4.1.5   latest version
dragon mounts r41_1.7.10    latest version 
malisiscore-1.7.10-0.10.5   latest version
malisisdoors-1.7.10-1.4.3    latest version
 
all of these mods work perfect with the current build of your modpack so they should all work fine in future versions

also please put ruins back in they are so much better than the current world spawn mod

thanks and good luck 

your welcome to come on our server once the update is done

**Comment by The-1-7-10-Pack** [comment]
I'm sorry but this is not the way to suggest mods.
Anyway I won't add any of these mods, sorry.
