### ISSUE TITLE
Please remove hats mods and progressive automation

### ISSUE THREAD

**Issue by MrKRONIC** [The-1-7-10-Pack/The-1.7.10-Pack#279]
the hats mod is silly and just pointless this pack could really do with out it , also there are plenty of faster ways to dig a hole ie a quarry !!! progressive automation is useless when you have a quarry please remove them!

**Comment by The-1-7-10-Pack** [comment]
Progressive Automation is for early game. Also I did a vote long ago about progressive automation and people use this mod a lot.
I won't remove them.
