### ISSUE TITLE
Crash in official server

### ISSUE THREAD

**Issue by Alexander175** [The-1-7-10-Pack/The-1.7.10-Pack#28]
So i was on the server today and i was in my inventory and highlighted over amber and pressed U for the usage and my game froze and crashed.

Here is my log https://www.dropbox.com/s/virsilem77lo6vb/techniclauncher_2015-01-04.log?dl=1

And here is the crash report https://www.dropbox.com/s/29vgb8950a4zcz1/crash-2015-01-04_12.24.51-client.txt?dl=0#

**Comment by The-1-7-10-Pack** [comment]
Can you please post both here?
http://paste.ubuntu.com

**Comment by The-1-7-10-Pack** [comment]
Thank you for the report.

**Comment by BlackJackAres** [comment]
I have a friend who also warned me of this problem.

**Comment by The-1-7-10-Pack** [comment]
For now it crashes only client, will fix next update.
