### ISSUE TITLE
destruction pickaxe from extra utilities acts like an iron pickaxe with infinite durability 

### ISSUE THREAD

**Issue by Tdoggy** [The-1-7-10-Pack/The-1.7.10-Pack#280]
the destruction pickaxe is exposed to have no drops and mine stone 5 times faster than diamond and everything else with the power of your fist. but it doesnt it has the power of an iron pick and and drops all the items

**Comment by The-1-7-10-Pack** [comment]
I don't see the problem. :)
http://ftbwiki.org/Destruction_Pickaxe
