### ISSUE TITLE
Suggested mods to add.

### ISSUE THREAD

**Issue by ZeWi** [The-1-7-10-Pack/The-1.7.10-Pack#281]
Advanced Generators
http://bdew.net/generators/

Adventure Backpack
http://www.curse.com/mc-mods/minecraft/225063-adventure-backpack

Archimedes Ships
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289952-archimedes-ships-v1-7-banking-ships

Elemental Creepers
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2111959-1-7-x-elemental-creepers-rebooted

Silent's Gems & Pets
http://minecraft.curseforge.com/mc-mods/220311-silents-gems
https://www.dropbox.com/sh/ocb6z7eawsz6kg7/AABunHilCrrVDH5eipw3YQf7a <-Pets

Would be awesome additions to a really robust mod. Thanks.

**Comment by The-1-7-10-Pack** [comment]
I'm sorry but I won't add any of those mods. They just doesn't fit the modpack.
Thanks anyway for suggesting.
