### ISSUE TITLE
osmotic enchanter crash

### ISSUE THREAD

**Issue by bennygeorgiev** [The-1-7-10-Pack/The-1.7.10-Pack#282]
hi
i have a problem, when i want to enchant something in the osmotic enchanter of thaumic tinkerer the server and the minecraft crash and i cant open the server until i will delete the block with mcedit and i did everything: changed wand the sword and it crash over and over again 
HELP!

**Comment by The-1-7-10-Pack** [comment]
This problem was fixed on v0.7.3, just be sure you're using an up-to-date version of the modpack :)

**Comment by bennygeorgiev** [comment]
ok thanks
