### ISSUE TITLE
Ticking World Exception Crash

### ISSUE THREAD

**Issue by Legomax98** [The-1-7-10-Pack/The-1.7.10-Pack#283]
I just updated to version 0.7.4 and I can't move around outside of a specific area without crashing. I've had this happen twice more upon relaunching the world. I've already traveled in the direction that I was going, along with a lot of other terrain generation around the area. Also, strange thing to note is that I need to replace all of the aqueous accumulators in the world because they weren't working after updating. Not sure if this is related or not.

**Comment by Legomax98** [comment]
Here's the crash log:
http://paste.ubuntu.com/10539615/

**Comment by The-1-7-10-Pack** [comment]
Try creating a fresh world with the latest version, does it work okay?

**Comment by Legomax98** [comment]
I launched a flat world and I couldn't replicate the issue

**Comment by The-1-7-10-Pack** [comment]
So can I close this issue?

**Comment by Legomax98** [comment]
done

**Comment by The-1-7-10-Pack** [comment]
@Legomax98, Can you please help #288 and tell him how did you fix it?
