### ISSUE TITLE
Mod suggestion 

### ISSUE THREAD

**Issue by Nemet01** [The-1-7-10-Pack/The-1.7.10-Pack#284]
Hello again with an other suggestion: I would like to suggest power converters mod because I didnt find any other suggestion about this and I think people is more familiar with this mod and also easier. If I'm wrong please tell me :D

**Comment by Yorick1234** [comment]
What we all do on this modpack server is use (heavy) aluminum wire from the galacticraft mod which is included. This wire pretty much converts whatever electricity you produce to whatever you need to consume, just make sure it connects to a batbox or such up to your consuming device.

**Comment by The-1-7-10-Pack** [comment]
There's also a block from OpenComputers that can do the job :)
