### ISSUE TITLE
Ruin Spawning Rate

### ISSUE THREAD

**Issue by TreePuncher9501** [The-1-7-10-Pack/The-1.7.10-Pack#286]
I love this modpack, yet a pet peeve of mine is ruins that spawn much too often. The castle ruins, added as a possibility during the 0.7.3 update excited me, and I loved it whenever I found one. Now, since I updated to 0.7.4, they spawn much more often. I do not know if this is deliberate, but it would be nice to know how to lower the spawn rate of ruins. Thanks!

Explored Area Screenshot:
![w](https://cloud.githubusercontent.com/assets/10838395/6514909/03b4d2b8-c354-11e4-924e-303977771937.jpg)

**Comment by TreePuncher9501** [comment]
I took the liberty to do some more exploring to check to see if it is simply an abnormality with RNG... Nope.
![mhzkhqp](https://cloud.githubusercontent.com/assets/10838395/6518850/005b32d0-c37a-11e4-95ec-4a5b0e34ceb3.jpg)

**Comment by The-1-7-10-Pack** [comment]
I think that you're god damn right.
Although, the configuration about the spawning rate is set to default, and we still see not just a massive spawning rate, but the same structures of the same type over and over again.
Recurrent Complex has 52 different ruins type, and it's weird how it acts.
I'll try to figure it out with the mod author, but for now it's not THAT bad, right?

**Comment by Ivorforce** [comment]
Yep, that one was entirely my fault. The issue was introduced with 0.9.5 2 days ago, and fixed with 0.9.5.1 yesterday. Sorry about that :)

**Comment by The-1-7-10-Pack** [comment]
Thanks @Ivorforce for a quick reply! :)
@TreePuncher9501 I'll consider a hotfix for the pack, also Team CoFH mods have been updated.

**Comment by The-1-7-10-Pack** [comment]
http://www.technicpack.net/modpack/the-1710-pack.453902/changelog/50989
