### ISSUE TITLE
Connection Issues (Since 0.7.4)

### ISSUE THREAD

**Issue by ChinesePeanuts** [The-1-7-10-Pack/The-1.7.10-Pack#287]
#### Hi again 
I can't connect to my server (it's normally on a rented server, but even in local) since **0.7.4**
as usual, I update by replacing every file except my map folder and my Server Propreties conf.

Here's my conf file, and my logs
I've been running the server Offline (without Internet) and with another new map called *TEST*
It's not working either !

http://pastebin.com/3FZLTnXi  (The short one)
http://paste.ubuntu.com/10544615/  (The fml one)

You'll see the connection issue in the first log (*highlighted*)

**Thanks** for your help !

**Comment by The-1-7-10-Pack** [comment]
To login to your own server you need to put in the IP "0.0.0.0" or "localhost".
You're doing this right?

**Comment by ChinesePeanuts** [comment]
Yes, I tried both ! and with the port too (which is 38979 or 38978 -> 127.0.0.1:38979) 
127.0.0.1 too (same as localhost anyway) but it 's not working.
The Client just ping the server, annd when I refresh the server page I get a
`[RCON Listener #2/INFO]: Rcon connection from: /127.0.0.1` 
on the terminal

I also tried with my **0.7.3** backup, and I have the same problem (I think, I'm not totally sure)

**Comment by The-1-7-10-Pack** [comment]
Did you try to update to the latest version now? (v0.7.4a)

**Comment by ChinesePeanuts** [comment]
I have uploaded both (serverside and client) and the problem is still there ! (in local)

*Note* : The server doesn't even run on the rented server (no logs, nothing) just a message to tell me that it can't start

**Comment by ChinesePeanuts** [comment]
Well...
I managed to fix the problem (even if I still can't understand why)
I have just deleted the propreties file on the server side, and now everything is ok...
If someone know what was the problem ! 
Thanks !

**Comment by The-1-7-10-Pack** [comment]
Did you ever touch anything in the propreties file?

**Comment by ChinesePeanuts** [comment]
I don't remember changing it, weird !

**Comment by The-1-7-10-Pack** [comment]
Weird indeed!
