### ISSUE TITLE
Server Crashing after 0.7.4 update

### ISSUE THREAD

**Issue by DetShaft** [The-1-7-10-Pack/The-1.7.10-Pack#288]
Hello! I am running a private server for a few friends and me to play on. I am running it off of a VPS running Debian 7. Up until this update it has run incredibly smoothly (props for that).

 I updated it as I have normally after every update and it seemed to work for a few hours then it has started to crash. The VPS has been running the server fine with 4G ram allocated supporting around 7-8 people normally. 

Here is the crash log: http://pastebin.com/szn3BsTk

Any help would be greatly appreciated. I have a few impatient friends hounding me to get the server back up! :P

**Comment by The-1-7-10-Pack** [comment]
Same crash report as https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/283, intresting.

**Comment by DetShaft** [comment]
Yes, it is upon startup now. At the first crash happened after terrain generation though. After work I will provide you with the fml log file Unless I can get it to you before I leave.

**Comment by The-1-7-10-Pack** [comment]
I'll also want to ask you if you can try with v0.7.4a too.

**Comment by DetShaft** [comment]
Alright, I wasn't aware that there was another update. I'll try to look for the fml file before I leave. Where are those located in the directory? I'll also update the server when I get home and then try.

**Comment by DetShaft** [comment]
I updated the server and nothing has changed. Still the same crash logs.

**Comment by The-1-7-10-Pack** [comment]
May I ask why you're using Java 7?

**Comment by DetShaft** [comment]
I'm new to using/running servers off a linux based VPS and had difficulty installing Java 8 early on so I installed Java 7 instead. Do you think upgrading to 8 would fix the issue?

**Comment by The-1-7-10-Pack** [comment]
I know that most of Java 7's issues were fixed in Java 8, one of them you can see in #291. Also I know that in #283, He had Java 7 too. Worth the try :)

**Comment by DetShaft** [comment]
Ok then, I will work on upgrading the server to Java 8 and see if that works. Thanks a lot for your help so far!

**Comment by DetShaft** [comment]
It seems to be working for now. I'm going to let it run for awhile and let everyone get on and see if anything goes wrong. But from the looks of everything Java 8 seems to be the fix!

**Comment by The-1-7-10-Pack** [comment]
@DetShaft I really hope it did it, sometimes making wild guesses help!
Update me if there's anything new.
Closing this for now.
