### ISSUE TITLE
Mod Suggestion: OpenModular Turrets

### ISSUE THREAD

**Issue by TreePuncher9501** [The-1-7-10-Pack/The-1.7.10-Pack#290]
I saw that someone had already suggested this mod, so hear me out. I believe that this mod will make a good addition to the pack, as it, in my opinion, seems to follow the technical side of things. Now, some may argue that "Flans does all that this mod does, why should we add this mod?" I have a couple of reasons as to why I believe this mod can do that which Flans cannot. First off, the only stationary defenses in Flans mod that I've seen is the Sentry Gun, which has difficulty protecting an area from a large amount of mobs, a well-armored player, or pretty much anything above it by two blocks or below it by 1. This mod can fix that, as not only does it act as a stationary, non-player-controlled defense that can attack hostiles near it, with little blind spots and to be completely honest, more specialized, with multiple kinds of turrets. My other reason is for those who prefer single player or simply have bad internet (Join the club.). This reason is for defense of certain things one would want to not get exploded by creepers when you're not paying attention or perhaps a village one would want to protect from zombies. There is one downside, and that is that the most recent update of the mod is in its beta stage. I don't want to beg, but I will restate my thesis of my idea that this mod would be a magnificent addition to your modpack. Thank you for reading my wall of text explaining my point of view, so have a cookie!

![image](https://cloud.githubusercontent.com/assets/10838395/6519218/57a12e00-c37f-11e4-8064-85920a1d9ff7.png)

Link to mod: http://www.curse.com/mc-mods/minecraft/224663-openmodularturrets#t1:description

**Comment by ChinesePeanuts** [comment]
I think it would be nice ! +1

**Comment by imsupermario** [comment]
+1

**Comment by MrKRONIC** [comment]
this would be great in this 1+ up

**Comment by The-1-7-10-Pack** [comment]
Currently I won't add the mod, we can't have everything!
Thanks anyway (:

**Comment by bochen415** [comment]
You're crule @xJon

**Comment by xJon** [comment]
@bochen415 Some weird Poland guy taught me once about realism. I think you could also learn from him

**Comment by xJon** [comment]
Added in version `0.10.5`!
