### ISSUE TITLE
Crashing upon startup

### ISSUE THREAD

**Issue by shnooop123** [The-1-7-10-Pack/The-1.7.10-Pack#291]
So I usually try to get a server working before I add my own type of stuff into it. Anyway I just downloaded the server, tryed to boot it up with what was provided, didn't want to mess anything up(I was gonna make my own starter.bat file to boot the server up later, but hadn't done it yet). I then had to exit and change the ELUA thing from false to true which I know is required with most servers. Then it crashed on the start up afterwards. Here is the crash log if you think it would help:

**EDITED: Please use a paste tool: http://pastebin.com/i3ej8jTe**

**Comment by The-1-7-10-Pack** [comment]
Lol, I know what does that, and I can tell you that a lot of things need to go wrong for that to happen.
You need to:
- [x] Have Java 7
- [x] Have a space anywhere on your server's path
- [x] Have Windows 7
Now you can change anything from those three things to fix it, do what you want!
