### ISSUE TITLE
Cannot install since new update

### ISSUE THREAD

**Issue by getbusyliving** [The-1-7-10-Pack/The-1.7.10-Pack#292]
when i tried to update yesterday it would not work, so i deleted the pack and tried to re-install. It gave me an error this is what it said

"Error unipping a file for the following pack: The1.7.10 Pack
Attemting to extract file the-1710-pack-0.7.4a.zip, but it did not exist.
Please consult the modpack author."

Please help me, I just want to play your mod pack.

**Comment by The-1-7-10-Pack** [comment]
It's just bad luck, try again :)

**Comment by cozac** [comment]
This is the fist time I've installed your modpack, yes.

**Comment by The-1-7-10-Pack** [comment]
Can you try totally delete the modpack and try to download again?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
