### ISSUE TITLE
Best weapons, tools and armor

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#293]
Guys what are the best?

I use magic crops armor Mark IV with full P4 and the mekanism tool for everything else

**Comment by TreePuncher9501** [comment]
Cowl of the Abyssal Depths, Robes of the Stratosphere, Leggings of the Burning Mantle, Boots of the Horizontal Shield for armor; for tools have a protoclay in your inventory and awakened ichorium tools. Pain in the ass to make, but they don't break, have various modes, and don't need charge.

Very Endgame.

**Comment by thebalck** [comment]
All the armor you said is about vis discount, they are good to as armor vs mobs and players ?

**Comment by TreePuncher9501** [comment]
Yes. Very strong. Haven't taken any non-void damage wearing it yet! The other good no-damage-ever armor is the other end-game armor, Gravity/Quantum. Ichorium is the magic side of things, and Quantum is the technical side. The new powersuits are pretty good too.

**Comment by thebalck** [comment]
yeah ty, and for a sword what you think its the best one ?

**Comment by TreePuncher9501** [comment]
For a sword? Awakened Ichorium. Has a soul mode for extra health, single mode for single mobs, and area attack.

**Comment by Dommain** [comment]
Use tinkers construct heart containers for three times more hearts.

**Comment by The-1-7-10-Pack** [comment]
I hope that you got the answers for your question (:
