### ISSUE TITLE
Add World Edit

### ISSUE THREAD

**Issue by Givemeyourgits** [The-1-7-10-Pack/The-1.7.10-Pack#294]
I don't know if there is something like it and what it is called, but when I ran a Bukkit server, there is a mod called World Edit, which allows you to quickly edit and clone large areas.  Is there something for 1.7.10 you could add that does something similar?  It was a huge time saver for doing things in creative.

**Comment by TreePuncher9501** [comment]
...World Edit is a plugin.

**Comment by ChinesePeanuts** [comment]
WorldEdit is a plugin, Forge doesn't support plugins and Cauldron is dead (I may be wrong).
So you won't be able to get it. (If there is an alternative, I don't know it)

**Comment by The-1-7-10-Pack** [comment]
Just as those two gentlemen said ^

**Comment by Givemeyourgits** [comment]
Yes, that.

Thanks!

**Comment by The-1-7-10-Pack** [comment]
World Edit for Forge 1.7.10 Is really unstable. It has bugs and it didn't update for months.
If you want to use it, you can - and I just gave you the link, but it won't be a part of the official modpack :)

**Comment by Givemeyourgits** [comment]
Fair enough, thanks.
