### ISSUE TITLE
Private Server Issues; World Generation

### ISSUE THREAD

**Issue by NinjaOnCrack** [The-1-7-10-Pack/The-1.7.10-Pack#295]
Me and three of my friends checked out this mod pack. I downloaded the server zip, and ran it normally but when we all entered the world it was just plain vanilla world. NEI and all of the mods work but the modded ores, plants, and biomes weren't spawning in the world gen. Any help?

![2015-03-06_21 13 18](https://cloud.githubusercontent.com/assets/11358924/6539599/fdaf6b1a-c445-11e4-9082-c53775296232.png)
![2015-03-06_21 13 28](https://cloud.githubusercontent.com/assets/11358924/6539600/ff9c675c-c445-11e4-8257-17d5b6b8b49c.png)

**Comment by ChinesePeanuts** [comment]
You have to change your **worldtype**
set in your *server.propreties* file the level-type to "BIOMESOP"
As follow :  `level-type=BIOMESOP`
Regen a world, and it should work !

**Comment by The-1-7-10-Pack** [comment]
Just as @ChinesePeanuts said, even though the server files incluide a server.propreties file that has this option built-in. You probably touched something so it has changed :)
