### ISSUE TITLE
Suggesting two mods that would be great. :Suggestion

### ISSUE THREAD

**Issue by 82280zx** [The-1-7-10-Pack/The-1.7.10-Pack#296]
Power Converters would be a great one to convert power from Industrial Craft to RF or from RF to Industrial Craft etc, I use it to combine power sources into one big power line that runs my entire base. Another great one I like is Quarry Plus but it might be a huge performance hit with some people, we ran it on are last server with no problems but I'm not  sure how more heavy populated servers would handle it, for now I can just toss it in on my pack when you do updates, I just serve a private server for me and a few friends, great pack btw!

**Comment by TreePuncher9501** [comment]
Why would we need power converters when Galacticraft's Heavy Aluminum Wire and Mekanism's Universal Energy Cables already convert one power type to the other? As for QuarryPlus, I think the modpack had it already but was removed due to instability.

**Comment by The-1-7-10-Pack** [comment]
@TreePuncher9501's comment is just as my words.
Thanks @82280zx for your suggestion, and thaks @TreePuncher9501 for helping the support!
