### ISSUE TITLE
Oil Refinery

### ISSUE THREAD

**Issue by Cyric313** [The-1-7-10-Pack/The-1.7.10-Pack#297]
does anyone have a clue how to properly extract oil from deposits?  when i try to use a BC pump and pipe it into the normal refinery the oil doesnt want to go into it and becomes incompatible. 

when placed in a extracells tank it reports as oilgc which i cant place in buckets or anything,..

**Comment by TreePuncher9501** [comment]
I don't know the issue. I just use BC Pump, BC Waterproof Pipe, then an enderchest which leads to a railcraft iron tank which pumps into refineries. Honestly, I think the oil YOU found is Galacticraft Oil, which can be refined into rocket fuel in a galacticraft refinery.

**Comment by The-1-7-10-Pack** [comment]
Can you provide a picture or something else?
You should double check that everything that you did is okay, but it is not a bug in the modpack. :)

**Comment by Cyric313** [comment]
I will get a picture when i get back home,  what i find is strange is that i can use a normal bucket to grab the oil and put it manually into the refinery... but if it is pumped into a tank first i cant take it out of the tank again with a bucket.  which you can if you use water or lava instead..

ive tried Mekanism and Thermal dynamics pipes.. but not BC pipes since i cant find any cactus around where i am to make pipe sealant.

**Comment by Cyric313** [comment]
Here is the refinery.. i can bucket op the oil and put it directly into the refinery.. but not pump it.
![2015-03-08_20 17 02](https://cloud.githubusercontent.com/assets/11364268/6547154/28b963b6-c5d0-11e4-946b-1eced9b22452.png)

**Comment by The-1-7-10-Pack** [comment]
I may be wrong but aren't you pumping into the output and outputting from the input?

**Comment by Cyric313** [comment]
No.. the back two chambers are input.. and i did try to change them just to be sure as well.. 
Oh and the Galacticraft refinery doesnt accept the oil either.. it just seems like its an incompatible oil 
a thermal dynamics tank that i fill manually with buckets are labeled Oil, and same tank filled with pump labels as oilgc

its Wierd..

**Comment by TreePuncher9501** [comment]
I figured it out using a universal oil canister in my world.

The oil is from Galacticraft. It's crude oil. Since Buildcraft oil replaces Galacticraft's crude oil is most recipes. It's worthless, unless you manually collect it with a portable oil extractor and some empty canisters. Then you put it in a galacticraft refinery. Sorry, but for BC fuel, that crude oil is worthless.

My advice to find BC Compatible oil is to look on the surface in deserts. Galacticraft oil spawns below Y20.

**Comment by Cyric313** [comment]
Really? thanks for the advice.. i did notice it was Crude oil.. but since i could bucket it up i didnt think to much of it... ill go look for BC oil then..

**Comment by The-1-7-10-Pack** [comment]
Thanks @TreePuncher9501 :)
