### ISSUE TITLE
Sudden Massive Lag

### ISSUE THREAD

**Issue by FirstWorldMatt** [The-1-7-10-Pack/The-1.7.10-Pack#298]
For some reason about 3 minutes after i start up the mod pack and get into my world, my frame rate just goes to about 5 frames per second. i have no idea whats doing this so can you please help me fix this issue?

**Comment by The-1-7-10-Pack** [comment]
Can you please provide some of the system details and the latest log?

**Comment by thebalck** [comment]
I believe this is the tesseract issue it happens to me too simply look away from all your tesseracts and try to remove them

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
