### ISSUE TITLE
Literally cannot make a world

### ISSUE THREAD

**Issue by ptrckstmp** [The-1-7-10-Pack/The-1.7.10-Pack#299]
Every time I try to make a world with this pack, it goes to the screen that says "generating world" then takes me right back to the title screen without making the world.

**Comment by The-1-7-10-Pack** [comment]
Can you please provide a bit more information?
I need your latest game log.

**Comment by ptrckstmp** [comment]
http://paste.ubuntu.com/10558180/

**Comment by The-1-7-10-Pack** [comment]
> NotEnoughResources-1.7.10-0.1.0.55.jar

The modpack uses NotEnoughResources version 0.1.0.93, which fixes this.
I don't know why do you have the wrong version. Just reinstall or switch the versions manually, that would do it.
