### ISSUE TITLE
Cannot find items in Inventory

### ISSUE THREAD

**Issue by yy1996** [The-1-7-10-Pack/The-1.7.10-Pack#300]
Hi I was playing yesterday and logged off after, when I opened the game today and searched my inventory for "Hollow slabs" it gave me nothing but "Hollow stone slabs", I went through every item in the inventory and the items that i could find yesterday are not there anymore. I am wondering what might have caused this issue. Thank you!

**Comment by The-1-7-10-Pack** [comment]
Weird, but I can't confirm this in any way.
If you see more of this issue, please report it back.
But maybe you just forgot something :)
