### ISSUE TITLE
Zip file doesn't exist?

### ISSUE THREAD

**Issue by cozac** [The-1-7-10-Pack/The-1.7.10-Pack#301]
When I attempt to install this pack I receive an error message that reads: "Error unzipping a file for the following pack: The 1.7.10 Pack Attempting to extract file the-1710-pack-0.7.4a.zip, but it did not exist. Please consult the modpack author." Can somebody help me fix this issue?

**Comment by The-1-7-10-Pack** [comment]
Is it the first time you install the modpack?

**Comment by The-1-7-10-Pack** [comment]
I'll answer you guys in #292!
