### ISSUE TITLE
RF tools

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#303]
What you think about add this one ?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-auto

**Comment by The-1-7-10-Pack** [comment]
What does this mod add?

**Comment by thebalck** [comment]
New dimentions, made by the user and some extras for the RF tools already in the mod pack

**Comment by The-1-7-10-Pack** [comment]
The 1.7.10 Pack has TONS of RF tools from a lot of mods (Mekanism, IC2, Redstone Arsenal and what not).
We don't need more, really don't.
Thanks anyway :)

**Comment by thebalck** [comment]
Men you want mystcraft in your mod pack but you cant have it this is an alternative to mystcraft and it is a complemente to RF arsenal mod
