### ISSUE TITLE
Chiseled Microblocks

### ISSUE THREAD

**Issue by GreatHolyCow** [The-1-7-10-Pack/The-1.7.10-Pack#304]
When upgrading server to 0.7.4a i noticed it changes all my chiseled microblocks to dark oak leaves
example: http://imgur.com/bI8laxM
originally these blocks where just like the ones around them chiseled marble choped into microblock covers covering glowstone covers...

All Vanilla microblocks are fine only microblocks that where chopped up from any chiseled block

**Comment by thebalck** [comment]
Same happen to me when i update to 0.7.3

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/241#issuecomment-77354364
