### ISSUE TITLE
Hey me again. New issue.

### ISSUE THREAD

**Issue by jakebee101** [The-1-7-10-Pack/The-1.7.10-Pack#305]
I posted a few months ago, and it was I couldn't launch at all. Now, I'm posting because I can launch, but barely, and what I CAN launch isn't worth much. I got a new computer, with 64 bit windows, got 64 bit Java, and allocated 3 G to Technic. I get to the screen with "Initializing" and an hourglass, then it stops. That's all I get to. Please help. This is a copy of my latest log, and it's not much: http://paste.ubuntu.com/10560484/

**Comment by The-1-7-10-Pack** [comment]
Try to delete all of your resource packs from the modpack's folder.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
