### ISSUE TITLE
Game wont Launch after I reopened my launcer

### ISSUE THREAD

**Issue by mictim13** [The-1-7-10-Pack/The-1.7.10-Pack#306]
I have been playing on the mod pack for about a Week and loving it. Today when I opened the launcher I couldn't launch the game itself my friend has had the same problem I am running version 0.7.3 and can run other modpacks 100% fine

Also if possible could you add Ars Magica 2

**Comment by The-1-7-10-Pack** [comment]
What do you mean game wont launch? Please provide the latest log.
Also guys you should play on the latest version, v0.7.4a.

**Comment by mictim13** [comment]
I tried 0.7.4a and I can open the launcher but when I press play the pack wont load just the same as the 0.7.3 

Ill get the log for you in a second

**Comment by The-1-7-10-Pack** [comment]
> Please provide the latest log.

**Comment by mictim13** [comment]
[B#283] 2015/03/08 20:03:01 [INFO] Console Mode Activated
[B#283] 2015/03/08 20:03:03 [INFO] Expected MD5: 94a9d4cbcb9ceaa25000fa303fa81acc Calculated MD5: 94a9d4cbcb9ceaa25000fa303fa81acc
[B#283] 2015/03/08 20:03:04 [INFO] Expected MD5: b62087eb4b11746987c800c0512890ef Calculated MD5: b62087eb4b11746987c800c0512890ef
[B#283] 2015/03/08 20:03:04 [INFO] OS: windows 8
[B#283] 2015/03/08 20:03:04 [INFO] Identified as windows
[B#283] 2015/03/08 20:03:06 [INFO] Starting download of http://crafatar.com/avatars/caf8ab158ada4664a8abda798088049a?size=100&helm, with 3 tries remaining
[B#283] 2015/03/08 20:03:07 [INFO] Starting download of http://www.gravatar.com/avatar/417979e451a4ed37c22f5340a9c3cd4a?s=60&d=retro, with 3 tries remaining
[B#283] 2015/03/08 20:03:07 [INFO] Starting download of http://www.gravatar.com/avatar/4c9b9cd817e62d043070a821551c04f0?s=60&d=retro, with 3 tries remaining
[B#283] 2015/03/08 20:03:07 [INFO] Starting download of http://www.gravatar.com/avatar/2a29f323eddf3410fb1b531b10f7df6f?s=60&d=retro, with 3 tries remaining
[B#283] 2015/03/08 20:03:07 [INFO] Starting download of http://www.gravatar.com/avatar/07b1950664b5569324a88727516e761d?s=60&d=retro, with 3 tries remaining
[B#283] 2015/03/08 20:03:07 [INFO] Starting download of http://www.gravatar.com/avatar/07b1950664b5569324a88727516e761d?s=60&d=retro, with 3 tries remaining
[B#283] 2015/03/08 20:03:11 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-logos/552559.png?1419880204, with 3 tries remaining
[B#283] 2015/03/08 20:03:11 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-backgrounds/552559.jpg?1419880204, with 3 tries remaining
[B#283] 2015/03/08 20:03:11 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-logos/552559.png?1419880204, with 3 tries remaining
[B#283] 2015/03/08 20:03:11 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-backgrounds/552559.jpg?1419880204, with 3 tries remaining
[B#283] 2015/03/08 20:03:12 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1425772153, with 3 tries remaining
[B#283] 2015/03/08 20:03:12 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/552559.png?1419880204, with 3 tries remaining
[B#283] 2015/03/08 20:03:12 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/552559.png?1419880204, with 3 tries remaining
[B#283] 2015/03/08 20:03:14 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/552559.png?1419880204, with 3 tries remaining
[B#283] 2015/03/08 20:03:18 [INFO] Starting download of http://www.gravatar.com/avatar/d593acb99c078196c657559168b57a6e?s=60&d=retro, with 3 tries remaining
[B#283] 2015/03/08 20:03:18 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1425772153, with 3 tries remaining
[B#283] 2015/03/08 20:03:20 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1425772153, with 3 tries remaining
[B#283] 2015/03/08 20:03:22 [INFO] Running C:\Program Files\Java\jre7\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m -Djava.library.path=C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack\bin\natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -Dminecraft.applet.TargetDirectory=C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack -Djava.net.preferIPv4Stack=true -Xms2048M -Xmx3072M -XX:PermSize=256M -Dfml.queryResult=Confirm -cp C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack\bin\modpack.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\mojang\realms\1.3.5\realms-1.3.5.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\java3d\vecmath\1.3.1\vecmath-1.3.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\google\guava\guava\16.0\guava-16.0.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.2.1\commons-lang3-3.2.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\mojang\authlib\1.5.16\authlib-1.5.16.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\tv\twitch\twitch\5.16\twitch-5.16.jar;C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack\bin\minecraft.jar net.minecraft.launchwrapper.Launch --username mictim13 --version 1.7.10-Forge10.13.2.1291 --gameDir C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack --assetsDir C:\Users\timmi_000\AppData\Roaming\.technic\assets --assetIndex 1.7.10 --uuid caf8ab158ada4664a8abda798088049a --accessToken 414855f8810e4deda3dfd00b6a985aec --userProperties {} --userType legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --title The 1.7.10 Pack --icon C:\Users\timmi_000\AppData\Roaming\.technic\assets\packs\the-1710-pack\icon.png
[B#283] 2015/03/08 20:03:22 [INFO] C:\Program Files\Java\jre7\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m -Djava.library.path=C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack\bin\natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -Dminecraft.applet.TargetDirectory=C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack -Djava.net.preferIPv4Stack=true -Xms2048M -Xmx3072M -XX:PermSize=256M -Dfml.queryResult=Confirm -cp C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack\bin\modpack.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\mojang\realms\1.3.5\realms-1.3.5.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\java3d\vecmath\1.3.1\vecmath-1.3.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\google\guava\guava\16.0\guava-16.0.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\commons\commons-lang3\3.2.1\commons-lang3-3.2.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\com\mojang\authlib\1.5.16\authlib-1.5.16.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;C:\Users\timmi_000\AppData\Roaming\.technic\cache\tv\twitch\twitch\5.16\twitch-5.16.jar;C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack\bin\minecraft.jar net.minecraft.launchwrapper.Launch --username mictim13 --version 1.7.10-Forge10.13.2.1291 --gameDir C:\Users\timmi_000\AppData\Roaming\.technic\modpacks\the-1710-pack --assetsDir C:\Users\timmi_000\AppData\Roaming\.technic\assets --assetIndex 1.7.10 --uuid caf8ab158ada4664a8abda798088049a --accessToken 414855f8810e4deda3dfd00b6a985aec --userProperties {} --userType legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --title The 1.7.10 Pack --icon C:\Users\timmi_000\AppData\Roaming\.technic\assets\packs\the-1710-pack\icon.png 
[B#283] 2015/03/08 20:03:22 [INFO]  Error occurred during initialization of VM
[B#283] 2015/03/08 20:03:22 [INFO]  Could not reserve enough space for object heap
[B#283] 2015/03/08 20:03:23 [INFO] Analytics Response [runModpack]: 200
[B#283] 2015/03/08 20:03:24 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1425772153, with 3 tries remaining

**Comment by The-1-7-10-Pack** [comment]
Please post the **full** fml-client-latest.log file and use a [paste tool](http://paste.ubuntu.com/).

**Comment by The-1-7-10-Pack** [comment]
A second has passed :)

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
