### ISSUE TITLE
Suggestions: Technomancy and Advanced Thaumaturgy

### ISSUE THREAD

**Issue by TreePuncher9501** [The-1-7-10-Pack/The-1.7.10-Pack#307]
This mod fits the Magic/Technology bit of this mudpack very nicely! It combines the use of Thaumcraft magic with RF Technology to bring about new and powerful mechanisms. One example of a new mechanic is the addition of Ender Jars - Warded Jars that function like Enderchests/Endertanks for essentia. Another addition is the essential coil - a device used to transmit essential wirelessly. It also adds a way to generate RF though vis, with the Node/Essentia dynamos. Technomancy is a small-medium sized mod. Link: http://forum.feed-the-beast.com/threads/0-5-1-technomancy-discussion-ore-processing-like-a-boss.40277/

As for my other suggestion, Advanced Thaumaturgy, it adds on to Thaumcraft and fits the magic side of things. It adds a few things that help the advancing thaumaturgist. One of which is the Fertilizer, which fertilizes an 8x8 area using Aqua essential. Another is a unique block called a Node Modifier, which allows one to modify a jarred node with essentia from nearby warded jars. It also allows for a thaumaturgest to 'repair' nodes that are hungry, sinister, fading, pale, tainted or unstable. Pretty useful, don't you think? Another thing it adds is the Mercurial Wand - a wand that holds 500 of any aspect, which makes it a good mid-end game wand if one doesn't wish to go all out and make Ichorium Strapped wands. Advanced thaumaturgy is also a rather small mod, and doesn't change much in the game. Link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445450-wip-advanced-thaumaturgy-thaumcraft-4-addon

**Comment by The-1-7-10-Pack** [comment]
I'm sorry but currently we won't add the mods.
Thanks anyway for suggesting! :)
