### ISSUE TITLE
Iron tanks

### ISSUE THREAD

**Issue by Snarvitlaus** [The-1-7-10-Pack/The-1.7.10-Pack#308]
it seems that iron tanks don't update whats in em if i'm on my server, if i disconnect and log back in then the tank updates whats in it but not if i'm in there. Nothing major but i thought id mention it

**Comment by The-1-7-10-Pack** [comment]
Can you explain a bit more? I'm not sure I totally understand.

**Comment by Snarvitlaus** [comment]
no problem, i pump water into the tank and nothing comes into it, the tank says 0 m/b of 100000 it stays like that untill i log out but when i log back in,then it is half full same thing with xp and lava

**Comment by The-1-7-10-Pack** [comment]
Oh I understand. Can anyone help confirm this?
I'll try to confirm this tomorrow. Thanks for reporting!

**Comment by The-1-7-10-Pack** [comment]
Tested on server with the latest version of the modpack and I can't reproduce it. :)
![image](https://cloud.githubusercontent.com/assets/10350644/6766867/50f211f2-d020-11e4-9f17-86b048411007.png)
