### ISSUE TITLE
Takes forever to load up for me, won't at all for my friend 

### ISSUE THREAD

**Issue by goldenflames15** [The-1-7-10-Pack/The-1.7.10-Pack#309]
I get that the pack takes a good while to load up and then runs perfectly after it finally does, but my friend's just keeps endlessly loading for hours if you leave it. It never starts. Is there anything you'd suggest doing to try and help make it able to start?

**Comment by The-1-7-10-Pack** [comment]
I need yours and your friend's fml-client-latest.log files, also both system details.
Please use a [paste tool](http://paste.ubuntu.com/) to post the logs.

**Comment by goldenflames15** [comment]
Where would I find the logs? I'm running an Alienware and I don't have a problem other than being patient, he has a Dell, what do you mean by system details?

**Comment by The-1-7-10-Pack** [comment]
I need to know how much RAM do you have, CPU type, GPU type, not just a company name.
The logs are in the modpacks folder/logs/fml-client-latest.log

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
