### ISSUE TITLE
ender io smeltery

### ISSUE THREAD

**Issue by liamcax** [The-1-7-10-Pack/The-1.7.10-Pack#310]
When I smelt ingots occasionally the ingots instead of getting pulled out by the itemduct  get pulled into the top slot so other ores cannot get smelted. it throws off my auto smelting system

**Comment by The-1-7-10-Pack** [comment]
Huh? are you sure you have setted up everything currectly?

**Comment by liamcax** [comment]
yes i'm sure

**Comment by The-1-7-10-Pack** [comment]
I can't get it to do what you're saying. Can you provide a picture and be more specific?

**Comment by liamcax** [comment]
http://i.imgur.com/hIucYEn.png

here is the picture

**Comment by The-1-7-10-Pack** [comment]
This picture doesn't tell me much.
You need to be sure you put the Smeltery putput to the itemduct side, also you need to be sure that the smeltery is pushing items to the itemduct, because if not, you need to put a servo.

**Comment by liamcax** [comment]
okay thank you

**Comment by The-1-7-10-Pack** [comment]
:+1:
