### ISSUE TITLE
Cant Craft Anything

### ISSUE THREAD

**Issue by martyb447** [The-1-7-10-Pack/The-1.7.10-Pack#312]
Hi,

Having an issue where by I can see recipies but cant take anything out of the crafting table grid.

At present as only started the world I have tried tinkers construct and bibliocraft.
I checked the configs and the server config file and the client file were different so Ive uploaded the client one (D/L via tecknic launcher) onto server but still no joy.

Not a genius at this so if you need me to do something please explain as if i'm about 5.

Cheers

**Comment by martyb447** [comment]
Update:

It seems that non of the mod craftable items are working. the recipe shows and when you put the materials in it does show in the RH box but you cant take it out.

So far i've replaced the server mods and config file with the one I have on my comp so I know they are both identical.

Googling suggests it could be a problem with forge?

**Comment by The-1-7-10-Pack** [comment]
So the server didn't load any mods at all, you've installed it wrong.
Just re-download the server files and keep the map :)

**Comment by martyb447** [comment]
I just copied it straight from the tecknic download straight to the server. But ill try again. Cheers

**Comment by The-1-7-10-Pack** [comment]
If you have any more questions be sure to post them here (:
