### ISSUE TITLE
Suggestion : NPC MOD 

### ISSUE THREAD

**Issue by Aldamert** [The-1-7-10-Pack/The-1.7.10-Pack#313]
Hello, Me And My Friends Are Doing A PvP Style Server but We Also Going Aesthetics So We Were Wondering If You Could Add Custom NPC's As One Of The Mods : The Link Is Here http://www.curse.com/mc-mods/minecraft/221826-custom-npcs 

Also If This Is Not Possible, I Would Like To Have Mystcraft

**Comment by NoGood4Me** [comment]
Read the last post :)
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/266

**Comment by The-1-7-10-Pack** [comment]
^
Mystcraft: The author of Mystcraft did not give me permissions, so I can't use it in the pack.
Thanks anyway :)
