### ISSUE TITLE
Nether iridium ore

### ISSUE THREAD

**Issue by Snarvitlaus** [The-1-7-10-Pack/The-1.7.10-Pack#314]
So i got my hands on a few of these but i cant figure out how to process em, i mean to get the iridium out of the block to use it in crafting. Dose any body know how?

**Comment by The-1-7-10-Pack** [comment]
Just press 'U' to see the uses with it :)

**Comment by Spellkaze** [comment]
Sorry for saying this, but the nether iridum ore doesn't work for anything, this is beacuse the Iridium ore (the block, not the item) was removed from IC2,  but I don't see cheating using the creative mode and changing them for two iridums ores (the item one), unless you don't have permissions, but that is something you can only decide.

**Comment by The-1-7-10-Pack** [comment]
NetherOres should be smart enough to process the nether iridum ore straight to iridium ingots.
