### ISSUE TITLE
help needed with voxelmap

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#315]
hi, 

I hope someone can help is there a way i can reset the minimap explored areas im about to start a series and since i built things, all over the map i don't want ppl to see if i can i want to have it like i was on a new map just the area around me shows up. i have looked in the folder and the mods website no one seems to say how if its possible.

**Comment by The-1-7-10-Pack** [comment]
I guess that the VoxelMap saves your map in a specific place on the modpack's folder.
You should go to the [VoxelMap MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2261180) and ask there where are the files located, so you'll be able to delete them.
Good luck! (:
