### ISSUE TITLE
missing folder to do with voxelmaps 

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#317]
i was told on the voxelmap forum thread to delete  cached data files at .minecraft/mods/VoxelMods/voxelMap/cache/WORLDNAME

i searched there is no .minecraft folder in roaming and upon searching the 1.7.10 pack folder i can not find the folders under voxelmap folder is a properties file and nothing else has this mod been installed in a different way, since the mod Arthur said thats where i need to delete.

**Comment by The-1-7-10-Pack** [comment]
If so, it's on .technic/modpacks/the-1710-pack/mods/VoxelMods/voxelMap/cache

**Comment by darktrek** [comment]
this is all thats in the folder 


![untitled](https://cloud.githubusercontent.com/assets/10510248/6607630/3d79184a-c838-11e4-952a-144974fb2c53.png)

**Comment by The-1-7-10-Pack** [comment]
So you've deleted all the cache (:
