### ISSUE TITLE
Initialising forever

### ISSUE THREAD

**Issue by AntoSerr** [The-1-7-10-Pack/The-1.7.10-Pack#318]
i have been waiting on my game to initialise for atleast 10-15 mins

**Comment by The-1-7-10-Pack** [comment]
10, 15 = forever
ANYWAY: Can't do anythin' without a log!
please read how to get help [there](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
