### ISSUE TITLE
JSON Shaped crafting 

### ISSUE THREAD

**Issue by Jaymathmatics** [The-1-7-10-Pack/The-1.7.10-Pack#319]
Hello!

First of all:
Love your modpack and we've had hours and hours of fun on our server! 
so thank you so much for the best modpack so far!

However.. we're starting to reach end game and I just started to make Modular Powersuits for our croup.
Everything else works just fine but I can't add "mechanical assistance" module or craft any of the pieces that it reguires? (artificial muscle and the lubricant stuff in them) all other JSON recipes work just fine and I can even see how to make them but when I go to a crafting table = nothing on right side?

I've tried using vanilla table, crafting station and ME-system but no luck 
(knowing that sometimes mods just don't work in all of the crafting tables and crids)

Any idea what could be the cause of this?

Thanks in advance

- Jay -

**Comment by The-1-7-10-Pack** [comment]
Happy to see you're having fun guys, thanks for telling me [:
About your problem..Amm..
![image](https://cloud.githubusercontent.com/assets/10350644/6616627/8ce6e774-c8b8-11e4-80bb-e5062afbe9fe.png)

**Comment by Jaymathmatics** [comment]
![myofiber gel](https://cloud.githubusercontent.com/assets/11436541/6619526/7e57a778-c8d3-11e4-9f45-360389020e8f.jpg)
This is my singleplayer world and no luck :/

**Comment by The-1-7-10-Pack** [comment]
Gotcha. A mod bug, I'll be sure to report that.
Thanks.

**Comment by Jaymathmatics** [comment]
No problem, happy to help :)
Hopefully this minor bug will get fixed soon.
keep up the awesome work on this modpack!!!

A big thanks from Finland!
will be sure to give a donation soon to support your hard work ;)

- Jay & Friends -

**Comment by The-1-7-10-Pack** [comment]
Thank you very much @Jaymathmatics, I appreciate it! [:

**Comment by TreePuncher9501** [comment]
Actually, something similar on my end. My brother plays this mudpack on his computer, and cannot use NEI to look at the recipes for the item for Modular Powersuits. Any other mod and the like works, but only Powersuits seems to be bugged.

**Comment by The-1-7-10-Pack** [comment]
@TreePuncher9501 This mod's recipes is located on it's config folder. I'm not sure in what version of the modpack your brother is playing but if he has problems he can just reset "QMXTech" & "machinemuse" folders on the config folder in the modpack's folder (:

**Comment by The-1-7-10-Pack** [comment]
Still waiting for an update from the mod author.

**Comment by The-1-7-10-Pack** [comment]
Unfortunately it doesn't seem like the author puts effort into the mod currently. Nothing I can do.
