### ISSUE TITLE
Crashing on login

### ISSUE THREAD

**Issue by DragonMaster260** [The-1-7-10-Pack/The-1.7.10-Pack#32]
whenever i log in to the server it crashes me for some strange reason and i have no idea why and

**Comment by chrisps89** [comment]
Can you paste your crash report into http://paste.ubuntu.com/ please. Is this a new error ? Have you been able to log into the server previously ?

**Comment by The-1-7-10-Pack** [comment]
Also what server do you need support to? a private one?

**Comment by DragonMaster260** [comment]
i need support with the public one

and also this has happened to me before so im pretty sure one sure way of doing it is deleting my player save file for the server its okay if you do that i had nothing valuble on me exept food

**Comment by DragonMaster260** [comment]
ok i pasted my crash report at http://paste.ubuntu.com/9672771/

**Comment by The-1-7-10-Pack** [comment]
So you're crashing when you enter the official server?

**Comment by DragonMaster260** [comment]
yes it just brings me to the launcher

**Comment by The-1-7-10-Pack** [comment]
We deleted your data from the server and it might help. Also server is currently having some issues so try again later.

**Comment by DragonMaster260** [comment]
oh no it didnt work well i have no idea what to do about it now

**Comment by The-1-7-10-Pack** [comment]
You still can't login to the server?

**Comment by DragonMaster260** [comment]
oh i guess the new server fixed it i can log in now 

problem solved i guess

**Comment by Hereks** [comment]
I'm currently having some problems entering the server as well ATM my username is Techno_Flame.

**Comment by DragonMaster260** [comment]
does it crash you to the launcher?

**Comment by Hereks** [comment]
Ya

**Comment by DragonMaster260** [comment]
oh ok wll your gonna have to ask the owner

**Comment by Hereks** [comment]
That is  why I posted in this current issue

**Comment by Hereks** [comment]
I can now join the server.

**Comment by The-1-7-10-Pack** [comment]
How did you fix it?

**Comment by Rabbidfan236** [comment]
I'm having the same issue that DragonMaster260 has. http://paste.ubuntu.com/9695675/

**Comment by The-1-7-10-Pack** [comment]
Well as I see it now, it's a Flan's bug, that doesn't like being only in client.
As the server doesn't have Flan's mod installed, and client do, here the problems start.

**Comment by Rabbidfan236** [comment]
So would a fix be to delete Flan's mod from my client and then try to reconnect?

I would also like to note that I was able to connect to the server for some time before this bug started happening, even after the world reset, but now I can't connect at all.

**Comment by The-1-7-10-Pack** [comment]
It should indeed be fixed if you delete Flan's from client. But I don't see it as a real fix.

**Comment by Flukethoughts** [comment]
Flans mod is the issue been verified on five accounts so far

**Comment by The-1-7-10-Pack** [comment]
Reported to Flan's, nothing we can do. Flan's doesn't like being on client only.
