### ISSUE TITLE
Lets try this again lol

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#324]
RF tools mod sugestion, this mod is like Mystcraft the mod that you want in the mod pack but u cant have because you dont have premitions, this one gives you the ability to create dimentions like in the mystrcraft.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-auto

**Comment by The-1-7-10-Pack** [comment]
Why would you open the same suggestion twice?
I won't add this mod, sorry :)
I'm not looking for replacement mods for Mystcraft
