### ISSUE TITLE
Modular power suit[server config]

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#325]
Hi, I want to disable modular power suit.
would you mind telling me what to change in the config file?

my google friend failed me again

**Comment by The-1-7-10-Pack** [comment]
If you wish to disable the mod from the server you can just delete it from the mods folder.
Just to be sure you need to know that this mod is separated to three parts, and you need to delete them all:
- "ModularPowersuits-0.11.0.7-QMX.jar"
- "ModularPowersuitAddons-0.11.0.7-QMX.jar"
- "Numina-0.4.0.7-QMX.jar"
