### ISSUE TITLE
Pack won't start

### ISSUE THREAD

**Issue by blackdragon2026** [The-1-7-10-Pack/The-1.7.10-Pack#327]
I re installed the pack, and updated my java, which was old and was giving me a fatal error message box before closing the pack.  But afterwards, I see that everything is going fine, but then it looks like the pack just closes by itself because I'm right back at the technic launcher.  I tried to launch vanilla minecraft and it works just fine, and closing it takes me pack to the launcher screen. Is there something obvious that I'm missing here? ._.

**Comment by The-1-7-10-Pack** [comment]
Please see how to get help [there](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md). :P

**Comment by blackdragon2026** [comment]
![screenshot 2015-03-14 13 35 42](https://cloud.githubusercontent.com/assets/11477260/6652728/1fe040ce-ca4f-11e4-9d6d-fc72a8199803.png)
There is no logs in the place you had designated in the link.
Like I said previously, I reinstalled the latest version without adding anything extra, on a windows 8 64bit version with updated java
I don't know what optifine is and isn't coming up on my search, so I'm going to assume I don't have it
And last time I looked around, herobrine wasn't around.

That's all I got chief, and I don't know why there is a MACOSX folder in my files

**Comment by The-1-7-10-Pack** [comment]
What version of Java?

**Comment by blackdragon2026** [comment]
It says version 8 Update 40 (build 1.8.0_40-b26)

**Comment by The-1-7-10-Pack** [comment]
Can you please give me your latest *launcher* log? (:

**Comment by blackdragon2026** [comment]
http://paste.ubuntu.com/10598667/

Is this what you need?

**Comment by The-1-7-10-Pack** [comment]
Indeed.
What makes you think that your Java version is 64 bits? because it's not. It's 32. :)
