### ISSUE TITLE
Block problems

### ISSUE THREAD

**Issue by liamcax** [The-1-7-10-Pack/The-1.7.10-Pack#328]
When I loaded up the game I was unable to break any blocks. I even tried restarting the pack and I still couldn't break any blocks

**Comment by The-1-7-10-Pack** [comment]
I need MUCH more information to help you mate. Please read [there[(https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
