### ISSUE TITLE
Mod Suggestion: More Wolves.

### ISSUE THREAD

**Issue by Voideon** [The-1-7-10-Pack/The-1.7.10-Pack#330]
So, There's a mod i've been wanting to play with a bunch of other mods...But I suck at modding, I can do basics but not that well. Anyways, Here's the mod.
http://www.planetminecraft.com/mod/125-more-wolves-mod---a-wolf-for-every-biome-v10/
I think it would definitely benefit the pack as there's not that much based around wolves in it, (personally Love Wolves).
This would add a new wolf for every biome and make having "pets" much more "colorful"
Anyways, if you add it Thanks Alot, And if not, that's fine.
Thanks for reading. Yours Truly.
~Voideon.

**Comment by The-1-7-10-Pack** [comment]
The More Wolves mod looks cool but not more than that, it doesn't add too much to the gameplay. I won't add it. Thanks anyway!
