### ISSUE TITLE
Not loading in correctly for Technic Launcher for Mac Osx

### ISSUE THREAD

**Issue by epicman9538** [The-1-7-10-Pack/The-1.7.10-Pack#331]
My friend opened a server for this pack and i can't join because it keeps crashing.

**Comment by The-1-7-10-Pack** [comment]
I need MUCH more information, see [there](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
