### ISSUE TITLE
Auto Refill Bug? :Bug

### ISSUE THREAD

**Issue by 82280zx** [The-1-7-10-Pack/The-1.7.10-Pack#332]
Having issues with items disappearing on the hotbar. Lets say I break a pickaxe and it puts a new one on my bar (or same slot I had equiped or was using), it doesn't show up unless you click the spot or logout and come back in. Anything that auto refills seems to disappear.

**Comment by The-1-7-10-Pack** [comment]
Inventory Tweaks: it's a known bug that nobody wants to fix, they mostly focused on 1.8 dev unfortunately; nothing I can do about it, it'll happen on every 1.7.10 modpack.
