### ISSUE TITLE
Minor Bug: Distortion

### ISSUE THREAD

**Issue by TreePuncher9501** [The-1-7-10-Pack/The-1.7.10-Pack#335]
Don't know what's causing it, but the distortion wand focus and the robes of the stratosphere aren't dissipating the arrows fired from skeletons. If there isn't enough information I will answer any inquiries.

**Comment by The-1-7-10-Pack** [comment]
Can you test it on other modpacks?

**Comment by The-1-7-10-Pack** [comment]
The robes of the stratosphere as I know shouldn't do the such.
I need to confirm the distortion wand focus though :)

**Comment by The-1-7-10-Pack** [comment]
The 1.7.10 Pack uses the latest version of Thaumic Tinkerer. You should report that on [their repository](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues) :)
