### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by Cubeoverlord** [The-1-7-10-Pack/The-1.7.10-Pack#337]
The link provided doesnt work for me for some reason.

http://api.technicpack.net/modpack/the-1710-pack

everytime i load the link this shows up on just a blank white screen with this code in it.
{
  "status": 401,
  "error": "Request Unauthorized"
}

**Comment by The-1-7-10-Pack** [comment]
You need to post it on the [Technic Launcher](http://www.technicpack.net/download), not on the broswer.
