### ISSUE TITLE
Wrench compatibility

### ISSUE THREAD

**Issue by Canuck117** [The-1-7-10-Pack/The-1.7.10-Pack#338]
In the Tekkit pack for 1.6.4, most mods wrenches, including the Crescent Hammer from TE, were interchangeable.  This does not seem to be the case here.  For instance, a Crescent Hammer will no longer interact with Applied Energistic blocks or entities.  Is this a mod issue or a modpack issue, or has that very convenient feature been removed?  I don't like having to switch between five different wrenches to work on my machines.

**Comment by Canuck117** [comment]
For clarity, I've only tested this between AE and Thermal Expansion.

**Comment by The-1-7-10-Pack** [comment]
I have no way to control what mod uses what mods APIs, and to be honest: I think it's more fair the way it is now as your describe it. (:
