### ISSUE TITLE
Mod pack quitting please HELP!!!

### ISSUE THREAD

**Issue by OnlyCylus** [The-1-7-10-Pack/The-1.7.10-Pack#339]
Whenever I click the play button on the technic launcher, the mod pack opens for about 4 seconds then quits. Please help!

the is the latest launcher log:
http://pastebin.com/0njG3Uyf

**Comment by OnlyCylus** [comment]
and this is the "Technic Launcher Console" if it would help, cuz i saw a bunch of errors there:
http://pastebin.com/g7rsC8Mv

**Comment by The-1-7-10-Pack** [comment]
Are you able to run other modpacks from the Technic Launcher?

**Comment by KingdomCrusher** [comment]
the same thing has been happening to me but i am still able to play other mod packs on the technic launcher
 i need help

**Comment by Cubeoverlord** [comment]
same issue is happening for me. Every time I hit play, it just load for a few seconds then nothing happens.

**Comment by The-1-7-10-Pack** [comment]
@KingdomCrusher & @Cubeoverlord: Guys, you probably just don't have the right version of Java. You need 7 or 8 and 64 bit. This is the reason for 98% of the "Modpack can't launch plz fix" problems :P

**Comment by KingdomCrusher** [comment]
how do i get 64 bit?

**Comment by The-1-7-10-Pack** [comment]
@KingdomCrusher Just uninstall your Java and install the 64bit version of it :)

**Comment by KingdomCrusher** [comment]
thanks

**Comment by Cubeoverlord** [comment]
I have java 8 and 64 bit. Still not doing anything everytime i hit play button. I can play all other mods from Technic Launcher.

**Comment by OnlyCylus** [comment]
I have java 8 and 64 bit. Still not doing anything everytime i hit play button. I can play all other mods from Technic Launcher

**Comment by OnlyCylus** [comment]
Haaaalp pl0x

**Comment by Cubeoverlord** [comment]
If you're running on 32bit and want to get 64bit
watch this video.

https://www.youtube.com/watch?v=nIQMpl5vn1M

He'll tell you what to download and how to do it.
when he tells you to un-install the old java and you can't find don't worry about it just install the new 64bit java and you'll be fine.

My game perfectly working now.

**Comment by The-1-7-10-Pack** [comment]
So everybody is perfect except for @OnlyCylus. Man, can you give me your latest launcher log?

**Comment by OnlyCylus** [comment]
@The-1-7-10-Pack http://pastebin.com/40eKxVz6 this is the latest one, just now

**Comment by OnlyCylus** [comment]
@The-1-7-10-Pack 
btw, tried java 7 & java 8
same shit :/

**Comment by The-1-7-10-Pack** [comment]
@OnlyCylus You're running with Java 6, this is your problem :)
> Running /System/Library/Java/JavaVirtualMachines/**1.6.0.jdk**/Contents/Home/bin/java

**Comment by OnlyCylus** [comment]
this is impossible, this is what I'm running

 http://gyazo.com/5b4cf14db38d86c8654b23d5fabe55de

**Comment by The-1-7-10-Pack** [comment]
You probably did some things wrong..You can have more than one version of Java running..You need to uninstall the old versions. Also on the launcher settings you can choose the Java you want to run.

**Comment by OnlyCylus** [comment]
ohh ok then this is reasonable, it might be multiple java versions running at the same time...
I'll check and let u know.
Thanks for the help, really appreciate it

**Comment by The-1-7-10-Pack** [comment]
(;

**Comment by OnlyCylus** [comment]
Fixed, thanks again C:
