### ISSUE TITLE
Bug: Creating the Runic Matrix?

### ISSUE THREAD

**Issue by Slablaatje** [The-1-7-10-Pack/The-1.7.10-Pack#34]
Hi,
I am in a server and I can't seem to make a "Runic matrix" from the "Thaumcraft" mod.
It did work in version 0.6.0 but not in 0.6.1
Plz. help

**Comment by The-1-7-10-Pack** [comment]
It's working for me in v0.6.1. Try to figure it out, maybe you lost your research?
![image](https://cloud.githubusercontent.com/assets/10350644/5606446/d0c9c93e-9438-11e4-872f-a5d59c211a60.png)

**Comment by Slablaatje** [comment]
I have tried all other shards (but not yet the balanced one's) but they don't seem to work...
The recipe say's it can use all type of shards

**Comment by The-1-7-10-Pack** [comment]
The NEI Recipes for Thaumcraft are not default, it's an add-on mod- so there might be some small mistakes. In the thaumonomicon it says you can use only the balanced ones. :)

**Comment by Slablaatje** [comment]
![werkt niet](https://cloud.githubusercontent.com/assets/10389176/5607935/14088ab0-946f-11e4-9f6b-a9577b26fbca.jpg)

I have tried balanced shards now, still nothing...

**Comment by The-1-7-10-Pack** [comment]
For the recipe to work you need to be sure you researched the item you wish to get in the thaumonomicon.

**Comment by Slablaatje** [comment]
I have researched the Infusion thing.
If i open my thaumonomicon is displays as researched, and shows how to craft it.

**Comment by The-1-7-10-Pack** [comment]
You actually have a research for the Runic Matrix itself I'm pretty sure.

**Comment by Slablaatje** [comment]
![werkt niet 2](https://cloud.githubusercontent.com/assets/10389176/5618755/4f4d40cc-951c-11e4-9854-797c8595b227.jpg)

**Comment by Slablaatje** [comment]
still nothing...

**Comment by The-1-7-10-Pack** [comment]
Weird, how did you get this ender pearl?

**Comment by Slablaatje** [comment]
I don't know anymore, but if I find out I will tell it in a new comment
