### ISSUE TITLE
1.7.10 pack not launching

### ISSUE THREAD

**Issue by TheCowCrafter** [The-1-7-10-Pack/The-1.7.10-Pack#340]
it will load for a few seconds, but then not launch... i have java 8 installed... help please?

**Comment by The-1-7-10-Pack** [comment]
32 bit version?

**Comment by TheCowCrafter** [comment]
no 64 bit version

**Comment by The-1-7-10-Pack** [comment]
Can you please provide the latest log? :)

**Comment by TheCowCrafter** [comment]
uhhh cant find it

**Comment by TheCowCrafter** [comment]
no text comes up when i try to launch it

**Comment by The-1-7-10-Pack** [comment]
Read [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by TheCowCrafter** [comment]
i cant find the log though

**Comment by TheCowCrafter** [comment]
could you tell me where it is?

**Comment by The-1-7-10-Pack** [comment]
If you can't find the modpack's log, please provide the latest launcher log (:

**Comment by filtses** [comment]
i have the same problem

**Comment by filtses** [comment]
here is the [log] (file:///C:/Users/xiou/Desktop/techniclauncher_2015-03-15.log)

**Comment by filtses** [comment]
file:///C:/Users/xiou/Desktop/techniclauncher_2015-03-15.log

**Comment by The-1-7-10-Pack** [comment]
@filtses You have Java 32 bit :P

**Comment by filtses** [comment]
i fixed it thanks ;)

**Comment by luna6667** [comment]
here is my log

**Comment by luna6667** [comment]
http://paste.ubuntu.com/10607350/

**Comment by luna6667** [comment]
halp i wanna play

**Comment by Cubeoverlord** [comment]
If you're running on 32bit and want to get 64bit
watch this video.

https://www.youtube.com/watch?v=nIQMpl5vn1M

He'll tell you what to download and how to do it.
when he tells you to un-install the old java and you can't find don't worry about it just install the new 64bit java and you'll be fine.

My game perfectly working now.

**Comment by luna6667** [comment]
k will try

**Comment by The-1-7-10-Pack** [comment]
@luna6667 Everything is okay? (:

**Comment by Eclipzz** [comment]
where can i find my log for the 1.7.10 pack??

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
