### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by gualtyphone** [The-1-7-10-Pack/The-1.7.10-Pack#341]
Hey, i really think you should take a look at Draconic Evolution, it's a very cool mod that i think would fit The 1.7.10 Pack ;) http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2093099-draconic-evolution-1-0-0e

Reason: it's really cool, and has some very interesting features that difer from the other mods ;)

Edit:Found out after posting it had been already suggested and rejected, sorry ;(

**Comment by The-1-7-10-Pack** [comment]
It's okay, thanks anyway for suggesting and taking a part of this project. :)
