### ISSUE TITLE
suggestion for new mods

### ISSUE THREAD

**Issue by zederock** [The-1-7-10-Pack/The-1.7.10-Pack#342]
Hey hi its me on should add a couple new mods that would be a great addition to your amazing modpack some like metallurgy 4 which adds tons of awesome new weapons and armor which is all compatible and adds more with tinkers construct. And also 2 more like ars magica 2 or minechem all great mods that would a lot of new suggestions and things to do in the pack thank you and keep making this modpack awesome!

**Comment by The-1-7-10-Pack** [comment]
I won't add any of these three mods unfortunately, sorry.
Thanks anyway for suggesting and being a part of this project!
