### ISSUE TITLE
Minecraft Comes Alive

### ISSUE THREAD

**Issue by Voideon** [The-1-7-10-Pack/The-1.7.10-Pack#343]
Minecraft Comes Alive.
It would fit perfectly with the new Witchery Update.
Plus, it's such a fun mod.
It would be awesome for the 1.7.10 Server.

**Comment by The-1-7-10-Pack** [comment]
Why do you think it'd fit perfectly with the new Witchery update?

**Comment by Voideon** [comment]
New witchery update adds Guards, Village Walls, Towers, Vampire Villagers and Werewolf villagers.
Minecraft gives them new skins and more too do with them. :3

**Comment by Voideon** [comment]
;p

**Comment by The-1-7-10-Pack** [comment]
Minecraft Comes Alive affects the gameplay a lot and not everybody like it. For now you can add it manually, it just doesn't fit the modpack 100%.
Thanks anyway for suggesting :P
