### ISSUE TITLE
1.7.10 pack not launching?

### ISSUE THREAD

**Issue by truhooo** [The-1-7-10-Pack/The-1.7.10-Pack#346]
Wont launch? i have latest optifine,and java 64 bit latest version

**Comment by The-1-7-10-Pack** [comment]
You need Java 7 or 8, not Java 6! :)

**Comment by truhooo** [comment]
http://paste.ubuntu.com/10615648/

**Comment by The-1-7-10-Pack** [comment]
You have Java 32 bit, this is your problem.
