### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by bennygeorgiev** [The-1-7-10-Pack/The-1.7.10-Pack#348]
i have a problem with thaumcraft, i can't research the ichor i researched all the normal thaumcraft[exept golems], thaumic tinkerer and Thaumic Exploration and it steel not apear to i have a problem with thaumcraft, i can't research the ichor i researched all the normal thaumcraft[exept golems], thaumic tinkerer and Thaumic Exploration and it still not apear

**Comment by The-1-7-10-Pack** [comment]
Wha? Can you please explain a bit better?

**Comment by bennygeorgiev** [comment]
i researched all the thaumcraft normal [without addons] and the thaumic tinkerer and the ichor research not appear

**Comment by bennygeorgiev** [comment]
in the  thaumonomicon

**Comment by bennygeorgiev** [comment]
somebody help please

**Comment by The-1-7-10-Pack** [comment]
I need to confirm this first, it may take a bit :)

**Comment by bennygeorgiev** [comment]
ok

**Comment by The-1-7-10-Pack** [comment]
Huh?
![image](https://cloud.githubusercontent.com/assets/10350644/6749432/dd39b6c0-cef8-11e4-9824-3613e71f4483.png)
