### ISSUE TITLE
Lotr and advanced genetics

### ISSUE THREAD

**Issue by vitokiller** [The-1-7-10-Pack/The-1.7.10-Pack#349]
I think adding lord of the rings mod would be good idea because it adds plenty of stuff from middle earth and middle earth. Advanced genetics would be great because you will just inject effect in yourself and releasing slots from different stuff. Sorry for the label but I don't know to add it.

**Comment by The-1-7-10-Pack** [comment]
I won't add both mods, they don't really fit the modpack.
Thanks anyway for suggesting!

**Comment by vitokiller** [comment]
Well I am making my own modpack for personal usage. Could you help a little bit.Like how to start or how to fix configs problems etc. ?

**Comment by The-1-7-10-Pack** [comment]
https://www.youtube.com/watch?v=9iZOHYuOWbU
