### ISSUE TITLE
NEI issue

### ISSUE THREAD

**Issue by RavenCGN** [The-1-7-10-Pack/The-1.7.10-Pack#35]
If I do a "Shift + R + Click" on an item in NEI, the Minecraft-Client completely crashes.

http://pastebin.com/embed_js.php?i=ivBJkkrE

**Comment by The-1-7-10-Pack** [comment]
ee3 problem.
ee3 is going to be removed next update so I hope it will fix that problem too.

**Comment by RavenCGN** [comment]
Ok, thanx for the quick replay.
