### ISSUE TITLE
modpack does not open when i click play

### ISSUE THREAD

**Issue by Eclipzz** [The-1-7-10-Pack/The-1.7.10-Pack#351]
when i launch the modpack the bar loads up and the launcher disappear for less then 1s and then it just appears again like nothing happend. No issue/error message appears :(

i have the latest verision of java(Version 8 Update 40)
.technic/logs: http://paste.ubuntu.com/10616591/
And i got no .technic/modpacks/the-1710-pack/logs folder :(
pleace help, i really wanna play :(

**Comment by The-1-7-10-Pack** [comment]
Your Java is 32bit, you need 64bit.

**Comment by Eclipzz** [comment]
But when i go in to the control panel and then programs it says I have Java version 8 update 40 64 bit?? But thanks anyway I'll try more from here :)
