### ISSUE TITLE
Issue With Witchery Werewolves.

### ISSUE THREAD

**Issue by Voideon** [The-1-7-10-Pack/The-1.7.10-Pack#352]
So i'm just letting you know this Mr Modpack Owner And Mod Owners alike. There's something wrong with the werewolf transition skin, You can go into the wolf form (wolf, and werewolf) and in FirstPerson you're able to see yourself shrink down too size or see your hand change, but in 3rd person your body stays the same. (players see the same thing, so even if you're a little wolf, they'll see a regular human you.) Now, I'm just thinking it's a Modpack issue (not too blame the modpack) but when I reinstalled the mod (same version) onto my Vanilla MC I was able to see myself change. Note: This happens in Sing player and Multiplayer.

**Comment by The-1-7-10-Pack** [comment]
![image](https://cloud.githubusercontent.com/assets/10350644/6699303/5d042878-cd09-11e4-9642-35efb905ac26.png)
Weird!
