### ISSUE TITLE
Bug report :)

### ISSUE THREAD

**Issue by Killerdoom14** [The-1-7-10-Pack/The-1.7.10-Pack#353]
Building the Advanced electric Jetpack 6178:26 in the crafting table the end product is invisible, took me a while and a random click to get the product. 

Just a bug, is this acceptable to post here?

**Comment by The-1-7-10-Pack** [comment]
I can't reproduce it, I crafted it perfectly fine. Anyway, even if it's a rare bug, it's a mod bug and I have no way to fix it.
Thanks for reporting anyway (:
