### ISSUE TITLE
Wooden Crafter Dupe

### ISSUE THREAD

**Issue by Chellex** [The-1-7-10-Pack/The-1.7.10-Pack#354]
When using the Wooden Crafter block from Progressive automation mod you can dupe items. Simply place the block on open ground, disconnected from power, and place your recipe inside. Do not craft the item, instead break the Wooden Crafter and you will get your materials AND the result back.

This was tested and easy to replicate on:
*Modpack version: 0.7.4a, 0.7.5
*A Multiplayer Server
*Singelplayer (tested by modpack creator)
*Mod version: 1.5.24, 1.6.1

**Comment by The-1-7-10-Pack** [comment]
In v0.7.5 of the modpack we updated Progressive Automation, can you test it again?
