### ISSUE TITLE
Induction Smelter Texture Problem Thermal Expansion :Bug

### ISSUE THREAD

**Issue by 82280zx** [The-1-7-10-Pack/The-1.7.10-Pack#355]
In Thermal Expansion they added a new button on the Induction Smelter underneath the arrow pointing to your resulted item. It's the flux unlock button, you can click it if you know where it is but the only way to see it is to disable the texture pack.

**Comment by The-1-7-10-Pack** [comment]
So basically the Sphax texture pack is problematic with this button?

**Comment by 82280zx** [comment]
Yes, you cannot see the button when sphax is applied, I know the mod belongs to Thermal Expansion.

**Comment by The-1-7-10-Pack** [comment]
This should be reported [there](http://bdcraft.net/community/pbdc-patches-rel/thermal-expansion-t161.html), it is not the Modpack's fault, we're just using the latest version of thermal Expansion :)

**Comment by 82280zx** [comment]
Well I figured I would let you know since the issues is in your texture pack add on to sphax :) I'll go submit it there as well.

**Comment by The-1-7-10-Pack** [comment]
Yeah I can understand that. Thanks for reporting here, and thanks for reporting there! [:

**Comment by 82280zx** [comment]
They said to check the changelog etc and to redownload it again... so I assume they fixed it? Did you update your pack with the new thermal expansion textures from there page? 

"Check the changelog and re-download the pack. It's definitely there and has been for a while now."

**Comment by The-1-7-10-Pack** [comment]
Okay, so it'll be on the next update of the Resource Pack, thanks for letting us know! :)

**Comment by The-1-7-10-Pack** [comment]
http://www.technicpack.net/status/125130
