### ISSUE TITLE
1.7.10 pack not launching

### ISSUE THREAD

**Issue by TheBommel** [The-1-7-10-Pack/The-1.7.10-Pack#356]
Hi,

the Pack isn´t lauchning ;(
I use Java 8u31 64bit for OSX

My log can you find here: http://paste.ubuntu.com/10617752/

Please help me ;(

**Comment by The-1-7-10-Pack** [comment]
Wow, you actually gave me a log! impressive report, thanks man for reading how to get help [:
Basically your problem is that your computer uses  Java 6 to the modpack. You probably have couple of Java versions installed on your computer. You should remove them all and keep only 8! :)
