### ISSUE TITLE
Unable to launch server

### ISSUE THREAD

**Issue by stoutrouge** [The-1-7-10-Pack/The-1.7.10-Pack#357]
So I downloaded the new update and uploaded it on the server. Made a new folder and everything. Go to run the .sh and it keeps crashing when it starts to load the mods. It doesn't even get to generating the map. I also tried it on my computer and it crashes at the same spot. 

[18:32:30] [Server thread/ERROR] [HatStand]: Skipping event FMLServerStoppedEvent and marking errored mod HatStand since required dependency Hats has errored
[18:32:30] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:32:30] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

Are you sure you tested the server files out before you uploaded them?

**Comment by The-1-7-10-Pack** [comment]
If I tested them? Haha, what do you think?
You've installed the server wrong. A lot of mods missing.

**Comment by stoutrouge** [comment]
How? I downloaded it from the tekkit website. Also I downloaded it twice just to be sure?

**Comment by stoutrouge** [comment]
If I download it a third time will it work?

**Comment by The-1-7-10-Pack** [comment]
Here is the download link for the latest version: http://bit.ly/The-1-7-10-Pack-ServerD-v0-7-5

**Comment by stoutrouge** [comment]
This will be my 4th time downloading it just fyi.

Thank you

**Comment by stoutrouge** [comment]
Happened again. I'm going to try to see if it happens on my friends computer. 

![4thtime](https://cloud.githubusercontent.com/assets/11480633/6699279/d6fc0534-ccd6-11e4-9361-080c3761c3c6.PNG)
![crash](https://cloud.githubusercontent.com/assets/11480633/6699286/eb5348c6-ccd6-11e4-9079-ec5ed0e7b293.PNG)

**Comment by The-1-7-10-Pack** [comment]
How do you installing the modpack? You need to unzip, put your world in and set eula.txt to true (:

**Comment by stoutrouge** [comment]
I just unzip and run the launchserver.bat

**Comment by The-1-7-10-Pack** [comment]
@stoutrouge Oh, great. So as you see, you just need to set your eule.txt to true and you're good to go [;

**Comment by stoutrouge** [comment]
Wow. I remembered that it would say that I had to accept it. I just didn't see it say anything about that. Sorry for the misunderstanding.

I'm an ass sorry

**Comment by The-1-7-10-Pack** [comment]
:P
