### ISSUE TITLE
mekanisum cables

### ISSUE THREAD

**Issue by djandy** [The-1-7-10-Pack/The-1.7.10-Pack#358]
ill leave plenty of pictures but strange things happen 1 min they will be fine all supplying power next off just dead like there not there its the supply to my farms so harvesters and planters ive tryed supplying directly from my big reactor (just kills all the power) also through an ender io vibrant capacitor bank (the bank when the cables off doesnt even see the cable exists) it works again after i destroy a few cables then put them back but its pot luck to which makes it work again and it is getting tedious i thought it was loops of power but i went through destroyed all of thouse i think and still doing it 
![2015-03-17_23 17 04](https://cloud.githubusercontent.com/assets/10949909/6699648/f07eee8e-ccfb-11e4-81ba-4c319ac27e35.png)
![2015-03-17_23 17 09](https://cloud.githubusercontent.com/assets/10949909/6699649/f1ec61a2-ccfb-11e4-929c-62c35819cdaa.png)
![2015-03-17_23 17 23](https://cloud.githubusercontent.com/assets/10949909/6699651/f365c7f8-ccfb-11e4-911e-53eef13072b7.png)

**Comment by The-1-7-10-Pack** [comment]
Mhm. I can't reproduce it, but maybe it's something specific with Mekanism and EnderIO. But at this point we have Thermal Dynamics, and EnderIO's ducts, you should try them. :)

**Comment by djandy** [comment]
swapped the problem part with the redstone energy fluxducts works fine now as i was replaceing though i think i found the problem a level emitter was on next to 1 of the cables far away from the start but the cables dont seem to like redstone signals or loops

**Comment by The-1-7-10-Pack** [comment]
> redstone signals

It disables them :P

**Comment by djandy** [comment]
yeh but because there was a redstone signal disableing that part of the cable it glitched we are talking about what 200 cables from the start also it was supplying 1 planter out of around 30 and it was at the end of 1 of the sections
