### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by JeanDJ** [The-1-7-10-Pack/The-1.7.10-Pack#36]
i tried to start the server but it wouldn't work could you help me ?

**Comment by The-1-7-10-Pack** [comment]
Please provide crash report / latest log.
Also be sure to check that your eula.txt is set to true.

**Comment by JeanDJ** [comment]
ok thx

**Comment by The-1-7-10-Pack** [comment]
Did you fix it?

**Comment by JeanDJ** [comment]
Yes
