### ISSUE TITLE
Witchery Update #2

### ISSUE THREAD

**Issue by Voideon** [The-1-7-10-Pack/The-1.7.10-Pack#360]
So, Me, and all of the players can't see each other as Werewolf (wolf, wolfman) or when in bat-form.
we just stay looking like our regular skins. 
So I tried on singleplayer and I couldn't see myself in either form so I asked 2 of the players to do it aswell and they couldn't see it either...
So since now i'm not the only one I think we need help.
Note: Version 0.7.5
Note#2: Not using Optifine.
Thanks...

**Comment by The-1-7-10-Pack** [comment]
Can anyone else try to reproduce it? Because I can't.

**Comment by Voideon** [comment]
I'll get some people to take screenshots?

**Comment by The-1-7-10-Pack** [comment]
I guess.

**Comment by Voideon** [comment]
Wolf-Form: 
-----------------------------
Voideon:
http://i.imgur.com/BNN8W2t.png
http://i.imgur.com/G3iqj47.png
http://i.imgur.com/nWLmHHJ.png (Jumped As A Little Wolf)
Alexaa7x:
http://imgur.com/bGEOJj6
http://imgur.com/iuDxDI7

two guys named NooneCares and Smite_Master also did it and they said it was the same as us...they didn't screenshot it though.

Bat-Form:
----------------------------
Voideon:
http://i.imgur.com/6OVXYDo.png 
http://i.imgur.com/9ZDx0so.png {Flying As A Bat)



Note: They all tried on singleplayer, And I tried on the Server, but none of us got it working!
Note: I only tried in bat-form since I only knew how to get into it, but I bet it would be the same for them.

**Comment by The-1-7-10-Pack** [comment]
Do you guys have any additional mods?

**Comment by Voideon** [comment]
Nope

**Comment by The-1-7-10-Pack** [comment]
You guys are on creative?

**Comment by Voideon** [comment]
I have done it on survival and it didn't work...And...Ugh, I'm actually testing if I install optifine it'll work..
but I don't think I have anymore info on it.

**Comment by The-1-7-10-Pack** [comment]
So basically there's nothing I can do.
If there's anything else you can give I'll re-open this (:
