### ISSUE TITLE
Mod Addition 

### ISSUE THREAD

**Issue by Aspeee** [The-1-7-10-Pack/The-1.7.10-Pack#361]
I would like to suggest the mod Mystcraft. I think that it will be perfect for the pack, as one of the quest lines is Adventures of Columbus. It is a mod that allows players to create their own dimensions and travel to them. 

BTW why not ask about Ducks? ;)

**Comment by The-1-7-10-Pack** [comment]
Thanks for actually reading the information.
I also think that Mystcraft will be a cool addition, but the author did not give us permissions to use the mod unfortunately, so - yeah :P

**Comment by Aspeee** [comment]
:( I'll ask ;) 

Thomas Aspinall
