### ISSUE TITLE
RAM issues

### ISSUE THREAD

**Issue by bisousbisous** [The-1-7-10-Pack/The-1.7.10-Pack#363]
Yesterday I updated the pack to 0.7.5, and now im having RAM allocation problems
Before I updated I set the launcher to allocate 4GB of RAM, and in game the allocated RAM read 4096MB, and it was constantly at that value
Now my RAM is all over the place, it seems to dynamically allocate RAM when I need it, except it kills my FPS, heres a picture: http://puu.sh/gFc1g/438e2cc71a.png
that allocated RAM value will cap out at around 3000MB, instead of staying at 4096
ive tried fully reinstalling minecraft, the pack, the launcher, and Java, all to no avail
I'm using java 8 64bit on windows 8.1

**Comment by The-1-7-10-Pack** [comment]
In The 1.7.10 Pack the RAM is allocating automatically. If your FPS is not the best you should download Optifine, but the RAM is not what killing your FPS.

**Comment by bisousbisous** [comment]
Yes it is...before it started auto allocating RAM i always had a stable 60fps, where as now its dipping to the low 20s frequently
cant i disable auto allocating somehow?
