### ISSUE TITLE
More RAM issues

### ISSUE THREAD

**Issue by bisousbisous** [The-1-7-10-Pack/The-1.7.10-Pack#364]
My last issue was closed with the explanation of "the 1.7.10 pack dynamically allocates RAM, not enough RAM isnt your problem" when my issue was that it wasnt allocating enough ram to keep my fps as 60, so yes not enough RAM WAS my problem.
so please try and address the problem this time, is there ANY way i can disable this annoying RAM allocating stuff and just have minecraft have 4096 MB allocated at all times again?

**Comment by bisousbisous** [comment]
And a lot of your comments also say "you dont need more than 3GB to play this pack". Well thats wrong because this auto allocating stuff doesnt keep my FPS at a stable 60fps, my fps is all over the place. When i had minecraft allocating 4GB of RAM at all times my fps NEVER dipped below 60, but this dynamic RAM thing is making my fps fluctuate wildly, and I even installed optifine for 1.7.10.

**Comment by TANGOjPANDA** [comment]
What he was trying to say is that the auto allocating has been a part of the pack for a long time now well before you had this problem. So in other worda this isn't your problem.

**Comment by The-1-7-10-Pack** [comment]
^
What is the precent of your RAM usage?

**Comment by bisousbisous** [comment]
It uses between 2500M and 3096M of the auto allocated RAM

**Comment by The-1-7-10-Pack** [comment]
Can you please provide a picture?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
