### ISSUE TITLE
Optifine 

### ISSUE THREAD

**Issue by vitokiller** [The-1-7-10-Pack/The-1.7.10-Pack#365]
When I try to install optifine I put optifine in mods folder and then start pack optifine doesn't show in mods list. I don't know what to do? Can you help me?

**Comment by The-1-7-10-Pack** [comment]
Just check out if you have Optifine's settings :)

**Comment by vitokiller** [comment]
No I don't have

**Comment by The-1-7-10-Pack** [comment]
Did you put the latest version of Optifine for MC 1.7.10 jar on the mods folder that is in the modpack's folder?

**Comment by vitokiller** [comment]
Yes

**Comment by The-1-7-10-Pack** [comment]
Can you please provide a picture or some more information? obviously you installed it wrong, I need a way to help you :P

**Comment by Dagwood64** [comment]
I don't know if this helps or not but I put the Optifine Jar file in the mods folder, then double click the Optifine Jar file, click install and it works fine for me. I use the 1-7-10 pack with the TechnicLauncher on windows 8.1. Sorry if it doesn't help, it's just what I do to make it work.

**Comment by vitokiller** [comment]
Ok I will try it

**Comment by The-1-7-10-Pack** [comment]
Did it work @vitokiller?

**Comment by vitokiller** [comment]
I m not at home at the weekend

**Comment by The-1-7-10-Pack** [comment]
Okay, I'm closing it for now, if you can't still install it I'll re-open it and help you. It's very simple though.
