### ISSUE TITLE
Death Dupe (Sync and other Mods)

### ISSUE THREAD

**Issue by Chellex** [The-1-7-10-Pack/The-1.7.10-Pack#366]
The 1.7.10 Pack v0.7.5

Required mods and tested versions:
- Sync (v 4.0.0) [Provides ability to dupe]
- Tinker's Construct (v 1.8.3) [Provides Dupe-able Items]

Optional:
- OpenBlocks (v 1.3) [Gravestones]

This was tested with the following Items:
- Knapsack
- Traveller's Gloves
- Traveller's Belt

When transferring from body to shell using a Shell Storage you will keep 'equipped' these items on your new (and old) shell. When you die with a body you will drop (or the gravestone will keep) the knapsack as well as the other items. You are then transferred to the nearest Shell Storage and the shell will have a Knapsack and other items still equipped. However, items contained inside the Knapsack will not be copied. Sync does not copy any items equipped in the armor slots.

But what was interesting was that the duped items kept the original items' enchantments. For example I had Haste (50 redstone) on my Traveller's Gloves. So one could copy his endgame items for friends.

While this isn't a full dupe, I'm pretty sure this wasn't intended to happen. Thank you for your continual support of the greatest modern modpack!

**Comment by The-1-7-10-Pack** [comment]
Intresting. This is a mod bug, but who should we even blame? It is complex.

**Comment by Chellex** [comment]
Sync is the mod responsible. Sync should be 'un-equipping' all items on the equipment screen. I don't think Sync was designed with Tinker's Construct in mind so the extra slots like belt, gloves and pack aren't unique to each shell/body, while armor is.

**Comment by The-1-7-10-Pack** [comment]
Well as I see this mod has already been reported, and it is complicated. If you want to read more, see [there](https://github.com/iChun/Sync/issues/9), but there's nothing I can do.
