### ISSUE TITLE
Nether Out of Control

### ISSUE THREAD

**Issue by Gifftron** [The-1-7-10-Pack/The-1.7.10-Pack#367]
Hi,

Might not be a modpack issue, was running a World Anchor in the nether as we are pumping lava out through endertanks for our factories.  There are literally hundreds/thousands of wither skeletons now, making it impossible to go to the nether without the client melting down..  Do witherskeletons not despawn?  Can I change this?

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/161
TL;DR
A bug with the EnderPump.

**Comment by Gifftron** [comment]
Will change this evening and report back.

**Comment by The-1-7-10-Pack** [comment]
:+1:

**Comment by Gifftron** [comment]
Tested it remotely, that worked as a fix!  I guess we lose the ability to spawn them individually via powered spawners but I don't use those anyway.

**Comment by The-1-7-10-Pack** [comment]
Seriously? Great! I'll apply this configuration change next update, and remove it from the known bugs list. :D

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/161
A big thanks to @bochen415 for the idea.
