### ISSUE TITLE
Ars Magica 2 (Suggestion)

### ISSUE THREAD

**Issue by Voideon** [The-1-7-10-Pack/The-1.7.10-Pack#369]
I was talking to someone on the Server and they said one of there favorite mods was Ars Magica 2.
Now I don't know much about this mod but after reading about it I think it's kinda neat and since the pack is based on 3 Major goals (Magic, Tech, Adventure) I thought since there's not that many magic mods you might add this one. It's a total suggestion and I haven't looked in it enough so if there's a problem with it being in the pack or someone then it's fine I wont cry.
Anyways here's my suggestion. Thanks.

**Comment by The-1-7-10-Pack** [comment]
It's getting a bit annoyed at this point: #59, #73, #142, #216, #222.
I'll currently won't add Ars Magica 2, and there are a lot of magic mods in the pack (:
Thanks anyway for suggesting!
