### ISSUE TITLE
Recipe Crash

### ISSUE THREAD

**Issue by James4007** [The-1-7-10-Pack/The-1.7.10-Pack#37]
I tried to get the recipe for "Programming Puzzle" using NEI and it crashed my game. It was the one with the flying seeds; I didn't try the others. It did no harm to my world, just crashed me to the launcher.

**Comment by James4007** [comment]
The crash report said it was updating screen events.

**Comment by James4007** [comment]
nvm

**Comment by The-1-7-10-Pack** [comment]
Okay..?

**Comment by James4007** [comment]
you get rid of this

**Comment by James4007** [comment]
You can get rid of this
