### ISSUE TITLE
3gb of ram is not enough .-.

### ISSUE THREAD

**Issue by zomboman** [The-1-7-10-Pack/The-1.7.10-Pack#372]
Look, I know, there are a ton of posts regarding this issue. I have been looking for quite some time now, and I haven't found the answer I'm needing. 3gb is not enough to run this pack with sphax on it. I am getting literally (like seriously LITERALLY) 1 fps. Its unplayable. Without it I am getting around 40. 40 is fine, 1 is not, and I would still like to be able to use the sphax pack. Any questions on how to get my allocate more ram. 

Also, I don't care if it doesn't need it. I just need a way to turn off the auto allocate feature. It's annoying. .-.

**Comment by The-1-7-10-Pack** [comment]
Can you please provide a picture of your RAM usage?

**Comment by zomboman** [comment]
Sorry for late reply, but here it is: 
http://tinypic.com/view.php?pic=2i87jvd&s=8

**Comment by zomboman** [comment]
Sorry for late reply:
http://i57.tinypic.com/2i87jvd.png

**Comment by Dommain** [comment]
Zomboman, Does you ram percentage go from 50% all the way up to 99% and goes back to 50% to repeat over and over?

**Comment by zomboman** [comment]
Yeah, sort of. It goes from 50 to 70 to 90, and hits random numbers in between that range.

**Comment by The-1-7-10-Pack** [comment]
It shouldn't make any lag spike unless it gets to about 95%-99%.
Install Optifine if you need to inprove performance, but 3GB is enough :)
