### ISSUE TITLE
Crash (Ender IO/IndustrialCraft)

### ISSUE THREAD

**Issue by Canuck117** [The-1-7-10-Pack/The-1.7.10-Pack#375]
http://pastebin.com/ZET6JRTj

The crash occurred when I placed an IC extractor next to an Ender IO energy conduit.  Playing on a server.

**Comment by Canuck117** [comment]
Another crash just occurred on a SP test world.  I placed one EnderIO energy conduit, and when I placed a second next to it, Minecraft crashed.  It appears the crash occurs when attempting to connect ANYTHING to an energy conduit.

**Comment by Canuck117** [comment]
Update:  Because I saw the word "render" in the crash report, I took out the Sphax 64x resourcepack.  I tested the EnderIO conduits again, and there was no crash.  Apparently the resourcepack was causing the crash.

**Comment by Canuck117** [comment]
Update 2: The crash happened again, in the same manner as the first, but without the texture pack.

**Comment by The-1-7-10-Pack** [comment]
Can you make a bit more order of the things? Thanks

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity. Anyway I think it's Optifine to blame.
