### ISSUE TITLE
Wont start up

### ISSUE THREAD

**Issue by italiankid13** [The-1-7-10-Pack/The-1.7.10-Pack#377]
Im on OSX to start off and your modpack just wont start up not sure whats going on but once the launcher goes away the modpack gets ready to launch but doesnt and kinda crashes 
i also have the log thing if that helps

**Comment by The-1-7-10-Pack** [comment]
You're using Java 6, this is your problem.

**Comment by italiankid13** [comment]
How would i change that because i downloaded java 8 64bit but it just defaults to java 6 i guess
