### ISSUE TITLE
Placing a mode inside of a mffs projector causes world crash

### ISSUE THREAD

**Issue by TheDoctorsLife** [The-1-7-10-Pack/The-1.7.10-Pack#378]
after testing, this appears to be a issue with Resonant Engine not being up to date. here is a log to confirm the crash. http://paste.ubuntu.com/10647894/

**Comment by The-1-7-10-Pack** [comment]
Can you try the same thing with the latest version of [MFFS](http://calclavia.com/mffs/downloads/) & [Resonant Engine](http://resonantengine.com/downloads/)?

**Comment by TheDoctorsLife** [comment]
I can, let me setup a local version of modpack in multimc

**Comment by ChinesePeanuts** [comment]
Have the same issue here, the sphere mod wasn't working (nothing was appearing), and the pyramid mod is crashing the server (Tested on Solo and Multi)
Have to take a backup for the multi, the world won't load
(http://paste.ubuntu.com/10655100/)

**Comment by The-1-7-10-Pack** [comment]
Yeah, it's a ticking entity. Annoying! Waiting for your reply @TheDoctorsLife.

**Comment by TheDoctorsLife** [comment]
latest version cause a crash, going to test until I get a working version of resonant engine, this is why I don't use Calclavia's mod to much anymore. right back to testing.

**Comment by The-1-7-10-Pack** [comment]
@TheDoctorsLife Thanks, expacting a reply from you

**Comment by The-1-7-10-Pack** [comment]
@TheDoctorsLife Anything new?

**Comment by TheDoctorsLife** [comment]
No, I plan to do more testing this weekend, I don't  have a decent enough computer to test on the weekdays.

**Comment by The-1-7-10-Pack** [comment]
I don't that there is any good build of the mod currently.
Going to be removed next update (v0.7.6).
If the mod will get better I will re-add it on the future.

**Comment by TheDoctorsLife** [comment]
Yeah, Thanks for the update.
