### ISSUE TITLE
Help ;-;

### ISSUE THREAD

**Issue by dAtsheepd0e** [The-1-7-10-Pack/The-1.7.10-Pack#379]
http://prntscr.com/6jsc8y
This error pops up when i hit play on the technic launcher. Just wasted a lot of time installing this modpack ;-;

**Comment by The-1-7-10-Pack** [comment]
https://www.youtube.com/watch?v=KH62sm-orE4

**Comment by dAtsheepd0e** [comment]
Well,  tried that, and now when i hit "play," the window just closes for a split second then opens again. Sadly, i dont think it works.

**Comment by dAtsheepd0e** [comment]
Ok, great. I just tried opening another modpack, and it doesnt work now. They all have the same outcome.

**Comment by The-1-7-10-Pack** [comment]
Don't worry, probably just the wrong version of Java. It's really easy to fix!
To understand your current status, can you please give me your latest launcher log?
