### ISSUE TITLE
Problems with the official server

### ISSUE THREAD

**Issue by KLuebbert** [The-1-7-10-Pack/The-1.7.10-Pack#38]
Hello everyone, I usually am not one to complain, and I'm sure you all heard of these issues before, but I thought I'd state them thoroughly.

Problem 1: On the server, the graves are a skull on top of a fence post. I died once, all I had to do was walk up to it, not morphed, and right click it with an empty hand. Once I removed everything, the head disappeared. Everything worked out perfectly.

However the second time I died, I found my grave, and I met all the conditions I explained above, except when I right clicked the skull, it didn't open. I right clicked it many times, and it didn't open. I left clicked it, I right clicked it, and eventually I just broke it, and it dropped a regular skeleton skull. I never got any of that stuff back, and even though it wasn't very valuable, what happens when I die with something valuable?

Problem 2: In single player, in my menu, I clicked the u key for item uses randomly on random blocks and items, sporadically, and it correctly showed the uses for those items no problem. On the server, if I use the u key for uses on anything, I instantly crash and the whole launcher dies on me.

These bugs seem severe to me, and they are dampening on my experience on the server. I understand the server is beta, and that is why I am reporting these issues so they can hopefully be resolved.

Thanks for reading, KLuebbert

**Comment by KLuebbert** [comment]
Besides those issues, I like the direction the server is heading, no world border, very active staff, a great looking spawn, a future economy system and even protections heading on its way. Great job on the mudpack and the server, I've played dozens of packs and nothing compares to this one.

**Comment by The-1-7-10-Pack** [comment]
1: The grave from OpenBlocks disabled on the server because we got ForgeEssentials system, "the skull". It should work - but maybe because the place you died in it bugged. You need to remember that the server doesn't have any plugins, and we can use only ForgeEssentials which is currently very buggy.

2: Look here: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/28.

Also thank you for the reports, it's very important.

**Comment by KLuebbert** [comment]
Ah, so you're working on the u key problem, and the grave was just a freak accident. Great! Because that grave malfunction made me so scared I'd lose everything due to a grave failure that I thought I'd be screwed if I died again. Those 2 problems were the only things (Besides Flans, but I know why that's disabled) that were making me uneasy about the server, but now that I know one will be attempted to be fixed and the other shouldn't ever happen, I'm glad! Also, hopefully flans gets itself together, because I'm really missing that mod xD. Anyways, I'll leave this thread, thanks for the response.
