### ISSUE TITLE
Pack Not Loading 0.7.5

### ISSUE THREAD

**Issue by mmooll** [The-1-7-10-Pack/The-1.7.10-Pack#380]
Hello I did not respond in my last issue. Sorry.  Anyway I do not know how it started to work but it did when the update was given out I stayed on the 0.7.0 version and it worked but when I updated to the 0.7.5 pack it went back to not working.  I really want help.  Every thing works fine up until it says initializing and then it just closes.  Right then.  I have Java 7 64-bit but I still not sure why it will not work.  Here is my last log. http://paste.ubuntu.com/10648986/  Please help me asap.  I really want to play.  For now I will play and earlier version when it was working for me.  Thank you for reading and helping.  Great modpack by the way!

**Comment by The-1-7-10-Pack** [comment]
No need to have 2 issues, I'll help you on the first one! (:
