### ISSUE TITLE
can i use the pack in forge?

### ISSUE THREAD

**Issue by monobovo01** [The-1-7-10-Pack/The-1.7.10-Pack#381]
i want to use the pack in my forge server (im using mcprohosting) is there any way to do this?

please help

**Comment by The-1-7-10-Pack** [comment]
I don't really understand the problem, there is a download for the server files (:

**Comment by monobovo01** [comment]
do every player needs to have the mod pack installd in his computer to play?

**Comment by The-1-7-10-Pack** [comment]
Indeed. :)

**Comment by monobovo01** [comment]
thank you very much!
