### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by Puggies** [The-1-7-10-Pack/The-1.7.10-Pack#383]
I was playing on my server with and sometimes when I break a block I will get kicked with the message "Internal Server Error". Anyone know why?

**Comment by The-1-7-10-Pack** [comment]
Mods are funny, but it's not critical. If you would be able to give me more information (client and server log) I may be able to dig into it and see who should I blame. :)

**Comment by Puggies** [comment]
Alright, next time it happens I will.

**Comment by The-1-7-10-Pack** [comment]
I'm closing it for now (:
