### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by PickaxePwnage** [The-1-7-10-Pack/The-1.7.10-Pack#384]
I have a high-end Macintosh with all the required software. But, something is crashing when starting up. I cannot launch Minecraft, or even open the window. Is this only for Windows PCs? I've reset the pack and the launcher with no success.

**Comment by Dommain** [comment]
Do you have at least 3 gigs of ram open and have 64-bit java installed?

**Comment by The-1-7-10-Pack** [comment]
As @Dommain asked for, you need Java 7/8 and 64bit version of it.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
