### ISSUE TITLE
Issue with Default World Generation

### ISSUE THREAD

**Issue by ChinesePeanuts** [The-1-7-10-Pack/The-1.7.10-Pack#386]
Little issue here, but because of Default World Gen we can't customize our Superflat world.
Not a problem, but still a bug.

**Comment by The-1-7-10-Pack** [comment]
What do you mean? Can you explain a bit more?

**Comment by ChinesePeanuts** [comment]
Sure sure,
When you want to create a flat world with a preset, here are the steps :
- Choose **Flat** World
- Presets
- Select your preset (wathever)
Once you're done, you just press Ok (or return can't remember)
But the world type will be **BoP** and not **Flat** as you have choosen, because of Default Wolrd Gen.
So you can get a flat world, but without any preset (else there is this bug)

**Comment by The-1-7-10-Pack** [comment]
You're 100% right! Although, I have nothing to do about it. Be sure to report it [there](https://github.com/FireBall1725/DefaultWorldGenerator/issues) so the mod will fix it. Thanks!
