### ISSUE TITLE
Change crafting quests to detection quests

### ISSUE THREAD

**Issue by Dommain** [The-1-7-10-Pack/The-1.7.10-Pack#388]
Flux tools do not fulfill the quest when made in AE2 crafting terminal. Do not know its compatibility with AE2 or the remote charger charging before it registers in the book. Also not there is no manual check button.

http://i.imgur.com/rf5vTLi.png

**Comment by The-1-7-10-Pack** [comment]
Yep, the HQM mod detects only when using the crafting table. I may just change it to a detection quest though. Also for the backpacks quest.

**Comment by Dommain** [comment]
I do not think it detects the tools if it has charge on it. I tried to make it with a project bench but I believe the ender IO RF charger is charging it before it detects it.

**Comment by The-1-7-10-Pack** [comment]
Hmm, maybe I can fix that too. I'll have to take a look at it.
