### ISSUE TITLE
Cant start the modpack from the techniclauncher

### ISSUE THREAD

**Issue by engen** [The-1-7-10-Pack/The-1.7.10-Pack#39]
here is the log:

http://paste.ubuntu.com/9673796/

**Comment by The-1-7-10-Pack** [comment]
How much RAM there's on your system?

**Comment by engen** [comment]
16 GB RAM

**Comment by The-1-7-10-Pack** [comment]
So you have 32bit Java installed on your computer.
Re-install it with the currect 64bit one. :)

**Comment by engen** [comment]
I've Java 8 Update 25 (64-bit) now, but it still doesnt work... is there any other versions of java i could try?

**Comment by The-1-7-10-Pack** [comment]
the "problem" you have has nothing to do with the version of Java. Please just provide a screenshot with f3 in game that will really show a memory usage of 4.1GB, beacause it make no sense to me at the moment.

**Comment by engen** [comment]
ok its working now, thanks for the help !
