### ISSUE TITLE
SUGGESTION : RFtools?

### ISSUE THREAD

**Issue by Aldamert** [The-1-7-10-Pack/The-1.7.10-Pack#390]
I was wonder since you do not have the rights to use mystcraft in your mod pack if we could use another more balanced (from what i know) dimension mod known as RFtools

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-auto

-Aldamert
--Have A Good Day

**Comment by The-1-7-10-Pack** [comment]
Already have been suggested like four times, thanks anyway :)

**Comment by Aldamert** [comment]
Ah ok, sorry, and thank you, and also you are fast at replying xD
