### ISSUE TITLE
Problems with using items

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#393]
Hi, this is not a server crash issue,but I gathered some feedback from players on server and heres a list of items that we cannot use:
IC2: Nano suit unable to trigger boost mode or hover mode
gravi suit : same
Flans mod: cannot use binoculars 
Mechanism : electric bow ,no infinite arrows and cant switch to fire mode

we all tried using these items but it doesn't work.
I hope it can be fixed,specially nano suit and gravi suit,otherwise the suits are basically useless

**Comment by 20Brogan** [comment]
Change keybinds. I had this issue with thaumcraft wands and it was fixed once I changed it so no other bind was on the F key.

**Comment by imsupermario** [comment]
what are the binds to those mods , because we all have customized key binds.
for my case ,i disabled all magics mod keys to ensure there are no key conflicts with flans mod ,mechanism and IC2

**Comment by imsupermario** [comment]
http://pastebin.com/cujihTDf

**Comment by The-1-7-10-Pack** [comment]
It's all controls issues.
Use the "MineMenu" Feature to set controls or just change them on the controls menu, press 'R'.
