### ISSUE TITLE
WAILA and Thermal Expansion

### ISSUE THREAD

**Issue by Canuck117** [The-1-7-10-Pack/The-1.7.10-Pack#394]
A simple question; can you do anything about WAILA not showing items or fluids in Thermal Expansion pipes and tanks?  TE tanks also don't display the 0/16000mB that they used to.  Some other tanks do, haven't checked all of them.

**Comment by The-1-7-10-Pack** [comment]
It's fixed on the next version of WAILA, will be implemented into the modpack next update :)

**Comment by Canuck117** [comment]
OK, cool.
