### ISSUE TITLE
The Camping Mod [Suggestion] 

### ISSUE THREAD

**Issue by Voideon** [The-1-7-10-Pack/The-1.7.10-Pack#395]
Ok, So personally I love travelling in the world of MC, but I find that if I don't have a base it would be extremely hard to travel, when I'm always depending on a already set up base...
I feel with we had this mod it would encourage players to really travel and get out there, or just have a base and when they want to explore bring a tent and some equipment and go travel.
It seems like a great mod for adventure and I personally think it would be awesome.

http://www.planetminecraft.com/mod/campfire-mod-campfire-will-be-your-new-better-furnace/

**Comment by The-1-7-10-Pack** [comment]
It's a really cool mod for adventure-type only modpack but it doesn't really fit The 1.7.10 Pack.
Thanks anyway (:
