### ISSUE TITLE
Mobs do not want to despawn / too many Mobs

### ISSUE THREAD

**Issue by Offertorium** [The-1-7-10-Pack/The-1.7.10-Pack#396]
Hello,
Unfortunately despawn apparently no more mobs. We play multiplayer on a Linux server and there are far more than a hundred mobs to our base.

How can we fix the problem. So we can not continue to play unfortunately.

greeting
offertory

**Comment by The-1-7-10-Pack** [comment]
I don't really understand you problem can you be more clear?

**Comment by Offertorium** [comment]
Hi , 
sorry my english is not so good and it's hard to be described.

In my world are to many mobs and they would't despawn at day. Around my base is an army of Zombies and Creeper. Every minute if a player goes online, there are more and more mobs. 

The fml-server-latest.log is full of this notice: [17:10:57] [Server thread/DEBUG] [FML/]: The world 189d0dcf (world) may have leaked: seen 45 times, but i can't find any other error.

Thank you for your support.

**Comment by The-1-7-10-Pack** [comment]
This is not an error, but you may want to set the difficulty to easy or hard as you need.
The message you saw is a normal report by the ChickenChunks mod and it's NOT an error or any kind of a problem :)
