### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#397]
My server today crashed 3x and idk why

can you help me here plz ?

http://paste.ubuntu.com/10685185/

**Comment by The-1-7-10-Pack** [comment]
Try to update to Java 8.

**Comment by thebalck** [comment]
its a server crash not client

**Comment by The-1-7-10-Pack** [comment]
I'm aware, I'm telling you still to try to update Java to version 8.

**Comment by thebalck** [comment]
I cant i have other programs that cant go with java 8, i think the crash was a ComputerCraft problem, because today all i did was a CC control for my BigReactor turbines

**Comment by The-1-7-10-Pack** [comment]
But other people with the same crash report as yours updated to Java 8 and it fixed their problem. I doubt that programs won't work with Java 8 these days, it's the recommended version.

**Comment by thebalck** [comment]
Not in programs that i did myself, and in OSX Yosemite i dont like how java works

**Comment by The-1-7-10-Pack** [comment]
You can at least try :)

**Comment by thebalck** [comment]
But how can that crash the server only? and if i turn all ComputerCraft machines off the server wont crash again

**Comment by The-1-7-10-Pack** [comment]
Uh huh. Well, if you're sure that it's a bug in ComputerCraft you should report it [there](http://www.computercraft.info/forums2/index.php?/forum/19-bugs/). :)

**Comment by thebalck** [comment]
ok i will test more and when im sure i will report it

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
