### ISSUE TITLE
Crashes when loading world

### ISSUE THREAD

**Issue by Pandahead** [The-1-7-10-Pack/The-1.7.10-Pack#398]
Attempting to load a previous world-save (deleted game, copied save folder to try and recover from failure) produces this logfile...

http://pastebin.com/7xTJeknY

Game is absolutely fine when creating a new world, though. A bit sluggish, but otherwise fine.

**Comment by The-1-7-10-Pack** [comment]
Your level.dat file got corrupted, you should try to use a backup or just try to reset the file, although it can damage stuff. Nothing else I can suggest.

**Comment by Pandahead** [comment]
Thanks for the assist, Aroma saved the day. Completely forgot about the backup until you reminded me.
