### ISSUE TITLE
Suggestion ReactorCraft

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#399]
Can you add this mod ?

http://mod-minecraft.net/reactorcraft-mod/

**Comment by The-1-7-10-Pack** [comment]
We have Big Reactors :)

**Comment by thebalck** [comment]
Cmon men imagine the thinks we can do with this mod, not only the power generation but the awesome buildings

**Comment by The-1-7-10-Pack** [comment]
You can do the same with Big Reactors!

**Comment by thebalck** [comment]
Have you ever seen one reactor from ReactorCraft?? those things are gorgeous men, and with big reactor you can only build 2 types of reactors and they are like squares, with ReactorCraft they are massive and awesome buildings
