### ISSUE TITLE
Crash related to Brewing Stands

### ISSUE THREAD

**Issue by Tesseractual** [The-1-7-10-Pack/The-1.7.10-Pack#40]
This keeps bringing my server down. I haven't been able to talk to the player yet to figure out anything beyond this crash report.

http://pastebin.com/Ute2TFii

**Comment by Tesseractual** [comment]
Sorry, gave you the wrong pastebin: 

paste.ubuntu.com/9674705/

**Comment by The-1-7-10-Pack** [comment]
It's a bug of Forge, you should report it here: https://github.com/MinecraftForge/MinecraftForge/issues
Be sure to give them all the information you got, and how it started.
