### ISSUE TITLE
Game Won't Load: Only shows a Black Screen

### ISSUE THREAD

**Issue by drezenx** [The-1-7-10-Pack/The-1.7.10-Pack#400]
Whenever I try to load the modpack from the technic launcher it just stays on a black screen and eventually says that java is not responding. Here is the latest log: http://paste.ubuntu.com/10691153/. I am running the java 8 update 40 64 bit version and changed the java settings in the launcher to the 64 bit javaw.exe file. I have 6 gb of RAM on my CPU. If you need any other info from me please let me know. Thanks in advance for the help.

**Comment by The-1-7-10-Pack** [comment]
Everything is okay on your log, just let it load. Minecraft can be funny, but it's still working on the end of things.
