### ISSUE TITLE
Crash when i get back from Aroma world

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#401]
idk why but the game is crashing when i get back from the aroma mining world 

This problem crashes the game (in my pc) and crashes the server (dedicated server not local)

http://paste.ubuntu.com/10695939/

**Comment by The-1-7-10-Pack** [comment]
This is very weird! A problem with both EnderIO & Thermal Expansion. You should report that on their repositories and see what they have to say because I can't do nothing. Sorry!
https://github.com/SleepyTrousers/EnderIO/issues
https://github.com/CoFH/Feedback/issues
