### ISSUE TITLE
Suggestion:  NotEnoughKeys

### ISSUE THREAD

**Issue by Canuck117** [The-1-7-10-Pack/The-1.7.10-Pack#405]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292963-not-enough-keys-making-pressing-buttons-easier

Considering the massive amount of mods, all with their own keybindings, this mod is a great help.

**Comment by The-1-7-10-Pack** [comment]
How exactly NEK will help?

**Comment by Canuck117** [comment]
It groups keybindings by mod, and it also has a list of conflicting keybindings, making them easier to find and fix.

**Comment by The-1-7-10-Pack** [comment]
But in 1.7 it already does that :P
