### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by ZombieTG** [The-1-7-10-Pack/The-1.7.10-Pack#406]
So i have my own hamachi server for just me and my friend but the problem is it's really laggy, i tried increasing the memory for the server in my custom "start.bat" file but when i try changing 1G to anything like 2G and try run the "start.bat" it just doesn't work. All it does is start up for like 1 second then it closes. When i go back and change it to original 1G it works fine. So i need to know a way to increase the servers memory. 

The server download is kinda complicated as the given "LaunchServer" doesn't work at all when i start it, it just says "Error: missing 'server' JVM at 'C:/Program Files <x86>/Java/jre.1.8.0/bin/server/jvm/dll'. Please Install or use the JRE or JDK that contains these missing components. Press any key to continue" Then i press a key and it just closes and nothing else happens.

It took me so long to get it working, the only way i had it work was by creating my own "Server.bat" file with inside code "java -Xms1G -Xmx1G -jar forge-1.7.10-10.13.2.1307-1.7.10-universal.jar -o true" Then using that to start up the server. But with that it's just too bad of connection when I'm on the server. So i have no idea how to increase the memory of the server because it just doesn't seem to want to work if i change the value inside to anything else than 1G.

I hope this makes some sense and someone can help me because servers are such a headache when something doesn't work.

**Comment by winglessraven** [comment]
Do you have 64-bit Java?

**Comment by ZombieTG** [comment]
I do

**Comment by The-1-7-10-Pack** [comment]
Obviously he has if his Java is installed on Program Files.
Anyway, making your own launch file is very bad and totally not recommended. That is what making your problems.
You have two options:
- Try to reinstall Java and see if it adds your 'server' JVM.
- Also you can just remove the "-server" on the LaunchServer.bat file.

**Comment by ZombieTG** [comment]
Okay i reinstalled Java and removed the "-server" from LaunchServer.bat and now this is what i get when i run it http://puu.sh/gUbAq/2f40e5e506.jpg

Then when i run it as administrator this happens - http://puu.sh/gUbGv/c65bfef786.jpg

**Comment by The-1-7-10-Pack** [comment]
How much RAM do you have on your computer?

**Comment by ZombieTG** [comment]
16 GB RAM, so I'm confused to why it's saying that

**Comment by The-1-7-10-Pack** [comment]
If you reinstalled Java you should try to just run the file as it :)

**Comment by ZombieTG** [comment]
When i run the "LaunchServer" with just the 1gb ram it starts to work but if i try more than 1gb it just says could not reserve enough space

I'm really confused right now xD

**Comment by ZombieTG** [comment]
Actually! I started it with just the 1gb with "launchserver" and the connection is great! Thank you for your time in helping me, also great mod pack!

**Comment by The-1-7-10-Pack** [comment]
Awesome, happy you figured it out :)
