### ISSUE TITLE
Re: server issue (Still need help)

### ISSUE THREAD

**Issue by ZombieTG** [The-1-7-10-Pack/The-1.7.10-Pack#407]
So this is a reply back to server issue https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/406

Okay i reinstalled Java and removed the "-server" from LaunchServer.bat and now this is what i get when i run it http://puu.sh/gUbAq/2f40e5e506.jpg

Then when i run it as administrator this happens - http://puu.sh/gUbGv/c65bfef786.jpg

I'm sorry if i started this new thread or whatever again but i really need this to work as this mod pack is awesome and i need the server to workkkkk :D

**Comment by The-1-7-10-Pack** [comment]
No need to have two issues, I'll help you there! :)
