### ISSUE TITLE
Problem with Mekanism's gases

### ISSUE THREAD

**Issue by Nikey646** [The-1-7-10-Pack/The-1.7.10-Pack#408]
EnderIO hasn't updated but you went gung ho and updated mekanism because it's major version number changed!

the Gases API for Mekanism changed in version 8, and EnderIO's usage of the Gases API hasn't been updated, resulting in a crash when attempting to load any world which already has a Gas Conduits connected, or when placing EnderIO's Gas Conduits against a Mekanism machine.

Best part! It can't be fixed unless you downgrade Mekanism, because EnderIO doesn't have an update out yet! /sarcasm

**Comment by The-1-7-10-Pack** [comment]
EnderIO [did update](http://ci.tterrag.com/job/EnderIO/364/), and for now you can update it manually for your client.
I just didn't include this update in the latest update because hey, I'm a human too.
Thanks for reporting :)

**Comment by Nikey646** [comment]
Fair enough. I was basing the "Not Updated" on the Curseforge for EnderIO, which is only upto 349, which was Feb 14th. (Pre-Mekanism 8)

**Comment by The-1-7-10-Pack** [comment]
Should be fixed with v0.7.6a.
