### ISSUE TITLE
Mods not working on server

### ISSUE THREAD

**Issue by ZacTheAcorn** [The-1-7-10-Pack/The-1.7.10-Pack#409]
I got the server to work but none of the mods seem to work. (E.g Placing a block from mod pack doesn't work, spawning mobs doesn't work etc) Any info on what is happening or how to fix it?

**Comment by The-1-7-10-Pack** [comment]
You need to launch the server with the LaunchServer.bat file :)

**Comment by ZacTheAcorn** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11708431/6887250/99f35976-d627-11e4-9ef6-eee2a32bb8a9.png)

This file right?
I click it, it will open then say "click a button to continue", I do and it closes :(
This is confusing stuff, sorry for my dumbness

**Comment by The-1-7-10-Pack** [comment]
Can you please give me the latest log?

**Comment by ZacTheAcorn** [comment]
![g l h](https://cloud.githubusercontent.com/assets/11708431/6887293/a11bddbc-d628-11e4-99e8-5b4e9a340879.png)

This?
It does say I'm missing a certain file, still to dumb to understand though

**Comment by The-1-7-10-Pack** [comment]
The fml-server-latest.log file, and please use a [paste-tool](http://paste.ubuntu.com/).

**Comment by ZacTheAcorn** [comment]
I can't seem to find the fml-server-latest.log 
But is this it?
http://paste.ubuntu.com/10703632/

**Comment by The-1-7-10-Pack** [comment]
What appears after you click on the "LaunchServer.bat" file?

**Comment by ZacTheAcorn** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11708431/6887686/36f05dd4-d635-11e4-97d6-0b81a91d9614.png)

**Comment by The-1-7-10-Pack** [comment]
Please try to reinstall your Java.

**Comment by ZacTheAcorn** [comment]
Ok yeeee, so I did that. Still doesn't work. If I'm an unfixable problem tell me, because I dont wanna waste anymore of your time :)

**Comment by The-1-7-10-Pack** [comment]
Can you try to remove the "-server" from the launch file?

**Comment by ZacTheAcorn** [comment]
Thanks for the help, but I give up now. Not even the modpack opens for me now.. lol :(

**Comment by The-1-7-10-Pack** [comment]
Why not? You can't launch?

**Comment by ZacTheAcorn** [comment]
It closes Technic launcher for a split second, then just reopens the same page

**Comment by The-1-7-10-Pack** [comment]
Can you give me your latest launcher log? located under launcher settings -> logs

**Comment by Aninhafofa77** [comment]
what is the address of the public server? Please answer me as soon as possible .
