### ISSUE TITLE
Anvil is not working on server.

### ISSUE THREAD

**Issue by Johnyxiade** [The-1-7-10-Pack/The-1.7.10-Pack#41]
I've created a private server with the latest server pack for version 0.6.1 and I can not get the anvil to work at all. I will put a new Iron pickaxed in the left slot and an efficiency 2 enchanted book in the second slot and it doesn't show the xp amount or the new item. The X over the arrow is still there as well. Only seems to be doing this on the server not in single player.

**Comment by The-1-7-10-Pack** [comment]
Maybe you putted them on the wrong sides?
