### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by spdkils** [The-1-7-10-Pack/The-1.7.10-Pack#411]
Would like to get Natura items into ore dictionary. Things like Natura fences can't be used for Jabba, etc.

**Comment by The-1-7-10-Pack** [comment]
Nature woods are more decorative and I like it that way, I don't see any major reason to change that :)

**Comment by spdkils** [comment]
Well, if I use a redwood for a wood farm, I can use the sticks to make fences, however if I use ONLY redwood sticks, it creates a redwood fence.

fences are an extensive component for JABBA upgrades, so now I have to farm oak and make oak only fences to ensure I can make the JABBA upgrades.

It's really just a matter of conveniences to create the JABBA and other subsequent recipes without having multiple wood farms.

Now I looked at oreDict a wee bit, because I was going to add it, and I'm not even sure how to do it yet, but the recipes for JABBA and others that use fences it would be nice if it included the "natura" looked woods.

**Comment by The-1-7-10-Pack** [comment]
It's not like this for a reason and I think that having a wood farm of Natura is just a tiny bit OP. You can easily make a different wood farm, it's really not a problem!
We'll keep it as it is for now :)

**Comment by spdkils** [comment]
Well, basic computer craft is probably one of the most powerful mods (OP) wise in this pack.
With scripts off pastebin you get infinite durability mining at the cost of 3 diamonds.

Add the silk touch mod, and you've got remote controlled robot army of miners that take almost no fuel, and can use ender chests to transport all the resources back. I don't even use computer craft anymore because it is far too powerful. I only use it for reactor control etc.

But I digress.

**Comment by The-1-7-10-Pack** [comment]
I agree that you can use it for powerful stuff, but I think it's irrelevant; No need to change how natura woods work.
Thanks anyway for suggesting :)
