### ISSUE TITLE
RAM stuck @ 3gig

### ISSUE THREAD

**Issue by spdkils** [The-1-7-10-Pack/The-1.7.10-Pack#412]
Because you have used JSON to set the RAM, the "standard" and "easy" way for users to increase their RAM allocation does not work.

Please remove this feature, so the built in TEKKET way to increase RAM functions.

(Launcher options, set RAM)
vs
(Open modpack, edit version.json)

Do this every time you update. :(

**Comment by The-1-7-10-Pack** [comment]
I've said it a 1000 times: You guys don't need more than 3 Gigs of RAM. People that use more are just wasting their computer RAM which can cause lag. Also people that don't know how to increase RAM and will be stuck at default will have lag. So we have this wonderful system that allocates RAM automatically, and until the Technic Platform implements the minimum RAM feature, this is what we got.

**Comment by spdkils** [comment]
Well, I'm sorry but you're wrong on this one. :(

I tested yesterday, as a client I was getting hitching after the update, and I thought there must be something wrong with an update. After looking at about 5 different things, and relaunching 4 times I realized the RAM was locked to 3g again.

I upped it to 6 again, and my hitching was gone.

I'm fine with just modifying it every time. But the launcher really does have this option for a reason. Overriding it for this one pack seems odd.

**Comment by spdkils** [comment]
The major issue is, I'm hosting a LAN server with some loaded chunks and a 2 friends running around. If I'm the only one on, and I don't use chunk loaders, and I don't create spawn areas with loaded chunks, and I just run around as a client. You're probably right, 3g is fine. Once I load up 24 chunks on 3 maps, the equation changes.

**Comment by The-1-7-10-Pack** [comment]
@spdkils Well you can easily run the server with the server files and it can have it's own RAM, default set to 3, configureable easily.
