### ISSUE TITLE
Add Custom LAN Port

### ISSUE THREAD

**Issue by spdkils** [The-1-7-10-Pack/The-1.7.10-Pack#413]
It's a super tiny mod, just allows people to host from single player on a port consistently.

**Comment by The-1-7-10-Pack** [comment]
Before I go to anything, is there a 1.7.10 version of the mod even?

**Comment by spdkils** [comment]
Yes, I have it installed.

**Comment by The-1-7-10-Pack** [comment]
Can you give a link?

**Comment by spdkils** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294206-customlanport-mod

**Comment by The-1-7-10-Pack** [comment]
This mod can be useful for some people, but the modpack has the server files up for download, and it's just another mod that will take more RAM, and I don't know how stable it is.
For now you can install it manually for you.
Thanks anyway for suggesting :)

**Comment by Aninhafofa77** [comment]
what is the address of the public server? Please answer me as soon as possible .

**Comment by The-1-7-10-Pack** [comment]
There's no public server.
