### ISSUE TITLE
Problem with update v0.7.6 & v0.7.6a

### ISSUE THREAD

**Issue by Spellkaze** [The-1-7-10-Pack/The-1.7.10-Pack#414]
Hi, I usually don't post issues becaue I always try to solve them by myself, but this trouble is out of my league. This only happends in the new versions (0.7.6 and 0.7.6a) Everything works fine with 0.7.5.

The places that I go, it is just savannah biome, but when I aproach, the client starts to drop fps very fast and then it freezes for a long time until I force it to close. I'm stuck there forever everytime I load, so I have to use a backup to go back where I was.

First I thought it were corrupted chunks, but when I downgraded to 0.7.5, I could walk and fly normaly there. Also, I noticed two kind of logs:

This one was the most common: http://paste.ubuntu.com/10704668/

This one was quite rare to have, but was different from the other one: http://paste.ubuntu.com/10704686/

For now, I have to avoid crossing that part of the world, I have to take another route (more longer) to go to the place I want, any ideas of what is happening in my world?

(I really want to know how to fix this, in the worst case scenario I would be forced to create a new world and, with the use of a minecraft editor, copy my base and paste it in the new world, but that would make me an awful headache)

*Everything was tested with 3Gb of memory, with and without optifine, resource pack, all the tests had the same result.

EDIT: It happends everywhere, I moved away of my base at another direction and had the same crash.

Also I figured out that I had 3 turbines on use (I usually only have one), Since that do not made any problems in 0.7.5, I dont believe this is the source of the problem, but I'm going to shut the down two of them to see what happend.
EDIT 2: Nope, it happends everytime I want to go away of my base
EDIT 3: Now there are only "Gathering id map for writing to world save Kaze World" in the logs and I can't move, well, if there is no solution, I probably have to play in the 0.7.5 version (Kaze world is the name of my world anyways)

**Comment by The-1-7-10-Pack** [comment]
Ugh.
Try to remove FastCraft, is anything different?
Also, are you playing on SSP only?

**Comment by The-1-7-10-Pack** [comment]
@Dommain, please try the steps one by one and check if any specific step helps.

**Comment by Spellkaze** [comment]
First, nope, nothing, once I load, it freezes indefinetly, but don´t crash.

Second, removed, I'm no longer stuck, I feel a little happy, tried to walk around, freeze and crash, I feel sad. Crash report: http://paste.ubuntu.com/10709027/

After that, any attempt to load the world it makes the client freeze indefinetly

Third, well, I removed the 3 mekanism mod, let's see what happend, it can not be worse.... Minecraft doesn't launch and goes to the technic launcher. Crash report: http://paste.ubuntu.com/10709100/

Awww, men :/
I really liked that update from mekanism that makes almost every machine upgradable, it helped a lot my ore factory, well, I believed I have to be sad for now :c

**Comment by The-1-7-10-Pack** [comment]
Well, until I figure it out I'm putting v0.7.5 as the recommended, v0.7.6a as the latest.

**Comment by The-1-7-10-Pack** [comment]
I'm just 99% sure it's Mekanism, it was the only big mod update between v0.7.5 -> v0.7.6.
Try to remove all three parts of Mekanism, and remove also EnderIO.

**Comment by Spellkaze** [comment]
Deletes Ender IO, testing, aaaaand, it crashed: http://paste.ubuntu.com/10709665/
My lack of knowledge in java code says that minefactory was causing the problem in this crash report. 
Deleted minefactory (and the magical crops addon), minecraft opened normally, open my world, apparently everything loads fine.

Wait, what?, everything loads fine!, but now I have a huge hole where my mekanism industry and my industrial farm were.


So we can conclude that something from Mekanism or Ender IO is messing with my world (and the world of Dommain)

I have a question, can I try to force the update of the mekanism mod with the 0.7.5 version?, if nothing happends there, then mekanism is not the problem and there is something weird with this version, but if is the opposite, then the blame is from mekanism.
(I only use EnderIO for the Travel Anchors, so I don´t think I'm going to have the gas bus that was mentioned in another issue)

**Comment by The-1-7-10-Pack** [comment]
(It first crashed because EnderIO needed Mekanism, then MFR needed EnderIO)
So basically it's Mekanism's fault?
If you'll try to push the update with v0.7.5 it may crash because it has an old versions of other mods like EnderIO and AOBD that supports Mekanism, but you can try.
You can also try to simply update all three parts of Mekanism in the v0.7.6a update.
http://aidancbrady.com/mekanism/download/
We're using v8.0.3.207 (Recommended), but maybe the latest one, v8.0.3.212, has a fix.
Update me!

**Comment by Spellkaze** [comment]
Well, as you said, the Mekanism v8 doesn't work in the 0.7.5 version, so I tried updating the 0.7.6a
Using the backup world, from my base I started to walking at the opposite direction of the "chunks of death", everything was fine, so now the finals test, I walked into the chunks of death, very slowly and.... it crashed: http://paste.ubuntu.com/10709833/
(It is the same crash report as before?)
Any attempt to load the world will cause the same crash report.

So, what should I do now? Post it as an issue on the Mekanism github? Since this is a modpack I don't think that I would recieve any good support :/

*As an another note, I used the 0.7.6a version with my world that do not had any machines from mekanism, ender io and minefactory, no problems with the death chunks, I could pass them without any trouble, so there is a problem with the mekanism machines when the chunks they are gets unloaded... i think?

**Comment by Dommain** [comment]
Noticed that too, if you might want to try to use a chunk loaded-er where you have mechanism stuff. It decreases the chance of inescapable freeze. My problem is exploring locations I have not been before.

**Comment by The-1-7-10-Pack** [comment]
@Spellkaze The crash report is different. Go to the modpack's folder, configs, backup and then delete the "cofh" directory. Check if anything is different.

**Comment by Spellkaze** [comment]
I have some... good news, I think...

Nothing worked, I tried taking off all the mekanism stuff that I had in my base, from cables to machines, death freeze again, so I had to do use a backup world were I only had the the "basic" form of my factory (25% of the size of my actual factory) and one turbine from four I had from the big reactors mod, it is a save that I had a week ago.... and... no more crashes or freezes in any chunk.....
Now I have to re-do everything from almost zero...

I really don't know if the huge structure of mekanism factory that I had was making the problem, but for now.... it seems the trouble it's gone.

Also, in the mekanism github, there is a closed issue that says "Crashes in heavly modded areas" and the author answered  that "It was going to be fix in a future version"

I'm going to re-do everything slowly so I can see what thing is causing the "dead chunks"

For now, I feel a little happy, and a little sad because I made a huge progress in my factory (producing like 10 stacks of iron per 2 minutes or less), but well, probably something in the machine codes weres messing around, also I noticed that I don't have fps drops anywhere (thing that happened usually in my previous world)

Well, this seems the end of the problem, I'm going to update you if  I suddenly start to experience the "dead chunks" again, thanks for supporting me all the time, let's hope there is a more suitable fix for this in the future C:

Now the problem with the world is with Dommain, I had the luck that all the last week I was working on the mekanism mod.

Also, I found something... interesting when I was using the resource pack ._.
http://i.imgur.com/4W6s9El.png

Well, I know that the actual trouble is not gone, but I least I found a method to "escape" from it.

**Comment by The-1-7-10-Pack** [comment]
Well this still doesn't help at all, becaue I don't know what is the problem.
Anything new @Dommain?

**Comment by Spellkaze** [comment]
I forgot to send you the last crash report that I had http://paste.ubuntu.com/10714008/
(I removed fastcraft but I still had the freeze on the chunks, having the "Leaking world" and "Gathering id from the world", that was the last crash report from the save, let's wait some time, the mekanism mod new version have a lot of bugs to be fixed.

**Comment by The-1-7-10-Pack** [comment]
You got this crash report after removing FastCraft?

**Comment by The-1-7-10-Pack** [comment]
Well FastCraft doesn't make the crash happen, it's just taking control over the crash report. Also "Gathering id from the world" and "Leaking world" are nothing wrong, you may notice that the world "may have leaked", a normal  message by ChickenChunks.
Anyway, I need to test something with the world that is crashing with this crash report of FastCraft, I can try to explain to you how to do it but It'll be easier if you'll send me your problematic save so I'll test it myself, because I can't get any crash.

**Comment by Spellkaze** [comment]
All right, I'm going to upload it, It is going to take some time because my internet is awful. Just wait.

**Comment by Spellkaze** [comment]
That is a graphic of where the "dead zone"  probably is http://i.imgur.com/8Ic38WM.png
Well, there you have it  https://mega.co.nz/#!AENmmZwR!E5n58jfCay2kiJ5pJUqr7fDcle0SRoP_sSvkluW1ISQ

**Comment by Dommain** [comment]
I tired reversing back you 7.5 and I can fly around the world with out any freeze issues I was having before in the previous dead zones.

Do you want me to upload what I have?

**Comment by The-1-7-10-Pack** [comment]
@Dommain I'll see if I can get the same crash with @Spellkaze's save first, if not - I'll ask for your save :)

**Comment by imsupermario** [comment]
hi, I have similar issues with mechanism as well (client crash), it has something to do with remote teleporter . Is it safe to wait for the next update/fix , our server is at version 0.7.6

**Comment by The-1-7-10-Pack** [comment]
@imsupermario For now you should revert to v0.7.5, it's stable. I need to figure out why Mekanism, EnderIO & CoFHLib codes hate each other.

**Comment by The-1-7-10-Pack** [comment]
@Spellkaze The save you gave is indeed crashing as you said.
Let's try something: Remove the "RefinedRelocation" mod before you launch, use the problematic save, the latest version (v0.7.6a), and check if anything is different.

**Comment by Spellkaze** [comment]
Well, i tried, I walked into the "death zone" like 3 times, but after the 4th time, it crashed http://paste.ubuntu.com/10716309/, any other attempt of loading that area end in a infinite freeze. The solution was to change my chunk loading from 6 chunks to 2 chunks to get away.

**Comment by Dommain** [comment]
Based on that log, there is a mekanism machine that has a 1 or 0 where there is not supposed to be anything and there was a tick update with it.

*******
Name: LogisticalSorter // mekanism.common.tile.TileEntityLogisticalSorter
Block type: ID #2422 (tile.MachineBlock // mekanism.common.block.BlockMachine)
Block data value: 15 / 0xF / 0b1111
Block location: World: (285,63,338), Chunk: (at 13,3,2 in 17,21; contains blocks 272,0,336 to 287,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
*********
Logical sorter at location 285,63,338 (x,z,y) chunk 17,21 region 0,0

You can try to world edit it out or remove it in a earlier update. Simple thing of connecting to something it was not designed for could bug the block.

**Comment by The-1-7-10-Pack** [comment]
@Spellkaze, @Dommain; Well the crash with cofh lib is due to derpy things with RefinedRelocation. After you removed the mod you got the actual crash about Mekanism. I've posted it on Mekanism's GitHub page, we'll see what they have to say.

**Comment by The-1-7-10-Pack** [comment]
Will be fixed in Mekanism v8.1, the author says.
It's the waiting game now, but I thing we'll have to say goodbye to RefinedRelocation.

**Comment by Spellkaze** [comment]
Mekanism 8.1 is now out, let's the round of tests begin!

**Comment by The-1-7-10-Pack** [comment]
@Spellkaze Waiting for your update.

**Comment by Spellkaze** [comment]
Well..... no good news, the mekanism updates makes all the pressurized tubes dissapear. (now there are different types of pressurized tubes). 
The same as always.
Crash when going to the "death chunks" (with RefinedRelocation): http://paste.ubuntu.com/10739056/
Well, the same.
Crash when going to the "death chunks" (without RefinedRelocation): http://paste.ubuntu.com/10739178/
(same crash)
When I re-load the world, it freezes, no crash report, here the log: http://paste.ubuntu.com/10739201/ (I see some openmods thing there, but I have no clue of what it means)
Removed fastcraft, still freeze, no crash report: http://paste.ubuntu.com/10739255/
An extra log that was made: http://paste.ubuntu.com/10739248/

As a final test, I run away from my base and loaded a lot of new chunks (places I have never been before), everything fine, but when I returned, I could pass the dead chunks zone without problem, but when I tried to use that route again, just a freeze. http://paste.ubuntu.com/10739464/

Tried to teleport using voxelMap, if it is an unloaded chunk, it will freeze, but when I load the world again, it is normal, no crash or anything

Now, there is something different, if I'm to close of my base and it freezes, then is a permanent freeze, but if I'm a bit far away from my base, the world loads normally (thing that never happened in the older version) even been in the dead zone

It is like something in my base get loaded, and when it gets unloaded or near it, it will freeze, i really don't think that is the problem, but anyways, I really don´t know why only in the 0.7.6 versions I can't do that, but in the 0.7.5 I can without any trouble. :/
Probably another mod is the problem and it just need to be updated?

**Comment by The-1-7-10-Pack** [comment]
The last option is to try figure out what is this crash with Fastcraft. I'll try to explain something a bit complicated here, bear with me.
Go to the modpack's folder -> bin, and delete the "version.json" file.
Now, enter "modpack.jar", and locate another "version.json" file. In it, in line 7, you'll see "javaArguments". [Here](http://pastebin.com/thGKBY8e) is a pastebin for how the line suposed to look, and what you should change this line to. This will activate Fastcraft's debug mode.

**Comment by Spellkaze** [comment]
After a lot of testing, even with the debug mode enabled, I can't get a crash, only an infinite freeze. But the log that I'm having is quite interesting
http://paste.ubuntu.com/10740367/

I tested it with fastcraft 1.21, some people are having some troubles with the previous versions.

**Comment by The-1-7-10-Pack** [comment]
I think we got it! that's an error from Mekanism. Reporting it now. Thanks @Spellkaze! I'll update here.

**Comment by Dommain** [comment]
Mechanism is definitely looping in Spellkaze log >_>

at mekanism.client.ThreadSparkle.loop(ThreadSparkle.java:86) [ThreadSparkle.class:?]


I found a freeze where if you had a IO conduit pipe connected to a salination plant that is not fully operational yet. I found if you went slowly it didn't freeze but if you were moving bat out of hell to quickly using power armor, you will freeze.

**Comment by The-1-7-10-Pack** [comment]
@Dommain You should comment on the issue I've opened on Mekanism's repository and add more information if you can.

**Comment by The-1-7-10-Pack** [comment]
@Spellkaze Can you try build 216 of Mekanism to see if that has fixed it?

**Comment by Spellkaze** [comment]
Today the mekanism mod was updated, from 8.1.0.215 to 8.1.1.217 (as recommended) should I test it or you are going to update it anyway?

**Comment by The-1-7-10-Pack** [comment]
@Spellkaze I'd ask you to test using the current recommended build (v8.1.1.217). If there is no change please try using the latest build (v8.1.1.219). Update me ASAP.

**Comment by Spellkaze** [comment]
My tests reveals.... that there is no freeze in the dead zone for 30 minutes now, nothing, everything is going well. Tested with the 0.7.6a only with the mekanism mod in the 8.1.1.217 version.

So, this is the end of my bug :/ (apparently) It have been a long road, but it seems everything is good now, I will update you if anything happends (let's hope anything goes ok from now)

My torture is finally over now, I will play with this custom version until your official update C:

**Comment by The-1-7-10-Pack** [comment]
Well..You may have to wait a bit for an official update..
http://www.technicpack.net/modpack/the-1710-pack.453902/changelog/80132

**Comment by Spellkaze** [comment]
Ehmmm, now there is another problem, there is an extrage leak of energy with the mekanism cables, Even with my turbines producing like 200 kRF, some mekanism cables that are connected to idle machines drain all of it, let me check if removing them work, well at least this is a mod bug that don't make crashes

**Comment by The-1-7-10-Pack** [comment]
Update me, also keep in mind that if it's not game-breaking you should report if directly to Mekanism's GitHub page.

**Comment by Spellkaze** [comment]
Nothing to worry about, mekanism changed their previous cable mechanics and was messing a bit with my huge cable system in my farms, but it is not a bug or anything like that, already fixed using a low-capability cable.
