### ISSUE TITLE
cant start the modpack 

### ISSUE THREAD

**Issue by TheGamingAngelz** [The-1-7-10-Pack/The-1.7.10-Pack#415]
when i press play it load.. after awhile it goes back to the launcher...
i am using 5 GB ram and 64 bit java

**Comment by The-1-7-10-Pack** [comment]
Can you please give me your latest launcher log? :)

**Comment by TheGamingAngelz** [comment]
ok i will do that in 5-4 days 
i cant use the computer unless its a holiday xD 
#blameschool

**Comment by mertomilo** [comment]
same problem What can ı do?

**Comment by TheGamingAngelz** [comment]
post your latest launcher log
then "the-1.7.10-pack" can help (maybe)

**Comment by Tex28112** [comment]
When i hit play it loads for a sec and takes me back to the launcher anything i can do to fix it?

**Comment by TheGamingAngelz** [comment]
I reinstalled .technic heres the log :)
http://pastebin.com/pLWybaCr

**Comment by The-1-7-10-Pack** [comment]
@Tex28112 Check you have Java 7/8 and a 64 bit version of it.
@TheGamingAngelz Try to completely delete the modpack's folder (backup saves if you wish), download and install it again.

**Comment by TheGamingAngelz** [comment]
I tried that before... dont work

**Comment by TheGamingAngelz** [comment]
I think i found the problem
I cant start minecraft (not modded) with 64bit java. When i try 32bit it worked (normal minecraft)

**Comment by TheGamingAngelz** [comment]
I think i found the problem
I cant start minecraft (not modded) with 64bit java. When i try 32bit it worked (normal minecraft)
Anyway to fix it? :(

**Comment by TheGamingAngelz** [comment]
Nope. I'll try it soon

**Comment by wurian** [comment]
Hello, Im not exactly postive if where to ask. But i updated my pack to the 0.7.6a version and I saw that the recommended version is 0.7.5.(a few days laters) I tried to down grade my pack to 0.7.5 and got an error "an error occured while attemping to delete 'C:\\ ect.. \the-1710-pack\1.7.10\baubles-1.7.10-1.0.1.10.jar' please check your systyem settings." Now i cant even play on the 7.6a version with out getting the same error and message. I am not using optifine. I am playing on a single player world. Is there anyway i can manually downgrade my pack? Or am i stuck with 0.7.6a?

**Comment by The-1-7-10-Pack** [comment]
@wurian You can, see in the modpack's settings.

**Comment by wurian** [comment]
@Jon I tried but when I click install while the launcher is set to install 0.7.5 I get the same message of "an error occurred while attempting to delete baubles 1.7.10. Is there anything I can do to help you better understand my situation?

**Comment by The-1-7-10-Pack** [comment]
@wurian Is it first install? Try to completely delete the modpack's folder (just backup the saves before) and download again v0.7.5.

**Comment by wurian** [comment]
@The-1-7-10-Pack ok sounds simple thank you.

**Comment by wurian** [comment]
@The-1-7-10-Pack 
![screenshot 1](https://cloud.githubusercontent.com/assets/11777170/6975215/b0570ed6-d94e-11e4-84b2-2225cf7cdd70.png)

**Comment by The-1-7-10-Pack** [comment]
@wurian Did you delete the folder even? Also it's a problem in the launcher, not even with the modpack.

**Comment by wurian** [comment]
@The-1-7-10-Pack I did delete the pack. I used the delete pack button shown on the pack screen. Found the pack again and tried to install and this was what i encountered.

**Comment by The-1-7-10-Pack** [comment]
Delete the modpack's folder not through the launcher, because you'd get the same problem. Delete it manually.

**Comment by wurian** [comment]
@The-1-7-10-Pack ok the mod pack is now installing and i have my saves zipped in another folder. Thank you!

**Comment by TheGamingAngelz** [comment]
@The-1-7-10-Pack that link you gave me dont work...
I cant find _JAVA_OPTIONS
any other options?

**Comment by The-1-7-10-Pack** [comment]
@TheGamingAngelz Did you have Java 32bit when you have installed the modpack?

**Comment by Muffinss** [comment]
Same problem where can i put the launcher log

**Comment by The-1-7-10-Pack** [comment]
@Muffinss Use a [paste-tool](http://paste.ubuntu.com/) to post your log.

**Comment by TheGamingAngelz** [comment]
@The-1-7-10-Pack no, I dont have 32bit when I install the modpack

**Comment by Muffinss** [comment]
every time i click open logs nothing comes up

**Comment by TheGamingAngelz** [comment]
soo...
now what?

**Comment by The-1-7-10-Pack** [comment]
@Muffinss Please open your own issue, you have a completely different problem, probably the wrong version of Java.
@TheGamingAngelz There's a problem with you Java on your computer but it's complex, are you able to run other modpacks through the Technic Launcher with ~3GB allocated?

**Comment by TheGamingAngelz** [comment]
@The-1-7-10-Pack no...I cant run anymodpack in Technic Launcher and FTB Launcher... I know its my java problem because when I try to run minecraft(not modded) with 64 bit java it wont work

**Comment by The-1-7-10-Pack** [comment]
@TheGamingAngelz I'm sorry but that's beyond my knowledge. You may need to get support somewhere else to fix how Java runs on your computer, but you need Java 64 bit to run the modpack. Are you sure that your system, PC, is able to support 64 bit Java even? Closing it for now anyway.
