### ISSUE TITLE
Launch but doesn't work

### ISSUE THREAD

**Issue by mertomilo** [The-1-7-10-Pack/The-1.7.10-Pack#417]
launch and installising complete then back technic launcher

**Comment by The-1-7-10-Pack** [comment]
Please give me your latest game log.

**Comment by bezlebub** [comment]
i can give you from mine . I got probably this same problem  i lunch "the 1.7.10 pack" everythink is fine i see in the console  mods are loading  but window with minecraft is always  black: here is http://paste.ubuntu.com/10709045/

**Comment by The-1-7-10-Pack** [comment]
@bezlebub You have no problem at all, your log is just fine. Let the client load :)

**Comment by bezlebub** [comment]
yep but how long it takes ?! i got all time  black screen  all time i start loading ( i give java 4gb in launcher option) and i go watch  Helix  it takes aroudn 40 min and nothink .... still black screen and  its seams loaded

**Comment by The-1-7-10-Pack** [comment]
@bezlebub Your game do load, just slowly. The log says 8 minutes, and you were close to finish. I don't see any specific errors, so I can guess that your system just takes it's time.

**Comment by bezlebub** [comment]
ok look now i got eror http://paste.ubuntu.com/10712850/   the last two lines [B#283] 2015/03/31 "
08:43:17 [INFO]  Exception in thread "Client thread" [08:43:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.OutOfMemoryError: GC overhead limit exceeded
[B#283] 2015/03/31 08:45:22 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1427676366, with 3 tries remaining "what i should do to fix it?

**Comment by The-1-7-10-Pack** [comment]
@bezlebub How much RAM do you have on your computer?

**Comment by bezlebub** [comment]
8gb and i launcher option i set 4gb

**Comment by bezlebub** [comment]
i have instaled latest version java 64

**Comment by The-1-7-10-Pack** [comment]
It may be your Java settings on the computer, check out [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/419#issuecomment-87834315).

**Comment by bezlebub** [comment]
yep finnaly worked  thx for help  . in my cause  help "I hit the "New..." button
Variable name: _JAVA_OPTIONS
Variable value: -Xmx5G" i set  4 gb :)

**Comment by The-1-7-10-Pack** [comment]
:)

**Comment by mertomilo** [comment]
How play java options

**Comment by mertomilo** [comment]
My crash report please check and solve problem. (http://paste.ubuntu.com/10802019/)

**Comment by The-1-7-10-Pack** [comment]
@mertomilo http://support.feed-the-beast.com/t/ftb-infinitiy-crash/10438/4

**Comment by mertomilo** [comment]
It is not work

**Comment by mertomilo** [comment]
What relevance FTB?

**Comment by The-1-7-10-Pack** [comment]
@mertomilo You can read there the fix for your problem.

**Comment by mertomilo** [comment]
Different problem different modpack and different crash report.

**Comment by The-1-7-10-Pack** [comment]
@mertomilo It's the exact same problem. Please do as they say if you wish to fix your issue.

**Comment by mertomilo** [comment]
Be there for FTB Launcher.

**Comment by The-1-7-10-Pack** [comment]
@mertomilo Simply go to the Technic Launcher -> Launcher Options -> Java Settings, and add "-Duser.language=en -Duser.country=US" In the "Java Args" Box.
