### ISSUE TITLE
Help with running it on a mac?

### ISSUE THREAD

**Issue by Deathlyangel** [The-1-7-10-Pack/The-1.7.10-Pack#418]
Sorry for being a noob but i have no idea how to get it to work on my mac! xD

**Comment by The-1-7-10-Pack** [comment]
Can you please give me your latest game log? :)

**Comment by Deathlyangel** [comment]
How do I do that? :P

**Comment by The-1-7-10-Pack** [comment]
Read [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by Deathlyangel** [comment]
Theres no logs at all,

**Comment by The-1-7-10-Pack** [comment]
If so, give me your latest launcher log.

**Comment by Deathlyangel** [comment]
Nvm, it finally works!

**Comment by The-1-7-10-Pack** [comment]
Great :)
