### ISSUE TITLE
Can't Launch 1.7.10 Pack

### ISSUE THREAD

**Issue by Getlon** [The-1-7-10-Pack/The-1.7.10-Pack#419]
Title says it all . I Launch the 1.7.10 pack and it goes back to the launcher . I Have Java 64 bits and 6GB Ram in it . I Don't have optifine . And here's my log http://paste.ubuntu.com/10709075/

**Comment by The-1-7-10-Pack** [comment]
http://www.reddit.com/r/Minecraft/comments/2iqoqj/ram_wont_properly_allocate_anymore_help/cl4mc5x
