### ISSUE TITLE
Pack doesn't respect memory limits set in launcher

### ISSUE THREAD

**Issue by coyninja** [The-1-7-10-Pack/The-1.7.10-Pack#42]
I'm using the latest version (0.6.1), connecting to a server hosted off my machine, running Windows 7 64-bit and the pack is launched through Technic using the latest version of Java 8 (64-bit) with Technic's java memory limit set to 2GB.

But for some reason the pack ends up using 4gB of ram, even immediately after start before connecting to any world. The memory usage never goes down either. I checked the path of the java process running the modpack, and it seems to be setting min/max correctly:

    javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m

I can paste the rest of the path if need be, but I'd rather not unless it's needed as it's rather long and has a few bits of identifying information in there (Auth token and whatnot) that I'd have to remove.

Oh, and I'm not alone in this - the person I am playing with has the same issue. I believe he's also using Win 7 64-bit, but may be running Java 7 (64-bit).

**Comment by coyninja** [comment]
The pack seems to be respecting memory limits on my server. It's only using 1.8gB according to top.

**Comment by BlackJackAres** [comment]
You need to paste the entire path with an online pasting tool like paste.ee or http://paste.ubuntu.com/

**Comment by coyninja** [comment]
Here it is: http://paste.ubuntu.com/9676648/

**Comment by The-1-7-10-Pack** [comment]
Changelog from v0.5.9:
"0.5.9 - Well with some of you guys reporting some issues of "can't launch" I found a tiny problem and I decided to remake the Java settings of the pack. from now on, the modpack will automatically allocate RAM, and will ignore the launcher's RAM settings. this should fix a lot of issues with people leaving the launcher settings at 1GB, which isn't enough of course, or with people allocating 10GB that could lag your MC because it doesn't like too much RAM aswell. 2-3GB RAM should TOTALY be enough. I hope that now it'll be good for everyone."
I hope that this will answer your question.
Also server has a completely diffrent system. :)

**Comment by coyninja** [comment]
That doesn't, because it allocates way too much ram - is there a way to turn it off? Because unless I close **everything** else I lag really bad.

**Comment by The-1-7-10-Pack** [comment]
Too much RAM? It uses between 2 to 3 GB. This is the amount needed, and because of this it's automatic.

**Comment by coyninja** [comment]
I don't know what to tell you... it uses 4gB for both myself and my friend, 4.1GB actually. Is there a way I can turn off the automatic memory allocation? There's clearly something wrong with it on certain systems.

**Comment by The-1-7-10-Pack** [comment]
Please give me a screenshot in-game that showing a use of 4.1GB.

**Comment by coyninja** [comment]
Minecraft only shows 3gB allocated (1.3gB used), but Process Explorer is showing 4gB used. I think the added -Xmx is being applied to another jar, because javaw.exe is clearly using more than 1.3gB. Where are you overriding Technic launcher's memory setting?

**Comment by coyninja** [comment]
Removing:

    -Xms2048M -Xmx3072M -XX:PermSize=256M 

From bin/version.json and locking the file fixes the issue. If it were me I'd just tell people to increase their memory in the launcher, because the method you're using clearly causes some problems. It's apparently not **that** big of a deal since no one else has reported it, but it seems like a bad way to fix something that already has a fix.

**Comment by The-1-7-10-Pack** [comment]
It's NOT a problem. if MC shows 3 allocated and 1.3 used that's the real statics. using Process Explorer is not accurate like in-game.
You should appreciate the automatic system - not making people have to set their RAM in the launcher, not doubt it.
The method has no problems.
