### ISSUE TITLE
Modsuggestion - RoadWorks, Web displays & Stargatecraft

### ISSUE THREAD

**Issue by Yorick1234** [The-1-7-10-Pack/The-1.7.10-Pack#420]
May I suggest 3 mods compatible with 1.7.10 Minecraft, that would really add up to the experience: 

-RoadWorks - adds all sort of roads, streetlights and roadsigns and such. http://www.planetminecraft.com/mod/roadworksforge/
-Web displays so you can visit websites in game via Computercraft, and even build a cinema with youtube video's for example. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291044
-Stargatecraft to build and have programmable portals (nice looking stargates) to any place or dimension you'd like. http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/SGCraft/

Thank you for considering these in a next version of this modpack. Cheers!

**Comment by The-1-7-10-Pack** [comment]
Thanks for suggesting, but I won't add any of these mods.
They don't really fit the general idea for the modpack.
For now you can add them manually if you want to use them :)
