### ISSUE TITLE
How do I receive my reward?

### ISSUE THREAD

**Issue by AidanCYT** [The-1-7-10-Pack/The-1.7.10-Pack#421]
Hey there, after completing the "Top of the Food Chain" quest I did not recieve an option to claim my rewards, even when it says that i have the requirements. Is this a bug or am I doing something wrong?

http://gyazo.com/a5e6aef96db1bf80b7aabb68c615a045

**Comment by The-1-7-10-Pack** [comment]
The quest has part two, you'll need to click on the "Well, you're OKAY." part :P
