### ISSUE TITLE
Launching Problems 

### ISSUE THREAD

**Issue by shadow00321** [The-1-7-10-Pack/The-1.7.10-Pack#422]
The mod pack won't launch for me. It will download libraries and check for assets but will reopen the launcher. Any help?

**Comment by The-1-7-10-Pack** [comment]
You need to be sure that you have Java 7/8 and a 64 bit version of it.

**Comment by shadow00321** [comment]
I do.

**Comment by shadow00321** [comment]
I feel like an idiot, I just needed to update my Java, thanks for helping me.

**Comment by The-1-7-10-Pack** [comment]
:)
