### ISSUE TITLE
Project E (Equivalent Exchange 3)

### ISSUE THREAD

**Issue by AzzaBGitHubories** [The-1-7-10-Pack/The-1.7.10-Pack#423]
I think EE3 would be a great mod to add. It's one of the originals that everyone loved! Yeah it was extremely OP in TEKKIT but after being abandoned and now taken over by a new developer he has stated that he will be developing it to be much more balanced and end gamey.

Also if people still think its OP and shouldn't be added because of this, then don't use it!:P Adds so many useful items to the game (Not just talking about the condensers) but such things as repair talisman and destruction catalysts :)

I think this would completely top the cake with a cherry and would make this my favorite modpack since the original Tekkit and Technic packs!:) (Also add Ars magica when its stable! ;D) 

Link - https://github.com/sinkillerj/ProjectE

Great Modpack!
AzzaB

**Comment by Deathwinng** [comment]
+1

**Comment by ZombieTG** [comment]
yes! +1

**Comment by Blazze909** [comment]
I would really enjoy this mod in the pack as well.. However it is super OP and that could easily annoy people. If the Technic launcher allowed for optional mods that'd be super cool but oh no LOL
Up to the pack creater

**Comment by AzzaBGitHubories** [comment]
Well yeah I mean its no more OP than Magical Crops is tbh because it takes a long time for it to eventually become OP. but yeah ahah down to Jon:)

**Comment by CriticalRocket** [comment]
Could add a config file to turn the mod on/off. Default would be off.

**Comment by AzzaBGitHubories** [comment]
Could do

**Comment by The-1-7-10-Pack** [comment]
EE3 has plans, and ProjectE has another plans. For now I'd prefer to not add any of these mods, thanks anyway for suggesting.

**Comment by AzzaBGitHubories** [comment]
sad days </3
