### ISSUE TITLE
OptiFine Launching Problem

### ISSUE THREAD

**Issue by LordRandom99** [The-1-7-10-Pack/The-1.7.10-Pack#424]
When I install OptiFine and try to launch the modpack, it will open the window, close, and then return to the technic launcher. 

To install it I copied the files from OptiFine into modpack.jar using 7Zip. I used OptiFine version 1.7.10 HD U B5. 

I can run the modpack without OptiFine but I would like to have it installed.

Thanks,
LordRandom99

**Comment by The-1-7-10-Pack** [comment]
You need to put the optifine jar into the mods folder. Now it's bad though, you'll need to reinstall the modpack.
