### ISSUE TITLE
Minechem

### ISSUE THREAD

**Issue by alex2710xela** [The-1-7-10-Pack/The-1.7.10-Pack#425]
Just an idea, what does everyone else think?

http://minechem2.wikia.com/wiki/Mine_Chem_2_Wiki

http://jakimfett.github.io/Minechem/

**Comment by Dommain** [comment]
minechem doesn't integrate well with other mods I feel.

**Comment by The-1-7-10-Pack** [comment]
Minechem is a real game changing game, it doesn't really fit the theme of the modpack. Thanks anyway for suggesting!
