### ISSUE TITLE
Compact Machines

### ISSUE THREAD

**Issue by alex2710xela** [The-1-7-10-Pack/The-1.7.10-Pack#426]
Just another idea, what does everyone else think?

http://www.curse.com/mc-mods/minecraft/224218-compact-machines

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2220422-compact-machines-v1-17

**Comment by Deathwinng** [comment]
Great mod, I already added it manually.

**Comment by The-1-7-10-Pack** [comment]
Not everybody like this mod, this is problematic. Thanks anyway for suggesting! :)
