### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Aninhafofa77** [The-1-7-10-Pack/The-1.7.10-Pack#427]
what is the address of the public server? Please answer me as soon as possible .

**Comment by Aninhafofa77** [comment]
i need the site

**Comment by Aninhafofa77** [comment]
HELP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by The-1-7-10-Pack** [comment]
GOD PLEASE THERE'S NO PUBLIC SERVER STOP PANIC!!!!

**Comment by Aninhafofa77** [comment]
hey

**Comment by Aninhafofa77** [comment]
but have a server

**Comment by Aninhafofa77** [comment]
i cant join

**Comment by Aninhafofa77** [comment]
plz
