### ISSUE TITLE
Problems loading?

### ISSUE THREAD

**Issue by jakebee101** [The-1-7-10-Pack/The-1.7.10-Pack#43]
I would also extremely enjoy this modpack, and I can see that it has almost 70k runs, but for some reason, no matter what I do, I just can not load this modpack up. I can run some modpacks, Voltz, Tekkit classic, and a few unofficial modpacks. I would like to include a crash report, but sadly, as I follow the path you provided, there is no "Logs" folder, but I guess I will try once more to follow the steps you have included in the post very similar to this. Thanks! jakebee101

ps. I did however include a screencapture of my 1.7.10 pack folder.
![image](https://cloud.githubusercontent.com/assets/10405769/5617677/2cc91e8c-94c6-11e4-928f-e5224c857676.png)

**Comment by jakebee101** [comment]
Those are the only folders.

**Comment by The-1-7-10-Pack** [comment]
If so, please provide the latest launcher log from .technic/logs.
Post it there: http://paste.ubuntu.com and link to here.

**Comment by The-1-7-10-Pack** [comment]
Your system can't afford using the automatic RAM settings of the modpack.
How much RAM do you have on your computer?

**Comment by jakebee101** [comment]
I have 4.0 GB ram.

**Comment by The-1-7-10-Pack** [comment]
So it should work. The only problem I can see is that your Java version is wrong, and you have the 32bit instead of the 64bit.

**Comment by jakebee101** [comment]
I have windows vista which does not support java 64bit. Oh well.

**Comment by jakebee101** [comment]
Okay so what version of Java do I need?

**Comment by The-1-7-10-Pack** [comment]
You need Java 64 bit, unfortunately.

**Comment by Jadababy** [comment]
Help Crash Report  paste.ubuntu.com/9763867/

**Comment by Jadababy** [comment]
i have all the requirement 64-bit Java 7 and 8

**Comment by The-1-7-10-Pack** [comment]
@Jadababy Please open your own issue.

**Comment by The-1-7-10-Pack** [comment]
Well I think I can't help anymore with this, closing this one.
