### ISSUE TITLE
Suggestion :D

### ISSUE THREAD

**Issue by cHaOZZoNE** [The-1-7-10-Pack/The-1.7.10-Pack#432]
As I was yelled at for posting in the comments here I go:

*Could you make passive generation of water through aqueous accumulators standard? Sprinklers are very annoying and kinda useless without. Also as others have said before Iguana Tweaks would be a neat addition. Either way, keep up the good work!*

**Comment by The-1-7-10-Pack** [comment]
Iguana Tweaks won't be add to the modpack, it's a game changing mod, and not everobody like it.
As for the first point, it should be like this as default, am I wrong?

**Comment by cHaOZZoNE** [comment]
They do not seem to generate water passively at all anymore unless the mechanic was changed at some point.

**Comment by The-1-7-10-Pack** [comment]
Can you please tell me where exactly in the configuration file do you see that "the option to generate water passively is set to false"? Thanks.

**Comment by The-1-7-10-Pack** [comment]
I agree, will change to true next update!

**Comment by The-1-7-10-Pack** [comment]
It's actually a bit problematic to do this change now, also a bit OP (where is this water coming from, eh?)
If you wish to enable it, you can do so for yourself.
Thanks anyway for suggesting, and I may implement it on the future, just not for the next update :)
