### ISSUE TITLE
Crashed upon opening

### ISSUE THREAD

**Issue by Asmodeus95** [The-1-7-10-Pack/The-1.7.10-Pack#433]
Whenever I open the game, I get to the initializing loading screen, and then the game stops responding and crashes. I'm giving it 8 Gb of RAM, but it's only using about 2 and I've tried reinstalling both the pack and the launcher. I've had this problem with other packs like Hexxit and Tekkit.

**Comment by The-1-7-10-Pack** [comment]
Crashing? I need your latest game log, or a crash log if you have one. Please use a [paste-tool](http://paste.ubuntu.com/).

**Comment by Asmodeus95** [comment]
ok, I've opened the logs, which part should I copy? I'm not a big tech with this lol

**Comment by The-1-7-10-Pack** [comment]
Read [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by Asmodeus95** [comment]
ok, here
http://paste.ubuntu.com/10715395/

**Comment by The-1-7-10-Pack** [comment]
I don't see any crash. Do you have a folder named "crash reports"?
If not, give me your latest launcher log.

**Comment by Asmodeus95** [comment]
Crash report, I have another if you want to see that too
http://paste.ubuntu.com/10715420/

**Comment by The-1-7-10-Pack** [comment]
You're missing the EnderIO mod, this is what crashing you.

**Comment by Asmodeus95** [comment]
I deleted that because it wasn't letting me join my friends server, also the extracells mod

**Comment by The-1-7-10-Pack** [comment]
You can't just delete it, other mods need it. If your friend was not able to join the server he was on a different version of the modpack - Not the latest.
