### ISSUE TITLE
Red Power 2

### ISSUE THREAD

**Issue by mmooll** [The-1-7-10-Pack/The-1.7.10-Pack#434]
I was looking thought the suggested and I saw a lot of requests for magic mods.  I am just saying that magic mods ruin the whole feel of a modpack.  You have magic and machines in the modpack but personally I try to only use machines because I really like Tech.  Anyways on to the real suggestion.  Red Power 2 has microblocks which work like a amazingly with pipes.  I really hope you add this in.  if this does not work you could also try immbles or something like that but Red power is so much better because of the wires and things it adds.

**Comment by The-1-7-10-Pack** [comment]
Wha? We have ProjectRed, and it's not Minecraft 1.2.5.
Thanks anyway.
