### ISSUE TITLE
Microblocks connection lost

### ISSUE THREAD

**Issue by Dydax** [The-1-7-10-Pack/The-1.7.10-Pack#435]
I was on my server last night and all of a sudden I got kicked from the server. When I try to log back in I get: Connection Lost. The following microblocks are not installed on this client: tile.whitestone. I don't know what to do for this, I tried reinstalling the pack and that doesn't seem to have fixed it. The versions are both the same too. Do you have any suggestions or solutions for this problem?

**Comment by xCaykex** [comment]
I'm gonna 2nd this as a problem for 2 other people trying to connect to my server.

**Comment by xCaykex** [comment]
Okay so. There is four of us. 1 has no problem what so ever. I have the same problem with the tile.whitestone had have made 0 alterations to my files in the last 24 hours. The last 2 have reinstalled their files and are still having issues.

**Comment by mickyb07** [comment]
Hi, just thought I'd chime in and mention I'm having the exact same problem on my server, got off before work last night and everything was working fine.
Made no alterations to any files on my end and as far as I know the server files were exactly the same and I either get a straight up crash with no error message, or I get the same message as described by Dydax. 
Have Reinstalled technic launcher + 1.7.10 pack and completely deleted and reinstalled server files, still the same issue! :(

**Comment by Dydax** [comment]
This might work maybe https://dd.reddit.com/r/TestPackPleaseIgnore/comments/310tpz/cant_connect_due_to_tilewhitestone_microblock_is/cpxkenu

**Comment by chrizza710** [comment]
yea same issue for me, havent been able to login to my server all day, tryed the fix above with no luck, tho apparently there will be an update later that fixes it, hopefully it comes out soon

**Comment by bezlebub** [comment]
hehe change date in your system :P

**Comment by The-1-7-10-Pack** [comment]
^

**Comment by The-1-7-10-Pack** [comment]
^
