### ISSUE TITLE
Modpack Server Issue

### ISSUE THREAD

**Issue by ZombieTG** [The-1-7-10-Pack/The-1.7.10-Pack#436]
So i have a issue, when i log into my hamachi server i crash every time and i get sent back to the launcher. My friend had the same issue when logging in too but he got a error message once and it said something like missing block white stone? Not sure... This only started happening last night and was working fine before that. 

My friend left the server at around 9pm and came back around 1 am and when he tried at 1 am it stopped working, i could still log in until i quit the launcher and went back into the launcher started up the mod pack and tried logging into the server and it then got the problem...

The server in the server list has a green tick so it's supposed to work... Not sure why this happened and have no clue in to why it happened since nothing was done within the time space of 9pm and 1am.

I even tried changing maps on the server ( I was running 0.7.6 server ) then i downloaded the updated version server ( 0.7.6a ) and tried logging into that one, yet it crashes me everytime STILL ! :(

I've tried everything i could think of but i need some help to fix this !

**Comment by ZombieTG** [comment]
Also, one of thing i could think of is making a 0.7.5 server since i did realize it's the recommended version now but where could i find the download to the 0.7.5 server?

**Comment by The-1-7-10-Pack** [comment]
Too much text and yet not enough info. I need a crash log or something, sum things up

**Comment by ZombieTG** [comment]
Okay sorry. 

Here's a crash log http://pastebin.com/xzkSkqjH

**Comment by ZombieTG** [comment]
Any info on what happened??

**Comment by CrazyDigga** [comment]
@ZombieTG Try this: http://www.reddit.com/r/TestPackPleaseIgnore/comments/310tpz/cant_connect_due_to_tilewhitestone_microblock_is/

Change the "hardcoreEnderbacon" from "0" to "2"

**Comment by ZombieTG** [comment]
Cheers it worked , god was wasting so much time to figure this out lol

**Comment by The-1-7-10-Pack** [comment]
Happy to see others @CrazyDigga helping others @ZombieTG. :)
