### ISSUE TITLE
[Issue] Server crashes on join

### ISSUE THREAD

**Issue by CriticalRocket** [The-1-7-10-Pack/The-1.7.10-Pack#437]
Hey :)

I've been using this modpack for about a week now, and I just love it!
I'm playing with a friend of mine on a private server which I host on my laptop.
Everything has been working untill today.

First I got the whiteblocks error, which after some googling I found out that it was caused but HardcoreEnderExpension, so I fixed it.

But now I'm getting more weird errors, some of which research suggests also might be caused by April Fools day, but I'm not sure and I don't know how to fix it.

I've tried redownloading the server and switching modpack versions, nothing seems to be working.

One of the errors I'm getting is 'exception ticking world', which google says is caused by a seasonal IC2 mob which I only found occurences of on halloween, so I don't if it is activated today as well. Google says (I mean what I found on google :p) that it should be fixed by disabling mobs, but that didn't work for me.

Another error I'm getting is

I've tried searching for as many server and client mods I could find, I don't know which would be of the most use.

**Server:**
CMD: http://pastebin.com/hRQYgzLL
*Line 281 and 285 are no problem, those chisel blocks are just placeholders, they aren't the cause of my crash*

Crash Report: http://pastebin.com/qCCF6tgx
NOTE: I just now noticed the new Ticking Block Entity error - googling it now.

fml-server-latest.log: http://codepad.org/vL6FyOMB
Not very usefull it seems

latest.log: http://pastebin.com/VaQCLtPT
Again showing the ticking block entity

I'm running java 64bit, got 3GB Ram on the server and 2GB Ram on the client. 
Windows 8.1

I've got no idea on how to fix this, any help would be greatly appreciated :)

P.s. I just notice I don't have a 'help wanted' tag in the title, and  I don't know how to add it :a

**Comment by The-1-7-10-Pack** [comment]
The crash report points out about a ticking block entity, the golden egg from the OpenBlocks mod.
They may have tried to do something for april fools with it? Because I don't remember any problem with it before.
Try to report the issue [there](https://github.com/OpenMods/OpenBlocks/issues), and provide the crash report too.

**Comment by CriticalRocket** [comment]
Hey, 

Thanks for the reply!

Yeah I noticed that too, I'm currently trying to remove the block/whatever it is through MCEdit, but it's not letting me (MCEdit is still in alpha). Going to try NBT Explorer next.

Man, I can't believe so many mods implement GAME BREAKING STUFF on hollidays. Aren't hollidays supposed to be fun? ><

**Comment by The-1-7-10-Pack** [comment]
Not april fools :)
Closing it for now, nothing I can do unfortunately.
