### ISSUE TITLE
Suggestion: Draconic Evolution

### ISSUE THREAD

**Issue by Blazze909** [The-1-7-10-Pack/The-1.7.10-Pack#440]
It has a huge ball of energy storage and lots of late game tools. And that ball of energy storage? The tier 6 one can hold 2.14 trillion RF. It also plays pretty nice with most other mods from what I've seen. 
link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2093099-draconic-evolution-1-0-1rc3

**Comment by The-1-7-10-Pack** [comment]
Except big power storing options, what else this mod has to offer that other mods can't?

**Comment by Nikey646** [comment]
The best set of Powered Tools that offer the ability to swap and change enchantments as you wish (silk touch and fortune 3 pick in 1 ;D), a Mob Grinder that doesn't idle, and can kill a Wither in 1 hit (OP :>), an End-Game in the mod that requires more than what a quarry could provide (Requires killing the Ender Dragon (multiple times), charging draconium blocks with 100 million RF to get awakened draconium), and is pure awesomeness in a nutshell?

P.S: In 0.7.6a, there seems to be a bug where the dust which should be made into the Blend can be smelted straight into an Ingot with Mekanism Machines, meaning getting the ingots is x4 times easier than what was intended. Not sure if Mekanism, AOBD, or Draconics Evolution RC3

**Comment by The-1-7-10-Pack** [comment]
@Nikey646 These are all bugs in Mekanism which got really unstable since the v8 update, we hope that it'll all get fixed soon. When it will, we'll release v0.7.6b.

**Comment by The-1-7-10-Pack** [comment]
The mod does not fit the modpack, and I won't add it. Thanks anyway for suggesting!
