### ISSUE TITLE
Suggestion: RF Tools

### ISSUE THREAD

**Issue by Blazze909** [The-1-7-10-Pack/The-1.7.10-Pack#441]
RF tools adds dimensions like mystcraft but it's not mystcraft so you could avoid the hassle of mystcraft entirely by adding this mod. I also adds logic gates and teleport systems some other really cool things. 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-crafter

**Comment by Boehrsi** [comment]
Sounds nice, would be nice to see this mod or Mystcraft to appear in the pack.

**Comment by CriticalRocket** [comment]
I don't really know either of the mods. What are the features of each of them?.. :p

I know mystcraft has bugs in which in some (rare) cases inventories can be wiped when switching dimensions/loading a dimension for the first time. If RF Tools offers the same experience without bugs like those then I'd go with RF Tools.

**Comment by The-1-7-10-Pack** [comment]
We'll probably add Mystcraft as a part of our future plans, so RF tools is not a real option. Thanks anyway for suggesting :)
