### ISSUE TITLE
Keep getting disconnected from server

### ISSUE THREAD

**Issue by Getlon** [The-1-7-10-Pack/The-1.7.10-Pack#445]
Me and my friends have a server with hamachi , and i keep getting "timed out" and "disconnected" and "Internal Exception: java.io.IOE.Exception:An existing connection was forced to close by the remote host" the server after 10m of playing . What's wrong ?

**Comment by The-1-7-10-Pack** [comment]
Nice profile picture.
Anyway, I need your full server log.

**Comment by Getlon** [comment]
http://paste.ubuntu.com/10725540/ I Guess

**Comment by The-1-7-10-Pack** [comment]
Okay, I need your full client log too (that you got the error with).

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
