### ISSUE TITLE
Cauldron confiction

### ISSUE THREAD

**Issue by AzzaBGitHubories** [The-1-7-10-Pack/The-1.7.10-Pack#446]
Hiya, not extremely important by those who want plugins on their server may not be able to have them as the pack seems to conflict with Cauldron, not sure what conflicts and neither does my server host. If anyone knows of any mods that have conflicts with Cauldron in the past would be great to find out and if a fix is possible :)

Again not hugely important but thought I would let people know :)

AzzaB

**Comment by The-1-7-10-Pack** [comment]
What Cauldron version do you use?

**Comment by AzzaBGitHubories** [comment]
Version 1.1236.04.209

**Comment by The-1-7-10-Pack** [comment]
This Cauldron version is as old as the creature on your profile picture.
You need your Cauldron version to match the modpack's Forge version.
Use the latest build from [there](http://tcpr.ca/cauldron), also you may have to remove the "FastCraft" mod.

**Comment by AzzaBGitHubories** [comment]
Hahah well shit :L thought that may be some issue :P and oh damn really? FastCraft seems to make this pack run extremely well...
I think this is the first modpack I've played with FastCraft on and it runs so damn good client and server side.. either FastCraft is doing this or you have done this great work ;)

Will performance drops be noticeable with fastcraft removed? 

Thank you :)

AzzaB

**Comment by The-1-7-10-Pack** [comment]
Just check yourself and see, I think it'll be fine though :)

**Comment by AzzaBGitHubories** [comment]
Great! Thanks!

AzzaB
