### ISSUE TITLE
Order of mods to play

### ISSUE THREAD

**Issue by AidanCYT** [The-1-7-10-Pack/The-1.7.10-Pack#447]
Hey guys, I've been playing with this mod pack for probably 10 hours now and I have not gotten anywhere. I spend a lot of time sitting in my 3 x 3 wood house wondering what mod i should spend some time completing. Obviously most of the mods requires a lot of resources that I probably don't have.

My question is: What is a good order to complete the mods, starting from 0?

**Comment by martinegui** [comment]
I would say to you to get start with mekanism (multiple ores!) and as soon as you can some kind of auto-miner.

**Comment by The-1-7-10-Pack** [comment]
Just complete the quests :)
