### ISSUE TITLE
How to use Cauldron

### ISSUE THREAD

**Issue by cyris69** [The-1-7-10-Pack/The-1.7.10-Pack#448]
How do you install Cauldron along side this pack? There are some plugins I'd like to use. I've downloaded the most recent version.

**Comment by The-1-7-10-Pack** [comment]
Just replace the Cauldron jar with the Forge jar, same with Cauldron's liberies - replace them with the current liberies. Also name the Cauldron jar just the same as the Forge jar that you have, it'll be easier that way :)

**Comment by cyris69** [comment]
Where do I get the lib files from the most recent march 30 zip only has installer and server jar no lib folder.

**Comment by The-1-7-10-Pack** [comment]
tcpr.ca/cauldron

**Comment by cyris69** [comment]
cauldron-1.7.10-1.1343.01.0.zip doesnt contain any folder only the installer jar and server jar. Running installer just extracts another server jar and running the server jar produces no lib folder.

**Comment by The-1-7-10-Pack** [comment]
You need to use Cauldron for the current forge, 1307. Anyway it's not recommended, this Cauldron is old.
