### ISSUE TITLE
Mac problems, please help.

### ISSUE THREAD

**Issue by Mati3sGala** [The-1-7-10-Pack/The-1.7.10-Pack#449]
When i try to launch the pack it doesn't appears, the only thing that happened was some librareis configurating, when i first tried to play it. The problem is that i installed Java 8 recently, but the Technic Launcher still has Java 6 , and it won't update itself. I don't know what to do. I'm not sure about it but the log is this one: [B#283] java.net.URISyntaxException: Illegal character in path at index 38: file:///Users/imac/Library/Application Support/technic/logs/
[B#283] 	at java.net.URI$Parser.fail(URI.java:2810)
[B#283] 	at java.net.URI$Parser.checkChars(URI.java:2983)
[B#283] 	at java.net.URI$Parser.parseHierarchical(URI.java:3067)
[B#283] 	at java.net.URI$Parser.parse(URI.java:3015)
[B#283] 	at java.net.URI.<init>(URI.java:577)
[B#283] 	at net.technicpack.utilslib.DesktopUtils$1.doInBackground(DesktopUtils.java:59)
[B#283] 	at net.technicpack.utilslib.DesktopUtils$1.doInBackground(DesktopUtils.java:51)
[B#283] 	at javax.swing.SwingWorker$1.call(SwingWorker.java:277)
[B#283] 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[B#283] 	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[B#283] 	at javax.swing.SwingWorker.run(SwingWorker.java:316)
[B#283] 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
[B#283] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
[B#283] 	at java.lang.Thread.run(Thread.java:695)

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/368#issuecomment-86014787

**Comment by Mati3sGala** [comment]
I know that this is not related, and the issue was closed but it seems that i exagerated a bit and deleted the Java folder, and when i install Java 8 Update 40 with the installer it does not créate nothing. Maybe you can help, but if not, there is nothing wrong with it :). Thanks.

**Comment by Mati3sGala** [comment]
create*
