### ISSUE TITLE
Getting uses for a grape crashes the game.

### ISSUE THREAD

**Issue by Shalashalska** [The-1-7-10-Pack/The-1.7.10-Pack#45]
Pressing "U" while hovering over a grape crashed the game.

Crash Report
paste.ubuntu.com/9679988/

**Comment by The-1-7-10-Pack** [comment]
Are you playing on the official server?

**Comment by BlackJackAres** [comment]
Yes. It is happening to literally everyone who does it.
Pressing R does the same thing and it happens with any item.

**Comment by The-1-7-10-Pack** [comment]
See here: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/28
