### ISSUE TITLE
Still Not Working....

### ISSUE THREAD

**Issue by ChiknNRiceGaming** [The-1-7-10-Pack/The-1.7.10-Pack#450]
Hold up a second! So I installed Java 8 Version 40, and yea.... still not working? Do you think the issue is something else, and not the pack itself? Thx!

INFO
I am using a Mac OSX, Java 8, no Optifine, using client, and absolutely no additional mods.

**Comment by ChiknNRiceGaming** [comment]
For background info, when I start up the pack, it goes to the CBDLoader as it should, and when the bar reaches 100%, it crashes, and it takes me back to the launcher.

**Comment by The-1-7-10-Pack** [comment]
Not ANY problem is because the wrong Java version, but with how you describe the problem, I bet that [that's](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/368#issuecomment-86014787) your fix. I'll reopen if it's not :)
