### ISSUE TITLE
Tried Everything, and Now I am Fustrated...

### ISSUE THREAD

**Issue by ChiknNRiceGaming** [The-1-7-10-Pack/The-1.7.10-Pack#451]
I have literally tried everything to get this pack working... and to no avail. I went to the page that you redirected me to Hi It's Me, and I did everything that the guy did to try to get the pack working. I don't understand how the person got the pack to start working, and I was wondering if you could clear it up for me or something?! I have even tried dragging all the mods to regular MC, but of course, it had to crash on me. I have confirmed that I am using Java 8 64 bit, but I am still unsure if the problem is Java. My Java version for Technic is Latest 64 bit (1.6.0_65 64-Bit). Thanks for reading.

**Comment by ChiknNRiceGaming** [comment]
I have a "Never Give Up" feeling about this issue.... I won't stop trying to get this thing fixed, so don't just get rid of this issue plz!

**Comment by Dommain** [comment]
1. Verify that you only have java 64 bit installed on your computer in the java section of the control panel. 
2. Verify you set the boot launcher to recommended. 
3. Verify that you have at least 3 gigs of ram open (not total). 
4. Defrag your hard drive and ensure there is couple gigs open on the drive.
5. disable the console from being viewed in the tekkit launcher.
6a. If it crashes, not freeze, please post that client crash log. 
6b. If it freezes, disable hardware acceleration for java and then update direct X, windows files, and hardware.
7. If you still have trouble, Type "dxdiag" into run and check for problems.

**Comment by The-1-7-10-Pack** [comment]
The modpack needs Java 7+ at least to launch, and you say you have Java 6. That's your problem. You need to update it! :)
