### ISSUE TITLE
AutoCrafter world crashing

### ISSUE THREAD

**Issue by scarless** [The-1-7-10-Pack/The-1.7.10-Pack#452]
Putting the essence orb[Magical crops] in to the ingredient side of Auto Crafter[Progressive automation] causes the game to crash every time the world is loaded.

**Comment by The-1-7-10-Pack** [comment]
Can you give me a crash report? :)

**Comment by scarless** [comment]
inital crash(server): http://pastebin.com/K0vpKQ6N
reloading crash(server):http://pastebin.com/Srv4b73s
reloading crash(client): http://pastebin.com/5m7KeZ5m
This was all single player.

**Comment by The-1-7-10-Pack** [comment]
Nothing I can do about it, you should report it [there](https://github.com/Vanhal/ProgressiveAutomation/issues). Thanks anyway! :)
