### ISSUE TITLE
Item Transfer node to crafting station bug

### ISSUE THREAD

**Issue by scarless** [The-1-7-10-Pack/The-1.7.10-Pack#453]
When having a transfer node pump items into a crafting station [Tinkers Construct] it will not allow you to craft the item until the player places an item into the grid, or the interface is closed and reopened once the recipe is correct.

Steps: 
Connect item transfer node to table:
Let the transfernode transfer cobblestone into the table[for example]
Once the 3x3 has cobblestone attempt to use the recipe to craft the item.
Keep the crafting interface open and repeat

**Comment by The-1-7-10-Pack** [comment]
You may want to use an automatic crafting table for this kind of stuff, Tinkers' crafting station does not supposed to work this way :)
