### ISSUE TITLE
Keep Crashing and it takes 30 minutes to load

### ISSUE THREAD

**Issue by TheAwesomeGuy7** [The-1-7-10-Pack/The-1.7.10-Pack#454]
when ever i join wich takes 30 minutes i load a world and it crashed and i have java 7/8

**Comment by The-1-7-10-Pack** [comment]
Mostly the people that have this problem have custom Java Settings. See [this](http://www.reddit.com/r/Minecraft/comments/2iqoqj/ram_wont_properly_allocate_anymore_help/cl4mc5x) fix. Anyway, I need your log for anything.

**Comment by wurian** [comment]
@The-1-7-10-Pack quick question how do i load a back up? I found the folder. Is it just click and drag? I had a crash and my inventory was deleted when i loaded my world again thats why i am asking, Thank you!!!

**Comment by The-1-7-10-Pack** [comment]
@wurian This is irrelevant to here, but mainly you unzip the backup and copy the actual save folder into the saves directory within the modpack's folder.

**Comment by wurian** [comment]
@The-1-7-10-Pack Yes I know it was irrelevent. I should have appoligized in advanced.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
