### ISSUE TITLE
0.7.5 server crash

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#455]
hi , i recently reverted a 0.7.6 server back to 0.7.5

but i am not if this is the cause of the problem.
i had unknown crashes at 0.7.5 aswell.

Please can you help check whats wrong.
Somehow it keeps on generating a new server properties file.
(server.properties.properties) with nothing in it.

very suspicious ,supernatural 

latest fml log
http://pastebin.com/yRdpRsZj

crash report 
http://pastebin.com/JyQuQyDu

more crash report
http://pastebin.com/9GZ4vgHF

The ouch crash report
http://pastebin.com/G0pcHZrb

The cyclone crash report
http://pastebin.com/J6uGMAS1

big thanks , happy easter,love your pack!!

**Comment by The-1-7-10-Pack** [comment]
A problem with the chisel mod, if you remove it does everything work okay?

**Comment by imsupermario** [comment]
give me one minute

**Comment by imsupermario** [comment]
ok i can login to server,smooth. and feels good. would you like to have a look at the save before i remove chisel?

**Comment by The-1-7-10-Pack** [comment]
Reverting is a problem and some mods do not like it, that's the price. I hope that when we'll go to the next update of the pack you will be able to use Chisel again, but nothing else I can do for now.

**Comment by imsupermario** [comment]
so it means i am in the waiting game now

**Comment by The-1-7-10-Pack** [comment]
It's not a real problem, it's just because you reverted a version of the mod.
