### ISSUE TITLE
server files

### ISSUE THREAD

**Issue by Doppler94** [The-1-7-10-Pack/The-1.7.10-Pack#456]
Hey

Everytime I attempt to use the server files provided by technic for this pack, it will launch fine although when i try join the world im am hosting it says missing 16 mods. My Java is up to date, I am not using any additional mods (so no optifine.) No herobrine.

http://puu.sh/h27KF/1cee93160a.png (this is the symbol that apears long side my server)
Error Message: Incompatible FML modded server
                         197 mods present (even though this is the official server files for this pack)

Thanks

**Comment by The-1-7-10-Pack** [comment]
Because you're using the wrong version of the server files and modpack.
Here's the download for the server files for v0.7.5:
http://bit.ly/The-1-7-10-Pack-ServerD-v0-7-5
