### ISSUE TITLE
How do i add plugins to my 1.7.10 pack server?

### ISSUE THREAD

**Issue by ZombieTG** [The-1-7-10-Pack/The-1.7.10-Pack#457]
So i run the 1.7.10 Pack on my hamachi server and was wondering how i would add plugins to my server?

I haven't added plugins to a minecraft server in a long time and not sure what bukkit was needed or what requirements is needed aswell for a modded server.

I'm not sure if I'm able to post this here but since i can't find any tutorials on YouTube for this modpack i will add it here to see if someone else has added plugins to their 1.7.10 pack server.

**Comment by The-1-7-10-Pack** [comment]
Adding plugins to a modded 1.7.10 server is not recommended at any way. Do you really want to do it?

**Comment by ZombieTG** [comment]
I just wanted to add a few small plugins, but if it's too complicated or is going to lag out the server then i guess not lol

**Comment by The-1-7-10-Pack** [comment]
The code for Cauldron is abandoned. Too bad, I know.
