### ISSUE TITLE
mod suggestions

### ISSUE THREAD

**Issue by MrTangoPIG** [The-1-7-10-Pack/The-1.7.10-Pack#458]
a few good mods ive encountered and would like included in your modpack, enhanced portals (last version i played was EP2), rails of war (havnt used it before but looks beautiful, a better vehical mod (maybe flan's civilian vehicals (would be great if there could be intergration between buildcraft oil/fuel and vehicals), tinker's steelworks, some form of shield mod with intergration with industrialcraft electricity/buildcraft energy). Other than that, love the modpack!

**Comment by MrTangoPIG** [comment]
ive just noticed why and details, why... because they would compliment many mods already in the pack.

**Comment by MrTangoPIG** [comment]
details, enhanced portals would change the nether portal to enable any dimensions (size), add travel between any dimension (mainly nether and overworld), and a stargate-like dialing system with gates being assigned addresses to be dialed (no longer portal 1 links to it's nether counterpart, any portal can connect to any other, so long as the address is given and it's not already occupied), rails of war adds laots of cool looking trains.

**Comment by pixelpreds** [comment]
try to add minecoleny it is really fun and there in next to none mod packs with it on so yeah make it possible...    PLEASE

**Comment by MrTangoPIG** [comment]
trouble with that style of mod (village improvement or management) they dont play nice with servers in my experiance

**Comment by pixelpreds** [comment]
ok

**Comment by pixelpreds** [comment]
MrTangoPIG  is there ant chance that you know how to make mod packs and if so could you make it that would be much appreciated

**Comment by The-1-7-10-Pack** [comment]
Currently I won't add any of those mods, thanks anyway for suggesting! :)

**Comment by pixelpreds** [comment]
MrTangoPIG is there ant chance that you know how to make mod packs and if so could you make it that would be much appreciated
