### ISSUE TITLE
[mod suggestion] RFTools

### ISSUE THREAD

**Issue by zaekeon** [The-1-7-10-Pack/The-1.7.10-Pack#46]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-powerful

This mod provides not only extremely cool teleport and power tools but a technological mystcraft functionality.  You use power to generate dimensions based on items you find/craft and create in sequence.  It also adds some functionality and features that mystcraft does not.

**Comment by zaekeon** [comment]
His post on the FTB forums give more detail on the dimensional builder stuff.  There would be a progression system to find certain resources from the dimensions to create better ones etc.

http://forum.feed-the-beast.com/threads/poll-rftools-dimension-builder-penalties.55720/

**Comment by The-1-7-10-Pack** [comment]
Look here about adding new mods: http://bit.ly/1xPbAl6
For now I will leave it open so other people will be able to comment their opinion. :)

**Comment by zaekeon** [comment]
I apologize.  I was linked to this issue's page to give mod suggestions on the technic discussion page.

**Comment by The-1-7-10-Pack** [comment]
No need to be sorry, I'm just saying that at this point adding new mods to the pack is a bit too much, with 200+ mods. Maybe in the future, but for now I won't add RFTools. :)
