### ISSUE TITLE
Server constantly crashes / closes down

### ISSUE THREAD

**Issue by martyb447** [The-1-7-10-Pack/The-1.7.10-Pack#460]
Hi,

Were experiencing as issue where the server keeps crashing and closing down. It seems to be due to something in a specific location as one of the players moved closer to a certian area and everytime they log in the server instantly closes. tested with another player to check it wasnt an inventory item etc.

Crash report is below,
**EDITED: Please use a paste-tool: http://pastebin.com/C2PLYfwJ**

Weve reinstalled the mod and updated etc and no use.

Any help would be appreciated.

Thanks

**Comment by martyb447** [comment]
Sorry should have said I dont know any coding ect can just about manage the rerinstal of the mod so please, if you can, explain it for an idiot to understand and follow.

Thanks again

**Comment by The-1-7-10-Pack** [comment]
Can you try to (backup and) delete the player's data on your server's save?

**Comment by martyb447** [comment]
Thanks Jon,

Yeah weve done this already, and checked on SP, it seems to be something to do with a physical location..but none of us can get anywhere near it to blow it up, fix etc.

Does the crash report suggest anything?

Thanks again

**Comment by CriticalRocket** [comment]
Does your client crash aswell when this happens?
If so, could you post the client crash logs? (should be 2).

Also, try updating your java (you're on 1.7 but 1.8 is available).

**Comment by martyb447** [comment]
Hi,

Client doesnt crash, just kicks all of us out to the main menu (where we could select the server). Once the server crashes it takes about 5 mins to come back up.
Ill have a look at Java but it isnt just me experiencing this..everyone on server is.Ill update asap.

thanks again guys.

**Comment by CriticalRocket** [comment]
If you know what block(s) is/are causing the problems it's easy to remove them. I just can't see anything pointing to a particular block/item in the world that's causing a problem.

**Comment by The-1-7-10-Pack** [comment]
In general you guys use build v0.7.6a which is not recommended. The good news, is that build v0.7.6b is on progress, and the update might help you.

**Comment by martyb447** [comment]
Hi- thats the problem we dont know which block it is just a vague suggestion we got off another post that it could be something like that. All we know is if anyone goes near a spot (very large area) the server crashes...and since were all already in the spot we cant do anything without wiping the server. 

Added two older crash reports incase they show anything - again appreciate this takes time to read so thanks again

http://pastebin.com/Q2kMdDzU

http://pastebin.com/LEFq8wgr

**Comment by martyb447** [comment]
Cheers Jon,

We were running 0.7.4a when the crashes started....we updated to 07.6a to see if it would fix it...it didnt

**Comment by The-1-7-10-Pack** [comment]
That's problematic guys, if so. When this thing happen you should revert to a backup.

**Comment by CriticalRocket** [comment]
Well you can easily change the location of the players on your server. If you only crash in a certain area you could find out which area through trial and error, and then make a bedrock wall around the area. Then you can keep your world, you just cant acces a part of it :)

**Comment by martyb447** [comment]
I think well try a backup Jon. Thanks. Still no idea what is actually causing it though so I guess it could just repeat. 
We could wall it off but it seems to be a whole chunk and annoyingly its just to the side of our main town.

Ah well guess its screwed. Thanks for the help guess.

**Comment by Yorick1234** [comment]
If you know what location or chunk is causing your crashed you can also delete the chunk / region / corrupted block with MCedit.

**Comment by The-1-7-10-Pack** [comment]
I hope this kind of stuff will get fixed in v0.7.6b, we just got to wait for Mekanism to fix it's silly bugs.
