### ISSUE TITLE
Texture Problem

### ISSUE THREAD

**Issue by Deathwinng** [The-1-7-10-Pack/The-1.7.10-Pack#461]
Hello. First I got to say that this is the best modpack and I love it! 
Now on the topic. I am playing the modpack with the official Sphax 32x patch and I found couple problems with the textures.

First the front faces of mekanism machines appear with original textures when they are off: 
![2015-04-07_16 52 54](https://cloud.githubusercontent.com/assets/11708611/7024994/314708e0-dd49-11e4-8839-4e95cd62526e.png)
And when they are on, the textures are just fine: 
![2015-04-07_16 52 28](https://cloud.githubusercontent.com/assets/11708611/7025012/552d4c9c-dd49-11e4-9221-af89aba0f6e9.png)

Second. A missing texture for the gas Chlorine (from mekanism mod too): 
![2015-04-07_16 57 36](https://cloud.githubusercontent.com/assets/11708611/7025076/c6567d30-dd49-11e4-87a5-1341bba5e577.png)
![2015-04-07_16 58 09](https://cloud.githubusercontent.com/assets/11708611/7025079/c67a0048-dd49-11e4-817d-b0791bc179a2.png)

And last wrong rendering of the liquid Resonant Ender from Thermal Foundation: 
![2015-04-07_16 51 30](https://cloud.githubusercontent.com/assets/11708611/7025174/5eeb56d8-dd4a-11e4-8d20-0afe12aa6e6e.png) (the side of the liquid you're facing is not displayed)

I don't know if this is only for me, but I decided to post it.
Excuse me for my bad english and keep the awesome work!

**Comment by The-1-7-10-Pack** [comment]
You should comment on the thread of the Sphax resource pack, in http://bit.ly/The-1-7-10-Pack-Sphax, so the creator of it wll be able to fix it. :)

**Comment by Deathwinng** [comment]
Yeah, I was wondering whether to post this here or on the Sphax thread but obviously I made the wrong decision. :D Anyways, I will do as you say. Cheers!
