### ISSUE TITLE
can't connect to own server

### ISSUE THREAD

**Issue by chyling** [The-1-7-10-Pack/The-1.7.10-Pack#462]
Hi, I've got problem between my client and my own server. When I try to login it says :

 Mod rejections [FMLMod:Mekanism{8.0.3], FMLMod:chisel{2.3.9.36}, FMLMod:OpenComputer{1.5.4.11}, FMLMod:gendustry{1.4.9.74}, FMLMod:StevesAddons{0.9.13}, FMLMod:LogisticsPipes{0.8.3.113}, FMLMod:BuildCraft:Transport{6.4.5}, FMLMod:PneumaticCraft{1.6.4-66}, FMLMod:bdlib{1.7.0.68}, FMLMod:aobd{2.5.0}, FMLMod:ProjRed:Integration{4.5.15.75}, FMLMod:ProjRed:Core{4.5.15.75}, FMLMod:ProjRed:Exploration{4.5.15.75}, FMLMod:ProjRed:Transportation{4.5.15.75}, FMLMod:ProjRed:Transmission{4.5.15.75}, FMLMod:BuildCraft:Energy{6.4.5}, FMLMod:extracells{2.2.63}, FMLMod:ttCore{MC1.7.10-0.1.0-67}, FMLMod:ChunUtil{4.2.1}, FMLMod:MekanismGenerator{8.0.3}, FMLMod:IC2{2.2.706-experimental}, FMLMod:ProjRed:Compatibility{4.5.15.75}, FMLMod:ProjRed:Expansion{4.5.15.75}, FMLMod:GalacticraftMars{3.0.11}, FMLMod:ProjRed:Illumination{4.5.15.75}, FMLMod:wailaplugins{MC1.7.10-0.0.1-14}, FMLMod:MekanismTools{8.0.3}, FMLMod:GalacticraftCore{3.0.11}, FMLMod:Botonia{r1.5-172}, FMLMod:BuildCraft:Silicon{6.4.5}, FMLMod:BuildCraft:Builder{6.4.5}, FMLMod:Roguelike{1.3.6.3}, FMLMod:progressiveautomation{1.6.5}, FMLMod:EnderIO{1.7.10-2.2.8.364}, FMLMod:BuildCraft:Core{6.4.5}, FMLMod:neresources{0.1.0.95}, FMLMod:appliedenergistics2{rv2-beta-18}, FMLMod:BuildCraft:Factory{6.4.5}] 

Can anyone help me with this thanks

**Comment by The-1-7-10-Pack** [comment]
You have the wrong version of the modpack and server installed, they do not match.

**Comment by chyling** [comment]
I took the server from this website: www.technicpack.net/modpack/the-1710-pack.453902
and I took The 1.7.10 Pack from Technic Launcher, could you give the link for the server and what to type in the Technic Launcher Thank you

**Comment by CriticalRocket** [comment]
When you launch the technic launcher and browse to the modpack, in the top right side there's a button 'modpack options'. There you can select the modpack version, just match it with your server version and you're good to go :)
