### ISSUE TITLE
You want mod suggesions? Here are some! :D

### ISSUE THREAD

**Issue by CriticalRocket** [The-1-7-10-Pack/The-1.7.10-Pack#463]
Hey!

I think a modpack can always use more mod(s) (suggestions), so here are some ^^

**Minecraft Comes Alive!**
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-0-0-loved-by-millions

*Overview:*
-You can interact with villagers in many ways, such as chatting with them, asking them to follow you, hiring them to do work, giving them gifts, and more!
-Interacting with villagers builds relationships. Get your relationship high enough, and you'll be able to marry a villager.
-Once you're married, you can have children. Children will grow up over time and do many different chores for you.
-Children eventually grow up into adults, who can get married and have children of their own.
You can marry other players and have children in SMP and LAN.
-MCA will change the way you play hardcore mode forever. Playing in hardcore unlocks a small, but game-changing super-secret feature. (not present in recent versions, sorry!)
-There's no loss of original Minecraft functionality. MCA villagers can be traded with, and any modded villagers are not overwritten with MCA villagers.

It doesn't affect the game in a big way, but it does add some, IMO, interesting interactibility between the player and the world, which to me, seems like a lot of fun :).

**The Chocolate Quest:**
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278075-chocolate-quest-mods-for-the-adventurers
*More info here:*http://chocolatequest.wikia.com/wiki/The_Chocolate_Quest_Wiki

Adds what looks like a lot of cool structures and dungeons to the game, giving adventurous people a lot more objectives. Right now for those people you have Twighlight and kindof Galacticraft, but there isn't much reason to go adventuring in the overworld (I've seen some structures but not many with a real purpose to go to).
It seems to be compatible with most mods, and it's dungeons are highly configurable. 

It also has costum HD textures for Sphax BDcraft which you could (if you get permission) just import to your current sphax texturepack for this modpack :) So thats great! (link on the bottom of the wiki homepage).

Another nice feature is that biome mods like Biomes 'O Plenty are supported by The Chocolate Quest, so there shouldn't be any problems using it in the modpack as far as I can see :).

**TIME TRAVEL!**
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1440781-timetraveler-real-time-travel-inside-of-minecraft

Looks like fun, haha :p Very complicated mod which I think has 0% chance of getting added to the modpack, but I just wanted to show it because I think it's really awesome.

**Advent of Ascension**
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286381-advent-of-ascension-16-new-dimensions-250-mobs

Wiki for this mod is down atm, so I couldn't find much info about it. At first glance it looks amazing, but depending on how the dimensions, but in particular skills are added, it might be kindof total-conversionny so not everyone might like it. Seems awesome though.

**Aether II:**
I remember the Aether from when I last played minecraft, like a year ago. I remember it being one of the most amazing mods I ever played. I don't know what happened to the mod, but I just did a quick search and saw it's still active and updated to minecraft 1.7.10 :)  Is there any reason not to implement it? Because IMO it's really awesome!

That's all for now :p I'll be searching for more!

Personally I especially like the Chocolate Quest mod :)  (I'd just like some more big/adventurous mods :p)

~CriticalRocket

**Comment by CriticalRocket** [comment]
Any thought on these mods? :p

**Comment by DakarMix** [comment]
I really would like Minecraft Comes Alive! and The Chocolate Quest to be added on this modpack, that will be great.

**Comment by The-1-7-10-Pack** [comment]
- Minecraft Comes Alive is a game changer and not everybody would like it.
- Chocolate Quest has it's own suggestion here, and it stays open for now there, so maybe.
- TIME TRAVEL, ARE YOU CRAZY?
- Advent of Ascension & Aether II: These mods are for adventure only modpacks, they do not fit.

Thanks anyway for suggesting :)
