### ISSUE TITLE
Weird World Loading?

### ISSUE THREAD

**Issue by ZombieTG** [The-1-7-10-Pack/The-1.7.10-Pack#464]
So i was playing on my server and this happened... 

It seems half of the tree has replaced its leafs with enchantment tables? I thought I'd just share this, i didn't put it there it just generated itself. This can't be part of the mod pack obviously xD ? I even mined the block and it dropped the enchantment table so it wasn't a graphical glitch or something. Is the world corrupted or something :/ 

![2015-04-07_21 32 28](https://cloud.githubusercontent.com/assets/11707627/7032959/585e1e80-dd6e-11e4-91f9-15aa6a23e683.png)
![2015-04-07_21 32 35](https://cloud.githubusercontent.com/assets/11707627/7032960/585e373a-dd6e-11e4-9b18-9e43e8bf2581.png)
![2015-04-07_21 32 40](https://cloud.githubusercontent.com/assets/11707627/7032961/58627912-dd6e-11e4-9fe2-d6b1e1ba609f.png)

**Comment by The-1-7-10-Pack** [comment]
Wha?
When did it happen? Did you update your modpack's version? What is this save?
It's not a conflicting id if only half of the tree, when all of it is made of the same kind of leaf, changed.

**Comment by ZombieTG** [comment]
I think this is a new world in the 0.7.6a update, i think o.o

This happened like literally as i posted this - I was exploring new areas and then i found it :p

**Comment by ZombieTG** [comment]
Also the ice in the picture is also a tree that was half ice and also the logs was turned into coal blocks o.o

**Comment by The-1-7-10-Pack** [comment]
Do you have any additional mods? Again - I need your latest game log.

**Comment by ZombieTG** [comment]
No, no additional mods. I tried uploading my log to pastebin but the content is too large so it won't upload

**Comment by The-1-7-10-Pack** [comment]
Use [this](http://paste.ubuntu.com/) paste-tool please.

**Comment by ZombieTG** [comment]
"413 Request Entity Too Large" When i try to "paste" it D:

**Comment by The-1-7-10-Pack** [comment]
Just upload the log file and put the download link here.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
