### ISSUE TITLE
Rebalanced quests

### ISSUE THREAD

**Issue by KreepyKreeper01** [The-1-7-10-Pack/The-1.7.10-Pack#466]
i have been looking at the quests. they are not rewarding at all. they make you do things like create a bunch of items that you wouldn't ever need the amounts that it is requiring but it then gives a small portion of what it required to make, if not, a reward bag. And also it makes you create large amounts of one item, but makes you create small amounts of another that is needed for it to run smoothly (im looking at you, power forever quest.). Personally, i believe in quality over quantity. but for this modpack there is very little of either in its quests. i do like the hardcore questing mod but it is misused in this pack. i do love this pack for the adventure, building, and everything else it has to offer but the more i play it the more i dislike its quests.

**Comment by The-1-7-10-Pack** [comment]
How do the reward bags not rewarding? Try to get some from creative and open them, see what you get.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.

**Comment by KreepyKreeper01** [comment]
ok

**Comment by KreepyKreeper01** [comment]
thx

**Comment by KreepyKreeper01** [comment]
Im used to skyblock though

**Comment by KreepyKreeper01** [comment]
and my main problem isn't the rewards but the items needed, they just aren't balanced

**Comment by KreepyKreeper01** [comment]
also i cant seem to find what type of reward bag is in the quests

**Comment by KreepyKreeper01** [comment]
i got nano suit from good so i have been working to it in my survival and my argument would be false (except for balancing but with this mod it is only truly needed for skyblock) so how many of each should i be expecting?
