### ISSUE TITLE
Chisel - block has no texture - causing a crash - corrupts world probably

### ISSUE THREAD

**Issue by CriticalRocket** [The-1-7-10-Pack/The-1.7.10-Pack#468]
Hey!

I was mining yesterday, and I came across a chisel block without texture, showing the error texture (4 squares on each side, of which 2 purple and 2 black).

I didn't think much of it so I mined it, it dropped with the same error texture and I moved on.
Some time later I suddenly crashed, and now I can't get back into my world.

I don't remember at what time this happened, but I've got 1 backup each hour. So I tried each of these in SSP, and each of these spawns me with 'you are death' on the location where I stood when I mined this block. I can see the on the background block in the 'death' screen, back in place. I remember certainly playing more after mining the block, and I don't remember dying there.

My friend continued playing a bit after that yesterday whilst I was looking for a fix, and he played a bit whilst I was at school. So I just tried entering the most recent version of the world in SSP, and that world I can't enter at all, it just crashes my game. That happened with my worlds yesterday as well, but now each of my backups atleast allows me to enter the world. 

So you'd think "hey, you can enter your backup world, you died, just go get your items and load the backup!". Well, I just tried getting my items but my world crashed when I got into a like 5 block range of the 'corrupted' block. Going to try again in a bit. 

Logs of my backup world crash:
-client.txt: http://pastebin.com/faYWrWT5
-server.txt: http://pastebin.com/SQGtiuXn
(also, my client sometimes gives me a -server.txt error log.. I dont know how why.. but its different from my -client.txt error log)

Log of my most recent world, which crashes at loadup:
-client.txt: http://pastebin.com/MTEfVZr7
no server.txt error log.

I'm not sure on how to tackle this problem. I tried finding the block with an NBTeditor but I couln't find it, I don't know where block data is located.

Any help is greatly appreciated!

~CriticalRocket

**Comment by CriticalRocket** [comment]
Oke, so I tried out some stuff.

-I've got Aroma configured to make a backup when I stop the server. I stopped the server when I came home a few hours ago. 

When I load the world directly from my server into SSP I crash at spawning.
When I load the world from the backup I don't crash! 

Thats weird because it should be exactly the same :/
The way I crash on the server world is weird aswell.
When I load the world, after a while it goes back to the main menu, stays there for 0.5 seconds, then goes to black screen, and then I enter the world. I see a black screen with an empty toolbar and an empty minimap, and then it crashes.


When I load the backup I spawn in a location I wasn't at at first, as I said in my first post, it's where I stood when I mined the corrupted block. Well, I 'spawn' there, I'm instantly dead, or I was dead just before the backup was made, I'm not sure. I only know that I get the 'respawn' screen on loadup.

When I respawn and walk to the location, everything is fine. But when I look at the block, as in, aim at the block, I crash. Maybe it has something to do with the block tooltips? (block name and 'can I mine it yes/no' information on top of the screen). 

http://i.imgur.com/on8JBoa.png
http://i.imgur.com/fFwJMQS.png

I don't know what the cause of this is, but it wasn't happening yesterday..

I'm going to try and blow the block up with some TNT. I don't remember which kind of block it is exactly, and I cant mine it or anything to find out now. I only remember that it was from the Chisel mod, and I remember coming across another block with the same error texture yesterday aswell, like 5 - 10 minutes after I found this one.

P.s. as you can see I'm using default minecraft textures. I was using optifine yesterday when I first crashed, but I removed it afterwards.

**Comment by CriticalRocket** [comment]
Fixed my world :) Still a very weird bug though!

**Comment by The-1-7-10-Pack** [comment]
No idea at all. Update me if there's anything new in the issue you opened there. Closing it for now.
