### ISSUE TITLE
I can't start

### ISSUE THREAD

**Issue by chyling** [The-1-7-10-Pack/The-1.7.10-Pack#469]
Hi, my friends are trying to launch the modpack through Technic Launcher, but when they click play the application try to start but goes back to the Launcher.

They have:
Windows 8 64bit
Java 64bit (both java 7 and 8 have been tried)

What have been tested:
Tried to delete modpack totally from the folder and reinstalling => got the same problem
Tried to allocate more memory for java
Tried to reinstall the Launcher then the modpack, same problem
Tried to change the version of the modpack, same problem with all of them(but we would really like to have 7.6a)
Tried to copy my working the-1710-pack file to their computer, nothing changed
Tried to copy my whole working .technic file to their computer, everything was not working so we cancelled that.

Here is the log one of them got:

**EDITED: Please use a paste-tool: http://pastebin.com/J95W90nC**

Thank you for all you answer and sorry for my English, I'm French

**Comment by The-1-7-10-Pack** [comment]
First of all, I'm happy to see people from Frech :)
Second of all, when you say "friends", I can't tell you that they all got the same problem in their system. One can have Java 6 and it won't work, one can have Java with 32 bit and it won't work.
If you guys really want help I'll have to ask you to get me each one's log and we'll see his problem, but please check that you **don't have Java 6, or any version of Java with 32 bit**.

**Comment by chyling** [comment]
like I said at the beginning of my post

They have:
Windows 8 64bit
Java 64bit (both java 7 and 8 have been tried)

What have been tested:
Tried to delete modpack totally from the folder and reinstalling => got the same problem
Tried to allocate more memory for java
Tried to reinstall the Launcher then the modpack, same problem
Tried to change the version of the modpack, same problem with all of them(but we would really like to have 7.6a)
Tried to copy my working the-1710-pack file to their computer, nothing changed
Tried to copy my whole working .technic file to their computer, everything was not working so we cancelled that.

Both of them have this and the log I posted is the log of one of them. I couldn't get the log for my other friend yet, but if I can at least solve the problem of one them that will be great

**Comment by The-1-7-10-Pack** [comment]
They need to go to the launcher, Launcher Options, Java Settings, and see that they are indeed using the currect version of Java.

**Comment by chyling** [comment]
it only show how much memory they are using, is there anything they have to input in the textbox below?

**Comment by chyling** [comment]
any solution?

**Comment by rage2424** [comment]
Same problem???? PLEASE HELP!!

**Comment by The-1-7-10-Pack** [comment]
Guys I need your launcher logs to know exactly what is wrong in your systems. Check that you have Java 7/8 and 64 bit.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
