### ISSUE TITLE
crash at startup of the game (coredump) and crash on loginscreen minecart sounds

### ISSUE THREAD

**Issue by darkfiretime** [The-1-7-10-Pack/The-1.7.10-Pack#47]
i hoop some one can help me with this. i have tried ram alocation manualy from 1 to 4 gigs in java it self as well as the mod pack launcher changed memory dump from kernel to 256kb even did the no dump option nothing works. can some one help me with this ?? 

pastebin.com/EUutXhHx

**Comment by The-1-7-10-Pack** [comment]
What is your Java and System information?

**Comment by darkfiretime** [comment]
just installed the java se dk 7u71 seems to run without the coredump error so far. now i just keep crashing when my character spawns in the server

**Comment by darkfiretime** [comment]
removed modpacks manualy and that seemd to fix the problem. i was able to get in the game again

**Comment by darkfiretime** [comment]
the mod pack hardly worked for me. about 15 min and then it crashes. plus when i want to see the recipe for tool bindings it crashes me as well ather mods like atack of the bteam i dont have this problem. maybe once a day sometimes no error at all

**Comment by darkfiretime** [comment]
manualy removing the deleted mods from the mods folder like listed on the removed mods section of the server didnt work either
only made it worse :P

**Comment by darkfiretime** [comment]
completely removed java several times including the temp files and hidden dll files reinstalled everything again. fail  
the same with the launcher and the mod packs. fail
allocating difrent sizes of ram to java minecraft main and the launcher. no effect

**Comment by darkfiretime** [comment]
update im ingame now havent crashed so far il send the next crash report if it dus . its still unstable sinds i never know when i crash becaus of the core dump error

**Comment by darkfiretime** [comment]
still getting coredump errors i realy dont know what might be wrong with this. literaly every single setting i have found so far has been changed and they all have the same outcome 

pastebin.com/1PcNakJ5

**Comment by darkfiretime** [comment]
did you perhaps found anything un usual in the reports that i can change for the mod to run smoothly ?

**Comment by The-1-7-10-Pack** [comment]
I am not sure, something is diffrent on your system. Can you play other modpacks no problem?

**Comment by darkfiretime** [comment]
no problem on ather minecraft mods now 
the problem seems to be reduced by somthing idk what though but now i can atleast get in game afther 5 atempts instead of 20 atempts and still not ingame :p. the problem is still in my system somewhere though. i just cant find it

**Comment by The-1-7-10-Pack** [comment]
There's nothing I can help in this situation, I don't have enough information.
