### ISSUE TITLE
I can't launch.

### ISSUE THREAD

**Issue by Byshup** [The-1-7-10-Pack/The-1.7.10-Pack#471]
I downloaded the mod  it on technic and when I hit 'play" it just brings me back to the technic launcher, please help.

**Comment by rage2424** [comment]
same with me someone help Please!!!?!?!?!

**Comment by The-1-7-10-Pack** [comment]
Probably the wrong version of Java. I need your latest launhcer log to be sure, but please double check that you have Java 7/8 and 64 bit version of it.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
