### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by LoseThePlot** [The-1-7-10-Pack/The-1.7.10-Pack#472]
There is an argument in the Modpack.jar in bin (install directory) which results in a constant memory allocation being set, ignoring what is in the technic launcher memory allocation. This is all well and good for standard texture packs but becomes a pain when using the Sphax Patch which uses about 6GB. The Argument is set to 3GB. 

The argument in question is "XmX3000M"  removing it completely allows the techniclauncher value to be used. This is the cause of most crashes ive seen. Can the modpack author remove this line as it causes a right heartache removing it each time...

Thanks! LTP

**Comment by TheFarseer** [comment]
OH GOD YES PLEASE

God I was going nuts trying to figure out what was messing with the ram

**Comment by The-1-7-10-Pack** [comment]
This is set for people that don't know that the modpack needs minimum of 3 GB to run. With Sphax 64x I am able to run the modpack with 3 GB allocated and 70% of it used, you don't need 6 GB in any way. This will be like that until Technic will finish their system of making a minimum RAM amount, will be really soon! So just wait a bit, that's all :)

**Comment by LoseThePlot** [comment]
Using sphax 64 without the patch mine can run in under 3G. Using the patch... It uses 6G

**Comment by The-1-7-10-Pack** [comment]
@LoseThePlot This is not accurate at all, but it's going to change soon anyway, so there's not much to talk about.
