### ISSUE TITLE
How to enable spawn protection.

### ISSUE THREAD

**Issue by Malorn44** [The-1-7-10-Pack/The-1.7.10-Pack#473]
How would I enable spawn protection on a server for this modpack via the server.properties? I tried spawn-protection=100 and that didn't work. Apparently it reads it as a boolean so i tried doing spawn-protection-size=100 and spawn-protection=true but that didn't work help please.

generator-settings=
spawn-protection-size=100
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=false
announce-player-achievements=true
server-port=25565
level-type=BIOMESOP
max_minion_spawn=-1
enable-rcon=false
force-gamemode=false
level-seed=5146175393340513075
server-ip=
max-build-height=256
spawn-npcs=true
white-list=true
spawn-animals=true
snooper-enabled=true
hardcore=false
online-mode=false
resource-pack=
pvp=true
difficulty=1
enable-command-block=true
player-idle-timeout=0
gamemode=0
max-players=10
spawn-monsters=true
view-distance=10
generate-structures=true
spawn-protection=true
motd=\u00A7cMalorn's 1.7.10 Pack Server

**Comment by Malorn44** [comment]
anyone?

**Comment by CriticalRocket** [comment]
Spawn-protection=100 should work. Default is Spawn-protection=16 and that always works on my servers.

**Comment by The-1-7-10-Pack** [comment]
You need to not be OP and it work.
