### ISSUE TITLE
What is the official server IP?

### ISSUE THREAD

**Issue by snoopiey** [The-1-7-10-Pack/The-1.7.10-Pack#475]
Basically, the title explains it. I'm kind of new to this whole technic thing but I saw someone post on the platform about an official server, and then I saw the creator of the mod pack telling people to post here with questions, so here I go. Unless there isn't one and I'm just very confused.

**Comment by The-1-7-10-Pack** [comment]
Thank you for going here, this is the official place for any kind of support for The 1.7.10 Pack. Anyway, there is not official server for the pack (yet?), so obviously there's no IP. :)
