### ISSUE TITLE
Error updating to modpack 0.7.6b

### ISSUE THREAD

**Issue by DakarMix** [The-1-7-10-Pack/The-1.7.10-Pack#476]
When updating this error occurred:

![error](https://cloud.githubusercontent.com/assets/11905609/7103681/5c9abb78-e081-11e4-8566-0e8f6b2fc819.png)

**Comment by The-1-7-10-Pack** [comment]
Should be fixed now, thanks for reporting.

**Comment by DakarMix** [comment]
Working perfectly right now, thanks for the quick response and for the great modpack :+1: :P

PD: There is a bug with the obsidian armor from Mekanism Tools and the Echanthing Plus that you can enchant the amor for just 1 echanting cost (exept the boots)
