### ISSUE TITLE
Optifine.

### ISSUE THREAD

**Issue by snoopiey** [The-1-7-10-Pack/The-1.7.10-Pack#477]
Hi. On the technic platform in the Overview tab, near the lower part of the page it says "Optifine is recommended and I was wondering how I could install it? All the videos I have searched up only explain how to install it for regular minecraft. If you are unable to explain it, but you know a good video that explains it well, please link it.

**Comment by The-1-7-10-Pack** [comment]
It's super simple. Go to [Optifine's website](https://optifine.net/downloads), and download the latest version for Minecraft 1.7.10. Then, get the jar you just downloaded and put it in the "mods" folder, in the modpack's folder.
Good luck!
