### ISSUE TITLE
Mekanism & EnderIO Integration issue

### ISSUE THREAD

**Issue by Dommain** [The-1-7-10-Pack/The-1.7.10-Pack#479]
I do not know  the real cause yet bu it might because I put speed and energy upgrade into the ElectrolyticSeparator (882,80,855) in version 0.7.6a had anything to do with it. It crashes the game upon load of the save game. I will open up fine in 0.7.5.

http://pastebin.com/ptPxyJ3j

**Comment by The-1-7-10-Pack** [comment]
It's super simple. Go to [Optifine's website](https://optifine.net/downloads), and download the latest version for Minecraft 1.7.10. Then, get the jar you just downloaded and put it in the "mods" folder, in the modpack's folder.
Good luck!

**Comment by The-1-7-10-Pack** [comment]
This shouldn't happen, EnderIO said they support Mekanism 8 API for gas and everything. Did it work in 0.7.6a or not?

**Comment by Deathwinng** [comment]
I gotta say i have problem with EnderIO gas conduits too. It connects with some machines but Minecraft crashes when I try to connect it with Chemical Injection Chamber for instance.

**Comment by The-1-7-10-Pack** [comment]
That's so annoying! The integration between EnderIO & Mekanism..God.
Please you guys try out the latest dev build of EnderIO from [here](http://ci.tterrag.com/job/EnderIO/), tell me if everything works.

**Comment by Deathwinng** [comment]
I tried that build and it's not crashing animore, but some conduits are not connecting to each other. 
![2015-04-12_13 50 12](https://cloud.githubusercontent.com/assets/11708611/7105310/00c4aa76-e11b-11e4-9d3d-224b20c0884f.png)
Weird things happeing. :D

**Comment by The-1-7-10-Pack** [comment]
@Deathwinng And you can't reconnect them?

**Comment by Deathwinng** [comment]
My bad, they connect but you have to connect them manuali, with a wrench.

**Comment by The-1-7-10-Pack** [comment]
@Deathwinng Do you see more weirdness or do you think we can include this build of EnderIO in an official patch?

**Comment by Deathwinng** [comment]
For the past 1 hour I played a bit with gas, energy and item conduits and I didn't saw anything wrong with them. I think it's better connect-with-wrench conduits than a minecraft-crashing conduits. :)
So yeah, I think you should include this build in the next patch.

**Comment by The-1-7-10-Pack** [comment]
@Deathwinng Okay, great, update me about anything, if no bad news expect the new update to come tomorrow.

**Comment by Deathwinng** [comment]
:+1:

**Comment by Dommain** [comment]
I'll start testing my side. I have a massive chunk with every connection possible with ender IO and mekanism.

**Comment by Dommain** [comment]
EnderIO-1.7.10-2.3.0.372_beta.jar
Description: Ticking block entity
blockVatTileEntity
http://pastebin.com/dtLdGJWm



EnderIO-1.7.10-2.3.0.371_beta.jar - Stable for me even had hardly any lag spike with ender IO conduit connecting unfinished solar evaporation (salination plant)

**Comment by The-1-7-10-Pack** [comment]
@Dommain Can you report this crash on there? https://github.com/SleepyTrousers/EnderIO/issues

**Comment by The-1-7-10-Pack** [comment]
We'll wait for .373.

**Comment by The-1-7-10-Pack** [comment]
Still waiting, update may be out only tomorrow.

**Comment by GroeneAppel** [comment]
Welp, I should have read here before updating the server. 

Time: 13/04/15 22:45
Description: Ticking block entity

java.lang.AbstractMethodError: crazypants.enderio.conduit.TileConduitBundle.receiveGas(Lnet/minecraftforge/common/util/ForgeDirection;Lmekanism/api/gas/GasStack;Z)I
	at mekanism.common.tile.TileEntityElectrolyticSeparator.onUpdate(TileEntityElectrolyticSeparator.java:227)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Guess i'll keep the server down till tommorow.

**Comment by The-1-7-10-Pack** [comment]
@GroeneAppel Well, sorry for that, but it's not in our control, it's just the waiting game (:

**Comment by RakovKreviech** [comment]
Hello comrades, i'm having issues with the mekanism mod, everytime i type "Mekanism" in NEI my world crashes and then i have to reboot my computer.I would appreciate if someone could help me.

**Comment by Dommain** [comment]
@RakovKreviech What version of 1.7.10 pack?

**Comment by RakovKreviech** [comment]
@Dommain The new version, 0.7.6b.

**Comment by The-1-7-10-Pack** [comment]
@RakovKreviech Should be fixed in the new update we're expecting to get, 0.7.6c. :)

**Comment by RakovKreviech** [comment]
@The-1-7-10-Pack I appreciate it, thanks a lot. :D
