### ISSUE TITLE
Possibilities for the Server

### ISSUE THREAD

**Issue by KLuebbert** [The-1-7-10-Pack/The-1.7.10-Pack#48]
Here's a list of ideas.

-An official shop that sells basic Minecraft blocks and items

-Ideas for protections in the future:
Worldguard (Wand)
Towny (Towns)
Grief Prevention (Gold Shovel)

-Ability for players to make their own official shops

-Maybe giant statues at spawn of staff and owners (For decoration, and to show the staff/ owners)

-A mod suggestion for the pack: Statues Mod:
http://minecraft-forum.net/minecraft-mods-downloads/1-7-2-statues-mod-download/#.VKxYSHk5CUk

This mod just adds statues to Minecraft. No guns, magic, armor, nothing that will change gameplay, just something appealing and fun like Carpenter's Blocks, but much more basic. This mod adds Statue paint, a Statue Chisel, and that is about it.

**Some of these ideas are not as vital  at the moment, like solving bugs and issues with the pack and server, so take as much time as you need regarding these ideas. I just thought of these to add more ideas to the idea pool, and more suggestions to make the server and modpack a better place.**

**Comment by KLuebbert** [comment]
Oh! I'd also like to add:

-Official places to vote for the server (If not already done, if so, give me the links please!)

**Comment by Flukethoughts** [comment]
-Ideas for protections in the future:
Worldguard (Wand) there isn't plugins on the server
Towny (Towns)only supports 1.6.4
Grief Prevention (Gold Shovel)not a plugin server

**Comment by BlackJackAres** [comment]
Hi there, Staff here;

-An official shop that sells basic Minecraft blocks and items
This is in the works, we're just working on performance first.

-Ability for players to make their own official shops
Ill talk to fluke about it.

-Maybe giant statues at spawn of staff and owners (For decoration, and to show the staff/ owners)
There are already statues in the pack.

-A mod suggestion for the pack: Statues Mod:
This is already added. Fluke uses it.

-Official places to vote for the server (If not already done, if so, give me the links please!)
Will also talk to fluke about it after our core work is done.

**Comment by KLuebbert** [comment]
Oops, didn't know the Statues mod was in the pack.

Also, when I said giant statues of the staff at spawn, I meant something like this:
http://dev.bukkit.org/media/images/63/479/2013-10-03_11.19.39.png

I also have one concern. If you don't operate plugins, aren't all protections operated by plugins? How will the protections work without plugins? =P Do you plan on adding a mod that enables protections to the pack if that exists, or is there another thing like plugins I don't know about? Because I have no clue how servers operate.

Also, I had more ideas, but once I got out of school, my memory got wiped and replaced with homework, so I forgot them. I'll think of them again later.

**Comment by Tesseractual** [comment]
I've always thought Traincraft was a cool mod for adding fluff to the world. Can't speak to it's stability but it may be worth an addition:

www.traincraft-mod.com/Traincraft/traincraft.html

**Comment by KLuebbert** [comment]
The modpack does have RailCraft, but it seems Traincraft is a little more specific on trains than RailCraft is, like it should... Could be interesting. (By the way if I ever say mudpack, it's because my pc uses auto correct only when I don't want it to, and it auto corrects modpack into mudpack!)

**Comment by The-1-7-10-Pack** [comment]
Thank you for the suggestions, for now I'm closing this one.
