### ISSUE TITLE
Applied Energistics problem

### ISSUE THREAD

**Issue by Deathwinng** [The-1-7-10-Pack/The-1.7.10-Pack#481]
Hi, I have a little bug with my applied energistics network and I feel like, I should report it. When I load my world and open my ME network I can see all the stuff in there but I can't take out or put in anything and crafting terminal appear like normal terminal, without the crafting grid. And the thing that doing all this is the Security Terminal. When I break it an place it down again everything is fine once again. It's not big problem it's just annoying to do it every time I play.
In version 0.7.6b I discovered another Applied Energistics related bug. I have my Modular Powersuit Power Fist with ME wireless terminal module, but when I try to use it, Minecraft just crashes.
[Crash Report](http://paste.ubuntu.com/10807607/)

Thanks in advance!

**Comment by The-1-7-10-Pack** [comment]
The Powersuit thingy is related to the actual power suit mod user an old API, it will get fixed.
For the first bug you should go to the GitHub page of AE2 because it's nothing that I can control.
Thanks anyway :)

**Comment by Deathwinng** [comment]
I see, thanks for the info. :)
