### ISSUE TITLE
Server Seems to contain 0 Diamonds!

### ISSUE THREAD

**Issue by Malorn44** [The-1-7-10-Pack/The-1.7.10-Pack#482]
So my friend has been looking for diamonds for several hours and we have yet to find one. We are running a server using 0.7.6a and we really need to find some diamonds and NO... I am not spawning anything in.

**Comment by TreePuncher9501** [comment]
...This can be the result of sheer unluckiness. Manually dig a quarry, 16x16 and you should find at least 1 vein. If not, then it's an issue.

**Comment by The-1-7-10-Pack** [comment]
Click "R" On the diamond ore in NEI, do you see the recommended levels to find diamonds?

**Comment by Malorn44** [comment]
I know where diamond are usually found level 10-16 usually but we have been looking for like 4 hours and we have come across nothing

**Comment by Malorn44** [comment]
But since you are the creator of the modpack I guess you probably have tested this so unless anything else comes up we will keep looking

**Comment by Dommain** [comment]
there is a rare chance a random seed would make certain zones produce nothing of certain types of ores.

**Comment by The-1-7-10-Pack** [comment]
Closing this one :)
