### ISSUE TITLE
Some crashes

### ISSUE THREAD

**Issue by Jofkos** [The-1-7-10-Pack/The-1.7.10-Pack#483]
My Game is crashing quite often running the new Version of this Modpack (0.7.6b)
Here are two common crash reports: [Game Crash](http://pastebin.com/31Pw1RkQ) | [Game Crash 2](http://pastebin.com/ibXbyhvB) | [JVM Crash](http://pastebin.com/qCuN6MX6)

I don't know if it's the modpack or my Java/my PC but it would be nice if i could play without crashes...

**Comment by The-1-7-10-Pack** [comment]
Remove Optifine..
At this point I may stop recommending people to install it.
It helps for FPS but I don't want people to crash....
