### ISSUE TITLE
Server crash updating to 0.7.6

### ISSUE THREAD

**Issue by Silvarald** [The-1-7-10-Pack/The-1.7.10-Pack#484]
Any server version over 0.7.6 will launch fine, but if I try to use my existing world folder, it will crash on start up.

Crash report: https://gist.github.com/Silvarald/7599d4df5f71587e3cb1

Any help would be greatly appreciated. Thanks.

**Comment by The-1-7-10-Pack** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/479

**Comment by Silvarald** [comment]
That seemed to work. Thanks.
