### ISSUE TITLE
Portals In Extra Utilities

### ISSUE THREAD

**Issue by coolside** [The-1-7-10-Pack/The-1.7.10-Pack#485]
The Portals to the Deep Dark and The Last Millennium are not working. Any Ideas?

Thanks

**Comment by The-1-7-10-Pack** [comment]
The portal to the deep dark should work, but it's known that we are not using the latest version of Extra Utilities as it requires a problematic version of Forge.

**Comment by coolside** [comment]
Ok will wait for update.  Will try deep dark again.

cheers

**Comment by The-1-7-10-Pack** [comment]
Deep dark also not working?! We'll revert.

**Comment by viesiu** [comment]
Apparently, there's some conflicts with Galacticraft: https://github.com/rwtema/extrautilities/issues/553

**Comment by The-1-7-10-Pack** [comment]
@viesiu v1.2.2 of Extra Utilities do work, can't blame Galacticraft. We'll revert and everything will be fine.

**Comment by viesiu** [comment]
1.2.2 works, but it doesn't have Last Millenium in it ;p Whether it's an issue with EU or GC doesn't rly matter to me. The fact is, both portals work just fine w/o Galacticraft installed ;)

**Comment by Dommain** [comment]
@viesiu Better not blame Mars or the asteroid field on this one.

**Comment by KreepyKreeper01** [comment]
also last millennium is not working for me :(

**Comment by The-1-7-10-Pack** [comment]
@KreepyKreeper01 We're aware. It's the mod's problem.

**Comment by draeath** [comment]
This is fixed by installing Player API as -instructed- on the Galacticraft compatibility wiki page. Links:
http://wiki.micdoodle8.com/wiki/Compatibility#Any_other_mod_with_.27Fake_Player.27_detection
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996

**Comment by Deathwinng** [comment]
Tried. Minecraft [crash](http://pastebin.com/hKyZc8J7). Also the crash has something to do with Mekanism.
