### ISSUE TITLE
Ender IO conduits/ Waila

### ISSUE THREAD

**Issue by Canuck117** [The-1-7-10-Pack/The-1.7.10-Pack#486]
Ender IO energy conduits do not display there contained energy, and ME conduits do not display their channels.  With one of each in the same block space, the ME conduit displays the energy contained in the energy conduit, but still not the channels.

**Comment by Canuck117** [comment]
![2015-04-13_03 56 59](https://cloud.githubusercontent.com/assets/7751306/7112008/6ae62bc8-e193-11e4-9d14-de15b6445071.png)

![2015-04-13_03 57 26](https://cloud.githubusercontent.com/assets/7751306/7111954/221484bc-e193-11e4-97a7-179bc483ce3f.png)
![2015-04-13_03 57 38](https://cloud.githubusercontent.com/assets/7751306/7111956/22216ff6-e193-11e4-8d2c-a81f603d8ee5.png)
![2015-04-13_03 57 40](https://cloud.githubusercontent.com/assets/7751306/7111955/221adc18-e193-11e4-8ff9-8e3cb1322dc1.png)

**Comment by The-1-7-10-Pack** [comment]
In the configs everything is true. It may be a problem from Waila's side, or EnderIO's side, but it's not a bug in the modpack.

**Comment by The-1-7-10-Pack** [comment]
I see that the problem is from EnderIO's side and it got reported already, It'll get fixed soon!
