### ISSUE TITLE
AE2 In v0.7.6b

### ISSUE THREAD

**Issue by kilps31** [The-1-7-10-Pack/The-1.7.10-Pack#487]
The first problem is my quantum links have stopped working and i can't figure out why. I have tried rebuilding them, putting in new cores, changing how they are powered, and nothing links them again.
The second problem happens when i use my power fist to wirelessly access my ae network the game crashes and tells me there was an internal server error.

is something wrong with ae in this update?

**Comment by The-1-7-10-Pack** [comment]
We jumped 10 builds of AE, which means that the API of it has changed a lot, and we're waiting for a fix to come from the Modular Powersuits mod, nothing we can do for now.
About the Quantum Links: This shouldn't be like this. I need to check myself, but maybe you just derped with something.

**Comment by kilps31** [comment]
update: i think the problem is with mekanisms universal cables.  I have them hooked to a reactor from BigReactors and if i have too many cables hooked up my reactor wont power them.

**Comment by The-1-7-10-Pack** [comment]
Since the Mekanism update you can try to brake and put again all the cables. Also check for redstone touching them anywhere, it'll disable them. So there's no problem with AE2 itself. Closing this one.

**Comment by kilps31** [comment]
thank you!
