### ISSUE TITLE
The name of the pack makes creating or finding a server especially a pvp server impossible.

### ISSUE THREAD

**Issue by foulblade1** [The-1-7-10-Pack/The-1.7.10-Pack#488]
The name of the pack makes creating or finding a server especially a pvp server impossible. While searching the web i can only find 1.7.10 modpacks and server's that are not yours. The keywords just show 1.7.10 minecraft is their any way you can change the name to something more unique or something that is more easy to search ?

**Comment by The-1-7-10-Pack** [comment]
Well that's just too bad.

**Comment by foulblade1** [comment]
its to* too means like also. An fine want to be a #*#$ ill just remake your pack and fix all the glitches my self with a different name. Was just trying to help you an others
