### ISSUE TITLE
Ingame Lags

### ISSUE THREAD

**Issue by chillmaster** [The-1-7-10-Pack/The-1.7.10-Pack#49]
Hello together,
i have already Problems with Hardcore Lags in this Modpack on my Multiplayer Server.
I already have written in Forum as djplay90.
Here the latest.log
http://paste.ubuntu.com/9689923/
What can i do?
1 Core of my 8 Core Root Server is every time at 100%
The other cores are doing nothing. 
The Server has 32GB RAM.
What is here the Problem?

**Comment by The-1-7-10-Pack** [comment]
This is a server overload.
What version of the modpack are you using?
Also, do you have any additional mods?

**Comment by Flukethoughts** [comment]
Doesn't matter if you have an 8 core you understand this right?

**Comment by chillmaster** [comment]
Every time when the Server is still online the Warnings are coming and the Server is lagging.
I haven´t other Mods installed and i use the 0.6.1 Version of the Modpack. 

My Server Specs:
CPU: Intel Core i7-3770 (3.4 GHz)
RAM: 32GB RAM
OS: Debian Linux

**Comment by chillmaster** [comment]
![auslastung](https://cloud.githubusercontent.com/assets/10364172/5661500/d1f4734e-972c-11e4-8002-5d42be47c4d5.PNG)

**Comment by The-1-7-10-Pack** [comment]
When did you start to play? in what version? and when did the overload started?

**Comment by chillmaster** [comment]
I startet in Version 0.4.8 i think. And the Problems are coming between 0.5.3 or 0.5.5. 
We are 3-4 Players. 
Only 2 Players are playing very often. The other 2 Players plays only 15-20 Minutes on day.
The warning comes always, even when no one is on the server.

**Comment by The-1-7-10-Pack** [comment]
Just an option: Try to remove "NoMoreRecipeConflict-0.2(1.7.10).jar" - is it helping?

**Comment by chillmaster** [comment]
I deleted the mod and the server is still overloaded.
It isn´t helping.

**Comment by Flukethoughts** [comment]
There are far to many mods in the mod pack start trimming I have explained this to john countless times.

**Comment by The-1-7-10-Pack** [comment]
Maybe something in your world. Try to open a new world, and play a bit, and check if the server is still overloaded. I know that old worlds can be a bit buggy due to some issues with unfinished mods like MPS.

**Comment by bochen415** [comment]
This server and the world should be debugged
Options: opis + mobiuscore, visualvm, Fastcraft sampler

**Comment by bochen415** [comment]
OP should upload a copy of the whole server directory with the world save to check

**Comment by The-1-7-10-Pack** [comment]
Please try using what Bochen mentioned, for now I'm closing this one.
