### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by TreePuncher9501** [The-1-7-10-Pack/The-1.7.10-Pack#491]
I noticed that, as I'm building, I would place blocks in places I can't. Such as, when I was working on replacing the oxygen pipes for my mechanism system, it would place pipes both where I put them AND on the roof. THE ROOF.

**Comment by The-1-7-10-Pack** [comment]
Picture? also maybe it's only with Mekanism?

**Comment by TreePuncher9501** [comment]
A picture is hard to show due to the nature of the issue. I'll see if I can get a decent one. As for if it's mekanism only... It also occurred with Chisel blocks.

**Comment by TreePuncher9501** [comment]
Okay, since I am just now  logging back in to get screenshots: crashing!!
http://pastebin.com/RY43wAb6

**Comment by The-1-7-10-Pack** [comment]
As I see in Mekanism's repo this crash has fixed in dev versions and will be out soon. Anything else on the weird placing thingy?

**Comment by CriticalRocket** [comment]
Which version is this? I'm still on 0.7.6b

**Comment by The-1-7-10-Pack** [comment]
@CriticalRocket Thanks! but why are you still on v0.7.6b? update ASAP!

**Comment by CriticalRocket** [comment]
Haha I just updated ;) Running into issues now though! making a new thread.

**Comment by TreePuncher9501** [comment]
All I can manage to explain is that it often results in annoyance. It isn't major in any way, as tools and the like can be replaced or recharged. The blocks don't place inside the player, but they do annoy when they stack 3 times above oneself when trying to build.

**Comment by TreePuncher9501** [comment]
Here's a screenshot I managed. I was building a wall under my bridge for aesthetic reasons and it placed 5 blocks with one place, causing me to be engulfed in said blocks and to put some above the bridge.

http://i.imgur.com/hziAroG.png
http://i.imgur.com/cEbylCa.png

**Comment by The-1-7-10-Pack** [comment]
Do you have any additional mods?

**Comment by TreePuncher9501** [comment]
The only additional mod I use is optifine... I was thinking about adding MCA but I don't have it installed.

**Comment by The-1-7-10-Pack** [comment]
I can't confirm this at any way. Also I see that you're changing your game mode while taking a picture, why?
Try to remove Optifine

**Comment by TreePuncher9501** [comment]
I changed the gamemode due to suffocation problems caused by the multi-placing. It's annoying, so I'm going to try to remain in creative for efforts to not die by the issue. Optifine didn't do anything, but I have a hunch that it may be caused by bad framerates, but even then that would not explain the face that it places blocks where I cannot see.

**Comment by CriticalRocket** [comment]
Maybe upload your modpack folder (and the save file) and send it to jon so he can have a look?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
