### ISSUE TITLE
Server exception

### ISSUE THREAD

**Issue by CriticalRocket** [The-1-7-10-Pack/The-1.7.10-Pack#492]
Hey,

So, yesterday I played on my 76b world, went to the twighlight forest dimension, got teleported under the world and died. I quit and decided to fix it with a backup today.

I noticed 76c was released and updated, and my backup was suddenly corrupted ><
I tried letting the server generate a fresh world to see if it was the world or the server causing it, and when I joined the world and moved about 20 blocks (flying in creative mode) it crashed, giving me this crash report: http://pastebin.com/QhPu1CrW

When I loaded the server again I could join fine, nothing wrong. Still, every crash is worth reporting.

**Comment by CriticalRocket** [comment]
(ps turns out I forgot to change the backups directory when I updated my server to 76b, so I've got more recent backups which do work ;) luckily. Still weird that that older backup somehow got corrupted)

**Comment by The-1-7-10-Pack** [comment]
The crash report doesn't say much, it's very general, could be anything.
Nothing I can do but thanks anyway for reporting :)
