### ISSUE TITLE
Taint swarm morph bug.

### ISSUE THREAD

**Issue by RetroJaro** [The-1-7-10-Pack/The-1.7.10-Pack#494]
I was by my base, which was by a taint biome (before I cleared it up with blooms and silverwood trees anyways) and got the taint swarm morph. I was going through the morph list and noticed that the particle effect for taint swarms bugged out and remained by my base when I morphed out of it.

I had to break my world anchors and fly about 8000 away from my base before the particle effect went away. I also closed out my game and restarted while far away from my base to reload the chunks.

It worked but it's just something I thought you guys and girls should be aware of.

**Comment by The-1-7-10-Pack** [comment]
It's a known bug that was even on modded MC 1.6. Not the modpack's fault, blame the modders.
