### ISSUE TITLE
Bug -> probably just the mods fault

### ISSUE THREAD

**Issue by CriticalRocket** [The-1-7-10-Pack/The-1.7.10-Pack#495]
Pretty straight forward: Redstone ore in a pulverizer doesn't output redstone dust(should output 6 redstone dust for each ore). nor cinnabar (cinnabar is 25% chance for each pulverised redstone ore, i've done 10 ores and got nothing).

**Comment by The-1-7-10-Pack** [comment]
Huh? It should. I need to confirm that.

**Comment by The-1-7-10-Pack** [comment]
![image](https://cloud.githubusercontent.com/assets/10350644/7216714/b7827ca8-e610-11e4-8d46-28114a02dac1.png)
