### ISSUE TITLE
Pack not installing!

### ISSUE THREAD

**Issue by Malorn44** [The-1-7-10-Pack/The-1.7.10-Pack#497]
My friend is trying to instal 0.7.6c on his macbook. 
He keeps getting this error everytime he tries to install the pack:

"Error downloading a file for the following pack: The 1.7.10 Pack
Failed to download http://solder.endermedia.com/repository/mods/blood-magic/blood-magic-1.3.1-7.zip
Please consult the modpack author"

so that is what I am doing because it told me to consult you!

**Comment by MGNKylan** [comment]
Same problem here.

**Comment by alphawolf221** [comment]
2 of my friends are having the same problem. 
You can load up to the previous update fine though

**Comment by Malorn44** [comment]
Yes but my server was just updated so not downgrading it again. I tried going to the link and no mod appeared there. You may have to download the mod manually to the pack however I don't know where you would place mods on a mac. Under Library > Application Support > Technic, there are no modpack folders. There is a modpack text file but I didn't see any folders when my friend shared screens with me on skype.

**Comment by CriticalRocket** [comment]
You're modpack should get saved in /AppData/Roaming/Technic/modpacks/the-1710-pack 
On windows*

On Mac idk. The 1710 folder should be in the same place in the technic folder as it is on windows, and the location of your technic folder can be viewed when you click 'Launcher Options' in the launcher (top right).

You should try updating/installing java, and removing the launcher(and the modpack) entirely, downloading the launcher again and doing a completely fresh install.

**Comment by Malorn44** [comment]
Java is fully updated already and my friend has already tried uninstalling and reinstalling everything

**Comment by The-1-7-10-Pack** [comment]
Should be working now, solder derpiness.
@Malorn44; @MGNKylan; @alphawolf221; @CriticalRocket
