### ISSUE TITLE
Problem Installing any modpack not built in with Technic Launcher D;

### ISSUE THREAD

**Issue by SirSpace** [The-1-7-10-Pack/The-1.7.10-Pack#499]
Can someone please help me I am having an issue when getting to the last stage of the install when downloading the libraries of a modpack (that is not built in with the technic laucher) an error pops up saying, "Failed to download http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config- 1.2.1.jar" I would really like to play the mod but I can't due to this error. P.S. This happens on every modpack I attempted to install so far that does not come with the launcher. T_T D;

**Comment by The-1-7-10-Pack** [comment]
Do you have a cisco router? something is blocking the Forge files. Nothing I can do about it though, sorry. Maybe try to ask a friend to download the pack and send you the files.

**Comment by CriticalRocket** [comment]
I've got a cisco router and I don't have any problems :x

**Comment by CriticalRocket** [comment]
Maybe its your firewall? Try giving technic full acces.

**Comment by SirSpace** [comment]
I've tried to give technic full access by disabling security, virus protection, and my firewall but nothing. Would windows defender have anything to do with it?

**Comment by The-1-7-10-Pack** [comment]
@SirSpace So weird! Anyway, you should try to get help [there](https://github.com/MinecraftForge/MinecraftForge/issues).

**Comment by SirSpace** [comment]
This kinda sucks D;
