### ISSUE TITLE
[mod suggestion] Custom NPCs 

### ISSUE THREAD

**Issue by funkyrowanpixie** [The-1-7-10-Pack/The-1.7.10-Pack#50]
Hey i though you could put the mod Custom Npcs into the mod pack

its a mod that adds npcs into the game 

more info about the mod in this link

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs

ps. i dont own this mod i'm only suggesting it

**Comment by The-1-7-10-Pack** [comment]
Look here: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/46#issuecomment-68941366
