### ISSUE TITLE
It won't Work!

### ISSUE THREAD

**Issue by JeremySilverSword** [The-1-7-10-Pack/The-1.7.10-Pack#504]
I install the Mod Pack and everything looks fine then after its done i try to play it and it just closes and opens the launcher again! This is the first time this happend with a modpack and this seems to be the best modpack i have seen so far so i would realy like to play. Pls Help!

**Comment by The-1-7-10-Pack** [comment]
You need to have Java 7/8 and 64 bit.

**Comment by JeremySilverSword** [comment]
Only 64 bit?

**Comment by The-1-7-10-Pack** [comment]
@JeremySilverSword Yes.

**Comment by JeremySilverSword** [comment]
I installed Java 7 64 bit but it takes a long time not responding and after like 6 mins it just closes and opens launcher

**Comment by The-1-7-10-Pack** [comment]
@JeremySilverSword Okay, so we should stop guessing and actually get the needed information. Please give me your latest log, read [there](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md) how to do so.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
