### ISSUE TITLE
Deleted World D:

### ISSUE THREAD

**Issue by FireFlameGuy** [The-1-7-10-Pack/The-1.7.10-Pack#507]

**Comment by FireFlameGuy** [comment]
my world got deleted while playing,i play the 1.7.10 pack

**Comment by The-1-7-10-Pack** [comment]
I need your latest log. Read [there](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md) how to do so.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.

**Comment by FireFlameGuy** [comment]
ugh
