### ISSUE TITLE
Forge Microblocks

### ISSUE THREAD

**Issue by Sangee33** [The-1-7-10-Pack/The-1.7.10-Pack#508]
Forge microblocks doesn't seem to be working with anything except the ME cables. Don't seem to be compatible with fluid conduits or ducts from thermal expansion or ender io... is there any way to fix this or does anyone know what may be wrong?

**Comment by The-1-7-10-Pack** [comment]
Thermal Dynamics got it's own covers, same for EnderIO and more.
