### ISSUE TITLE
mod suggestion ships and mob power

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#509]
I want to suggest 2 small mods, they are pretty fun to play with
-----------------------------------------------------------------------------------------------------------------------------
Advanced Genetics Mod allows you to get the special abilities of mobs and to combine them to yourself. 
Compatible with:
IC2 Experimental
Redstone Flux

http://ag.teamdna.de/
------------------------------------------------------------------------------------------------------------------------------
Ships Mod brings Minecraft ships to life with realistic floatation mechanics and propulsion systems. Build your ship out of blocks, find a spot to put the special ship block, and then watch it float on the water. Take the helm and point your ship in any direction to sail the seas. Bring along your friends, your items, and even your bed for an adventure.

http://www.cuchazinteractive.com/ships/

------------------------------------------------------------------------------------------------------------------------------

**Comment by The-1-7-10-Pack** [comment]
Advanced Genetics is a very powerful mod that doesn't really fit the pack. As for the Ships mod, it's pretty much useless as you have freakin' jetpacks and planes, why would anyone want to build a boring boat?
Thanks anyway for suggesting and being a part of the modpack's development!

**Comment by CriticalRocket** [comment]
I don't agree with the 'why would anyone build a boring boat'.

I think the boat looks epic. And even though I've got a plane, I would still use the boat to travel across the huge ocean that lies behind my base. 

Minecraft isn't about aquiring the stuff that makes the game the easiest. It's about having the most fun. And IMO those boats look like a lot of fun to build and use!

**Comment by imsupermario** [comment]
this mod can hold up to 10000 blocks per "boat". Possible builds such as aircraft carrier or a movable base...etc
I own a server ,so sometimes I gather suggestions from other players and bring it to Github.
We understand sometimes stuff just don't fit. But yea , Ships are not boring, some people play rail-craft even we have portals.

Anyway love your pack ,looking forward to 0.7.7

**Comment by The-1-7-10-Pack** [comment]
@imsupermario v0.7.7 is in early dev, mostly due to the latest problematic Forge updates.
