### ISSUE TITLE
[Mod Suggestion] Thaumic Energistics

### ISSUE THREAD

**Issue by Cjors** [The-1-7-10-Pack/The-1.7.10-Pack#51]
I love your mod pack. I've been exploring all that there is to thaumatergy. I've been really struggling with managing my storage situation and i think applied energistics 2 is the answer. out of curiosity i wanted to see what kind of thaumcraft add-ons are out there and found Thaumic Energistics. 

url here : 
www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2150151-1-7-10-tc4-ae2-thaumic-energistics    

From the page:
[Because the digital age could use some magic.

The goal of the mod is to serve as a bridge between Thaumcraft and Applied Energistics. The primary focus is essentia management, both in storage, transportation, and application.

Features:
Import and export essentia to the ME network.
Interface with Thaumcraft devices which use suction to request essentia.
Store essentia in the ME network and/or use Thaumcraft jars as storage extensions.
View how much of each essentia type is stored on the network.
Interface with infusion devices such as the Runic matrix.
Thaumcraft crafting terminal with access to items on the ME network.
Emit redstone signal based on amount of essentia in network.
Charge wands in arcane crafting terminal.
Golems can do the work of cranking your grinder.

Dependencies:
Minecraft 1.7.10
Forge 10.13.2.1230
Thaumcraft 4.2.1.4+
Applied Energistics 2]

I don't yet know how nicely AE2 plays with essentia but this mod seems to integrate essentia storage and management directly into AE2. Thanks so much for creating and maintaining this mod pack. I'm having my first modded adventure and having a blast.

**Comment by The-1-7-10-Pack** [comment]
For now adding new mods is a bit too much for the pack, but I'll leave it open so other people can comment.

**Comment by BoWiWo** [comment]
I would very much support the addition of this mod, as it gives great possibility of automating many otherwise unnessecarily difficult tasks. It also enhances the possibility to extend the unbelieveably powerful Apllied Energistics system.

**Comment by bennygeorgiev** [comment]
can you add this mod in about 10 days please i realy like this mode

**Comment by Flukethoughts** [comment]
I understand you guys would love the addition and u can apply the mod yourself. But currently as of now the modpack is undergoing alot of work to get everything working for all users. John has the full ability to add and remove as he see fits in the official pack. But you guys can add to it at anytime just don't expect john to offer support for those addons.
