### ISSUE TITLE
Client crash for unknown reason

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#511]
Hi, I have a client who keeps on disconnecting,crashing in our server for unknown reasons.
would you mind taking a look at the logs.
thankyou

player: KillTheChokTim

server log:
http://pastebin.com/fJPGmCiq

**Comment by The-1-7-10-Pack** [comment]
The files that you gave me don't help, it's not the right log. I need your crash report, and please use a paste-tool, don't give me a download link.

**Comment by imsupermario** [comment]
crash report:
http://pastebin.com/ub8wgTYF

**Comment by The-1-7-10-Pack** [comment]
@imsupermario I need the crash report of your client, this is not it. Do you have it?

**Comment by imsupermario** [comment]
i am so sorry this is all i have from the client, i will open a new issue when a have an update.

**Comment by The-1-7-10-Pack** [comment]
@imsupermario Well I can't help you with this. Anyway try to update your Java. Closing it for now!
