### ISSUE TITLE
It wont start up

### ISSUE THREAD

**Issue by VT2k6** [The-1-7-10-Pack/The-1.7.10-Pack#513]
When i hit play on the modpack launcher, It crashes with the message:
"Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occured. Program will exit."
and that pops up every time. The other modpacks work fine, and i downloaded the latest Java??

Update: I fixed the issue with the message popping up, but instead of the message, nothing happens and it just refreshes the launcher?

**Comment by The-1-7-10-Pack** [comment]
https://www.youtube.com/watch?v=KH62sm-orE4

**Comment by VT2k6** [comment]
Thank you! I appreciate it!
