### ISSUE TITLE
Tesseract client kick bug

### ISSUE THREAD

**Issue by rastamanfb** [The-1-7-10-Pack/The-1.7.10-Pack#514]
I run a hosted private server using this pack and if i use a tesseract and right click it to get to its configurations 5 times out of 10 it will kick me from the server.
if i rejoin and right click again it is fine.

I didnt take note of the error exactly and it didnt fully crash my game
I will get further details tomorrow

Kind Regards
Rastaman

**Comment by The-1-7-10-Pack** [comment]
I need the error.

**Comment by rastamanfb** [comment]
I will try and get the error if it happens again. it was litterally placing a tesseract and right clicking resulted in client kicking from the server.
happened multiple times but ill try and get it again

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
