### ISSUE TITLE
Pack not launching

### ISSUE THREAD

**Issue by Sangee33** [The-1-7-10-Pack/The-1.7.10-Pack#515]
Hey my friends got a problem with trying to launch the 1.7.10 pack. Other packs seem to launch fine on the technic launcher but for some reason the 1.7.10 pack will say it's downloading assets etc until about 18% and then it just goes back to the launcher and doesn't open.
specs:
8gb RAM
Intel i5-4300u CPU 64bit
Java 1.7.0_75 64bit

thanks for the help

**Comment by The-1-7-10-Pack** [comment]
I need the full log, and please use a [paste-tool](http://paste.ubuntu.com/). Anyway tell your friend to update his Java to the latest 1.8.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
