### ISSUE TITLE
Will Not Open

### ISSUE THREAD

**Issue by Nogotogon** [The-1-7-10-Pack/The-1.7.10-Pack#517]
It has worked twice but it takes for ever and then it said Not Responding for like 3 Mi. I have java 64 bit an updated Technic pack lancher and it is quite annoying

After it is done not responding it Initializes to about 95% then goes not responding again then after a while it seems to work

**Comment by The-1-7-10-Pack** [comment]
I need your latest client log.

**Comment by Nogotogon** [comment]
sorry i loged off ... how do you do that?

**Comment by The-1-7-10-Pack** [comment]
Go to the modpack's folder, then go to the logs folder, and paste the latest log from there :)

**Comment by Nogotogon** [comment]
0.7.6

**Comment by The-1-7-10-Pack** [comment]
You need to post what is inside of the latest log

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
