### ISSUE TITLE
AE2 Energy Acceptor & Crystal growth accelerators 

### ISSUE THREAD

**Issue by rastamanfb** [The-1-7-10-Pack/The-1.7.10-Pack#518]
Seems to be broken, I have used Mekanism Universal cables with energy acceptors since your pack first came out with no issues.
Im not sure at which update it has broken it as i havent used them for a while however I cannot get them to come online when linked to the energy acceptor.
i removed the acceptor and cabled them up to the controller using ME quartz cable and it worked fine.

I have not tested the energy acceptor with other AE2 mods however I thought i would highlight this issue

Regards
Rastaman

**Comment by The-1-7-10-Pack** [comment]
Try to power it with other cabels

**Comment by rastamanfb** [comment]
Hi, I have connected it to me controller and the same thing so theres deffo a compatibility issue with this energy acceptor and so far mekanism.
its going to be hard for me to test as the things i use it for are built around a mass off mekanism cables connected to a tesseract connected to a big reactor.
Ill try and report back

**Comment by rastamanfb** [comment]
Update:
I have tried a selection of cables most of which are not compatible with tesseract however the Redstone Fluxducts from Thermal Dynamics seem to function fine with it.
So its deffo a compatibility issue with mekanism. not sure when it started but it used to work fine

**Comment by The-1-7-10-Pack** [comment]
It's a known issue with Mekanism and will get fixed soon, thanks anyway for reporting.
