### ISSUE TITLE
Still can't start server

### ISSUE THREAD

**Issue by DolanDuck123** [The-1-7-10-Pack/The-1.7.10-Pack#519]
I had an issue before, Can't start a server #516 , and I thought maybe my java needed an update, so I updated it. Now when I try to start the server, this happens:
![image](https://cloud.githubusercontent.com/assets/12111999/7334160/1c75aba6-eb59-11e4-8c3f-de47048a7f17.png)

**Comment by The-1-7-10-Pack** [comment]
http://stackoverflow.com/a/18123162
simply switch the "7" with "8" in this guide.

**Comment by DolanDuck123** [comment]
I think i fixed it. I followed #406 and it seems to be working
