### ISSUE TITLE
[Mod Request] Better Dungeons

### ISSUE THREAD

**Issue by TheIceballLP** [The-1-7-10-Pack/The-1.7.10-Pack#52]
The Titel says anything i guess ... if not i think better dungeons would be awesome in this pack :D 

here is an link to an post http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284476-1-7-10-smp-bukkit-forge-dungeonpack-24-dungeons-3

(i would like it to see it ingame and on server too

**Comment by The-1-7-10-Pack** [comment]
New mods are a bit too much at this point. We have some dungeons mods and for now I won't add more. Thank you anyway.
