### ISSUE TITLE
One problem after the next

### ISSUE THREAD

**Issue by DolanDuck123** [The-1-7-10-Pack/The-1.7.10-Pack#520]
This is my 3rd issue today, and hopefully my last. The other 2 problems were resolved, but now I can't start the modpack, and it closes at installing minecraft assets 0%.  Launcher log: http://paste.ubuntu.com/10889599/ I did try to open a different modpack, and the other one worked but this one didn't

**Comment by The-1-7-10-Pack** [comment]
Can you give me the launcher log after you try to launch The 1.7.10 Pack?

**Comment by DolanDuck123** [comment]
http://paste.ubuntu.com/10889989/

**Comment by The-1-7-10-Pack** [comment]
You have installed Java 32 bit, you need 64 bit.
