### ISSUE TITLE
Digital miner issue

### ISSUE THREAD

**Issue by Dommain** [The-1-7-10-Pack/The-1.7.10-Pack#525]
If you put "*av*" into custom dictionary, it will crash.

http://pastebin.com/MmCn7UeU

**Comment by The-1-7-10-Pack** [comment]
Weird! Please report it [there](https://github.com/aidancbrady/Mekanism/issues), I can't do anything else.

**Comment by Dommain** [comment]
It was an NEI issue. where can I post for that?
https://github.com/aidancbrady/Mekanism/issues/2593

**Comment by The-1-7-10-Pack** [comment]
https://github.com/Chicken-Bones/NotEnoughItems/issues
