### ISSUE TITLE
Adding mods to The 1.7.10 Pack

### ISSUE THREAD

**Issue by SlickeyWins** [The-1-7-10-Pack/The-1.7.10-Pack#526]
Hey and first of all thanks for creating this magnificent modpack :) me and my friends are having a wonderful time so far but they asked me to add very few mods, now when I paste a mod into the mods folder of the server, it used to work on other modpacks however on this one it doesn't, the LaunchServer.bat gives me an error after a few seconds.
Does anyone know how to add mods? Thanks so much in advance!
Regards, Riley

**Comment by The-1-7-10-Pack** [comment]
Can you give me the logs?

**Comment by SlickeyWins** [comment]
Yes sir, thanks for responding to fast, the crash report says this:

---- Minecraft Crash Report ----
// Don't do that.

Time: 4/26/15 8:56 AM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_76279_b
	at com.github.AbrarSyed.secretroomsmod.common.MaterialFakeAir.<init>(MaterialFakeAir.java:11)
	at com.github.AbrarSyed.secretroomsmod.common.SecretRooms.<clinit>(SecretRooms.java:148)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 644643944 bytes (614 MB) / 1358954496 bytes (1296 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xmx3G -XX:PermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.103.1352 Minecraft Forge 10.13.2.1352 195 mods loaded, 195 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.103.1352} [Forge Mod Loader] (forge-1.7.10-10.13.2.1352-1.7.10-universal.jar) Unloaded->Constructed
	Forge{10.13.2.1352} [Minecraft Forge] (forge-1.7.10-10.13.2.1352-1.7.10-universal.jar) Unloaded->Constructed
	appliedenergistics2-core{rv2-beta-28} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	ivtoolkit{IvToolkit} [1.1.1] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed
	RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) Unloaded->Constructed
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed
	OpenModsCore{0.7.1} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed
	debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed
	IC2{2.2.716-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.716-experimental.jar) Unloaded->Constructed
	AdvancedMachines{1.1.2} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) Unloaded->Constructed
	appliedenergistics2{rv2-beta-28} [Applied Energistics 2] (appliedenergistics2-rv2-beta-28.jar) Unloaded->Constructed
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) Unloaded->Constructed
	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed
	asielib{0.3.12} [asielib] (AsieLib-1.7.10-0.3.12.jar) Unloaded->Constructed
	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) Unloaded->Constructed
	Grinder{4.0.0} [Grinder] (AttachableGrinder-4.0.0.jar) Unloaded->Constructed
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed
	bdlib{1.7.1.71} [BD Lib] (bdlib-mc1710-1.7.1.71.jar) Unloaded->Constructed
	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) Unloaded->Constructed
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed
	BuildCraft|Core{6.4.11} [BuildCraft] (buildcraft-6.4.11.jar) Unloaded->Constructed
	Forestry{3.5.3.11} [Forestry for Minecraft] (forestry_1.7.10-3.5.3.11.jar) Unloaded->Constructed
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed
	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed
	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.1-7.jar) Unloaded->Constructed
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed
	Botania{r1.6-176} [Botania] (Botania r1.6-176.jar) Unloaded->Constructed
	BuildCraft|Transport{6.4.11} [BC Transport] (buildcraft-6.4.11.jar) Unloaded->Constructed
	BuildCraft|Silicon{6.4.11} [BC Silicon] (buildcraft-6.4.11.jar) Unloaded->Constructed
	BuildCraft|Builders{6.4.11} [BC Builders] (buildcraft-6.4.11.jar) Unloaded->Constructed
	BuildCraft|Energy{6.4.11} [BC Energy] (buildcraft-6.4.11.jar) Unloaded->Constructed
	BuildCraft|Factory{6.4.11} [BC Factory] (buildcraft-6.4.11.jar) Unloaded->Constructed
	BuildCraft|Compat{6.4.0} [BuildCraft Compat] (buildcraft-compat-6.4.2.jar) Unloaded->Constructed
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed
	TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed
	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed
	colorchat{1.7.2-0.1.0} [ColorChat] (colorchat-1.7.10-0.1.0-22.jar) Unloaded->Constructed
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.306.jar) Unloaded->Constructed
	Mekanism{8.1.1} [Mekanism] (Mekanism-1.7.10-8.1.1.225.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.3.0.371_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.371_beta.jar) Unloaded->Constructed
	EnderStorage{1.4.6.31} [EnderStorage] (EnderStorage-1.7.10-1.4.6.31-universal.jar) Unloaded->Constructed
	MrTJPCoreMod{1.0.5.12} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.12-universal.jar) Unloaded->Constructed
	ProjRed|Core{4.5.16.77} [ProjectRed] (ProjectRed-1.7.10-4.5.16.77-Base.jar) Unloaded->Constructed
	ProjRed|Transmission{4.5.16.77} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.16.77-Integration.jar) Unloaded->Constructed
	OpenComputers{1.5.6.13} [OpenComputers] (OpenComputers-MC1.7.10-1.5.6.13-universal.jar) Unloaded->Constructed
	computronics{1.4.6} [Computronics] (Computronics-1.7.10-1.4.6.jar) Unloaded->Constructed
	DeathCounter{4.0.0} [DeathCounter] (DeathCounter-4.0.0.jar) Unloaded->Constructed
	Doge{0.5.2} [Doge] (DogeMod_0.5.2_[1.7.10].jar) Unloaded->Constructed
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed
	EnderTech{1.7.10-0.3.2.382} [EnderTech] (EnderTech-1.7.10-0.3.2.382.jar) Unloaded->Constructed
	EnderZoo{1.7.10-1.0.11.27} [Ender Zoo] (EnderZoo-1.7.10-1.0.11.27.jar) Unloaded->Constructed
	extracells{2.2.68} [ExtraCells] (ExtraCells-1.7.10-2.2.68bNIGHTLY.jar) Unloaded->Constructed
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities-1.2.2.jar) Unloaded->Constructed
	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed
	factorization{1.7.10-0.8.88.7} [Factorization] (Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed
	factorization.misc{1.7.10-0.8.88.7} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed
	fastleafdecay{1.0} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.0.jar) Unloaded->Constructed
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed
	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-5a.jar) Unloaded->Constructed
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.306.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded->Constructed
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-474.jar) Unloaded->Constructed
	MagicBees{1.7.10-2.1.31} [Magic Bees] (magicbees-1.7.10-2.1.31.jar) Unloaded->Constructed
	gendustry{1.4.10.77} [GenDustry] (gendustry-mc1710-1.4.10.77.jar) Unloaded->Constructed
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed
	HardcoreEnderExpansion{1.8} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.jar) Unloaded->Constructed
	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) Unloaded->Constructed
	HardcoreQuesting{The Journey (4.2.2)} [Hardcore Questing Mode] (HQM-The Journey (4.2.2).jar) Unloaded->Constructed
	IC2NuclearControl{2.1.2a} [Nuclear Control 2] (IC2NuclearControl-2.1.2a.jar) Unloaded->Constructed
	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-54.jar) Unloaded->Constructed
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed
	LogisticsPipes{0.8.3.117} [Logistics Pipes] (logisticspipes-0.8.3.117.jar) Unloaded->Constructed
	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed
	MekanismGenerators{8.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.1.225.jar) Unloaded->Constructed
	MekanismTools{8.1.1} [MekanismTools] (MekanismTools-1.7.10-8.1.1.225.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	ProjRed|Exploration{4.5.16.77} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.16.77-World.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatMagicalCrops{1.0beta} [MFR Compat: MagicalCrops] (MineFactoryReloaded-CompatMagicalCrops.jar) Unloaded->Constructed
	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal.jar) Unloaded->Constructed
	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.6.jar) Unloaded->Constructed
	numina{0.4.0.7-QMX} [Numina] (Numina-0.4.0.7-QMX.jar) Unloaded->Constructed
	powersuits{0.11.0.7-QMX} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.7-QMX.jar) Unloaded->Constructed
	powersuitaddons{0.11.0.7-QMX} [Modular Powersuit Addons] (ModularPowersuitsAddons-0.11.0.7-QMX.jar) Unloaded->Constructed
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed
	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded->Constructed
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed
	necromancy{1.7.1} [Necromancy] (Necromancy-1.7.10.jar) Unloaded->Constructed
	NEIAddons{1.12.6.18} [NEI Addons] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed
	NEIAddons|Botany{1.12.6.18} [NEI Addons: Botany] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed
	NEIAddons|Forestry{1.12.6.18} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed
	NEIAddons|CraftingTables{1.12.6.18} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed
	NEIAddons|ExNihilo{1.12.6.18} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed
	neiintegration{1.0.8} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.8.jar) Unloaded->Constructed
	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) Unloaded->Constructed
	recipemod{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) Unloaded->Constructed
	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) Unloaded->Constructed
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed
	OpenMods{0.7.1} [OpenMods] (OpenModsLib-1.7.10-0.7.1.jar) Unloaded->Constructed
	OpenBlocks{1.4.1} [OpenBlocks] (OpenBlocks-1.7.10-1.4.1.jar) Unloaded->Constructed
	OpenPeripheralCore{1.1} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-3.jar) Unloaded->Constructed
	OpenPeripheral{0.3.1} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-3.jar) Unloaded->Constructed
	OpenPeripheralIntegration{0.2.1} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-3.jar) Unloaded->Constructed
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed
	PneumaticCraft{1.6.6-68} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.6-68-universal.jar) Unloaded->Constructed
	progressiveautomation{1.6.14} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.14.jar) Unloaded->Constructed
	ProjRed|Transportation{4.5.16.77} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.16.77-Mechanical_beta.jar) Unloaded->Constructed
	ProjRed|Compatibility{4.5.16.77} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.16.77-Compat.jar) Unloaded->Constructed
	ProjRed|Integration{4.5.16.77} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.16.77-Integration.jar) Unloaded->Constructed
	ProjRed|Illumination{4.5.16.77} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.16.77-Lighting.jar) Unloaded->Constructed
	ProjRed|Expansion{4.5.16.77} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.16.77-Mechanical_beta.jar) Unloaded->Constructed
	reccomplex{0.9.6.1} [Recurrent Complex] (RecurrentComplex-0.9.6.1.jar) Unloaded->Constructed
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed
	RefinedRelocation{1.0.8a} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.8a.jar) Unloaded->Constructed
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) Unloaded->Constructed
	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) Unloaded->Constructed
	secretroomsmod{4.6.0} [SecretRoomsMod] (SecretRoomsMod-universal-4.6.0.281.zip) Unloaded
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded
	squidless{0.6.0} [Squidless] (squidless-1.7.10-0.6.0.jar) Unloaded
	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) Unloaded
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded
	StevesAddons{0.10.2} [Steve's Addons] (StevesAddons-1.7.10-0.10.2.jar) Unloaded
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded
	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) Unloaded
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) Unloaded
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded
	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) Unloaded
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded
	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) Unloaded
	wailaplugins{MC1.7.10-0.0.1-14} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-14.jar) Unloaded
	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) Unloaded
	witchery{0.24.0} [Witchery] (witchery-1.7.10-0.24.0.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	yampst{1.3.5} [YAMPST] (Yampst-The 1.7.10 Pack-0.7.6.jar) Unloaded
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded
	aobd{2.5.0} [Another One Bites The Dust] (AOBD-2.5.0.jar) Unloaded
	denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:ENABLED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	AE2 Version: beta rv2-beta-28 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.0-80
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by The-1-7-10-Pack** [comment]
You're using an outdated version of the mod. Download the latest [there](http://files.minecraftforge.net/SecretRoomsMod/).
