### ISSUE TITLE
Big Reactors to Applied Energistics Issue

### ISSUE THREAD

**Issue by TireurMatrice** [The-1-7-10-Pack/The-1.7.10-Pack#528]
I'm trying to power my AE2 system using the Big Reactors mod since that has been my main power hub. For whatever reason, the AE2 energy acceptor isn't taking the power from the Mekanism universal cables or the extra utilities Energy pipes. I was able to hook it up via some copper wires and using the industrial craft generators and it worked fine. Am I doing something wrong or is it just not working?

**Comment by martinegui** [comment]
Do you have sure that your big reactor is provinding enough energy? (because I use universal cables in my single player and works fine execpt that i use meknaism generators to my AE2 system)

**Comment by TireurMatrice** [comment]
The reactor is producing 550 ish rf/t at the moment. But I even tried hooking up an energy cell to the Energy acceptor and it wasn't filling up at all

**Comment by martinegui** [comment]
Maybe you need to configure with some kind of a wrench to "IN" or "OUT" power. I dont remember now.

**Comment by TireurMatrice** [comment]
I didn't have to do that with the Industrial Craft power though.

**Comment by The-1-7-10-Pack** [comment]
You may be doing something wrong with the Extra Utilities pipes but the Mekanism pipes do not work with AE2 systems this version. Use Thermal Dynamics pipes :)

**Comment by TireurMatrice** [comment]
![image](https://cloud.githubusercontent.com/assets/11196182/7347213/bd160cf6-ecab-11e4-90df-679c40e7f811.png)
![image](https://cloud.githubusercontent.com/assets/11196182/7347219/db9491fc-ecab-11e4-88d5-315147e53073.png)
Those aren't working either. The Leadstone Cell is receiving power but the AE2 system isn't getting anything.

**Comment by The-1-7-10-Pack** [comment]
Your energy cell is set to input.
