### ISSUE TITLE
Tinker's contruct

### ISSUE THREAD

**Issue by ImBundle** [The-1-7-10-Pack/The-1.7.10-Pack#529]
I've install on multicraft server hosted by Bisect Hosting all OK but no Book at start up and i can't craft Tinkers item. What I can do to Solve? 

p.s. In single player it's ok

**Comment by The-1-7-10-Pack** [comment]
What do you mean you can't craft them?

**Comment by ImBundle** [comment]
Example:
I put two stick and two planks to craft a blank pattern.
The image of blank pattern appear in the crafting table.
When I try to pick it but remains on the table as if it were magnetic

**Comment by The-1-7-10-Pack** [comment]
![image](https://cloud.githubusercontent.com/assets/10350644/7469963/ad305a22-f321-11e4-8e11-c95cc5f9d4a7.png)
Be sure you're using normal planks.
