### ISSUE TITLE
one of the mods need java 1.7 or newer but I'm using java 8

### ISSUE THREAD

**Issue by jumperstick** [The-1-7-10-Pack/The-1.7.10-Pack#53]
when i try to op it, it says that one of the mods needs java 1.7 or newer and that I'm using java 1.0.6_56 but I'm using java 8, any suggestions?

**Comment by Flukethoughts** [comment]
Yea look into all the java you have installed and uninstall them and install java 7

**Comment by Joey-Nolan** [comment]
Having the same problem!

**Comment by Silphsy** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html
Sorry for the delay

**Comment by Joey-Nolan** [comment]
Thanks you so much Silphsy! I'll be playing this pack for a looooooong time :D
