### ISSUE TITLE
Progression

### ISSUE THREAD

**Issue by CriticalRocket** [The-1-7-10-Pack/The-1.7.10-Pack#530]
Hey,

So I've been playing this modpack for like, 4 weeks nog I think?
And I'm at a point that there isn't much more interesting stuff to do.

I got into magic crops a bit and that means that I now have unlimited resources.
I've got machines and some solar panels set up, generating enough to power everything I could need. There's no reason to build a reactor or smthing if I don't need more energy.

We've been to space, but there's not much to do there.
I've beaten almost all Twilight Forest bosses, but it's just too easy with advanced PowerSuit armor.
I've got the best tools I can possibly make with tinker's costruct.

I guess I could try out that Ender mod, but I don't know if that really adds a new challenge/interesting objective. 

I hope there's some more interesting stuff! Because when you've got all resources you'd ever want the game (for me) loses it's reason to play and becomes, well, creative mode :p

The combination of all these mods just causes you to be able to beat mods way to fast by using more powerfull/easier to obtain stuff from other mods. This causes the game to be too easy and you progress way to fast. But I'm not going to just not use my power suit in the twilight forest because I've worked hard to obtain it, but with it the game is just too easy. There's no real fix for this, and I guess thats the reason to play modpacks in the first place, because you like all of the mods. But idk, I just feel like I could've gotten way more fun out of this modpack if I wasn't able to progress to high tier armor and tools (and addons like night vision, flying, superspeed and such) so fast. 1 fix would be to make power suit addons cost waaay more, and to slow down Magic Crops crop growing speed by a lot.

**Comment by The-1-7-10-Pack** [comment]
Did you complete all of the quests?

**Comment by imsupermario** [comment]
defeat all thaurmcart bosses!!

**Comment by CriticalRocket** [comment]
thaumcraft bosses? :x

**Comment by Dommain** [comment]
Botania has 2 interesting end boss but takes a while to generate mana to that point.
The blood magic quest has mana difrent mini demon bosses to kill but also requires time and lots of food.
Hardcore ender can be well..... hard.

**Comment by The-1-7-10-Pack** [comment]
@CriticalRocket Did you get your answer?

**Comment by The-1-7-10-Pack** [comment]
Well, I didn't get mine.

**Comment by CriticalRocket** [comment]
Sorry :x haven't played as much the last few weeks. Got my graduation exams or whatever they're called in english xd Yeah I did get my answer :)
