### ISSUE TITLE
Dosnt load

### ISSUE THREAD

**Issue by Spectrel** [The-1-7-10-Pack/The-1.7.10-Pack#531]
Sorry for not posting on that one issue I didnt have access to my computer here the log http://pastebin.com/DN6DaRdV

**Comment by The-1-7-10-Pack** [comment]
This is not the right log. Anyway, 99% you have the wrong Java. You need Java 7/8 and 64 bit.

**Comment by Spectrel** [comment]
It said Latest

**Comment by Spectrel** [comment]
And how do I get that java?

**Comment by Spectrel** [comment]
http://pastebin.com/Xh5st7Xk

**Comment by The-1-7-10-Pack** [comment]
When exactly your game crashes?

**Comment by Spectrel** [comment]
It gets up to 90% on launch and just stops it dosnt shut down it just stops.

**Comment by The-1-7-10-Pack** [comment]
You're playing on an old version of the pack, please update to the latest.
