### ISSUE TITLE
Unable to access .jar using .sh or .bat

### ISSUE THREAD

**Issue by Deathwater57** [The-1-7-10-Pack/The-1.7.10-Pack#532]
I can't run the server from a mac. I Launch the server and it crashes saying that forge couldn't be opened

**Comment by Deathwater57** [comment]
A problem occurred running the Server launcher.
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.reflect.InvocationTargetException
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:         at java.lang.reflect.Method.invoke(Method.java:597)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:         at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:         at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: ivorius/ivtoolkit/IvToolkitLoadingPlugin : Unsupported major.minor version 51.0
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.lang.ClassLoader.defineClass1(Native Method)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.security.AccessController.doPrivileged(Native Method)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.lang.Class.forName0(Native Method)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at java.lang.Class.forName(Class.java:249)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]:         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
4/29/15 5:25:18 PM	[0x0-0x35a35a].com.apple.JarLauncher[59182]	[17:25:18] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]:

**Comment by The-1-7-10-Pack** [comment]
Double Click the "LauchServer.bat" file and set "eula.txt" to true.

**Comment by Deathwater57** [comment]
Mac doesn't recognize batch files and it's set to true.

**Comment by The-1-7-10-Pack** [comment]
If you're using mac use the other LaunchServer file

**Comment by Deathwater57** [comment]
when i run it through terminal "only way i know how to run .sh files" nothing happens.

**Comment by The-1-7-10-Pack** [comment]
Open the .sh file and edit the "1291" to "1352", try again

**Comment by Deathwater57** [comment]
same error message Unable to access jarfile forge-1.7.10-10.13.2.1352-1.7.10-universal.jar

**Comment by The-1-7-10-Pack** [comment]
@Deathwater57 This makes no sense, please redownload the server files.

**Comment by Deathwater57** [comment]
Same Error message I've tried assigning permission manually and using chmod but to no avail.

**Comment by Deathwater57** [comment]
This is the Error message i get when trying to execute my forge.jar
Server thread/INFO]: Loading properties
[08:46:08] [Server thread/INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.
[08:46:08] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[08:46:08] [Server thread/INFO] [FML]: Applying holder lookups
[08:46:08] [Server thread/INFO] [FML]: Holder lookups applied
[08:46:08] [Server thread/INFO] [FML]: The state engine was in incorrect state POSTINITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by The-1-7-10-Pack** [comment]
Now you need to set eula.txt to true...

**Comment by Deathwater57** [comment]
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	A problem occurred running the Server launcher.[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.reflect.InvocationTargetException
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Method.invoke(Method.java:597)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.UnsupportedClassVersionError: ivorius/ivtoolkit/IvToolkitLoadingPlugin : Unsupported major.minor version 51.0
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass1(Native Method)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.security.AccessController.doPrivileged(Native Method)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName0(Native Method)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.Class.forName(Class.java:249)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
4/30/15 10:15:36 AM	[0x0-0x77077].com.apple.JarLauncher[1343]	[10:15:36] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 6 more

**Comment by Deathwater57** [comment]
I'm also running OSX 10.6 Snow Leopard on java 6 because snow leopard doesn't support 7 or 8. I noticed a lot of bugs are caused because of java 6, but there must be a work around.

**Comment by Deathwater57** [comment]
New error same problem
Server/LaunchServer.bat: line 1: @ECHO: command not found
: command not founde/Desktop/1.7.10 Server/LaunchServer.bat: line 2: 
: command not founde/Desktop/1.7.10 Server/LaunchServer.bat: line 3: 
Unable to access jarfile forge-1.7.10-10.13.2.1352-1.7.10-universal.jar

**Comment by CriticalRocket** [comment]
Please use pastebin (or a similar website) to post logs :s

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
