### ISSUE TITLE
Mekanism - Solar Evaporator

### ISSUE THREAD

**Issue by gimble49** [The-1-7-10-Pack/The-1.7.10-Pack#535]
My old Salination Plant, now Solar Evaporator, is working fine. However, I have made two more (i need the new fusion reactor) and Neither will process any fluids. I have one sitting full of water that won't make brine, and I have one that i pumped brine into from the old Evaporator, but it wont make what its supposed to. They accept water and brine just fine. I also have noticed either generating heat, but again, the old one does. Any thoughts on how to fix it?

**Comment by The-1-7-10-Pack** [comment]
It may be a bug on Mekanism, that will get fixed in the future.

**Comment by gimble49** [comment]
Alright, here's hoping for soon!
