### ISSUE TITLE
World Crashes

### ISSUE THREAD

**Issue by lepinkie** [The-1-7-10-Pack/The-1.7.10-Pack#536]
I was playing fine for about a month and then last week whenever i would click to join my world it would crash. I tried to see if my world was corrupted but it wasn't. I cant even make a new world because it crashes then too. I tried redownloading and installing it but still have the same problem. My java is up to date and i have 2 g.b. of ram hooked up to the Technic launcher. I'm not really sure how to read crash reports but maybe i thought by asking this, others problems will be answered too. Thank you .

**Comment by lepinkie** [comment]
latest log 
http://paste.ubuntu.com/10964043/
latest crash report
http://paste.ubuntu.com/10964017/

**Comment by The-1-7-10-Pack** [comment]
It has something to the keys you're using in game, maybe. Try to reset all of your keys. I should note that when you reinstall packs through the launcher it keeps your settings, so things like that won't reset.

**Comment by lepinkie** [comment]
Thank you so much! resetting the keys made it work.

**Comment by The-1-7-10-Pack** [comment]
:+1:
