### ISSUE TITLE
Bukkit implementation

### ISSUE THREAD

**Issue by Badpoizone** [The-1-7-10-Pack/The-1.7.10-Pack#539]
Hay there ;)
First of all, we want to thank you for such great modpack.
We are using it on our Server and there is my question.
How do we implement some Bukkit Plugins. Our admin tried it but it didnt work.

Thanks in advance 
Badpoizone

**Comment by The-1-7-10-Pack** [comment]
It's not possible as Cauldron is dead, adding plugins to a server with old Cauldron files can make bad things happen. Too bad!
