### ISSUE TITLE
[Mod Request] Mystcraft

### ISSUE THREAD

**Issue by walrusgumbo** [The-1-7-10-Pack/The-1.7.10-Pack#54]
I think Mystcraft would add a lot to this pack, I admit it is one of those mods that I just assume is going to be there when I play a modpack. It takes a lot of the hassle out of travel between dimensions, especially if you want to go back and forth with any regularity. It is a pretty balanced mod as well: it doesn't have a giant impact on the feel of the game.

**Comment by walrusgumbo** [comment]
http://binarymage.com/mystcraft-dev-page/

Here is the official page for it, by the way: again, Mystcraft adds a lot to the game without really changing the character. It does make certain mods more accessible: Forestry comes to mind (beehives are much easier to find in user generated ages). It makes any dimension easier to travel back to as well.

**Comment by The-1-7-10-Pack** [comment]
Mystcraft will not be added due to permissions, the mod author does not want the mod in The 1.7.10 Pack.
