### ISSUE TITLE
mod /add on suggestions

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#540]
hi, i would like to suggest 2 small mods for the pack.
=========================================
Dynamic transport and Thaumic Energistics.
=========================================
Dynamic Transport
----------------------------------------------------------------
Its basically a cheaper ,customization elevator mod, and yes i know . I love funky locomotion.
This is an elevator specific mod,and not to replace funky locomotion, funky locomotion is a great multi-purpose mod.

The reason I suggest this is because we tried using funky loco- to build an elevator(worked) but we discovered it has limitations.

Funky locomotion (elevator):
-stops at each block when going up/down 
-you need complex redstone to make it stop from floor to floor.
-too expensive or an elevator
video link: https://www.youtube.com/watch?v=x_eIC97AfgE

Dynamic transport
-cheap to build
-smooth up/down animation(non glitchy)
-offers floor to floor selection
-absolutely a better solution for vehicle elevators 
This will benefit players who love base building. 
/
--------------------------------------------------------------------------------------------------------------
Thaumic Energistics
------------------------------
It is time to digitize thaumcraft ,make it possible to automate with AE2
----------------------------------------------------------------------------------------

Because the digital age could use some magic.

The goal of the mod is to serve as a bridge between Thaumcraft and Applied Energistics. The primary focus is essential management, both in storage, transportation, and application.
hence automate thaumcraft stuff when crafting gets boring during mid game.

-------------------------------------------------------------------------------------------------------------------
MOD links:
Dynamic transport
http://minecraft-forum.net/minecraft-mods-downloads/1-7-2-dynamic-transport-mod-download-2/#.VUTyu_lVh8M

Thaumic Energistics
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2150151-1-7-10-tc4-ae2-thaumic-energistics

**Comment by The-1-7-10-Pack** [comment]
Both mods may be nice but not really necessary, they won't be added to the pack.
Thanks anyway for suggesting! :)
