### ISSUE TITLE
Another The1.7.10 pack ?

### ISSUE THREAD

**Issue by SlackerNet** [The-1-7-10-Pack/The-1.7.10-Pack#542]
I am no expert by any means but i do test out different packs. When I opened the Cyberia pack the screen says The1.7.10 pack v076. I thought i opened the wrong one so i did it again and same result.
Here is the link to the pack

[code] http://www.technicpack.net/modpack/cyberia.640865 [/code]

here is a screen shot of the pack opened

http://tinypic.com/r/2dso8ro/8

not sure if it means anything but you seem vested in your project

/r
SlackerNet

**Comment by The-1-7-10-Pack** [comment]
People may copied, but as this pack looks small and stupid I won't do any move.
Thanks anyway for reporting.
