### ISSUE TITLE
Pack Crashes

### ISSUE THREAD

**Issue by ChiknNRiceGaming** [The-1-7-10-Pack/The-1.7.10-Pack#543]
My 1.7.10 pack was working perfectly fine for about a week, until I installed the recommended Sphax 64x Texture Pack. When I switched to the texture pack and I hit "Done", it froze up, and I eventually had to force quit out. Ever since then when I try to get on the pack, it loads up to the actual 1.7.10 pack window, and then it crashes. Any thoughts?

**Comment by ChiknNRiceGaming** [comment]
Java version is 8

**Comment by ChiknNRiceGaming** [comment]
Good news! I took out the sphax texture pack from the file, and it started working again! But, I still want the texture pack, could u recommend a pack for me? I have a Mac OSX

**Comment by The-1-7-10-Pack** [comment]
If your computer is having a hard time with the 64x, try out the 32x :)
