### ISSUE TITLE
Mod Suggestions ''Ztones''

### ISSUE THREAD

**Issue by Alakatria** [The-1-7-10-Pack/The-1.7.10-Pack#545]
It is a decorative mod adding a lot of futuritic looking block , I know chisel 2 is already in the pack but it is still complementaray with it.

Link to the mod : http://www.curse.com/mc-mods/minecraft/224369-ztones

Also just want to say , i really apreciate your modpack and can't imagine all the work behind so if i can help a bit let me know

**Comment by The-1-7-10-Pack** [comment]
Thank you for the appreciation!
About the mod - it's nice, but not really necessary. It won't be added to the pack.
Thanks anyway for suggesting!
