### ISSUE TITLE
ChickenChunks' Chunk loaders not working in the nether

### ISSUE THREAD

**Issue by retrozool** [The-1-7-10-Pack/The-1.7.10-Pack#546]
Well it's kind of necroing an old thread (#276), but I have the same issue with Chicken Chunk loaders in the 1.7.10 pack v0.7.6c
It seems like only ChickenChunks' Chunk Loader don't work (they even are not animated it I put them down in the nether) 
using /chunkloaders shows "0 forced chunks" - if I put the chunk loader in the over world it works perfectly.
And a quarry works because it seems to keep the chunks loaded in a different way (/chunkloaders shows 2 forced chunks)
any thoughts on that?

**Comment by retrozool** [comment]
sorry - that was a COMPLETE user derp :-( seems to work as expected - Thanks for the great pack!
I enjoy playing it a lot!

**Comment by The-1-7-10-Pack** [comment]
:+1:
