### ISSUE TITLE
MFFS Bug (and crash reports)

### ISSUE THREAD

**Issue by Jakorosin** [The-1-7-10-Pack/The-1.7.10-Pack#55]
I found a bug. MFFS has always been a buggy/challenging mod to implement, I know. So here's what happened: both times, I went to plug a 'cube' shape module into the projector, and it abruptly crashed on me (thank God for AromaBackup, is all I have to say). The first time I did it, the projector was on, so I figured that had messed things up. The second time, though, the projector was off.

Oh, and this is a client bug. :)

Crash reports:
Numba One paste.ubuntu.com/9701138/
Numba Two paste.ubuntu.com/9701141/

**Comment by The-1-7-10-Pack** [comment]
Indeed, MFFS is challenging.
You should report it there though: http://tracker.calclavia.com/issues?q=project%3A+%7BModular+Force+Field+System%7D

**Comment by Jakorosin** [comment]
Got it, thanks. :)
