### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Optiguest** [The-1-7-10-Pack/The-1.7.10-Pack#551]
i start the game and it loads for like 5 sec then it crashes...no log!

**Comment by The-1-7-10-Pack** [comment]
Please give me your latest client log (not crash log)

**Comment by Optiguest** [comment]
um, it seemed to work now, dont know what i did but i cant remove this thread, thx tho!

**Comment by The-1-7-10-Pack** [comment]
Sure!
