### ISSUE TITLE
Myths & Monsters Mod[suggestion]

### ISSUE THREAD

**Issue by iloveadv69** [The-1-7-10-Pack/The-1.7.10-Pack#552]
Hi ,I hope I am not too late for suggestions.
This was a popular mod back then,2 years ago?
anyway it recently got updated to 1.7.10

Myths &Monsters Mod is a well balanced,non-op mod
which adds different types of mobs from legends/Myths in different biomes(vanilla).
dessert,mesa,ocean,hills....etc

There are rare human mobs"hunters" who you can team up for adventures aswell.
I hope this small mod could fit in to the pack.

link:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2157350-1-7-2-1-7-10-v1-0-2-myths-and-monsters-mod-new

**Comment by The-1-7-10-Pack** [comment]
This can be a really cool mod for an adventure-type modpack but it doesn't really fit here. Thanks anyway for suggesting!
