### ISSUE TITLE
Thaumcraft Wand Foci

### ISSUE THREAD

**Issue by kenpachol** [The-1-7-10-Pack/The-1.7.10-Pack#553]
hey guys, 
there is a problem with the keybinding of the thaumcraft Wand Foci.
i was wondering if you know a way to change it?

**Comment by The-1-7-10-Pack** [comment]
Simply change it on your controls menu? I can't fix this problem by default because other mods that don't give a config option took this key already.

**Comment by kenpachol** [comment]
oke, can you tel me where the control menu for thaumcraft is. 
i cant find it. please help
