### ISSUE TITLE
GB's DepLoader Error

### ISSUE THREAD

**Issue by spitfire1824** [The-1-7-10-Pack/The-1.7.10-Pack#556]
Whenever I launch the modpack it starts to load and then a window pops up saying 

CB's DepLoader was unable to download required library slick-util-0.0b9db0b2.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/slick-util-0.0b9db0b2.jar and put it in your mods folder.

When I click the link it takes me to a non-existant page and I have tried resetting the pack, deleting and re-installing the pack and it still says this every time.
PLEASE HELP

**Comment by The-1-7-10-Pack** [comment]
This is known and it's due to a host problem of a specific mod. I hope it'll get fixed soon, but it has nothing to do with your system.

**Comment by funkyrowanpixie** [comment]
yeah im having problems too. A file called vorbis java core wont download plus i cant download it from the link its given me

**Comment by The-1-7-10-Pack** [comment]
@funkyrowanpixie Obviously, if the loader were not able download it why would you able?

**Comment by funkyrowanpixie** [comment]
ok thanks

**Comment by The-1-7-10-Pack** [comment]
@spitfire1824 @funkyrowanpixie Should be working now, can you guys confirm?

**Comment by r5416** [comment]
A download error has occurred #615
