### ISSUE TITLE
Touching the Sky Quest Bug

### ISSUE THREAD

**Issue by LeSwagMaster** [The-1-7-10-Pack/The-1.7.10-Pack#557]
I just discovered a bug with the "Touching the Sky"

![2015-05-07_21 00 48](https://cloud.githubusercontent.com/assets/12313467/7528840/bfff707a-f4fc-11e4-9283-33e011e5fb04.png)

I have all the required stuff for the quest but it won't accept it :(

**Comment by The-1-7-10-Pack** [comment]
Did you build the two sit or one sit plane?

**Comment by LeSwagMaster** [comment]
The one sit. I don't know if it's the  engine (V4 Engine) I used or if something is actually wrong.

Thanks for answering!

**Comment by The-1-7-10-Pack** [comment]
Uh huh. The quest is set to the rotary engine, it'll change to detect whatever engine next version. Thanks for reporting!
