### ISSUE TITLE
Game Laucher

### ISSUE THREAD

**Issue by nate2crush** [The-1-7-10-Pack/The-1.7.10-Pack#558]
So I go into the Technic Launcher as usual.
I installed your modpack.
I hit play and it goes through the final configuration aspects of the mod to finalize the initial installation and to pull resources if any are there.
The previous step finishes and the technic pack launcher flashes and no minecraft game menu opens. It is not even in my task manager.
I have no Idea whats going on to be honest and would really like to try out your mod, but this is stopping me from doing so.

**Comment by The-1-7-10-Pack** [comment]
You probably have the wrong Java version. You need Java 7/8 and 64 bit.

**Comment by Matterhorn3** [comment]
i have the same problem and i got java 7&8 on..

**Comment by Matterhorn3** [comment]
got java 7 and 8 on 64 
still not starting

**Comment by The-1-7-10-Pack** [comment]
I need your latest log.

**Comment by Matterhorn3** [comment]
hmm how can i send you my log i have to upload it somewhere?

**Comment by The-1-7-10-Pack** [comment]
@Matterhorn3 http://pastebin.com/

**Comment by Matterhorn3** [comment]
file:///D:/Games/Technic%20Launcher/logs/techniclauncher_2015-05-11.log

**Comment by Matterhorn3** [comment]
woops i dont htink that did work so haha

**Comment by The-1-7-10-Pack** [comment]
I need the text inside it.

**Comment by Matterhorn3** [comment]
uhm how do i upload that on pastebin :S

**Comment by Matterhorn3** [comment]
http://pastebin.com/LGPeeuQA

**Comment by The-1-7-10-Pack** [comment]
@Matterhorn3 Do you have any additional mods?

**Comment by Matterhorn3** [comment]
uhm not that i can think off i just download'd the pack and try'd to start it :S

**Comment by Matterhorn3** [comment]
i reinstallt it now for the 10th time now it lookslike it would work thx for your time buddy :D

**Comment by The-1-7-10-Pack** [comment]
Good! :)
