### ISSUE TITLE
Shop prices (Possible)

### ISSUE THREAD

**Issue by KLuebbert** [The-1-7-10-Pack/The-1.7.10-Pack#56]
Stone 64    (200B, 10S)                                

Grass Block 64 (1000B, 100S)            

Dirt 64        (200B, 10S)            

Podzol 64    (1000B, 150S)            

Cobblestone 64    (200B, 10S)            

Oak Sapling 16    (150B, 5S)            

Spruce Sapling 16    (150B, 5S)    

Birch Sapling 16    (150B, 5S)            

Jungle Sapling 16    (150B, 5S)            

Acacia Sapling 16    (150B, 5S)    

Dark Oak Sapling 16    (150B, 5S)    

Sand 64    (200B, 20S)

Red Sand 64    (300B, 50S)

Gravel 64    (300B, 20S)

Sponge 1    (1000B, 500S)

Glass 64    (400B, 20S)

Sandstone 64    (800B, 50S)

Chiseled Sandstone 64    (800B, 50S)

Smooth Sandstone 64    (800B, 50S)

Note Block 8    (500B, 50S)

Powered Rail 32    (300B, 100S)

Detector Rail 16    (300B, 100S)

Sticky Piston 8    (400B, 50S)

Cobweb 8    (200B, 50S)

Piston 8    (400B, 50S)

Wool 16    (100B, 20S)

Bricks 64    (500B, 50S)

Bookshelf 4    (500B, 50S)

Moss Stone 64 (1000B, 200S)

Obsidian 16    (1500B), (250S)

Rail 32    (200B, 20S)

Ice 64    (500B, 50S) 

Snow 64    (500B, 20S)

Cactus 16    (150B, 10S) 

Clay 64    (500B, 50S)

Jukebox 1    (1200B, 100S)

Pumpkin 64    (300B, 50S)

Netherrack 64    (200B, 5S)

Soul Sand 64        (250B, 50S)

Glowstone 64    (1200B, 200S)

Stone Bricks 64    (200B, 20S)

Mossy Stone Bricks 64    (500B, 50S)

Cracked Stone Bricks 64    (500B, 50S)

Chiseled Stone Bricks 64    (500B, 50S)

Iron Bars 16    (500B, 50S)

Glass Pane 64    (100B, 0S)     

Vine 16    (150B, 5S)

Mycelium 64    (1500B, 50S)

Lily Pad 16    (150B, 20S)

Nether Brick 64    (200B, 5S)

Endstone 64    (1200B, 50S)

Redstone Lamp 8    (800B, 50S)

Beacon 1    (5000B, 500S)

Block of Quartz 16    (1000B, 20S)

Chiseled Quartz Block 16 (1000B, 20S)

Pillar Quartz Block 16 (1000B, 20S)

Activator Rail 16    (300B, 100S)

Hardened Clay 64    (500B, 50S)

Packed Ice 64    (1200B, 20S)

Bauxite Ore 16    (2500B, 100S)

Temple Pillar 64    (1200B, 200S)

Temple Pillar (Damaged) 64    (1200B, 200S)

Temple Brick 64    (1200B, 200S)

Temple Block 64    (1200B, 200S)

Temple Stairs 64    (1200B, 200S)

Temple Brick Stairs 64    (1200B, 200S)

String 8    (50B, 20S)

Feather 8    (50B, 20S)

Gunpowder 8 (50B, 20S)

Leather 8 (100B, 20S)

Snowball 16 (100B, 0S)

Clay (Item) 64 (150B, 10S)

Sugar Cane 16    (100B, 20S)

Book 8    (200B, 10S)

Slimeball 8 (150B, 20S)

Egg 16    (200B, 5S)

Glowstone Dust 64 (300B, 50S)

Ink Sac 8 (50B, 20S)

Bone 8 (150B, 50S)

Sugar 8 (50B, 20S)

Rotten Flesh 32 (50B, 50S)

Ender Pearl 8        (500B, 20S)

Blaze Rod 8    (100B, 10S)

Ghast Tear 8    (500B, 20S)

Nether Wart 32    (200B, 5S)

Spider Eye 8    (50B, 20S)

Fermented Spider Eye 8    (50B, 20S)

Mushroom (Red) 16    (200B, 10S)

Mushroom (Brown) 16    (200B, 10S)

Magma Cream 8    (150B, 20S)

Bottle o’ Enchanting 32    (1000B, 500S)

Nether Quartz 64    (1000B, 20S)

I made this for my friend's server which he never made, so I thought 3 hours on nothing. But hey, maybe it can come to use, there are no prices for ores because me and my partners who were interested in the server liked the idea of players getting ores themselves. Enjoy!

-KLuebbert

**Comment by Flukethoughts** [comment]
I like that u posted it but wtf is B we use gold lol

**Comment by KLuebbert** [comment]
B is Buy, S is Sell. These prices are for actual in-game money =P

**Comment by The-1-7-10-Pack** [comment]
Thank you very much! we may use it (:
