### ISSUE TITLE
1.7.10 pack bugged world

### ISSUE THREAD

**Issue by PoopingRhino65** [The-1-7-10-Pack/The-1.7.10-Pack#560]
My world crashes about a second after I load it. I had a very old backup and restored that, and the world worked for another hour or so. Then it crashed again and I have been unable to play on it since. Even the automatic AromaBackups are bugged and don't work. I have the crash report pasted below, any help?

**EDITED: Please use a paste-tool: http://pastebin.com/WjMVF9KT**

**Comment by The-1-7-10-Pack** [comment]
Your quest data is bugged. Did you use the quest or mess with them?

**Comment by Papajo01** [comment]
have the same crashes and can not start the world again. If i change the Player position in MCedit 200-300 bloks it works sometimes for the next 2-3 hours. currently I only play with tech mods.

my last Crash Report:  http://pastebin.com/reU9gV4a

**Comment by The-1-7-10-Pack** [comment]
@Papajo01 That's a bug from Mekanism that got fixed.

**Comment by The-1-7-10-Pack** [comment]
@PoopingRhino65 & @Papajo01 Try with the modpack version 0.7.7. Should work. Will re-open if not.
