### ISSUE TITLE
Modpack Server

### ISSUE THREAD

**Issue by skohlhepp** [The-1-7-10-Pack/The-1.7.10-Pack#562]
So recently I have been playing this modpack, and I must say that it is freaking awesome. Because of how awesome it is, I want to start a server because this modpack can make it big. However there are a few issues. The main thing in my opinion that separates this modpack from one of those default technic ones like tekkit is that the tekkit pack can be handled by almost any computer. With this modpack, on my old computer, it takes 20-30 minutes just to start up, something that not many people would be willing to wait around for. So, my proposition is to possibly cut out some extraneous mods for a number of reasons. Firstly, it is much easier on the client, and secondly, it would be much easier on a server. Those two things are a big part of what makes a mod pack good and usable for everyone.

I have extensive experience running technic servers and had two top servers for the Voltz and BigDig when it used to be popular. If you care I can provide more details about the success of my servers but for now thats all I will say. I dropped the whole hosting gig when I started school last fall and have received countless emails to bring them back. I want to start up a really big and awesome 1.7.10 pack server and I want a lot of people to know about it. Right now this pack is relatively small and not very well known. We can change that. This modpack offers so many aspects of gameplay and that is important to a good and successful server. I want to start up a team here. I'm not saying that im the best and that I can do it all or anything like that. Of course I would be willing to put down considerable investment of money and time into the pack and the server to help make it successful. 

So if the creator of this pack, Hi It's Me, or anyone else reading this is interested in anything that I have talked about then please lets work together to get this pack the recognition it deserves. Additionally, I know I talked about removing mods but you might consider adding MFFS and ICBM XD

Thanks guys,

Scott

**Comment by CriticalRocket** [comment]
Well, the server isn't really a problem IMO, sorry!
I'm running it on my laptop, and it takes about 5 - 10 minutes to startup. I can then play minecraft and run the server on the same computer smoothless (tested with 5 friends simultaneously, few more probaby wouldnt be a problem either). I's not a gaming laptop. Samsung Ativ book 6.

Intel i5 3230M (2.6 ghz)
8GB DDR3-1600
AMD Radeon HD 8850M (2048 MB)
win 8.1


Besided that, if you really want to have a good/famous server, you'll need to have it running 24/7. You won't need to start up/shut down often if all goes well, so then it's not a problem at all. 
It's not right to ask the modpack to downgrade when your own hardware just isn't all that great. I don't know what your using, but 20-30 mins is a LOT of time. I can recomment using a program like Razer Cortex or AVG Tuneup, which have features to turn off programs running in the background to give more RAM and CPU to your games. 

Whats your hardware if I may ask?

**Comment by skohlhepp** [comment]
My current computer runs it just fine. I just assume that not everyone has amazing computers but its no issue none the less. And I am ready to have the server up 24/7 with dedicated hosting thats not an issue. I just need people to help me with it and start it up and be admins and what not. But my idea was to possibly get this server up as the official server for this modpack or something like that so thats why I posted on here to gain support and a team. I easily could just start it up on my own but I want this to be big ya know..

**Comment by The-1-7-10-Pack** [comment]
How do you think you'll be able to run a big public server with no plugins? It's challenging.

**Comment by skohlhepp** [comment]
I have been able to set up a test server running Cauldron 1.7.10 and all of the mods work fine and plugins as well. If you aren't familiarize with that project it was formerly MCPC+ which I used to run those other servers I mentioned. It's basically a combination of forge and bukkit

**Comment by The-1-7-10-Pack** [comment]
Cauldron is very problematic as it's code is very old. Problems such as random time outs may occur.

**Comment by skohlhepp** [comment]
I mean if you don't think it's a good idea to start a server then I won't, I just thought that this modpack could offer a lot when combined with plugins like factions and a solid economy and such

**Comment by skohlhepp** [comment]
I know there has been issues in the bukkit community with the EULA and that there won't be any more updates for it and all the plugins are screwed then, Mojang really screwing us lol

**Comment by skohlhepp** [comment]
I mean since the pack is called 1.7.10 we cold just stay on 1.7.10 for a while at least until new things like bukkit come up. Do you have any plans to ever change the name of the pack like say if you wanted to update all the mods to 1.8 eventually?

**Comment by The-1-7-10-Pack** [comment]
@skohlhepp Let's keep future plans in the future.

**Comment by skohlhepp** [comment]
So you do or don't think it's a good idea for me to start up a server

**Comment by The-1-7-10-Pack** [comment]
@skohlhepp It's your decision, I won't tell you what to do. You can try and see if you encounter any problems.

**Comment by skohlhepp** [comment]
Okay so I have gotten a server up and running smoothly, Im just wondering what is the possibility of getting it to be the official server for the pack, I mean I could have a portion of all donations go to you or anything that you want really, the name, part ownership of the server whatever. I just want this to be successful.

**Comment by The-1-7-10-Pack** [comment]
@skohlhepp Currently no, I don't want any server to be "official". Anyway good luck with the stuff

**Comment by skohlhepp** [comment]
This server is coming along very well, what about the possibility of it becoming a recommended server? For example ours along with any other you find that is good comes up in the server lost by default on the client?

**Comment by skohlhepp** [comment]
@The-1-7-10-Pack Like I just want to know if it is a future possibility. That would be my goal and its a lot of work to put into a server for a modpack that isn't all that popular yet.

**Comment by skohlhepp** [comment]
@The-1-7-10-Pack I have put weeks of work into this, could you list my server on that list of community servers you posted the other day? It would mean the world if you came on and have a look at how great it is. The IP is blackwood.beastmc.com running 0.7.6c

**Comment by The-1-7-10-Pack** [comment]
@skohlhepp Added
