### ISSUE TITLE
Sugestion - Pistronics 2: and AoA

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#563]
this mod i think would fit in very well into the mod pack it gives the ability to create massive moving structures, i myself use it injunction with ancient warfare mod at present i have built the Jurassic parks doors that open and close. 
 
The core features of this mod are modular pistons and rotators. Modular meaning that multiple blocks in the world interact in a way so you can move and rotate structures of any size and shape. This can be used to build things like slide/swing doors, quarries, elevators or even vehicles.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294844-pistronics-2-modular-pistons-rotators-and-statues

great mod i added myself and was blown away this would open up the adventure side of the mod
18 New Dimensions• 300 Mobs• 27 Bosses• 450+Items• Skills• if i knew how to make quest i would make one this would add hrs onto playing and needing more stuff to build from other parts of the mod. 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286381-aoa-18-new-dimensions-300-mobs-27-bosses-450-items

**Comment by The-1-7-10-Pack** [comment]
Pistronics is a very cool mod, but currently it's just not stable enough. We may add the mod at the future, but not now. As for "AoA", the mod fits more Adventure type modpacks and not The 1.7.10 Pack.
Thanks anyway for suggesting!
