### ISSUE TITLE
Crash on launch with Mac or Linux in v0.7.7

### ISSUE THREAD

**Issue by Noxialis** [The-1-7-10-Pack/The-1.7.10-Pack#564]
It begins to load, but crashes before reaching the title menu.

[Crash report](http://paste.ubuntu.com/11115626/)

**Comment by The-1-7-10-Pack** [comment]
Weird..it's a Forge error I didn't see before.

**Comment by notorganic** [comment]
I have the same issue, clean install on MacOSX

http://pastebin.com/yE0PFrt4

**Comment by The-1-7-10-Pack** [comment]
You both are not using Windows. I'm aware that there was a problem like this with Forge 1400, incompability with LiteLoader and Optifine, but it shouldn't be like this now.

**Comment by Noxialis** [comment]
Linux mint 17.1 if that helps at all.

**Comment by The-1-7-10-Pack** [comment]
@Noxialis, @notorganic It's a problem with Forge and some different OS than Windows, if there would be an option to disable the fancy new loading screen that makes this problem I'll change it so it won't happen. There might be a new hotfix version of the pack soon, but for now you should go back to 0.7.6.

**Comment by The-1-7-10-Pack** [comment]
@Noxialis, @notorganic Please go to the modpack's folder and then to the config folder, enter a file named "splash.properties", and there in line 10 set "enabled" to false. Try to launch again. Update me ASAP please.

**Comment by notorganic** [comment]
I don't seem to have a splash.properties file in config. Am I doing something wrong, or need to create it?

![screen shot 2015-05-14 at 12 11 55 pm](https://cloud.githubusercontent.com/assets/12432222/7624847/6ffe0eac-fa32-11e4-9dfc-7f74d35b71d8.png)

**Comment by Noxialis** [comment]
Oh, thank you, that did the trick.

@notorganic I didn't have to create the file, as it was already there, however you could try to see if that works? Here's mine, the one that made it work:

#Splash screen properties
#Thu May 14 08:10:35 CEST 2015
logoTexture=textures/gui/title/mojang.png
background=0xFFFFFF
font=0x0
barBackground=0xFFFFFF
barBorder=0xC0C0C0
rotate=false
bar=0xCB3D35
enabled=false
resourcePackPath=resources
logoOffset=0
forgeTexture=fml\:textures/gui/forge.gif
fontTexture=textures/font/ascii.png

**Comment by notorganic** [comment]
I just found it, I hadn't enabled hidden files on this machine yet. Dumb oversight on my part.

Setting to false worked a treat, thanks guys.

**Comment by The-1-7-10-Pack** [comment]
@Noxialis @notorganic Ok good, expect a small update to hit today, will disable the loading screen by default.

**Comment by Noxialis** [comment]
You're a champ, thanks for everything :)

**Comment by The-1-7-10-Pack** [comment]
@Noxialis & @notorganic v0.7.7a is launching okay, right?

**Comment by Noxialis** [comment]
Sure is, thanks for the quick fix :)

**Comment by The-1-7-10-Pack** [comment]
@Noxialis Good :+1: 
Be sure to report if you find anything else, hoping to bump 0.7.7a to Recommended soon.
