### ISSUE TITLE
Pack does not want to launch

### ISSUE THREAD

**Issue by Excepto** [The-1-7-10-Pack/The-1.7.10-Pack#567]
The game (with the pack) does not launch. It says error in the console but thats all i know really
https://drive.google.com/file/d/0B8nZekFnT16kbmhrRnBQZy1kQ1E/view?usp=sharing

**Comment by The-1-7-10-Pack** [comment]
You have Java 32 bit.

**Comment by Excepto** [comment]
SO i just install 64-bit?

**Comment by The-1-7-10-Pack** [comment]
Uninstall the current one and install 64 bit.

**Comment by Excepto** [comment]
thanks
