### ISSUE TITLE
Server Restarting

### ISSUE THREAD

**Issue by jinkhya** [The-1-7-10-Pack/The-1.7.10-Pack#568]
Hello, just updated to 0.7.7, the server i'm running is working fine but it somehow restarts pretty often (like every 10 or 15 mn). Is there any configuration file that needs to be edited or something. (It didn't do that on 0.7.6c)
Otherwise, greatwork, I love this modpack ^^
Cya

**Comment by The-1-7-10-Pack** [comment]
0.7.7 or 0.7.7a? Anyway I need your crash report. Please use a [paste-tool](http://paste.ubuntu.com/).

**Comment by jinkhya** [comment]
I tried 0.7.7a, same problem. I reinstalled 0.7.6c, it doesnt happen. It doesnt seem to crash, just restart. I don't see any crash report (or maybe i'm not looking in the right place) I only have a "logs" folder.

**Comment by The-1-7-10-Pack** [comment]
So give me your latest server log, and use the paste-tool.

**Comment by AzzaBGitHubories** [comment]
http://paste.ubuntu.com/11170369/

I'm not sure if this will contain much information but it's kinda hard to grab information from the console when the problem is it restarting :P 

Thanks!

**Comment by The-1-7-10-Pack** [comment]
@AzzaBGitHubories Are you sure that that's the right (and full) log? I need the "fml-server-latest.log" file.

**Comment by AzzaBGitHubories** [comment]
http://paste.ubuntu.com/11170859/

There we are, sorry about that!

**Comment by The-1-7-10-Pack** [comment]
@AzzaBGitHubories All I see in the log is a normal log. How the server restarts actually? can you give me the details?

**Comment by AzzaBGitHubories** [comment]
Um, there ain't really much to say :/ Just every say 20 minutes the server will automatically restart itself even with an empty server. The server will boot, will remain up for 20 minutes give or take, then restart and repeat this process all day... :/

Is there anything more I could provide in the way of files or logs that could help determine the problem?

Thank you :)

**Comment by jinkhya** [comment]
Same is happening to me, it just seems to be restarting. 
Here is my log, if you can find any information : 
http://paste.ubuntu.com/11173346/

**Comment by jinkhya** [comment]
I'm using forgemod by the way.

**Comment by The-1-7-10-Pack** [comment]
@AzzaBGitHubories I'm just seeing a normal log of a server. I guess that when the server restarts it makes a new log. @jinkhya What do you mean by saying "forgemod"?

**Comment by jinkhya** [comment]
As server type, i'm not using cauldron but forgemod :)

**Comment by The-1-7-10-Pack** [comment]
Okay. I do see that you're both using Windows Server 2008/

**Comment by jinkhya** [comment]
I can't I'm using a server on roxservers.com :( never had a pb with their offer before :(

**Comment by AzzaBGitHubories** [comment]
Holy shit wait dude, I'm using RoxServers as well... So it must be on the host side right?...

**Comment by jinkhya** [comment]
holy .... oO But why would 0.7.6c work fine but not 0.7.7+ though?

**Comment by The-1-7-10-Pack** [comment]
0.7.6c -> 0.7.7a had a HUGE change in the Forge versions. Forge's dev can't be stopped and we can expect even more big changes soon. You guys should contact the company, good luck!

**Comment by jinkhya** [comment]
what should we ask for then? new java?

**Comment by The-1-7-10-Pack** [comment]
I'm not too sure. It may has something to do with the Java version, although I doubt it. Maybe the Windows Server. You may also want to consider getting support from Forge in their [forums](http://www.minecraftforge.net/forum/index.php/board,15.0.html) of [GitHub repository](https://github.com/MinecraftForge/MinecraftForge/issues).

**Comment by jinkhya** [comment]
alright then. Well thanks for you help anyway :)

**Comment by jinkhya** [comment]
Hello,

After talking to roxservers, they found what was the problem, so i'm sharing with you what you have to do to fix it : you have to delete the mod "inpurecore" on your server. It's been 1H45 that my server has been up and no restart. So it seems to be working with 0.7.7a perfectly fine now :)

**Comment by The-1-7-10-Pack** [comment]
@jinkhya Try to use the latest build of INpureCore (from [here](http://minecraft.curseforge.com/mc-mods/223792-inpurecore/files/2238507)). Does it fix the issue? it should.

**Comment by AzzaBGitHubories** [comment]
Yes the updated version of INpure core seems to work fine! Server has been running for 40+ minutes now with no restart!:) Thanks @jinkhya and @The-1-7-10-Pack :)

**Comment by jinkhya** [comment]
same here, thanks :) I'm glad we found a solution :D

**Comment by The-1-7-10-Pack** [comment]
Alright, so we'll consider releasing another hotfix version
