### ISSUE TITLE
0.7.7/0.7.7a (Forge?) Problem

### ISSUE THREAD

**Issue by Deathwinng** [The-1-7-10-Pack/The-1.7.10-Pack#569]
Hello, I got a problem with the new update. I hit play, the launcher closes an re-open. I searched the error on google and I believe the problem is forge but I'm not sure, and I have no idea how to fix it.
Re-installed modpack - no luck
re-installed java 8/7 - nope
tried with/without additional mods - same error
I really want to play with Mystcraft, so any help will be appreciated!
[Log](http://paste.ubuntu.com/11145166/)

**Comment by The-1-7-10-Pack** [comment]
You're using the Technic Launcher?

**Comment by Deathwinng** [comment]
Yes, I'm using Technic Launcher, and deleting the modpack's folder doesn't fix the problem.

**Comment by The-1-7-10-Pack** [comment]
@Deathwinng Try to launch [another modpack with the latest Forge version](http://www.technicpack.net/modpack/project-omnius-pack.631908), are you able to?

**Comment by Deathwinng** [comment]
Same things happen with that modpack, and almost the same error. 
[Log](http://paste.ubuntu.com/11146983/)

**Comment by The-1-7-10-Pack** [comment]
And everything is working with 0.7.6c?

**Comment by Deathwinng** [comment]
Yes, I was playing the day before the 0.7.7 update without problems.

**Comment by The-1-7-10-Pack** [comment]
So your system has some problems with the latest Forge updates. You should go to [Forge's GitHub page](https://github.com/MinecraftForge/MinecraftForge/issues) to get support, nothing I can do!

**Comment by Deathwinng** [comment]
Thanks for trying to help and sorry for wasting your time. :)

**Comment by The-1-7-10-Pack** [comment]
Happy to help :)
