### ISSUE TITLE
[Mod Suggestion] Hardcore Ender Expansion

### ISSUE THREAD

**Issue by KLuebbert** [The-1-7-10-Pack/The-1.7.10-Pack#57]
http://hardcore-ender-expansion.wikia.com/wiki/Home

The End is boring, once you beat the Ender Dragon, all the End is, is a lot of endermen, useless endstone, and obsidian which you can get anywhere else. But with Hardcore Ender Expansion, it adds meteors randomly out in space, it adds 3 new end based biomes that generate on other endstone islands other than the main one, and giant towers found in the end with great loot and dangers lurking inside! This mod doesn't add much gear or useful things that can alter gameplay, but rather make the End a more exciting place to be.

Also, one of the best features of the mod, is it makes the Ender Dragon learn new moves, and makes it more difficult based on the difficulty of the world. So if you thought the Ender Dragon was easy, think again with this mod.

**Comment by The-1-7-10-Pack** [comment]
What do you think guys? I want to see more comments! (:

**Comment by KLuebbert** [comment]
Want to see more comments? You didn't say what you want in them xD, so here's a comment for you! (lol)

**Comment by Alexander175** [comment]
I think it would be awesome!

**Comment by The-1-7-10-Pack** [comment]
Well I feel bad I won't stop you for helping [;
Currently I am working on the new update and there are couple of things that are stopping me from launching. Also big changes on the official public server. The only thing is that everything is basically in the middle of the progress so nothing new for now. Adding HEE? Not in the next update. We have new quests and big mod updates. Not everything together. Maybe in the future.

**Comment by maartenblom** [comment]
I think it would be a great idea

**Comment by djandy** [comment]
he is rite at the moment all im trying to get to the end for is ender pearls with a sword i found in a chest but after i kill the very easy enderdragon in whisp form and maybe kill a few ender men for there pearls thats it end is done no reason for adventure :D

**Comment by DragonOfStendarr** [comment]
I agree, would be better with Hardcore Ender Expansion. x)

**Comment by The-1-7-10-Pack** [comment]
Yep.
