### ISSUE TITLE
[question] Any advice would be appriciated 

### ISSUE THREAD

**Issue by oryfoxer7410** [The-1-7-10-Pack/The-1.7.10-Pack#571]
I know you cannot support cauldron, but we have a server that is just being killed on chunk generation. I want to setup worldborder and generate the world for performance reasons. 

I attempted using FE, but the filler starts, runs for a little bit, then completely fails out. 

I tried starting the server with Cauldron, but no go, I continue to get the same error, "A problem occurred running the Server launcher".

I am using the Cauldron files to match the forge version from http://tcpr.ca/cauldron

Any suggestions or ideas on getting Cauldron to work or a working port for worldborder besides the one contained in FE?

**Comment by oryfoxer7410** [comment]
BTW. Server is dedicated - 32 GB Xeon 1270.

**Comment by The-1-7-10-Pack** [comment]
[/pregen](http://minecraft.curseforge.com/mc-mods/221584)
