### ISSUE TITLE
RotaryCraft

### ISSUE THREAD

**Issue by extraordinaryguy** [The-1-7-10-Pack/The-1.7.10-Pack#572]
Reika's RotaryCraft mod offers really cool new machines and ways of power generation, it's one of my favorite mods and it would be nice, if you think about adding it to the modpack ;D

**Comment by The-1-7-10-Pack** [comment]
People suggested RotatyCraft many times and it won't be added. The mod doesn't really fit the modpack. Thanks anyway for suggesting!
