### ISSUE TITLE
flans mod problem

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#573]
the recipe of sentry gun and flakvierling-38 AA gun are the same,making it impossible to craft sentry gun

**Comment by The-1-7-10-Pack** [comment]
You're crafting them in a special block from the Flan's Mod or in the crafting table?

**Comment by The-1-7-10-Pack** [comment]
Well, in general it's a mod-bug, but we have a mod in The 1.7.10 Pack that makes it possible to fix recipe confilicts. Go to the Controls menu and under the "GUI" section you'll find the "RecipeSwitch" key. Set it to an open key, then when you're in the crafting table click it to switch between recipes. Works like a charm.
