### ISSUE TITLE
Agricraft Mod suggestion

### ISSUE THREAD

**Issue by TANGOjPANDA** [The-1-7-10-Pack/The-1.7.10-Pack#575]
I have seen this mod a lot lately this is a great little mod, it is also compatible with magic crops (i am unsure of the latest beta version though). I think it is a great way to farm as well also has mod integration with MFFR. I thought i would leave this here cause from what i can tell no one has suggested it yet which i think is a shame.
I am unsire of the permisions for the mod though so you might have to look that up.
http://forum.feed-the-beast.com/threads/1-7-10-agricraft.50964/

**Comment by The-1-7-10-Pack** [comment]
The mod is really different but it doesn't really fit the pack. Thanks anyway for suggesting! :)

**Comment by sgdc3** [comment]
@The-1-7-10-Pack What's the issue with Agricraft? It doesn't change the gameplay too much...
