### ISSUE TITLE
My creations keep disapering

### ISSUE THREAD

**Issue by Shadowbull6130** [The-1-7-10-Pack/The-1.7.10-Pack#576]
Whenever i log off my single player world and log back on later,All of my creations are gone!I do not know why and this has not been a issue before so if anyone has a fix for this please tell me!

**Comment by The-1-7-10-Pack** [comment]
What do you mean by that? The game doesn't save?

**Comment by Shadowbull6130** [comment]
Well I still have my INVENTORY.but my house and stuff are gone.

**Comment by The-1-7-10-Pack** [comment]
How are you logging off? Do you just close the window, or actually going out through the menu?

**Comment by Shadowbull6130** [comment]
I press save and quit.and when i get back to the main menu i press the X

**Comment by The-1-7-10-Pack** [comment]
Try to exit the game through the menu button.

**Comment by Shadowbull6130** [comment]
Ill give that a shot

**Comment by Shadowbull6130** [comment]
Yeah its was still gone but my inventory saved

**Comment by The-1-7-10-Pack** [comment]
When did it start to happen? is it happening with just one specific save of with every save? I need more info to reproduce.

**Comment by Shadowbull6130** [comment]
It happend the first time i exited the modpack and has been happening since.

**Comment by Shadowbull6130** [comment]
ill try to see if it does it with other saves

**Comment by Shadowbull6130** [comment]
yeah it works now and i am having SO much fun with the modpack thanks

**Comment by The-1-7-10-Pack** [comment]
:+1:
