### ISSUE TITLE
Pack not launching

### ISSUE THREAD

**Issue by Selly12** [The-1-7-10-Pack/The-1.7.10-Pack#577]
So i just got this pack and i'm trying to play it. Nothing happens. When i press Play, it doesnt open a window. It just does grabbing blah blag. scale blah blah installing minecraft assests then just stays at the menu. please help i want to play this!!! i have it updated to!

**Comment by chanwiz0810** [comment]
i am having the same problems we need help plz help us i really want to play

**Comment by DakarMix** [comment]
Sometimes that happen to me, i just need to sign out windows or restart it and when i open it again it start working fine.

**Comment by Selly12** [comment]
ok ill try this out!! but please find out a solution i want to play this!

**Comment by The-1-7-10-Pack** [comment]
@Selly12 & @chanwiz0810: You have the wrong Java version, 99%. You need Java 7/8 with 64 bit. If that's not working for you, please report here your logs and I'll re-open the issue, closing it for now.

**Comment by Selly12** [comment]
thanks it worked

**Comment by The-1-7-10-Pack** [comment]
:+1:
