### ISSUE TITLE
Java Outdated

### ISSUE THREAD

**Issue by Joey-Nolan** [The-1-7-10-Pack/The-1.7.10-Pack#58]
When I try to launch the modpack it says "Outdated Java" even though I've deleted the old Java downloaded the new Java over and over but it still won't work! Help please!

**Comment by Silphsy** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html
Scroll down and go to the first set of links and downloads (7u 71 or something) and click on the link that matches your system. Make sure to click accept before downloading.

**Comment by illegalpoo** [comment]
hey this is also happening to me i have the latest version of Java however it still says that a mod requires java version 1.7 or later, please uninstall previous versions to prevent problems in the future. I have uninstalled my previous versions of Java and done what you said above but it still has the same error message
