### ISSUE TITLE
Crashing On NEI page

### ISSUE THREAD

**Issue by SuckAWhale** [The-1-7-10-Pack/The-1.7.10-Pack#580]
Edit: Weve narrowed it down to enderstorage, on removal of the mod the issue no longer happens. Since the mod only has a few items the removal should go unnoticed until a fix is found.
This also only happens on a server, not single player.
Around page ~~10-20~~ (Dependent on screen size, just flip through and youll hit it) it crashes the client, output from console

**EDITED: Please use a paste-tool: http://pastebin.com/yfrEQrMA**

**Comment by The-1-7-10-Pack** [comment]
I can already tell you that it's due to the use of the Unofficial Cauldron. Although, I can still help you and say that you're using an old version of it. Download the latest version of KCauldron from [here](https://prok.pw/git/Prototik/KCauldron/releases), and it might help you.
