### ISSUE TITLE
"Bug" or issue with Thaumcraft Sanity Checker

### ISSUE THREAD

**Issue by DakarMix** [The-1-7-10-Pack/The-1.7.10-Pack#581]
Greetings,
The Thaumcraft Sanity Checker doesn't bring up the bar on the top left of the screen like wands do.

Is suppose to bring up a bar like the one on the next screenshot:

![screenshot 42](https://cloud.githubusercontent.com/assets/11905609/7666331/f3f5ff7a-fbaf-11e4-8902-b81396a7f28e.png)
(This is a screenshot that i took from a video on youtube)

And this is the screenshot from my game:
![screenshot 46](https://cloud.githubusercontent.com/assets/11905609/7666370/bffab386-fbb0-11e4-8911-cfe2a0ee5f1b.png)

I just get to this part on Thaumcraft so i don't know if this "Bug" is new or is old.

Thanks a lot for the modpack, the best one that I've played so far and thanks in advance for the help =P

DakarMix.

**Comment by The-1-7-10-Pack** [comment]
![image](https://cloud.githubusercontent.com/assets/10350644/7667419/6136ffbc-fc0f-11e4-9066-e98da70af00e.png)
Maybe you're using Optifine?

**Comment by DakarMix** [comment]
confirmed, the problem is the sphax the 1.7.10 pack 64x, if I use the 32x or just the default resource pack there is no problem, I didnt think of that option, thanks a lot like always =D

**Comment by The-1-7-10-Pack** [comment]
We'll try to get a fix into the 64x version in the next update of the Sphax patch, thanks for reporting!

**Comment by DakarMix** [comment]
Always, Thanks to you guys for the great modpack and all the support! =P

**Comment by The-1-7-10-Pack** [comment]
@DakarMix The 64x patch has the GUI working on the latest version of it, just be sure to update your Sphax patch when you see it gets updated :)

**Comment by DakarMix** [comment]
Wow that was fast, thanks a lot again, hoping to be able to help you guys with a donation soon =D

**Comment by The-1-7-10-Pack** [comment]
Thank you :)
