### ISSUE TITLE
Blocks not loading/invisible blocks

### ISSUE THREAD

**Issue by Simmonds89** [The-1-7-10-Pack/The-1.7.10-Pack#582]
Hey! When I started a new world for the first time with this pack which I was really excited to play I found that certain blocks were not visable like bamboo, blueberry bushes and a few others... Also when digging the chunks hadn't loaded properly and I could stand in thin air but see right down to bedrock? Any answers?

**Comment by The-1-7-10-Pack** [comment]
Are you using Optifine?

**Comment by Simmonds89** [comment]
Yeah got it installed! I didn't notice at first was just walking and then couldn't move and noticed there was an invisible block in the way? Also when I crafted a wooden axe it chopped down the entire tree and when I made a crafting station from tinkers and put it down it was invisible?

**Comment by Scravey** [comment]
Last time I check Tinkers and Optifine together caused some invisible parts on characters, doors, and mobs. Could be related to that.

**Comment by The-1-7-10-Pack** [comment]
@Simmonds89 You have an old version of Optifine then. Use only the latest builds from [Optifine's website](https://optifine.net/downloads).
