### ISSUE TITLE
Trying to add plugins to the server. 

### ISSUE THREAD

**Issue by Scravey** [The-1-7-10-Pack/The-1.7.10-Pack#584]
Could anyone help me with this? With all the recent take downs it was hard to even find Cauldron and I can't seem to get it working for anything. Any help would be greatly appreciated.

Here is a link to what happens in the console, which I have found nothing on the internet with a solution. I have even gone looking in the depths of the internet... the second page of google search results.
http://i.imgur.com/fp5Dwj9.png
Clearly it is something with CoFH, but I was unaware Cauldron and it had incompatibility. So I did some googling and found out they updated it and fixed CoFH so that could work. However, I am aware of Cauldron and Fastcraft being rude. So I tried removing CoFH and Fastcraft, then this is what happened:
http://i.imgur.com/M02mfkx.png
So now Galaticraft also does not work? This is where I am truly stuck. FIY, I am aware Cauldron was abandoned.

**Comment by The-1-7-10-Pack** [comment]
You can't remove CoFH. Also use the latest "KCauldron" (unofficial) from [here](https://prok.pw/git/Prototik/KCauldron/releases). More than that I can't really help, it's not a part of the modpack and I don't recommend it. Plugins may be nice, but thinks may be very unstable.
