### ISSUE TITLE
The Game keeps crashing (Bug?)

### ISSUE THREAD

**Issue by RivalSpirit** [The-1-7-10-Pack/The-1.7.10-Pack#585]
I need help to figure how to fix a bug. I would assume. I've been playing this modpack for about a month. This is has happened to me twice. The first time I blamed it on for out dated java so, I had to restart the world. This time I have updated Java using and max amount of memory. The modpack would crash when I would open up the world. Not instantly though. It would say "Loading" then "Building Terrain" like as usual and then revert back to the home screen, which was also common. It would show the home screen for a brief second. Then it'll either crash right after or go black the crash. Yesterday I placed down mekanism blocks and items like Digital miner, logistical pipes, logistical sorter and some wiring. Is there a bug that im not aware of? Also I don't use optifine. 
Here is the Crash report from the start up of the modpack to the crash of it 

http://paste.ubuntu.com/11190439/ or http://paste.ubuntu.com/11190439/plain/ 

I really hope someone can help, and thank you.

**Comment by The-1-7-10-Pack** [comment]
Can you please use a [better paste option](http://paste.ubuntu.com/)? It'll be more clear there.

**Comment by RivalSpirit** [comment]
http://paste.ubuntu.com/11190439/plain/ or http://paste.ubuntu.com/11190439/
 I put the whole crash report from begening to end. So, I wont fit into
repository text box

**Comment by The-1-7-10-Pack** [comment]
Update the pack to it's latest version (set in the launcher to get the latest updates) - and it should fix it. Was a bug in Mekanism that got fixed.
