### ISSUE TITLE
The pack crashes when ran

### ISSUE THREAD

**Issue by awall200** [The-1-7-10-Pack/The-1.7.10-Pack#587]
every time I try to open the pack it opens for less that a 1/5 of a secound and then it crashes. I have deleted and redownloaded and launcher and the pack and nothing happened and i have switched around the versions too .what can I do to fix this problem?

**Comment by oryfoxer7410** [comment]
probably need 64 bit Java

**Comment by The-1-7-10-Pack** [comment]
You need Java 7/8 and 64 bit,
