### ISSUE TITLE
Don't know how to download

### ISSUE THREAD

**Issue by CycloneBlitz** [The-1-7-10-Pack/The-1.7.10-Pack#588]
![aaaa](https://cloud.githubusercontent.com/assets/12483280/7673739/c37b4902-fd4b-11e4-85cf-8b7d01144755.png)

When i download the 1.7.10 pack with the link (api.technicpack.net/modpack/the-1710-pack) it said "{   "status": 401,   "error": "Request Unauthorized" }" and i cant download again... Help again please!

**Comment by The-1-7-10-Pack** [comment]
Here's a video:
https://www.youtube.com/watch?v=aFfp0cj3640
