### ISSUE TITLE
Mods Suggestions: Orespawn or Ars Magica 2

### ISSUE THREAD

**Issue by teamgamersquad** [The-1-7-10-Pack/The-1.7.10-Pack#59]
Orespawn is a great mod for adventurous people and has many powerful bosses. Ars Magica 2 is a great mod for the pack, as it fits perfectly into the technical and scientific environment. If you can add them in, please do!

**Comment by The-1-7-10-Pack** [comment]
Ore Spawn does not fit the modpack, and Ars Magica may be added in the future if it'll be more stable.
Thank you anyway (:
