### ISSUE TITLE
Random fires

### ISSUE THREAD

**Issue by Shadowbull6130** [The-1-7-10-Pack/The-1.7.10-Pack#590]
Ok for some reason my house and other things i made can just randomly go on FIRE.I have no lava placed in the house anywhere and I wanted to know if anyone would have a explanation?Like is this taking the fun out of the modpack for me :(

**Comment by The-1-7-10-Pack** [comment]
You can check underground. Also it might my a lighting strike.

**Comment by oryfoxer7410** [comment]
lol

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
