### ISSUE TITLE
Unable to download required libary

### ISSUE THREAD

**Issue by lotrg54** [The-1-7-10-Pack/The-1.7.10-Pack#591]
i download this mod in latest version 0.7.7b and deploader loading and crashed
![sadasd](https://cloud.githubusercontent.com/assets/7364422/7772743/b4d941c8-00a8-11e5-9c2d-4b235616d770.png)

**Comment by lotrg54** [comment]
i try this mod in reconmended version but minecraft gives black screen..

**Comment by The-1-7-10-Pack** [comment]
It's not a crash. The servers that hosts the libs are down, just try again later it should work.

**Comment by lotrg54** [comment]
thanks

**Comment by lotrg54** [comment]
now game opened and i see the loading and intializing after this closed and back to modpacks..

**Comment by The-1-7-10-Pack** [comment]
This issue got fixed. You guys should try to reinstall if you have problems.
