### ISSUE TITLE
Server Has An Error

### ISSUE THREAD

**Issue by Malorn44** [The-1-7-10-Pack/The-1.7.10-Pack#594]
My server for version 0.7.6c of the modpack was working fine and now I am getting this:

**EDITED: Please use a paste-tool: http://pastebin.com/au1JGr1w**

**Comment by oryfoxer7410** [comment]
Try removing HardcoreQuesting folder from the world. Don't forget to backup.

**Comment by The-1-7-10-Pack** [comment]
Your questing data is corrupted. If you don't have much progress, you can try to delete the mod and readd it to reset the data. If it doesn't work I'll reopen the issue.
