### ISSUE TITLE
Crash on world start up

### ISSUE THREAD

**Issue by RivalSpirit** [The-1-7-10-Pack/The-1.7.10-Pack#596]
When I star up my original world, it would say building terrain and Loading world. Then it would revert back to the home screen then crash a few seconds after. It is only this particular world. Today there was start up problems that were fixed. I was unaware what it was so I re-downloaded the mod pack and the launcher and i saved the world in my computer. When I placed it back into the save folder it would crash. 
I hope you can help, 
Crash report:
http://paste.ubuntu.com/11297710/

**Comment by oryfoxer7410** [comment]
try enabling remove erroring  entities in your forge.cfg. You will notice its "not recommended".

Also, I think its a bug with Mekanism

**Comment by RivalSpirit** [comment]
I kind of understanding what you are saying. I am also on my Mac, so, that might make a difference.

**Comment by RivalSpirit** [comment]
Yeah, That didn't work. I have three copies of the world is there anything else I can do?

**Comment by oryfoxer7410** [comment]
You could try MCEDIT... Remove the ILogisticalTransporter

**Comment by RivalSpirit** [comment]
Alright i got the basics of mc edit. but the colors are confusing me. Researched it  but I never got a straight answer. 
Purple-(no texture? right?)
Green-
Yellow highlight-
Red highlight-

**Comment by RivalSpirit** [comment]
Also high would I know what part of the world is making it crash?

**Comment by oryfoxer7410** [comment]
Remove the Logistical Transporter as referenced here in your crash report

"java.lang.ClassCastException: TileMultipart_cmp$$40 cannot be cast to mekanism.common.base.ILogisticalTransporter"

**Comment by RivalSpirit** [comment]
Ok thanks

**Comment by BeardedGrue** [comment]
We saw this same problem on a private server.  Ultimately we identified it as a problem with the item pipes in Mekanism (* Logistical Transporter).  Once we removed these from our server, everything worked fine.  Sadly, we used server backups to restore the server, so I have no advice on how you would do this with MC Edit :(

**Comment by RivalSpirit** [comment]
MC Edit fixed it, Thanks oryfoxer7410

**Comment by The-1-7-10-Pack** [comment]
Happy to see you guys helping others!
