### ISSUE TITLE
Backup Help

### ISSUE THREAD

**Issue by ChiknNRiceGaming** [The-1-7-10-Pack/The-1.7.10-Pack#597]
I was mining for diamond, and finally found some, but of course i fell into the void and died w/ no explanation. My aroma1997 backed up my world right before i died, can anyone help me replace the world with a backup? ive tried looking for tutorials, but i cant find any ;(

**Comment by oryfoxer7410** [comment]
just unzip the backup under the folder "backup" in your main directory. Rename your current world to "world_" then put the zipped world in its place.

You can go back to "world_" by deleting the backup and removing the "_"

**Comment by ChiknNRiceGaming** [comment]
Thx man! I mined back to those diamonds and found dense diamond ore!!!!! I avoided the death glitch, and returned safely to my house

**Comment by The-1-7-10-Pack** [comment]
Thanks @oryfoxer7410
