### ISSUE TITLE
game is crash at loading and intializing screen

### ISSUE THREAD

**Issue by lotrg54** [The-1-7-10-Pack/The-1.7.10-Pack#598]
![dasd](https://cloud.githubusercontent.com/assets/7364422/7783832/02d062f2-0159-11e5-8bc4-b90c85702a33.png)
then the game back to modpack screen 
http://paste.ubuntu.com/11304791/

**Comment by TheLegend714** [comment]
Let it load fully and don't click on it.

**Comment by oryfoxer7410** [comment]
"Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[14:32:27] [Client thread/ERROR] [FML/]: "

"java.io.FileNotFoundException: enderıo:models/farm.tcn"

Have you tried reinstalling your pack?

**Comment by lotrg54** [comment]
this is so annoying i reinstall this pack four times

**Comment by The-1-7-10-Pack** [comment]
Try to go to the configs folder and delete the configuration folder of the EnderIO mod. Let it reset.

**Comment by lotrg54** [comment]
thanks i try

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
