### ISSUE TITLE
Modpack not loading

### ISSUE THREAD

**Issue by xNoxian** [The-1-7-10-Pack/The-1.7.10-Pack#599]
Whenever I press play to start up the modpack, it will load the mods it needs to load. Then when it says loading Minecraft Assets it just reloads the launcher and it doesn't load into the modpack. I have reinstalled the pack about 3 times. I even tried loading it on recommended and latest versions, and still doesn't work. There is no way for me to even play/get into this modpack, sadly.

**Comment by TheLegend714** [comment]
You need java 8 and 64 bit or 32 for your system.

**Comment by oryfoxer7410** [comment]
use java 7/8 64 bit. 

Also, pull up console in your launcher and see what errors are being shown. Then post them here if it doesn't start with 64 bit.

**Comment by The-1-7-10-Pack** [comment]
Probably the wrong Java version. If you do install the currect version and it still doesn't work, please post here your latest launcher log and I'll reopen the issue, closing it for now.

**Comment by xNoxian** [comment]
thank you for the help guys! Ill get back on results
