### ISSUE TITLE
[Server (Unrecoverable?) + Client crash] Using a Relocator, a Logistical Sorter and a Chest

### ISSUE THREAD

**Issue by fettor** [The-1-7-10-Pack/The-1.7.10-Pack#60]
Just want to say, I'm really enjoying the modpack!

However I've currently got a dead server.

Rather simple to replicate, put a chest on top of a Logistical Sorter (Mekanism), then put a Relocator (Refined Relocation) adjacent to the Logistical Sorter.

As seen if the Relocator is placed where I'm looking in this screenshot:

https://i.imgur.com/TGkVdLO.jpg

As soon as the Relocator is placed both the client and server will crash, the server will not restart.

Server error log on startup:
http://paste.ubuntu.com/9708769/

Minecraft Crash report:
http://paste.ubuntu.com/9708812/

**Comment by The-1-7-10-Pack** [comment]
Well, it is indeed a bug but there's nothing I can do about it.
Please report it there: https://github.com/Dynious/RefinedRelocation/issues
Have a nice day!
