### ISSUE TITLE
Growcraft barrel broken

### ISSUE THREAD

**Issue by Nogotogon** [The-1-7-10-Pack/The-1.7.10-Pack#600]
Everytime you try to activate Growcraft cellar's barrel the game crashes

**Comment by ChiknNRiceGaming** [comment]
that has happened to me twice in a village

**Comment by ChiknNRiceGaming** [comment]
just avoid them, i think its a mod bug

**Comment by Ceritus** [comment]
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/583
