### ISSUE TITLE
Tabbycrap

### ISSUE THREAD

**Issue by Ceritus** [The-1-7-10-Pack/The-1.7.10-Pack#601]
-- Head --
[B#301]  Stacktrace:
[B#301]  	at acs.tabbychat.core.GuiChatTC.func_73866_w_(GuiChatTC.java:555)
[B#301]  	at acs.tabbychat.core.GuiSleepTC.func_73866_w_(GuiSleepTC.java:15)
[B#301]  	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:255)
[B#301]  	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:808)
[B#301]  	at acs.tabbychat.util.TabbyChatUtils.chatGuiTick(TabbyChatUtils.java:148)
[B#301]  	at acs.tabbychat.core.LiteModTabbyChat.onTick(LiteModTabbyChat.java:39)
[B#301]  	at com.mumfrey.liteloader.core.event.HandlerList$Tickable8.onTick(HandlerList$Tickable8.java:104)
[B#301]  	at com.mumfrey.liteloader.client.ClientEvents.onTick(ClientEvents.java:416)
[B#301]  	at com.mumfrey.liteloader.client.CallbackProxyClient.onTick(CallbackProxyClient.java:63)

**Comment by The-1-7-10-Pack** [comment]
Well, the modpack uses the latest version of the mod. You should go [there](https://github.com/killjoy1221/tabbychat/issues) to report it.
