### ISSUE TITLE
The Router Utility from the Project Red Mod is not functioning

### ISSUE THREAD

**Issue by Malorn44** [The-1-7-10-Pack/The-1.7.10-Pack#603]
When I put in the upgrades for my item extractors and click install, the latency for the R and L sides do not change. I really want my items to extract faster... any suggestions?

**Comment by Malorn44** [comment]
Extra note: I am able to click the install button  but then the items just dissappear and nothing happens to the item extractor chip.

**Comment by The-1-7-10-Pack** [comment]
Does that still happen on v0.7.8 of the pack?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
