### ISSUE TITLE
[Suggestion] Minechem

### ISSUE THREAD

**Issue by oryfoxer7410** [The-1-7-10-Pack/The-1.7.10-Pack#604]
Not too sure if fits, but thought I'd suggest. (Not really magic or tech), but cool mod

http://jakimfett.github.io/Minechem/

**Comment by The-1-7-10-Pack** [comment]
Minechem is indeed a cool mod but it doesn't really fit the pack. It changes to gameplay too much. Thanks anyway for suggesting!
