### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#607]
I have this crash in my server with the latest version of the pack, i can play fine for like 10 minutes then the server crashes

http://paste.ubuntu.com/11346436/

**Comment by The-1-7-10-Pack** [comment]
Are you using ComputerCraft with BigReactors?

**Comment by thebalck** [comment]
Yes im

**Comment by The-1-7-10-Pack** [comment]
That's a problem between the two mods. You can report it, but it's a mod-bug, nothing I can do about it.
