### ISSUE TITLE
Another server crash, now on startup

### ISSUE THREAD

**Issue by thebalck** [The-1-7-10-Pack/The-1.7.10-Pack#609]
Now the server don't even start

I didn't change anything since the last crash 
http://paste.ubuntu.com/11354823/

**Comment by The-1-7-10-Pack** [comment]
Try to remove the mod named "CartFixes", does it crash again?

**Comment by thebalck** [comment]
Yes it crashes 

http://paste.ubuntu.com/11355064/

**Comment by The-1-7-10-Pack** [comment]
When does it crash? On launch? or when you're doing something?

**Comment by thebalck** [comment]
On launch

**Comment by thebalck** [comment]
But its odd because yesterday it was ok and i didnt change anything

**Comment by The-1-7-10-Pack** [comment]
Are you using the Steve's Carts mod?

**Comment by thebalck** [comment]
no, not on my builds

**Comment by The-1-7-10-Pack** [comment]
Well the crash has something related to Steve's Carts. You can remove the mod and see, it should launch.

**Comment by thebalck** [comment]
yeah i remove it it works, do i need to remove from the client ?

**Comment by The-1-7-10-Pack** [comment]
You don't have to. Anyway, Steve's Carts 2 is not the most stable mod around. Happy you got the fix. I'm closing this for now.
