### ISSUE TITLE
Custom NPC's

### ISSUE THREAD

**Issue by KLuebbert** [The-1-7-10-Pack/The-1.7.10-Pack#61]
Poor, poor Rob, xD, you have just been so flooded with mod suggestions, and I know you like to hear them, but I also know it's probably driving you insane and adding stress, so here's another one... =P

Now, I know, there's more severe problems to handle at the moment, like game crashes and horrific errors, but this is just a suggestion to look at.

Custom NPC's is a infinite mod. It's a mod where you get a entity by using a NPC Wand, and it just stands there and does nothing. You want it to do stuff, but it does nothing, and the way to fix that is by programming it. You choose what it looks like, the size, scale of body parts, you can choose the way it moves, you can choose a path, change the AI of these NPC's, give them tasks, give them roles, make them hand out quests or even make them a paid Bounty Hunter. You start from scratch, and in the end, you can get infinite combinations to make a mob 10x more complicated than everything the Ender Dragon can do. Not to mention, you can make the NPC's look like any entity or player skin, or even any pre-made Steve models the game gives to you.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs

**Comment by The-1-7-10-Pack** [comment]
Custom NPC's is a very cool mod but with over 200 mods, I'll leave it as a possibility for people who want to add it to their game manually.
