### ISSUE TITLE
Random fires

### ISSUE THREAD

**Issue by Shadowbull6130** [The-1-7-10-Pack/The-1.7.10-Pack#610]
Ok for some reason my house and other things i made can just randomly go on FIRE.I have no lava placed in the house anywhere and I wanted to know if anyone would have a explanation?Like is this taking the fun out of the modpack for me :(.There is no lava source under my house and i have literally forced it to rain to stop all these fires

**Comment by Shadowbull6130** [comment]
Ok now it is just wherever i walk a fire starts near.Is there any possible way i can turn off fire completely?

**Comment by The-1-7-10-Pack** [comment]
Maybe you have lava under your house.

**Comment by Shadowbull6130** [comment]
Already checked.I do not

**Comment by konvaa** [comment]
well was it stormy weather? Maybe lightning hit your house? Was your house from wood?

**Comment by Shadowbull6130** [comment]
It was sunny when it started,I turned on rain to make it stop and it did but when I stepped back in my house it started AGAIN.No matter where I step a fire starts around it.My garden,ME System,house,laser drill,enchanting table.Anywhere on my creations a fire starts

**Comment by SniZupGun** [comment]
It is likely that you are carrying an ore from Railcraft known as Firestone, which sets off random fires around the player. Just drop it to the ground if you have it.

**Comment by Shadowbull6130** [comment]
ill check but i dont think i do,Can it set fires if its in a chest?

**Comment by Shadowbull6130** [comment]
YUP.problem solved thanks man!

**Comment by The-1-7-10-Pack** [comment]
@SniZupGun Thank you!
