### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by ziba1** [The-1-7-10-Pack/The-1.7.10-Pack#611]
updated my server from 0.7.6a to 0.7.7a yesterday and its become fairly laggy, with cpu and ram usage both mostly 100% on the server, even when noone is online. Has anyone else had any issues running servers after updating ? 

This isn't a big server by any means, 2 players only on it, was 2gb of ram, upgraded to 3gb of ram

when I upgraded it, it was running fine for a few hours, ram usage at like 65-70% and cpu usage was at like 50%, got up this morning and logged into mcadmin to check and both are at 100% again, logged into game and its laggy again.

The only new thing so far as I can see is mystcraft with the update, it did its configuration thing yesterday but we haven't used it yet.

We pretty much turned off every contraption running - my mate was messing around heavily with laser drills and the big reactors.  Turned off our mob spawner setup, broke every chunk loader we have (which was like 4) But still having this issue.

**Comment by The-1-7-10-Pack** [comment]
Did you start to play with Mystcraft yet? Try to remove the mod and see if it helps. If it does, we know what is the problem.

**Comment by ziba1** [comment]
uninstalled it, not really any difference tbh

**Comment by The-1-7-10-Pack** [comment]
So I don't blame it on the update. Something you did made your server to work harder. Can you please give me your latest server log? Also use a [paste-tool](http://paste.ubuntu.com/).

**Comment by ziba1** [comment]
sure thing, there seems to be 2 different logs though, with different information, so here's both of them


http://paste.ubuntu.com/11374188/

http://paste.ubuntu.com/11374265/

**Comment by The-1-7-10-Pack** [comment]
You have the same 3 lines going over and over again for about 150,000 times.
> [16:16:21] [Server thread/DEBUG] [MekanismTransmitters/]: No networks found. Creating new network
[16:16:22] [Server thread/DEBUG] [MekanismTransmitters/]: Dealing with 15 invalid Transmitters
[16:16:22] [Server thread/DEBUG] [MekanismTransmitters/]: Dealing with 15 orphan Transmitters

See there: https://github.com/aidancbrady/Mekanism/issues/2673
He had the same problem as you, it's a bug related to Mekanism, that makes your server work really hard.
Post your logs in the issue and ask to reopen it. It's a mod-bug, and it doesn't relate to the modpack or the update.
