### ISSUE TITLE
New Server!

### ISSUE THREAD

**Issue by skohlhepp** [The-1-7-10-Pack/The-1.7.10-Pack#612]
I know that this repository is for bug reports but I really want to share this with all of you guys. I have started up the absolute best 1.7.10 server and you really need to check it out!

The IP of the server is blackwood.beastmc.com
And we are running 0.7.6c (New recommended version has countless bugs)

Here's a youtube video of the server: https://www.youtube.com/watch?v=njPB0468FD8

We are one of the only servers out there currently that has full working plugins, economy, games, factions, and everything else.

I have put weeks of work into this please if you are interested in a quality server check it out.

**Comment by The-1-7-10-Pack** [comment]
Best tag?
Anyway, can you open a new issue saying why didn't you use v0.7.7b? "coutless bugs". It has some fixes that 0.7.6c don't have, also with more updated mods.

**Comment by skohlhepp** [comment]
Could you give a detailed change log for the new update? @The-1-7-10-Pack

**Comment by The-1-7-10-Pack** [comment]
Simply updated all the mods to their latest (stable) version. I always tell about mods added or removed. Bug fixes there were also some. Update is simply recommended.

**Comment by skohlhepp** [comment]
@The-1-7-10-Pack Could you add my server website to that list when you get a chance? Its http://blackwoodservers.enjin.com/

**Comment by The-1-7-10-Pack** [comment]
@skohlhepp added
