### ISSUE TITLE
extra utilities bug

### ISSUE THREAD

**Issue by imsupermario** [The-1-7-10-Pack/The-1.7.10-Pack#613]
Just want to report The portal to the deep dark is not working

**Comment by The-1-7-10-Pack** [comment]
You need to use the latest version of the modpack.

**Comment by imsupermario** [comment]
My version is 0.7.7b

**Comment by imsupermario** [comment]
Right click does not activate the portal, how can I get more information for the bug?

**Comment by The-1-7-10-Pack** [comment]
Can you give me your latest client log (located in the logs folder inside of the modpack's folder), and please use a [paste-tool](http://paste.ubuntu.com/).

**Comment by imsupermario** [comment]
http://paste.ubuntu.com/11396866/

**Comment by The-1-7-10-Pack** [comment]
@imsupermario Not this log, but the "fml-client-latest" log.

**Comment by imsupermario** [comment]
http://paste.ubuntu.com/11398931/

**Comment by The-1-7-10-Pack** [comment]
I can confirm this bug and I can see it has been reported already. A mod-bug, and there's nothing I can really do. When the mod updates, we'll include the update in the modpack to fix the problem.
Thanks for reporting!
