### ISSUE TITLE
Can't download libaries

### ISSUE THREAD

**Issue by ChaseThePyro** [The-1-7-10-Pack/The-1.7.10-Pack#614]
I have tried installing and reinstalling the recommended version (0.7.7a) and when I try to start it up, I am greeted with a CB's DepLoader issue-

 "CB's DepLoader was unable to download required library slick-util-0.0b9db0b2.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/slick-util-0.0b9db0b2.jar and put it in your mods folder"

**Comment by skohlhepp** [comment]
Other people are having the same problem, it might be an issue with the repository that the file is hosted on. I would downgrade back to 0.7.6c for now..

**Comment by The-1-7-10-Pack** [comment]
@skohlhepp This won't help, you'll need to download the file again.
We'll consider hosting these files ourselfs, for now it should fix itself.
Keeping this open for others to know.

**Comment by skohlhepp** [comment]
To anyone that needs the core files for 0.7.6c heres a link to download them. You just have to put them into the 1.7.10 folder inside of your mods folder. 
https://www.mediafire.com/#e7e2ged0lpgjs

**Comment by ChaseThePyro** [comment]
Your link appears to be incorrect. Brings up default mediafire page.

**Comment by skohlhepp** [comment]
Here https://www.mediafire.com/folder/e7e2ged0lpgjs/1.7.10

**Comment by skohlhepp** [comment]
You are gonna have to download the whole folder and just put it where I said before in the 1.7.10 folder inside of your mods folder. None of the dependencies are downloading.

**Comment by ChaseThePyro** [comment]
K

**Comment by ChaseThePyro** [comment]
Thanks

**Comment by skohlhepp** [comment]
And remember those files are only for 0.7.6c, I dont think they will work with any other version.

**Comment by rastamanfb** [comment]
so this means i cant upgrade to 7.7b? ive just upgraded my server :(

**Comment by CiriTheTeddyBear** [comment]
It worked

**Comment by CiriTheTeddyBear** [comment]
You drag all of those mods into the mod folder

**Comment by rastamanfb** [comment]
repo seems to be back online. restarted server and restarted the game via technic and its downloaded them all.
maybe the repo server is throttling connections

**Comment by The-1-7-10-Pack** [comment]
Good! closing this one.
