### ISSUE TITLE
A download error has occurred

### ISSUE THREAD

**Issue by CiriTheTeddyBear** [The-1-7-10-Pack/The-1.7.10-Pack#615]
CB's DepLoader was unable to download required library vorbis-java-core-0.8-20150201.161816-1.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar and put it in your mods folder

Anyone know how to fix?
I can open the link, it doesn't load.

**Comment by Airfirewall** [comment]
Im Getting this stupid error also

**Comment by skohlhepp** [comment]
@CiriTheTeddyBear @Airfirewall Sounds like an error with the new version. I assume you are trying to run 0.7.7b? Im gonna stay on 0.7.6c for a bit until any kinks in the new version are smoothed over. Feel free to downgrade and play on the best server out there at blackwood.beastmc.com

**Comment by CiriTheTeddyBear** [comment]
Thankyou

**Comment by ChaseThePyro** [comment]
Already posted this. It is listed at #556. Installed 0.7.7b before and this didn't happen.

**Comment by CiriTheTeddyBear** [comment]
Thats a different error Chase

**Comment by CiriTheTeddyBear** [comment]
That is  http://files.qmxtech.com/libs/slick-util-0.0b9db0b2.jar And mine is http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar

**Comment by skohlhepp** [comment]
@CiriTheTeddyBear @CiriTheTeddyBear All I know is that it has never happened to me on 0.7.6c which to me seems to be much more stable at the moment..

**Comment by ChaseThePyro** [comment]
Ah. I see. However, I believe that the cause is similar.

**Comment by skohlhepp** [comment]
Yeah It probably has to do with the repository that those files are hosted on

**Comment by ChaseThePyro** [comment]
I assume that the host is down.

**Comment by ChaseThePyro** [comment]
Well, the author of the pack may have a solution if that isn't the case.

**Comment by skohlhepp** [comment]
If that host stays down the only solution is for someone who had already downloaded this file posted it on a file sharing site for you guys

**Comment by CiriTheTeddyBear** [comment]
I have the same error on 0.7.6c

**Comment by ChaseThePyro** [comment]
Well, apparently the file is for multiple versions. So I suggest that no one reinstall the pack if it is currently working.

**Comment by skohlhepp** [comment]
I can upload my library files for 0.7.6c if you want so that you can play the pack

**Comment by CiriTheTeddyBear** [comment]
Yes please, id love to play on your server

**Comment by skohlhepp** [comment]
https://www.mediafire.com/?efn8tg60urcvyov,oc00101awzkh1to,335lv5a56hxzp6g,986n3kvzy92sl8i,ima941v3j89vhas,q2vlzaj8m15pcjh,k61oo53ediawien,686v47e3x644ftn,xq4sbebib7bt4ed,8xype9n25hfwctf,tcc8e1e0jatmz44

**Comment by skohlhepp** [comment]
If all you need is vorbis then you can just put that in your 1.7.10 folder that is inside of the mods folder. You might need more than just that one, Im not sure what all is hosted on that repository.

**Comment by The-1-7-10-Pack** [comment]
#614
