### ISSUE TITLE
Can't start the modpack

### ISSUE THREAD

**Issue by Egocitius** [The-1-7-10-Pack/The-1.7.10-Pack#616]
Hi,

Can download it but when I try to start it, the launcher disappears and then immediately reappears without starting the pack.

Here's the pastebin:
http://paste.ubuntu.com/11396840/

I have Java8 64bit

Thanks!

**Comment by The-1-7-10-Pack** [comment]
Read my my comment here: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/589#issuecomment-104577990
(The second part of it)
That's your problem!

**Comment by Egocitius** [comment]
It worked!
Thanks for the quick support

**Comment by The-1-7-10-Pack** [comment]
:+1:
