### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by Lomokos** [The-1-7-10-Pack/The-1.7.10-Pack#617]
Hello! I recently downloaded the modpack and am having a ton of fun.

I set up a server with a group of friends and one of them cannot run the modpack. The laptop that he uses just cannot keep up with the all of the mods. 

Thus comes my question: Is it possible that my friends and I can "trim" the modpack of mods we have little interest in so that our friend might be able to play with us?

**Comment by The-1-7-10-Pack** [comment]
I wouldn't recommend it. I can recommend your friend installing the latest version of [Optifine](http://optifine.net/downloads), and maybe even [BetterFps](http://minecraft.curseforge.com/mc-mods/229876), if he needs every piece of fps he can get.

**Comment by Lomokos** [comment]
Yeah I would have just pointed him to Optifine, but he cannot even get to the main menu. 

Whenever we start the mod there's a long "not responding" period followed by the long initializing period before getting to the main menu. It takes so long for my friend that we've never actually seen the startup finish. We were curious if the fancy menu with the background music could be one of the culprits as to why it takes so long, so we thought we might be able to remove it and a few other mods if necessary to make it easier on his fairly weak laptop. 

We've played smaller modpacks in the past, so I guess we'll just go back to those. Thanks for the reply!

**Comment by The-1-7-10-Pack** [comment]
You should tell your friend to post here his latest client log, the big one. And to use a [paste-tool](http://paste.ubuntu.com/).

**Comment by rastamanfb** [comment]
it takes so long due to forge having it unpack and initialise the mods into the java machine the more mods the longer it takes. less ram and it becomes even longer.
I find minecraft is cpu bonded so a half decent cpu and 8gb of ram is really whats required for comfortable game play

**Comment by konvaa** [comment]
well how much RAM he have allocated?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
