### ISSUE TITLE
Can not start the Modpack

### ISSUE THREAD

**Issue by flamex3** [The-1-7-10-Pack/The-1.7.10-Pack#619]
Hi,

This just started happening today, i was able to play before but today it decided to stop.
Everytime i start it, it says this: http://imgur.com/BArCbRy
I do not have any other information on what might be the problem, i hope this helps.

**Comment by thesantosxen** [comment]
Got the same problem.

**Comment by The-1-7-10-Pack** [comment]
The host for the files is down currently, it should be up again soon!

**Comment by flamex3** [comment]
Thank you very much!
