### ISSUE TITLE
black loading screen, the crashes,

### ISSUE THREAD

**Issue by jumperstick** [The-1-7-10-Pack/The-1.7.10-Pack#62]
hi there, thanks to one of the players of this pack, the helped me with the 1.7 or newer java problem but now when i load it up, it shows a plain black screen, which takes like 20 minutes to load then it shows and hours glass loading screen and crashes, anyone ells hv this problem and could help me? oh and I'm use mac

**Comment by The-1-7-10-Pack** [comment]
So I guess you have the same issue as there: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/10
This issue closed due missing information but maybe you can provide this information.
Please give me your latest log from .technic/modpacks/the-1710-pack/logs

**Comment by The-1-7-10-Pack** [comment]
Use this: http://paste.ubuntu.com/

**Comment by jumperstick** [comment]
must i download it as text? then take the file and put in the post?

**Comment by jumperstick** [comment]
it still says its too long to send

**Comment by jumperstick** [comment]
and it doesn't make it any shorter,? how is that meant to help?

**Comment by The-1-7-10-Pack** [comment]
If you can't copy your latest log to anywhere, upload it and send me the download link. :)

**Comment by SleepingTea98** [comment]
It's a problem with liteloader. I

**Comment by jumperstick** [comment]
ok thx =)

**Comment by The-1-7-10-Pack** [comment]
Ok, but I still need your latest.log file, so I can report it.

**Comment by jumperstick** [comment]
ok sure, oh and is there only 1 light loader mod?

**Comment by jumperstick** [comment]
i dont thin light loader is the problem unless its not only one mod i had to take out, i sent u a email of the latest.log

**Comment by SleepingTea98** [comment]
How much memory have you given to your game?

**Comment by SleepingTea98** [comment]
if you cant get it to work, sorry about pull people away form your pack, i have found a pack that is in the same update and has smiler mods and wont black screen. The pack has only just come out, but it runs fine. Here is a link: http://www.technicpack.net/modpack/the-chris-packet.563396

**Comment by The-1-7-10-Pack** [comment]
Please post **here** the download link for the latest.log

**Comment by SleepingTea98** [comment]
Working Pack http://www.technicpack.net/modpack/the-chris-packet.563396
Same Mods, Same Update and Works!

**Comment by jumperstick** [comment]
i can't give u the link for it says that it does not support this kind of file

**Comment by The-1-7-10-Pack** [comment]
Well I guess we can't help each other.
Also please do not post here other modpacks.
