### ISSUE TITLE
Crash when entering End

### ISSUE THREAD

**Issue by konvaa** [The-1-7-10-Pack/The-1.7.10-Pack#621]
Hello, I just reached it and got crash with no message. When I look at crash reports in modpack folder, I found something from server side like. I dont understand it whats wrong.
Tried to restart game, still got crash. Any idea what went wrong? Is there a way how to recover mine save?

**Comment by The-1-7-10-Pack** [comment]
You can give me the crash report thingy you found? Please use a [paste-tool](http://paste.ubuntu.com/).

**Comment by konvaa** [comment]
http://paste.ubuntu.com/11429148/
here we are

**Comment by konvaa** [comment]
well i have found another log: http://paste.ubuntu.com/11429296/

**Comment by The-1-7-10-Pack** [comment]
You have a corrupted chunk there, possibly. May be due to additional mods.

**Comment by konvaa** [comment]
well, ok, how to repair them?

**Comment by konvaa** [comment]
Should I try to update modpack and reinstall those extra mods?

**Comment by The-1-7-10-Pack** [comment]
@konvaa I'd recommend you to do that anyway, the recommended build now is 0.7.7b and not 0.7.6c :)

**Comment by konvaa** [comment]
ok reinstalled and updated...
log 1: http://paste.ubuntu.com/11430154/
log 2:http://paste.ubuntu.com/11430156/

How could I find what chunk is corrupted? Or how could I restore mine save?

**Comment by The-1-7-10-Pack** [comment]
I'm still not sure it's 100% chunk-corruption, but anyway you should try to get help in the [Forge forums](http://www.minecraftforge.net/forum/index.php?board=15.0). They can help you!

**Comment by konvaa** [comment]
well I figured which mods woks with the pack and I keep playing this. Thanks anyway

**Comment by The-1-7-10-Pack** [comment]
:+1:
