### ISSUE TITLE
Server upgrade 0.7.6c -> 0.7.7b

### ISSUE THREAD

**Issue by ninjamckickass** [The-1-7-10-Pack/The-1.7.10-Pack#623]
Just looking to see if there's any reason we couldn't directly migrate our current map between versions. New ore generation, etc? 

Thanks!

**Comment by ninjamckickass** [comment]
Found my answer when I double checked the closed tickets. Thanks again for the best mod pack.

**Comment by The-1-7-10-Pack** [comment]
:+1:
