### ISSUE TITLE
Cauldron Server needs a load order list

### ISSUE THREAD

**Issue by TeslaTheBrave** [The-1-7-10-Pack/The-1.7.10-Pack#624]
Looking for a load order list for the mods.

We are trying to get the mod pack to load on cauldron to be able to integrate grief prevention and server load reduction.

Anyone who knows what this is or can point me in the right direction, please help. :)

**Comment by The-1-7-10-Pack** [comment]
I don't see the need for it. Loading the modpack on KCauldron should be easy

**Comment by TeslaTheBrave** [comment]
Its not. It continuously crashes. After trying to deal with this for hours, we have decided to use a different mod pack that is compiled properly :) thanks anyway.

**Comment by oryfoxer7410** [comment]
I run kcauldron fine. What version of the pack are you using? You need the version for your forge. Also, remove color chat mod from server, will crash client when a player chats.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
