### ISSUE TITLE
Can't open Modpack

### ISSUE THREAD

**Issue by mudwarp** [The-1-7-10-Pack/The-1.7.10-Pack#625]
Whenever I try to open it, (I'm using Mac OS X), it opens a tab which says "CB's Deploader", which loads some things, then closes and the mod pack itself doesn't open.

**Comment by mudwarp** [comment]
Closed the Issue by mistake.

**Comment by mudwarp** [comment]
Tried to open it again, and it's working now.

**Comment by The-1-7-10-Pack** [comment]
:+1:
