### ISSUE TITLE
Giant Chunk Loading Errors No Solution

### ISSUE THREAD

**Issue by jakebee101** [The-1-7-10-Pack/The-1.7.10-Pack#626]
Hi! You more than likely don't remember me, but about 4 months back I posted about the pack not loading at all, to my dismay, I found out I needed a better computer. So, I have finally gotten one, and allocated 3GB of ram to the launcher. I was very excited to launch this pack, and got to the menu screen, the into a new singleplayer world. Now, this isn't a crash report, but rather something I have seen numerous times in many different modpacks. As I started to explore the world, I got about 100 blocks from spawn and there it was: an enormous, maybe 6-7 chunks of nothing. I walked into it and lagged out and couldn't get out, so I relogged and it was fine, but then another 30 blocks revealed another and another past that. So, I tried everything: shooting a bow into it, riding a boat into it, and updating blocks. Nothing worked so I thought I would make a issue here to see if there is any way to resolve this in not only yours but other modpacks as well. I have included a link to  a picture of the original chunk error. http://imgur.com/EpqkFY2 Thanks :) ~Jake

**Comment by TheLegend714** [comment]
F4 +A I belive reloads chunks.

**Comment by jakebee101** [comment]
I tried that also. No avail D:

**Comment by The-1-7-10-Pack** [comment]
@jakebee101 It's just a line of chunks not loading, right?
It should'nt be critical, and it may be due to FastCraft's fancy things.
Maybe you were just unlucky to get 2 of these in a row, but it happens from time to time, in all modpacks, and there's nothing we can really do about it.

**Comment by jakebee101** [comment]
Okay, thanks :D I will try to look into the fastcraft thing. Thanks for the help ;)

**Comment by The-1-7-10-Pack** [comment]
:+1:
