### ISSUE TITLE
Manually Allocating RAM

### ISSUE THREAD

**Issue by Angelsneverfade** [The-1-7-10-Pack/The-1.7.10-Pack#629]
Hello,

Is there any way to allocate more RAM to this mod? Standard ways of writing "-Xmx4G -Xms4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M" doesnt work. Also the option in the launcher for allocating RAM doesnt work either. It seems to just override everything on its own. I have 16GB of RAM and it only allocates 3.5 GB of RAM automatically so I am always sitting at 100% allocation and lags start happening after a while.

I have tried other mods and vanilla with the mentioned ram allocation methods and they both allocated ram accordingly. 

Thank you

**Comment by The-1-7-10-Pack** [comment]
> Go to the modpack's folder -> bin -> delete the "version.json" file. Then, enter "modpack.jar" and locate there the (other) "version,json file". Under "javaArguments" you can do what you want.

That being said, I doubt that you have "lag spikes" due to the RAM. The games allocates 100% of the RAM he gets, and that was it is supposed to do. The RAM usage is the important thing. Giving the game too much RAM is not recommended at all.

**Comment by Angelsneverfade** [comment]
Yeah I meant to say its used ram that gets to 100% sometimes. I would love to have like 1 more GB of RAM for this. Thanks for that.
