### ISSUE TITLE
Initialising Issue

### ISSUE THREAD

**Issue by GuardianMars** [The-1-7-10-Pack/The-1.7.10-Pack#631]
I have this problem with the launcher/minecraft. Every-time I try starting the pack it will finish all of the other stuff, but it will get stuck on Initialising. I have Java 7-64 bit btw...

**Comment by GuardianMars** [comment]
http://paste.ubuntu.com/11485247/ 
thats my latest log for the pack

**Comment by The-1-7-10-Pack** [comment]
I need the other log, the "fml-client-latest"

**Comment by Lindsmars** [comment]
Ive been having the same problem! I had all the problems trying to open the pack and now the launcher works and the minecraft 1.7.10 pack window opens but it initialises forever and wont finish. here is my log (its a little long...): http://paste.ubuntu.com/11523664/

**Comment by The-1-7-10-Pack** [comment]
@Lindsmars What is your CPU type?

**Comment by Lindsmars** [comment]
@The-1-7-10-Pack Intel Core i5-4210U CPU @ 1.70GHz
I believe thats what you mean, if not let me know and ill look for another figure :P

**Comment by GuardianMars** [comment]
http://paste.ubuntu.com/11533189/ thats the latest log I think you are looking for if not I will need help locating it :I

**Comment by The-1-7-10-Pack** [comment]
@GuardianMars What is your CPU type?
@Lindsmars Anyway your guys your logs show nothing special. Just that the normal loading takes too damn much time.
Let's try something: go to the modpack's folder -> configs -> splash.properties
Enable there the loading splash screen and see if you find anything new.

**Comment by Lindsmars** [comment]
@The-1-7-10-Pack this is just proving just how long its taking for it to load. Its been about 10 minutes and its not past the second stage out of 7, not even half way

**Comment by Lindsmars** [comment]
@The-1-7-10-Pack so i tried that and let it go as far as it could. It made it to 7/7 and froze my entire computer and i had to restart my computer. I guess Ill have to give up? unless you have any other ideas or suggestions...

**Comment by The-1-7-10-Pack** [comment]
It's like 1% of the players have this problem, and I'm not sure who to blame.
You guys should go to the [Forge Forums](http://www.minecraftforge.net/forum/index.php?board=15.0) to get support, you'll be able to get help there.
I'l try also to figure out what the hell is the problem.

**Comment by GuardianMars** [comment]
So I looked into device managers and went to proccessors and this is what was under it
AMD A4-5000 APU with Radeon(TM) HD Graphics
that was repeated 4 times btw

**Comment by GuardianMars** [comment]
http://paste.ubuntu.com/11549557/ thats what i found on the forge forums, idk what to do with this info :I

**Comment by RivalSpirit** [comment]
I have the same issue too. When I load this modpack, this doesn't usually happened. It just started today. It stops during initializing, right before the I can get to the Menu screen. The Loading bar would fill up and 10 seconds later it would crash. http://paste.ubuntu.com/11570413/ and the crash report from my files, http://paste.ubuntu.com/11570461/
I hope this can help...

**Comment by The-1-7-10-Pack** [comment]
@RivalSpirit Did you enable Forge's loading screen? It's disabled in v0.7.7b by default to prevent crashes like this.

**Comment by RivalSpirit** [comment]
I don't recall enabling the Forge's loading screen. Today was the first day I ever saw it, ithought it was supposed to be there. How would I disable it?

**Comment by The-1-7-10-Pack** [comment]
@RivalSpirit Go to the modpack's folder -> configs -> "splash.properties". You'll see there the option to enable/disable it.

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
