### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by Darkcreeper2011** [The-1-7-10-Pack/The-1.7.10-Pack#632]
It Loads everything just fine on the tekkit launcher then it says loading minecraft assets after it gets done nothing happens nothing at all the mod pack doesnt open or anything Im running win 8.1

**Comment by TheLegend714** [comment]
You need Java 7/8 64 Bit

**Comment by Darkcreeper2011** [comment]
To run what?

**Comment by Darkcreeper2011** [comment]
Also I have java 8

**Comment by TheLegend714** [comment]
Post your FML log and client and use a paste tool.

**Comment by Darkcreeper2011** [comment]
I have the console log but what is the fml Log

**Comment by Darkcreeper2011** [comment]
http://pastebin.com/FkKCUi6v

**Comment by The-1-7-10-Pack** [comment]
You have Java 32 bit. You need 64 bit.
