### ISSUE TITLE
Journey Map

### ISSUE THREAD

**Issue by yes86** [The-1-7-10-Pack/The-1.7.10-Pack#635]
http://journeymap.techbrew.net/
How about this to replace Voxel Map?  I find it has a couple of cooler features like showing where you have explored throughout the world when viewing the large map.

**Comment by TheLegend714** [comment]
Seems like a cool map mod.

**Comment by The-1-7-10-Pack** [comment]
They don't give permissions to Technic modpacks.
Don't ask me why.
