### ISSUE TITLE
Forbidden Magic

### ISSUE THREAD

**Issue by The-1-7-10-Pack** [The-1-7-10-Pack/The-1.7.10-Pack#636]
[Forbidden Magic](http://minecraft.curseforge.com/mc-mods/224237-forbidden-magic), opinions?

**Comment by mckulich** [comment]
I already play with forbidden magic, so i vote yes :)

**Comment by Voideon** [comment]
I Second this

**Comment by mandm635** [comment]
Yes!!! I love that mod!
