### ISSUE TITLE
Crashing at certain point, cannot re-log without crashing

### ISSUE THREAD

**Issue by Mistercris** [The-1-7-10-Pack/The-1.7.10-Pack#637]
I am having an issue when trying to log-in to our server.
I somehow crashed the server when travelling through the nether, so just for shits we started it right back up to see if it was caused by one individual, the others joined, then i joined and crashed it on log-in to the nether.

http://pastebin.com/DzR06WEU 

possible related to #634 ? (Mine is set to "true")
I think I posted this too early before doing more troubleshooting, one of our members pointed out it may be a corrupted chunk?

**Comment by The-1-7-10-Pack** [comment]
Indeed a corrupted chunk. If you care from your nether you can use NBTExplorer to delete just the one chunk. This is the location:
> Location: World: (64,30,85), Chunk: (at 0,1,5 in 4,5; contains blocks 64,0,80 to 79,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
