### ISSUE TITLE
Launcher Issues

### ISSUE THREAD

**Issue by Mgkoll** [The-1-7-10-Pack/The-1.7.10-Pack#639]
When I exited out of my world, I couldn't get back in, and it kept going back to the menu. I went to restart it but whenever I press play at the technic launcher screen, it shows that it's loading then goes back to showing the play button. It doesn't happen with any other modpacks, and this is not my first time playing the 1.7.10 pack.

**Comment by The-1-7-10-Pack** [comment]
I need your latest client log. Please use a paste-tool.

**Comment by TheLegend714** [comment]
Probably chuck error

**Comment by TheLegend714** [comment]
Chunk *

**Comment by samiristhebest** [comment]
Hi need help i cant play the game 
![image](https://cloud.githubusercontent.com/assets/12765818/8011189/e4ea648c-0bb6-11e5-9751-a471f91ca06d.png)

**Comment by samiristhebest** [comment]
can someone please help me i wanna really play this game

**Comment by samiristhebest** [comment]
![help modpack](https://cloud.githubusercontent.com/assets/12765818/8012042/7fdd5f1a-0bbe-11e5-95ab-9d8a69c242b4.png)

**Comment by samiristhebest** [comment]
![image](https://cloud.githubusercontent.com/assets/12765818/8012280/77bfffde-0bc0-11e5-998c-27743ad7d56f.png)

**Comment by Mgkoll** [comment]
![error](https://cloud.githubusercontent.com/assets/12758149/8015724/89a12554-0b87-11e5-86c9-6d61132e87ad.png)

**Comment by The-1-7-10-Pack** [comment]
@samiristhebest You have Java 32 bit. That's your problem.
@Mgkoll Did you try to reinstall?

**Comment by samiristhebest** [comment]
oow lol ive update it but thx i try it again !!

**Comment by The-1-7-10-Pack** [comment]
@samiristhebest Just be sure you're using the updated version and uninstall the old version.

**Comment by samiristhebest** [comment]
i did but it stil not work

**Comment by samiristhebest** [comment]
ive tread to install the modpack again nothing works :(

**Comment by samiristhebest** [comment]
![image](https://cloud.githubusercontent.com/assets/12765818/8021504/86e723d8-0ca2-11e5-9336-c2e141343494.png)

**Comment by samiristhebest** [comment]
![image](https://cloud.githubusercontent.com/assets/12765818/8021509/b6567dee-0ca2-11e5-98cd-94b19a97a982.png)

**Comment by TheLegend714** [comment]
Does your launcher allocate enough ram? It should do it automatically but sometimes it does not Rarely

**Comment by Mgkoll** [comment]
I reinstalled the modpack and it worked fine for a while, then it crashed and I couldn't play again. I restarted my computer afterwards and its been working fine ever since. O.o

**Comment by The-1-7-10-Pack** [comment]
Weird!

**Comment by samiristhebest** [comment]
@TheLegend714  how do you mean allocate sorry but my english is not very good
and how do you allocate more ram ??
