### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kevador** [The-1-7-10-Pack/The-1.7.10-Pack#640]
So i tried to add veinminer to the modpack butwhen i clicked play on the launcher it did nothing, when i deleted veinminer again it didn't work either so i reinstalled the pack but now when i try to install it is says: and error has occured while trying to delete:.....
Please help because i want to play again (i also can't delete any of the files manually.

**Comment by The-1-7-10-Pack** [comment]
99% you have the wrong Java version. You need Java 7/8 and 64 bit. Please check for that. If you do have the right version please post here your latest log and I'll reopen the issue.
