### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by bray7bray1** [The-1-7-10-Pack/The-1.7.10-Pack#641]
whenever I try to play it the whole download shuts down when it gets to 'installing minecraft assets'
any way to help

**Comment by winters323** [comment]
Make sure your Java is up to date. I just had to install a new version (64-bit) for it to work.

**Comment by bray7bray1** [comment]
I did do that before for another mod pack and it still seems to not work

**Comment by samiristhebest** [comment]
i have that problem to i cant start the modpack

**Comment by TheLegend714** [comment]
Allocate more RAM (memory) and if that does not work then maybe it's your anti-virus

**Comment by samiristhebest** [comment]
how do you mean ?

**Comment by samiristhebest** [comment]
this is what i get 
![image](https://cloud.githubusercontent.com/assets/12765818/8020261/b3383768-0c72-11e5-8256-513697ddac82.png)

**Comment by The-1-7-10-Pack** [comment]
@samiristhebest I helped you already in another issue. 
@bray7bray1 Please open a new issue, with the information required. Please read [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).
