### ISSUE TITLE
Can't go to server.

### ISSUE THREAD

**Issue by TheCraftedMax** [The-1-7-10-Pack/The-1.7.10-Pack#642]
When i tried to put server in the game, it says can't resolve hostname and when my friend put the same server he can join it. Please Help =(

**Comment by The-1-7-10-Pack** [comment]
There's no such thing. You've done it wrong, 100%.
Also it's not the modpack's problem.
When you're checking IPs for server you can use [this](dinnerbone.com/minecraft/tools/status/) tool to see if it's online.
Good luck!
