### ISSUE TITLE
Dragon Mounts

### ISSUE THREAD

**Issue by kevador** [The-1-7-10-Pack/The-1.7.10-Pack#643]
Can you please add Ars Magica 2 and dragonmounts and update Magical crops?

**Comment by The-1-7-10-Pack** [comment]
Ars Magica 2 is too unstable, and Magical Crops 4 is in the same place, currently.
I'll leave this open for comments about Dragon Mounts

**Comment by kevador** [comment]
The last update from AM2 isn't unstable it's used in many packs that are 1.7.10 and i've never experienced problems. okay the MC4 i can understand because i did have problems with that

**Comment by osum4est** [comment]
I think dragon mounts would be awesome! Please add it

**Comment by The-1-7-10-Pack** [comment]
Dragon Mounts is not in a really stable point now, also it doesn't really fit the pack.
Thanks for suggesting anyway :)
