### ISSUE TITLE
Memory Allocation issue (max of 3041mb in-game)

### ISSUE THREAD

**Issue by Tei3** [The-1-7-10-Pack/The-1.7.10-Pack#645]
I have 16GB of ram and am only able to allocate 3041 mb of it for my the 1.7.10 pack. 
http://gyazo.com/886b8ab46ec0242f177d351c257c9bbb (picture of my screen confirming 3041 mb)
https://mega.co.nz/#!tUU03a4B!5Ivz_oZsG3pxH9DBc3KuOAQop1dfuBL_DokkfcoU8DU (dxdiag)
The game works without any sphax resource packs but I really want to use the 128 or 64 bit versions if possible... which it should be, if I could allocate the 12gb of ram that I want to give it. 
gyazo.com/58e66f4a89b6f16fc74bdabab20765e9 (picture of launcher settings used)
Another seperate issue is that this is the latest version that I could get working, any later version simply doesn't start up, an issue I believe can be solved if the allocation one is dealt with.

**Comment by The-1-7-10-Pack** [comment]
The memory allocation is automatic, you don't need more than 3GB.
The 128x Sphax is problematic in many ways and not recommended at all.

About other versions of the pack that don't launch - give me your latest log and I'd be able to confirm the problem.

**Comment by Tei3** [comment]
Where do I find the log? Also, the crashing happens with the 64 bit texture pack.

**Comment by The-1-7-10-Pack** [comment]
In the modpack's folder -> logs -> "latest-client-fml.log". Please use a [paste-tool](http://paste.ubuntu.com/).

**Comment by Tei3** [comment]
I've been playing it without the resoruce pack for a while but here's the latest paste.ubuntu.com/11631427/

All of the other logs:
https://mega.co.nz/#!QMd3RL4S!dl0n49QE7dJkkhOdlDIryGLHxj97H5rExiDX-Rust7A (2nd newest)
https://mega.co.nz/#!hU8HjbyI!2USQkbfHBriIF77mn0SUJVn37sBDrDbgN2zfbWTQYQI
https://mega.co.nz/#!IMsRBZJJ!A5UFbW-DqofqS3yJ23lNpg1CR_gt75M-DLBNnj2CZsk
https://mega.co.nz/#!5Vsm0ZLa!mE5SbB7olGZPjFi_8ocPGrcEGIckbOuGbKhSlpCBKYw
https://mega.co.nz/#!xVNnHTqZ!btU5IVCN_U109Tcvw5C_UfDNriSiMxWYDbgZZbypNHk
https://mega.co.nz/#!FVtgHS6J!qpNO3ARBraCVD6NWDBnYJSN0ecnV4KX5iRtG7JYaqX0
https://mega.co.nz/#!UdkmyD5C!2h36DKFJdenqJbXvWDOQw4cpjWfYzrnZyjOKL0xvMZU
https://mega.co.nz/#!RAVhTTyR!yN6Txn0YhthRpNENm0d7nqOvSQSzFjMX34UM-H8YtiY
https://mega.co.nz/#!VZlRDBLa!f6hHH-p6ucL1BmnApkspVIwxAiYFdVqtyMH3up4E6tI
https://mega.co.nz/#!VcEW2AIT!e5eYcwbS9YU1HMy_fT5xMmv-T_PuezAIljzuSs7wtSM (Oldest)

**Comment by The-1-7-10-Pack** [comment]
@Tei3 Please use a **[paste-tool](http://paste.ubuntu.com/)** and just post the latest one, I don't want them all

**Comment by Tei3** [comment]
"I've been playing it without the resoruce pack for a while but here's the latest  paste.ubuntu.com/11631427/ " <- In the last post

**Comment by The-1-7-10-Pack** [comment]
Did you generate a crash report?

**Comment by Tei3** [comment]
Sorry about the 8 hours, I had work. No, when I try to start up the latest version it simply starts up, screen goes down, nothing happens for 30 seconds, and then the launcher comes back up as if I had exited the game.

**Comment by The-1-7-10-Pack** [comment]
In the log you gave me I see you were able to launch. Please give me the latest log when you're unable to launch.

**Comment by Tei3** [comment]
http://paste.ubuntu.com/11642950/

**Comment by The-1-7-10-Pack** [comment]
That's a launcher problem. Reinstall the Technic launcher and it should work.
