### ISSUE TITLE
I can't start a server (The 1.7.10 Pack)

### ISSUE THREAD

**Issue by lasiecz** [The-1-7-10-Pack/The-1.7.10-Pack#646]
Hi there, 

I downloaded the server from Technicpack.net and tried to run it but it is not working. I dont know what to click to start it but when I click the minecraft_server.1.7.10 It opens for a 2 seconds and it disapear. The same with everything else. I got fast  screenshot but i dont know what to do. 

I need help. Java is updated, eula true ...
![asd](https://cloud.githubusercontent.com/assets/12786747/8025161/e582bb42-0d4b-11e5-9ba4-e6b98d4e4138.jpg)

**Comment by The-1-7-10-Pack** [comment]
You click the "LaunchServer" file, you're now launching vanilla.

**Comment by lasiecz** [comment]
I tried every file. Launch closed after loading. I am at the end. ..

**Comment by lasiecz** [comment]
![sdasda](https://cloud.githubusercontent.com/assets/12786747/8025204/53e537b2-0d4d-11e5-826d-83fd03d8a4a6.jpg)

Launch i am missing something. How?

**Comment by lasiecz** [comment]
![dsada](https://cloud.githubusercontent.com/assets/12786747/8025225/eaa500b0-0d4d-11e5-95f6-e25398a66788.jpg)

Another problem. I got the missing dll and this appears. I really want to play it with my BF :(

**Comment by The-1-7-10-Pack** [comment]
You have Java 32 bit. You need 64 bit. You can't launch the server with Java 32 bit.

**Comment by lasiecz** [comment]
So I deleted all java and installed new the 64 but nothing happends.

**Comment by lasiecz** [comment]
Ok this is working but after clicking on barrel it drop :(

**Comment by lasiecz** [comment]
GROWTHCRAFT - thats what is not working, the 3 brewing tools :(

**Comment by The-1-7-10-Pack** [comment]
That's a known issue with the mod, and it doesn't relate to anything.

**Comment by lasiecz** [comment]
And will it bee repaired? :(

**Comment by The-1-7-10-Pack** [comment]
It's a mod-bug and currently I don't see progress from the mod author.

**Comment by lasiecz** [comment]
:( Sad but I hope they will reapir it :) its amazing mod :) so thank you very much :)
