### ISSUE TITLE
Server won't run

### ISSUE THREAD

**Issue by lasiecz** [The-1-7-10-Pack/The-1.7.10-Pack#647]
My last issue is closed even when I have still issue.

So i downloaded the missing dll: 
![53e537b2-0d4d-11e5-826d-83fd03d8a4a6](https://cloud.githubusercontent.com/assets/12786747/8025262/3aa2cb14-0d4f-11e5-87c4-82ab3615c7a5.jpg)

But this appears:
![eaa500b0-0d4d-11e5-95f6-e25398a66788](https://cloud.githubusercontent.com/assets/12786747/8025265/44a62548-0d4f-11e5-8ab8-a6f5e6063d81.jpg)

And now what? :(

**Comment by The-1-7-10-Pack** [comment]
Don't open new issues, I'll reply on the first one. It's simple.
