### ISSUE TITLE
Failed load class ?!?!?!?!

### ISSUE THREAD

**Issue by samiristhebest** [The-1-7-10-Pack/The-1.7.10-Pack#648]
![image](https://cloud.githubusercontent.com/assets/12765818/8026562/c9e73c3e-0d7b-11e5-939b-38eff8b539a6.png)

what does it mean ?!??!?!?!

**Comment by The-1-7-10-Pack** [comment]
,These errors relate to the launcher and have nothing to do with the modpack.
