### ISSUE TITLE
Chat crashes client?

### ISSUE THREAD

**Issue by RedGoblin** [The-1-7-10-Pack/The-1.7.10-Pack#649]
At first I thought there was a hidden language filter, but I tried to just say hi and it just crashes client side.

Usually we use teamspeak to chat with each other. But sometimes they don't just want to talk.

**Comment by The-1-7-10-Pack** [comment]
I need the crash report.

**Comment by RedGoblin** [comment]
The thing it isn't a full crash. It just boots you out of the game.

**Comment by The-1-7-10-Pack** [comment]
I still need more details, maybe located in the latest client log.

**Comment by RedGoblin** [comment]
If you want, not sure how you can try and join my server and see for yourself. Just message me. 

I don't even know what to look for in the log.

**Comment by The-1-7-10-Pack** [comment]
Just post the full latest client log using a paste-tool and I'll search for the error.

**Comment by RedGoblin** [comment]
A few additional facts
1. Chat works on single player.
2. Bukkit Pluggin Essentials allows /msg to go through.
3. Commands works.

https://www.dropbox.com/s/8l277l7vu6nf764/fml-client-latest.log?dl=0

**Comment by The-1-7-10-Pack** [comment]
So you have plugins on your server?

**Comment by RedGoblin** [comment]
Yes. Only one.

**Comment by The-1-7-10-Pack** [comment]
And did you try to remove the plugin?
What is the KCauldron version you're using?

**Comment by RedGoblin** [comment]
Yes I did remove the plugin and tried it. Still freezes.

1.7.10 - 1408.95

Though it does say there's an update to 1.7.10-1448.121

**Comment by The-1-7-10-Pack** [comment]
Try to get help at https://prok.pw/gitlab/Prototik/KCauldron/issues
This is a Cauldron problem, and I don't think it has something related to the pack.

**Comment by The-1-7-10-Pack** [comment]
@RedGoblin Try removing ColorChat.

**Comment by mtracy01** [comment]
I feel like I may be a bit late to the party here, but I can confirm removing ColorChat will allow KCauldron to run the server without crashing when using chat.  Other servers don't seem to have this issue, so I'm still trying to figure out which open source server others are using for this pack to enable plugins.  Will update this thread when I've found that alternative.
