### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by Florb** [The-1-7-10-Pack/The-1.7.10-Pack#653]
LOG: http://pastebin.com/MucafMBT
CPU: Core i7 5960x
GPU: GTX 980 G1

**Comment by The-1-7-10-Pack** [comment]
It's a launcher problem, not the modpack's.
Reinstall the Technic Launcher and try again, it should work.

**Comment by Florb** [comment]
Alright, thanks

**Comment by samiristhebest** [comment]
@The-1-7-10-Pack  hi jon me again i did what you ask but it stills not work :(
what should i do  it says failed load class????
