### ISSUE TITLE
Help with server making

### ISSUE THREAD

**Issue by Nemet01** [The-1-7-10-Pack/The-1.7.10-Pack#654]
Hi there,
Okay the thing is I can start a server even get on it but my friends cant see it. The port is open on router. So if you know a way to check if its actually online or something please let me know.
Thanks for your time and your awesome modpack.

**Comment by The-1-7-10-Pack** [comment]
https://dinnerbone.com/minecraft/tools/status/

**Comment by Nemet01** [comment]
Found the solution for it basically I didnt know i can port forward in my modem :| tyx for oyur reply

**Comment by The-1-7-10-Pack** [comment]
:+1:
