### ISSUE TITLE
Removing Mods

### ISSUE THREAD

**Issue by BeavyJr** [The-1-7-10-Pack/The-1.7.10-Pack#655]
I love this pack, but i'd like to remove some of the mods to make it easier on my terrible laptop to run. I've tried deleting them but I get the "GuiMissingMods" error every time, is there a special way to remove mods? 

Thank you

**Comment by The-1-7-10-Pack** [comment]
You shouldn't just remove mods, it wouldn't always simply make things run better. If you want to get higher FPS you should install [Optifine](https://optifine.net/home), or [BetterFps](http://minecraft.curseforge.com/mc-mods/229876).
