### ISSUE TITLE
Two fairly popular mod suggestions to make this the ultimate pack

### ISSUE THREAD

**Issue by osum4est** [The-1-7-10-Pack/The-1.7.10-Pack#656]
Hello, after searching and searching, this is the the BEST 1.7.10 pack I could find. There are three mods, though, that I really wish it had. Those are:
* Portal gun mod: http://ichun.us/mods/portalgun/
* ~~Forge multipart: http://files.minecraftforge.net/ForgeMultipart/~~
* Ars magica 2: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292222-ars-magica-2-version-1-4-0-008-updated-february-6

If those three mods could be added I would be extremely happy!

**Comment by The-1-7-10-Pack** [comment]
Forge multipart is already in the pack, obviously.

**Comment by osum4est** [comment]
Oh... I didn't notice it! Sorry, then disregard that. Portal gun and ars magica would still be awesome, though

**Comment by MBYilmaz** [comment]
I don't know about the Portal Gun, but Ars Magica is absolutely needed IMO. Just giving nice feedback

**Comment by The-1-7-10-Pack** [comment]
- [Portal Gun](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/480)
- Ars Magica 2: #59, #73, #142, #216, #222, #369 

Thanks anyway for suggesting, but please look if anyone has suggested it before you :)
