### ISSUE TITLE
Crash At Startup

### ISSUE THREAD

**Issue by MBYilmaz** [The-1-7-10-Pack/The-1.7.10-Pack#657]
Hello, I want to really play this pack but it crashes at startup. Here is the crash log http://pastebin.com/VTJGJEPy I use 64-bit java, allocated 4 gbs of RAM, I have everything needed but it crashes. I couldn't find the solution maybe you can help me?

**Comment by TheLegend714** [comment]
Caused by: java.io.FileNotFoundException: enderıo:models/farm.tcn Heres your problem.

**Comment by MBYilmaz** [comment]
Yes, exactly but file is there, I tried to delete EnderIO config and the mod itself, but it didn't work. When I deleted the mod, game gave an error saying EnderIO not found so that's not a fix. Still need a solution

**Comment by TheLegend714** [comment]
Try reinstalling the modpack and a clean installation.

**Comment by samiristhebest** [comment]
@TheLegend714  how do you allocate more ram ?!?!?!

**Comment by MBYilmaz** [comment]
Unfortunately I did that too. You allocate from the launcher settings. I still desperately need help because it happens to some of the other packs too and I don't understand the problem.

**Comment by TheLegend714** [comment]
Do you use Java 8?

**Comment by TheLegend714** [comment]
@Samiristhebest Go to launcher settings in the top right corner.

**Comment by MBYilmaz** [comment]
Yes I use Java 8, 1.8.0_45 64 bit

**Comment by samiristhebest** [comment]
@TheLegend714  and then ??

**Comment by MBYilmaz** [comment]
Launcher Options, Java Settings tab, Memory. Choose the amount. That's how you allocate more RAM which is a thing you could find easily with a little research. Still no answer for my problem though

**Comment by samiristhebest** [comment]
@MBYilmaz  lol im not that stupid the highest amount is 1gb not eneough for an 1.7.10 modpack

and i get failed load class i updated java and allocate to 1gb but stil..........

**Comment by MBYilmaz** [comment]
Well obviously the pack is big so you need 3-4 gbs of RAM allocated. Looks like you need to upgrade.

**Comment by TheLegend714** [comment]
This has also happened me and it's probably that the mod tinkered does not like your system.

**Comment by TheLegend714** [comment]
@Samiristhebest 99% of the time you have the wrong java version check again and if that does not work post your log and please use a paste tool.
