### ISSUE TITLE
Game crashed - can't reopen

### ISSUE THREAD

**Issue by Solenea** [The-1-7-10-Pack/The-1.7.10-Pack#658]
Hi, i really love this modpack and want to keep exploring, but my game keeps crashing.
When the game crashed i was automating things with IC2 machines, a big reactor from Big reactors and had a Quarry going with gold+diamond pipes going around when suddenly the game just crashed and i can't seem to figure out why. Nor can i see what my problem is compared to others crashes.
This is singleplayer client.
Hope you can help, thanks.

Latest Crash report: http://paste.ubuntu.com/11695491/

**Comment by The-1-7-10-Pack** [comment]
This is a bug from AdvancedMachines (addon to IC2). Now you have a ticking block entity stopping you from launching the world, the only option to fix it is to delete the block using NBTExplorer, here's a [guide](https://www.youtube.com/watch?v=fWUUsdp3pJ8).

The mod has updated and fixed the issue, and this update will be included in the next update of the pack :)

**Comment by Solenea** [comment]
Thank you so much, saved my game! 
It doesn't seem to have deleted any block - so how do i make sure it doesn't happen again?

**Comment by The-1-7-10-Pack** [comment]
It won't happen again in v0.7.8 of the modpack, so just be carful until you update :)

**Comment by Solenea** [comment]
I will then. Thank you for responding so fast ! :)
