### ISSUE TITLE
Random Client Crashes on Server

### ISSUE THREAD

**Issue by PotatoSauceMC** [The-1-7-10-Pack/The-1.7.10-Pack#659]
I have a server running this modpack with a survival world that my friends and I have been working on for a long time. I just updated the server to 0.7.8 of the pack and now when we join we get a "Falty Missing Blocks and Items" error and cant join.

**Comment by The-1-7-10-Pack** [comment]
Can you please give me a picture of the error, or any more information in another way?

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.

**Comment by PotatoSauceMC** [comment]
Sorry, I for got about this. I just installed a clean server and client using version 0.7.9 and I go to join the server and I get this error: 
![error](https://cloud.githubusercontent.com/assets/7833468/8602065/1bcc21ec-263e-11e5-9a1b-a05a8c82f170.PNG)

**Comment by The-1-7-10-Pack** [comment]
With the same save?

**Comment by PotatoSauceMC** [comment]
Nope, everything's fresh

**Comment by PotatoSauceMC** [comment]
then I try to play in single player and it crashes with this error report:
http://pastebin.com/raw.php?i=sz2quUqr

**Comment by The-1-7-10-Pack** [comment]
Well, if so, obviously something is wrong with your client.
Backup your saves, and completely delete the modpack's folder.
Then, redownload and install it. Should fix it.

**Comment by PotatoSauceMC** [comment]
Alright I'll try that.

**Comment by PotatoSauceMC** [comment]
I did a fresh install and I still get the same error.

**Comment by PotatoSauceMC** [comment]
I'll look into this, thanks anyway. If I find a resolution I will update this issue. Is there a way you could re-open it?

**Comment by PotatoSauceMC** [comment]
I give up, I can't find anything... Back to FTB I guess

**Comment by The-1-7-10-Pack** [comment]
Did you try to use the recommended version of the pack? (v0.7.7b)

**Comment by PotatoSauceMC** [comment]
I'll try it, I had another problem with earlier versions of the mod pack where the players on my server would travel and then their clients would crash and when they restart the game they would crash every time they try to join unless someone else tried to quickly TP (said person who crashed) to them.

**Comment by PotatoSauceMC** [comment]
I guess since this version works I'll use this one. If that crashing problem happens then I'll give more info.

**Comment by The-1-7-10-Pack** [comment]
:+1:

**Comment by PotatoSauceMC** [comment]
Its happening again... We started a new world and right away my friend wandered into a bad chunk or something and his client crashed. Here's his crash report. http://pastebin.com/FxsRUcV0

**Comment by The-1-7-10-Pack** [comment]
One of the mods spawned an invalid mob. Do you have any additional mods?

**Comment by PotatoSauceMC** [comment]
I've only installed Optifine and I crashed but my friend does not have optifine and he also crashed.

**Comment by PotatoSauceMC** [comment]
I just tried joining my server and I crashed with a different crash report: http://pastebin.com/raw.php?i=M9nTfAEy

**Comment by The-1-7-10-Pack** [comment]
This crash report really says nothing, maybe a corrupted chunk.
Still having a problem?

**Comment by PotatoSauceMC** [comment]
I haven't yet, I was able to update the server to the latest after realizing it was a config problem so as of right now I'm not having any issues but I haven't been playing that much.

**Comment by The-1-7-10-Pack** [comment]
If you'd encounter any issue, be sure to report here :)
