### ISSUE TITLE
Client Crash when crafting ME Covered Cable from NEI

### ISSUE THREAD

**Issue by Boehrsi** [The-1-7-10-Pack/The-1.7.10-Pack#664]
If I try to shift click the ME Covered Cable recipe from NEI in a Crafting Station from Tinkers' Construct the client crashes. The Server is unaffected but at the client side its a total crash back to desktop.

Client and Server Version: 0.7.8 (Local Lan Server)
Client Crash log: http://boehrsi.de/temp/crash-2015-06-12_23.41.54-client.txt

Not a game breaking bug but I thought mentioning it wouldn't be the worst idea.

**Comment by Boehrsi** [comment]
Happens with and without Optifine.

**Comment by Boehrsi** [comment]
Also happening when shift clicking ME Dense Cable. Checked the "normal" work bench also, crashes too. Things likes the ME Terminal (and the needed components) can be crafted from NEI without problems. So until now it seems that only the cables are affected?!

**Comment by The-1-7-10-Pack** [comment]
@Boehrsi Crash report?

**Comment by Boehrsi** [comment]
Crash report? Linked in the first post. (Client Crash log: http://boehrsi.de/temp/crash-2015-06-12_23.41.54-client.txt)
Modpack version? Mentioned in the first post. (Client and Server Version: 0.7.8 (Local Lan Server))
Additional mods? Nothing beside Optifine as mentioned in the second post (but happens also without optifine, as also mentioned.

**Comment by The-1-7-10-Pack** [comment]
@Boehrsi Try to switch your NEI version to the [latest](http://adf.ly/1IqaBO), does it still happen?
(I'm unable to confirm the problem myself at the moment).

**Comment by Boehrsi** [comment]
@The-1-7-10-Pack Tried it with the same result.
Log (Crafting Station from Tinkers' Construct):  http://boehrsi.de/temp/crash-2015-06-14_19.22.48-client.txt
Log (normal crafting table): http://boehrsi.de/temp/crash-2015-06-14_19.17.31-client.txt

As additional information, using the AE2 Crafting Terminal and shift clicking the recipe works fine. Other players on the server are also affected. They use the same config as me.

**Comment by The-1-7-10-Pack** [comment]
@Boehrsi Didn't happen with 0.7.7b, am I right?

**Comment by Boehrsi** [comment]
No everything is on 0.7.8 (Server and all clients)

**Comment by The-1-7-10-Pack** [comment]
@Boehrsi And it happens only with Covered Cabels from AE2?

**Comment by Boehrsi** [comment]
Covered and Dense Cable as far as I recognized.

**Comment by The-1-7-10-Pack** [comment]
@Boehrsi So it's NEI or AE2, I guess. Let me try to confirm the problem myself first though.

**Comment by Boehrsi** [comment]
Thanks in advance and if you need more information I try to provide them.

**Comment by The-1-7-10-Pack** [comment]
Indeed I can confirm the crash, I'll try to get more information at AE2's repo.

**Comment by Boehrsi** [comment]
No problem, at least a small thing the community can do to support the development of this great pack. We have to thank you. :)

**Comment by The-1-7-10-Pack** [comment]
Confirmed as a bug in AE2.

**Comment by The-1-7-10-Pack** [comment]
This is just a minor mod bug, nothing I can do about it really.
I don't see that they're trying to fix it in the current updates, so I'm closing this one for now.

**Comment by xJon** [comment]
Fixed in new builds of AE2, will be in the modpack when they get stable.
