### ISSUE TITLE
Two bugs? Quarries and hunger bar

### ISSUE THREAD

**Issue by Bleuz** [The-1-7-10-Pack/The-1.7.10-Pack#665]
Running verison 0.7.8 - 

Losing hunger all the time even when sitting still. Seems to be at an abnormal rate as well. Recently when to the moon via Galacticraft for the first time.

Secondly - Seems the Quarry is not staying loaded when I leave. My Quarry runs in the mining world dimension, is loaded via a world anchor as well, and uses a tesseract. When i warp home my AE system is not receiving anything. If I stand next to the quarry it runs and my items enter my AE system.
Perhaps world anchors issue?

Thanks!

**Comment by The-1-7-10-Pack** [comment]
The first problem is a bit weird, try to give me more information.
The second problem I'll try to confirm myself. Big changes to Buildcraft recently.

**Comment by Bleuz** [comment]
The hunger bug appears to be gone after a simple restart of the world. I will see if I can replicate it though.

The quarry is still not staying loaded even with a world anchor. Replaced the anchor etc.

Playing single-player and running a LAN server as well.

**Comment by Bleuz** [comment]
Guessing it's not the world anchors because my ones in the nether are staying loaded and continuing to pump lava.

**Comment by The-1-7-10-Pack** [comment]
![image](https://cloud.githubusercontent.com/assets/10350644/8164597/b4f0670c-1392-11e5-812b-089c183ae3ae.png)
Did a small test, and I'm unable to reproduce the problem myself. Please double check your setup.
I'm of course not even using Chunk Loaders due to the fact that quarries chunk-load themselfs.
