### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by kylieswartz** [The-1-7-10-Pack/The-1.7.10-Pack#666]
I don't know if this is happening to anyone else but every time I try to run the modpack the window pops up and it just just shows black. I tried to re INSTALL the pack and change the update multiple times but it keeps happening. Can someone please help me I really want to play the pack!

**Comment by TheLegend714** [comment]
Wait for it to load fully because it has to load a lot of mods.

**Comment by kylieswartz** [comment]
Do you know how long it would usually take for it to load fully because I have waited about 20 minutes and it still had not loaded in.

**Comment by TheLegend714** [comment]
It should take a few minutes and don't click on it.

**Comment by kylieswartz** [comment]
I have waited ten minutes with out clicking on it and still nothing :/

**Comment by TheLegend714** [comment]
Odd do you have Java 8 64 bit? Also maybe allocate more ram?

**Comment by The-1-7-10-Pack** [comment]
Please give me your latest log.

**Comment by kylieswartz** [comment]
Ok, I got past the black but now the screen is frozen with a hourglass and the word Initialising at the bottom.


And I don't know how to give you my latest log.

**Comment by kylieswartz** [comment]
It has been like this for 10 minutes and I know it is not my computer

**Comment by The-1-7-10-Pack** [comment]
@kylieswartz You're aware that you've opened issue #666?
