### ISSUE TITLE
RFTools

### ISSUE THREAD

**Issue by mckulich** [The-1-7-10-Pack/The-1.7.10-Pack#667]
Hi guys, what about add RFTools into this mod pack ?
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-crafter

You ask why ? It is simple, this mode has huge potencial, it works well with ender IO, thermal expansion and so on. 

You can make your own dimension same like in mystcraft, BUT you need to keep powered this dimension and this is reason why we should add this. In late game you have ( or you will have so much power) and there is only a few things which require so much power (for example like lasers from MFR) so now you can create some awesome dimension with this mod. (more awesome dimension = more energy to maintain) 

So what do you think ?
PS: I am not native speaker, so my english isnt perfect :)

**Comment by The-1-7-10-Pack** [comment]
The 1.7.10 Pack doesn't miss tech mods.
Although RFTools is a great mod, it won't be added due to the overload of tech mods.
Thanks anyway for suggesting :)
