### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by BoneCrusherR** [The-1-7-10-Pack/The-1.7.10-Pack#668]
Hello everyone,

When I want to join the server i get this error: http://gyazo.com/71f0a7f1b6d978d2f7f1c9e72aac6363
I have tried to reinstall the game and download the pack again. Nothing seems to work.
Can anyone please help me to solve this, im not that good with this kind of stuff.

**Comment by The-1-7-10-Pack** [comment]
Log out of your launcher and then log back in.
