### ISSUE TITLE
NEED HELP PLEASE!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by reaperwii** [The-1-7-10-Pack/The-1.7.10-Pack#669]
So when ever I try and play this mod pack it loads up with a black screen then it says that it's not responding at all. I have the current update for the mod, technic launcher, java and windows 8 but it's not wanting to load up. I've gotten it to load up a couple times but when it does it starts to lag because of the not responding message. The link to their mod is down below and any answers would be appreciated. Thank you!

http://www.technicpack.net/modpack/the-1710-pack.453902

**Comment by The-1-7-10-Pack** [comment]
Please give me your latest log.

**Comment by mckulich** [comment]
Hey man and what about your memory configuration ? Do you use texture pack ? If you use tex. pacl you need increase your memory or your game dont start, try to increase you memory for mc + add java argument like I in this picture

http://i.imgur.com/mdJELAF.jpg?2

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
