### ISSUE TITLE
[Mod Suggestion] Metallurgy 4, ExtraTic

### ISSUE THREAD

**Issue by walrusgumbo** [The-1-7-10-Pack/The-1.7.10-Pack#67]
Metallurgy 4 adds a lot of new materials to Minecraft and greatly expands the variability of the game. It can even be configured to put certain metals only in some dimensions (you can, for example, populate the Twilight Forest and only the Twilight Forest with fantastic metals like Mithril and Adamantite). It works with both Technology and Magic (it has metals for both) and is very well balanced.

ExtraTic allows for metallurgy metals to work with Tinker's Construct.

**Comment by The-1-7-10-Pack** [comment]
I'm sorry but such a big mod like Metallurgy 4 will not be added to the modpack, it just doesn't fit.
Thank you anyway!
