### ISSUE TITLE
Failed to load class and cant open the mod pack

### ISSUE THREAD

**Issue by Wolfygod** [The-1-7-10-Pack/The-1.7.10-Pack#670]
i opened up the console and said failed to load class please help

**Comment by TheLegend714** [comment]
Do you have Java 8 64 Bit?

**Comment by The-1-7-10-Pack** [comment]
I need your logs.

**Comment by samiristhebest** [comment]
ive that problems also failed load class but its not launcher but something else @The-1-7-10-Pack 
and its not the problem with java

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
