### ISSUE TITLE
error updating the mod to 0.78 

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#671]
hi, 

i have been trying to update the mod pack to 0.768 but every time i click update it says unable to install a mod for this mod and giving this as the problem and says contact the mod author 

http://solder.endermedia.com/repository/mods/project-red/project-red-4.6.2.82.zip

**Comment by The-1-7-10-Pack** [comment]
Was a problem with the host and it should be fixed now.
Thank you!
