### ISSUE TITLE
Modpack crashes before opening

### ISSUE THREAD

**Issue by KushTreats** [The-1-7-10-Pack/The-1.7.10-Pack#672]
Hello. I am trying to run the 1.7.10 modpack but when I click play. A progress bar on the bottom appears and says "Installing Minecraft" then disappears and when I check the crash log I got this.

http://pastebin.com/61jyVnqe

I tried both versions of java (java 7 and 8) 64 bit

**Comment by The-1-7-10-Pack** [comment]
It's a problem of the launcher, reinstall it and it should work.
