### ISSUE TITLE
My Minecraft crashes every 5 minutes.

### ISSUE THREAD

**Issue by TheLegend714** [The-1-7-10-Pack/The-1.7.10-Pack#674]
So i can load my world but it crashes after a few minutes for no reason at all. Also I have Java 8 64 Bit and I have allocated 8-10 gigs of ram and i have like 240+ mods.

**Comment by The-1-7-10-Pack** [comment]
If you have additional mods it's probably the problem.
Still, maybe I'd be able to help you.
Give me your crash report please.

**Comment by TheLegend714** [comment]
Well this is odd now its not crashing and if it does ill post the log closing this until it stops working.
