### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by montyferret** [The-1-7-10-Pack/The-1.7.10-Pack#676]
Just upgraded to latest version 0.7.8.  When I start my LAN server I get the above error and the following comment. 

"java.lang.RuntimeException: A defective recipe has crashed the game! Another mod is creating recipes with non-existent blocks or items, which is a serious error that will cause item or even world loss when crafting these recipes. Corrupted recipes have been saved in the log with tag [HEE-ORB], please try to find which mod they belong to and report them to the respective modder. Then enable the 'overrideRemoveBrokenRecipes' option in Hardcore Ender Expansion and the game will start."

Latest Log - http://paste.ubuntu.com/11717935/
Crash Report - http://paste.ubuntu.com/11717929/

**Comment by The-1-7-10-Pack** [comment]
Do you have any additional mods?

**Comment by The-1-7-10-Pack** [comment]
HEE Forced a crash due to an error it found.
Please give me the "HEE-ORB" log

**Comment by montyferret** [comment]
I've searched the server folder but can't find a HEE-ORB log, can you let me know were it is located.  There are references to HEE-ORB in the latest log linked above on lines 34546-34562.

**Comment by The-1-7-10-Pack** [comment]
It should be in the logs folder, is it not?

**Comment by The-1-7-10-Pack** [comment]
I don't think that the recipes are actually broken, just some small mod-bugs.
Go to the config files and enable "overrideRemoveBrokenRecipes" in HEE.

**Comment by montyferret** [comment]
Definitely no HEE-ORB logs in the log folder.  Editing the HEE config file has enabled the server to start.  Hopefully without any complications.

**Comment by The-1-7-10-Pack** [comment]
:+1:
