### ISSUE TITLE
Hunger Overhaul

### ISSUE THREAD

**Issue by mckulich** [The-1-7-10-Pack/The-1.7.10-Pack#677]
Hi guys, and what about this mod ? 

Hunger Overhaul
http://minecraft.curseforge.com/mc-mods/224476-hunger-overhaul

We have so many foods in our pack, but why ? Honestly how many of you really use full potential of our food possibilities ? So make our food more important for us and so add this mod, and give our food reason why we should make more variation of food

**Comment by TheLegend714** [comment]
Na lol

**Comment by The-1-7-10-Pack** [comment]
The mod is a big game-changer that doesn't really fit the pack.
Thank you anyway for suggesting :)
