### ISSUE TITLE
Requesting a new mod for the pack.

### ISSUE THREAD

**Issue by Armani52561** [The-1-7-10-Pack/The-1.7.10-Pack#679]
I think the modpack should probably have betterstorage. It is 1.7.10. And the modpack author says if you'd like to use his mod in his pack, you could give him credit but it is not necessary. You can read more about it on his page.

It's a great mod that provides better methods of storing your items. As opposed to the simple chests and double chests. It also adds a lot of cool blocks that look interesting along with storing your items.
This is the minecraftforum page for the mod:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1442380-betterstorage-0-13-1-126-wip

Here is what he says about modpacks:
 "Modpack Permissions
Spoiler (click to hide)
You can use BetterStorage in your modpack, public or private. It would be nice if you could link to the mod's website (currently redirects here) or this thread, so people know where it came from, but this is not required. I'd appreciate it if you avoid using adf.ly or similar services."

**Comment by Armani52561** [comment]
Some more information about it is that it includes backpacks to store your items on the go to increase your carrying capacity. Along with integration for Thaumcraft, a mod the modpack already has. But it also adds armor stands and locked chests to ensure your things do not get stolen on a server without residence/towny/anti-grief.

**Comment by The-1-7-10-Pack** [comment]
The mod is indeed cool, but it doesn't add anything that is not already in the modpack.
Adding more mods, even if they're good, for now good reason, is not something we want to do :)

Thanks anyway for suggesting!
