### ISSUE TITLE
Game isn't launching. Stops and launches nothing at 0% at Installing Minecraft Assets

### ISSUE THREAD

**Issue by ethanwdp** [The-1-7-10-Pack/The-1.7.10-Pack#68]
I click play, and it stops at 0% Installing Minecraft assets and the technic launcher closes as though it launched but immediately reopens.
I completely uninstalled Java and reinstalled it. It is Java 8.
I am running 0.6.1, which is the only option available.
I deleted the pack and reinstalled it three times, one from the reinstall pack button, one from deleting it using the delete pack button and a redownload, and the last was another deletion and redownload to ensure it wasn't a fluke.
I reinstalled Technic Launcher completely.
My computer has 4GB ram, it is a 32 bit Windows 7 OS.
My Java is 32 bit.

There is no logs folder at all, though the rest of the game directory is intact. However, I do have the launcher log file which may be useful: http://pastebin.com/0Lx0YTp1.
If it helps narrow down the problem, I'll try to use this modpack on my gaming rig. (The computer I am currently using is a school computer. Just for the record, there are no filesystem restraints or anything of the sort on it, so I don't believe it's a file firewall issue)

**Comment by The-1-7-10-Pack** [comment]
Unfortunately, The 1.7.10 Pack may include all the mods you like and wish to play in, but it can't support 32 bit systems (that can give Java only 1GB of RAM) - The 1.7.10 Needs at least 2GB of RAM, and that is more than 1.
Although, I am not sure why would you have 32 bit OS Installed on your computer if you have 4GB or RAM. If you wish to improve performance on your computer I recommend you switching to an 64 bit OS. Maybe there's a reason that I don't know, but I'm just saying.
If you'll have 64 bit system -> 64 bit Java, you'll be able to allocate 2 GB of RAM and play the modpack.
Good luck!
