### ISSUE TITLE
A plugin suggestion for the up and coming server

### ISSUE THREAD

**Issue by Armani52561** [The-1-7-10-Pack/The-1.7.10-Pack#680]
I read that you are using Akliz for the up and coming server. Well, I believe that when the server does come to shine, it should have the residence plugin.
http://dev.bukkit.org/bukkit-plugins/residence/

It allows you to use a selected item (of the owners choice) to select land to claim. It has a lot of flexibility when it comes to protecting homes. But it can also be limited on how many residences one can have, how large it can be. If you can allow people to tp to it or not. If you want them to be able to not allow people to be inside. (You can make it so people cannot go inside a residence) 
You can also ensure that there isn't pvp, firedamage, waterspreading, redstone usage. 
However, all of these features can be enabled/disabled by the server owner.

Along with that, you can easily and cleanly tell where your residence begins and ends And you can also become a real estate engine as the residence plugin comes with addons. For example residence: signs. That allows you to sell your residence for whatever currency specified in the config file. You can sell/purchase property.

**Comment by The-1-7-10-Pack** [comment]
Thank you for the feedback, will be able to use it in the future :)
