### ISSUE TITLE
Won't load through Technic?

### ISSUE THREAD

**Issue by Dysdayn** [The-1-7-10-Pack/The-1.7.10-Pack#682]
When I try to launch the pack through Technic Launcher, it proceeds as normal until reaching a point right after "checking for MInecraft access." A white window flashes for less than a second, then the process terminates, leaving the launcher open. I've checked with one other modpack, Hexxit, and am able to load that successfully. Windows 8.1. I'm not sure what other information is relevant.

**Comment by The-1-7-10-Pack** [comment]
> 99% you have the wrong Java version. You need Java 7/8 and 64 bit. Please check for that. If you do have the right version please post here your latest log and I'll reopen the issue.
