### ISSUE TITLE
Mod-pack doesn't run. The Technic launcher disappears and no visible error pops up. 

### ISSUE THREAD

**Issue by sajjed** [The-1-7-10-Pack/The-1.7.10-Pack#683]
http://paste.debian.net/hidden/9d709ace/

Ok basically I've got the issue where the modpack doesn't run. Now I know usually it is to do with java. So I downgraded to Java 7. And it still doesn't run/work. It just blanks on me.

The link above is the log.
O.S is Windows 8.1 64bit 

If any more info is needed. Let me know. Would be great if I can resolve this error.

**Comment by sajjed** [comment]
Oh and I had the command window operating in the background while the modpack was being launched (which it was in the process of) but nothing happened.

**Comment by TheLegend714** [comment]
Your going to need Java 64 Bit for your 64x system m8

**Comment by The-1-7-10-Pack** [comment]
Reinstall the launcher.

**Comment by sajjed** [comment]
Ok I'll try this

**Comment by sajjed** [comment]
Alright it still doesn't work. I'm gonna post a full log.

**Comment by sajjed** [comment]
So I am using the latest version of the modpack. I am also using the right version of java for my Windows 8.1 java 64bit. I am using the right version of Java 7 64bit. Not java 8. I am not using Optifine. This is nothing to do with servers but rather the modpack just not starting up (It just attempts to start up then nothing). 

Here is the full log:
http://paste.debian.net/235711/

Note: I have Java 64 Bit for my 64x system
Oh and I also re-installed my launcher and even installed another modpack which ran fine.
