### ISSUE TITLE
KCauldron Incompatble mods?

### ISSUE THREAD

**Issue by Jasems** [The-1-7-10-Pack/The-1.7.10-Pack#684]
Which mods are the least compatible with KCauldron?

**Comment by The-1-7-10-Pack** [comment]
FastCraft and ColorChat, maybe even NotEnoughResources.

**Comment by Jasems** [comment]
Great, thanks for the reply.  Some of the crashing issues I am experiencing are over my head I think.  I will try removing FastCraft, I already removed ColorChat.

**Comment by The-1-7-10-Pack** [comment]
Try posting the crash reports and I'll help.

**Comment by Jasems** [comment]
Ok, will do when I get home from work tonight.  Thanks for the help!

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
