### ISSUE TITLE
Client crash when I join a server 

### ISSUE THREAD

**Issue by tcostella** [The-1-7-10-Pack/The-1.7.10-Pack#688]
This is the crash report: 

**EDITED: Please use a paste-tool: http://pastebin.com/2jn7kZWA**

**Comment by The-1-7-10-Pack** [comment]
> Server brand: vanilla

The server has the pack installed?

**Comment by tcostella** [comment]
Yes, I can join perfectly, but when I try hitting an animal or breaking a block it crashes.

**Comment by tcostella** [comment]
Yes, I can join perfectly, but when I try hitting an animal or breaking a block it crashes.

**Comment by The-1-7-10-Pack** [comment]
@tcostella Maybe the server is missing few mods. I need your latest log to check for that.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
