### ISSUE TITLE
mod are not installing

### ISSUE THREAD

**Issue by giladmi9** [The-1-7-10-Pack/The-1.7.10-Pack#689]
something worng, i hear about this modpack and its hearing very fun!, but the only problam they say when i click play its tolding i need to download mod so i try download but from a reson this website closed! if someone can show me the mod i need or i talk about him right now so pls sent me them!, thanks.

**Comment by The-1-7-10-Pack** [comment]
What?

**Comment by TheLegend714** [comment]
What The FK?

**Comment by TroublingMink59** [comment]
everybody has been getting it recently. Try downloading a new instance of your pack, you'll have the same problem

**Comment by giladmi9** [comment]
ok, i try to restart the modpack download, thanks

**Comment by giladmi9** [comment]
still not work!, this is what the tolding me with the CB'S DepLoader Cannot Istall the mod:
CB's DepLoader was unable to download required library slick-util-0.0b9db0b2.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/slick-util-0.0b9db0b2.jar and put it in your mods folder


so idk what just happend there and pls try fix that website or try other website can you download from them this file!

**Comment by giladmi9** [comment]
and my secend idea:
try delete the mod from the modpack if its not an important mod, i mean, if they remove the website maybe that mod was not so important.

**Comment by The-1-7-10-Pack** [comment]
@giladmi9 Look #690
