### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by Solenea** [The-1-7-10-Pack/The-1.7.10-Pack#690]
I get this download Error, when i am loading the game after reinstalling the modpack.

"CB's DepLoader was unable to download required library slick-util-0.0b9db0b2.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/slick-util-0.0b9db0b2.jar and put it in your mods folder"
i do have internet connected and the link in the text doesn't work.. 
Solenea

**Comment by jrmysprks** [comment]
CB's DepLoader was unable to download required library vorbis-java-core-0.8-20150201.161816-1.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar and put it in your mods folder

When I try the link my browser returns this: Google Chrome could not load the webpage because files.qmxtech.com took too long to respond. The website may be down, or you may be experiencing issues with your Internet connection.

**Comment by jrmysprks** [comment]
Hi Solenea,
 It seems the host is down but I Found your file at:
http://www.mediafire.com/download/986n3kvzy92sl8i/slick-util-0.0b9db0b2.jar

**Comment by giladmi9** [comment]
its nice but now its wirte an other message:

CB's DepLoader was unable to download required library vorbis-java-core-0.8-20150201.161816-1.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar and put it in your mods folder

so what i do with this one?

**Comment by giladmi9** [comment]
So PLLSSS if its not the modpack blame so delete this stupid mod!!!!!!!
PLSS

**Comment by Solenea** [comment]
Hey all, i searched around a bit and it seems that it is a general problem with technic launcher and not the "1.7-10 pack".
It can be fixed by downloading the 11 files that has to be in: ".technic-> modpacks->the-1710-pack-> mods -> 1.7.10
I would upload them for you, but i'm not familiar with how to do so?

**Comment by giladmi9** [comment]
do you got the folder i need?

**Comment by giladmi9** [comment]
i got an idea!

Make a winrar foler, run all the files to them, then search me at skype and sent my the winrar foler!

easy :D

**Comment by jrmysprks** [comment]
Looks like the site hosting the files is back up, everything should should work now.

**Comment by The-1-7-10-Pack** [comment]
Indeed.

**Comment by pixelpreds** [comment]
can u please fix this "CB's DepLoader was unable to download required library vorbis-java-core-0.8-20150201.161816-1.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar and put it in your mods folder" it wont work

**Comment by Shtucer** [comment]
Down again? Is it a feature?

**Comment by Solenea** [comment]
I'm quite sure it's technic launcher that is the problem and not 1710 pack

**Comment by The-1-7-10-Pack** [comment]
It's a mod that requires a libary file, and his host is down.
