### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by TheLegend714** [The-1-7-10-Pack/The-1.7.10-Pack#691]
My Minecraft crashes when I go to creative mode and I go to the search bar (compass) it crashes.
Also Iam using additional mods if that effects anything. Using version 0.7.6 because I cannot load the newer versions for some odd reason.

**Comment by The-1-7-10-Pack** [comment]
I need the crash log.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information, although I'm pretty sure that there was a bug in Buildcraft in that time. Please open a new issue and I'll see what is your problem launching the newer versions of the pack.

**Comment by TheLegend714** [comment]
I've opened the issue before but your post was to go to tinkerers git-hub and wait for a response but they have not responded since I've posted the issue. Also Ive tried 7.8 and it also did not work so...

**Comment by TheLegend714** [comment]
Also do you still want the log for the issue concerning the compass?

**Comment by The-1-7-10-Pack** [comment]
You simply need to use the latest/recommended version of the pack. Please give me more info why can't you.

**Comment by TheLegend714** [comment]
Heres the log for the newer versions of the modpack not loading.
http://paste.ubuntu.com/11746711/

**Comment by The-1-7-10-Pack** [comment]
There's a problem with your launcher libaries. You need to reinstall the launcher **completely** to fix the libaries and it should work :)

**Comment by TheLegend714** [comment]
Alright ;)
