### ISSUE TITLE
Travelers Outfit problem?

### ISSUE THREAD

**Issue by RedGoblin** [The-1-7-10-Pack/The-1.7.10-Pack#692]
When putting a glove in the tool forge or when pressing swap[b] with the travelers belt. 
Will probably do the same with the other equipment.

http://pastebin.com/FmKE0JV6

**Comment by The-1-7-10-Pack** [comment]
Unable to reproduce with v0.7.9 of the modpack.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
Probably server wasn't set up right.
