### ISSUE TITLE
Allocate more Ram

### ISSUE THREAD

**Issue by LordYellow** [The-1-7-10-Pack/The-1.7.10-Pack#694]
how can i allocate more than 3 ram? I run out of memory very often

**Comment by TheLegend714** [comment]
Through the Launcher go to the top right corner then java settings and memory and there you go. You will need the newest java and 64 Bit to allocate more ram.

**Comment by The-1-7-10-Pack** [comment]
The RAM allocation is automatic and will be like that until Technic will implement their system (which should actually be pretty soon).

**Comment by LordYellow** [comment]
but can i deactivate this feature?

**Comment by The-1-7-10-Pack** [comment]
Why would you?

**Comment by LordYellow** [comment]
because i run out of memory very often

**Comment by The-1-7-10-Pack** [comment]
You shouldn't. Can you provide a screenshot?

**Comment by TheLegend714** [comment]
He is probably using additional mods or either his comp has to do something with it.

**Comment by LordYellow** [comment]
I cant make a screnshot because my game often suddenly just closes , and when I press F3 , I see that 100 % is used

**Comment by The-1-7-10-Pack** [comment]
100% allocated, or used?

**Comment by LordYellow** [comment]
100% allocated and used

**Comment by The-1-7-10-Pack** [comment]
Can I have a picture?
