### ISSUE TITLE
Suggestion  ... consider adding Ore Dictionary Converter

### ISSUE THREAD

**Issue by SlackerNet** [The-1-7-10-Pack/The-1.7.10-Pack#695]
A mod like this lets you convert ores to the same type or to a different type if you need to. Maybe there is already a way to do just that and I don't know about it ? I tried searching the net and ore dictionary Converter was all I found.

[url]http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286974-ore-dictionary-converter [/url]

Thanks for all you do
/R
Slackernet

**Comment by The-1-7-10-Pack** [comment]
We don't need it, there is only one type of each ore in the modpack.

**Comment by SlackerNet** [comment]
The copper alone has 6 different versions, maybe its supposed to be that way for the mods to work..I am not really sure

the copper types are:

galactic craft, industrial craft 2, mekanism, railcraft, tinkers construct, thermal foundation, and forestry are the ones i ran across

I am currently using..... ver 078 on the canadian bacon public server

here is a screen shot so you see what  mean
[IMG]http://i61.tinypic.com/rmtlk2.png[/IMG]

/r
Slackernet

**Comment by The-1-7-10-Pack** [comment]
The ore generation is disabled for all except one.

**Comment by Bleuz** [comment]
You are able to do this via JABBA - Example... Place copper ingot from tinker's construct then place the other mods... All of them will be tinker's
