### ISSUE TITLE
Getting errors while trying to host a server.

### ISSUE THREAD

**Issue by falloute** [The-1-7-10-Pack/The-1.7.10-Pack#696]
http://gyazo.com/ec161509b702501807b367e3237cc5e4     That is when I load up the,  LaunchServer.bat             and also with the server itself  Forge-1.7.10-10.13.4.1448-1.7.10-universal it just loads, says some errors and at very end it says shutting down and closes. Not sure what to do. Please help.

**Comment by The-1-7-10-Pack** [comment]
"eula.txt" -> true

**Comment by falloute** [comment]
What does eulu.txt true mean?

**Comment by The-1-7-10-Pack** [comment]
A text file you need to edit.

**Comment by falloute** [comment]
Sorry, took me so long to reply, but I can't find the file? I downloaded the 0.8.8 server download and couldn't find what file to edit.

**Comment by falloute** [comment]
Never Mind
