### ISSUE TITLE
Work for mac?

### ISSUE THREAD

**Issue by superbpuppet** [The-1-7-10-Pack/The-1.7.10-Pack#697]
does this modpack work for mac? it always crashes when i start up the pack from technic launcher without explanation. this also happens with many other mods if that says anything. and when i start up technic i get this error in console
[B#301] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[B#301] SLF4J: Defaulting to no-operation (NOP) logger implementation
[B#301] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
please help.

**Comment by The-1-7-10-Pack** [comment]
These errors are minor and related to the Launcher itself. If you're unable to launch the pack, 99% you have the wrong Java version, you need Java 7/8 and 64 bit. If you do have it I'll reopen the issue.
