### ISSUE TITLE
World Crashed, Cannot reopen

### ISSUE THREAD

**Issue by Anicena** [The-1-7-10-Pack/The-1.7.10-Pack#7]
Had been playing world for 3-4 hours, took a break for dinner, saved and closed. Came back and played for another hour, crashed to white screen. Had to reboot computer. Cannot reload world. Crashes to TechnicLauncher when trying to load world. Computer is known good, no running issues. Plays all other games flawlessly. Java is up to date, as are all other aspects of computer.

**Comment by Flukethoughts** [comment]
Aroma Makes back ups of your world to repair your world look into using the backup and deleting hard questing mod.
