### ISSUE TITLE
"Installing minecraft assets: 0%"

### ISSUE THREAD

**Issue by Jmick363** [The-1-7-10-Pack/The-1.7.10-Pack#70]
Using the Tecnic launcher, Stable version 4.211, I've installed "The 1.7.10 Pack" modpack version 0.6.1.  When I click "Play" in the launcher, it shows a few progress bars that load instantly, until it gets to "installing minecraft assets" where it stays at 0%, anywhere between a half second flash and 2 seconds long. Then the launcher just flashes quickly and nothings opens.
 
I initially had Java 8 update 25 installed, the latest version.  My friends have gone through the same process and are using the same versions as me, and are able to play with 8u25.  I also instally 7u72, and I uninstalled them both, restarted the computer, and installed 7u71, and it still does the exact same thing every time. My friends are all able to play with few differences than what I'm doing, yet it works for them and not for me.  Is there a known solution to this problem? Any help is appreciated, let me know if any more information is needed.
 
I've already tried uninstalling and reinstalling the pack.  I've also deleted my .minecraft and .technic folders completely, and then launched minecraft, then launched the modpack, and the same thing happened. I've tried those 3 versions of java I mentioned above. I've also tried just double clicking the .jar in the bin folder of the modpack and nothing happens.  I tried doing it after deleted everything expect the jar, and it just redownloads everything. I don't know what else to try so any ideas you have I'm happy to hear.
 
Here is a screenshot of the screen that I'm seeing: http://i.imgur.com/cjDTKgq.png
I deleted all of the logs and did nothing except open the launcher and click play on this modpack, so as to isolate the messages specifically to what's happening: http://pastebin.com/8vQakTJ4

**Comment by The-1-7-10-Pack** [comment]
It's just as https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/68

**Comment by Jmick363** [comment]
Unfortunately, this cannot be the problem.  I have Windows 7 Ultimate x64 installed with 10GB of RAM.  In the technic launcher settings I allocated 9GB of RAM to it and still nothing changes.

**Comment by The-1-7-10-Pack** [comment]
No need to allocate 9GB, you can keep it at the default 1GB, the pack will use the exactly amount of RAM it needs and will ignore the launcher's settings.
The only problem I can guess you have is the wrong version of Java installed, 32bit and not 64bit as needed.
