### ISSUE TITLE
Game crashes while loading

### ISSUE THREAD

**Issue by UNCL3LARRY2** [The-1-7-10-Pack/The-1.7.10-Pack#701]
I dont know why but the game reaches "Initialising..." for a few minutes, then returns to the Technic Launcher, I updated Java to 8u45, I have 5GB allocated, so I dont know what the problem is. 

The error log is here http://pastebin.com/RdswqfUx

**Comment by B4113Y** [comment]
I have exactly the same problem, i placed all of the mods into my Minecraft folder and it didn't work either!

HELP WOULD BE MUCH APPRECIATED!!!!!

**Comment by The-1-7-10-Pack** [comment]
@B4113Y You have a **completely different problem**, you need to have Java 7/8 and 64 bit.
@UNCL3LARRY2 You're out of Heap space, you may have custom Java settings on your computer that block you from allocating much.

**Comment by UNCL3LARRY2** [comment]
How would I go about checking it, and if need be, changing it?

**Comment by The-1-7-10-Pack** [comment]
Right click on "This PC" -> choose "Properties" -> then on the left, click "Advanced system settings" -> then in the "Advanced" tab click "Environment Variables". Then scroll down on "System variables" to see if you have anything related to Java.

**Comment by UNCL3LARRY2** [comment]
Only thing that even references Java is this, with the Variable name of "Path", and value of "C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%CommonProgramFiles%\Microsoft Shared\Windows Live;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\system32\wbem;C:\Program Files (x86)\AMD APP\bin\x86_64;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static"

**Comment by UNCL3LARRY2** [comment]
I tried adding adding -Xms4g to the Runtime Parameters, which didnt work

**Comment by The-1-7-10-Pack** [comment]
A picture might be more clear

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information. Will reopen if needed.

**Comment by BringOutTran** [comment]
I've read through it, I still do not know what to do to fix the problem T__T
