### ISSUE TITLE
Binnie's mods

### ISSUE THREAD

**Issue by ugolin24** [The-1-7-10-Pack/The-1.7.10-Pack#702]
I'm playing forestry for minecraft and i would like MORE BEES !!!
so could you add this mod please ?

**Comment by mckulich** [comment]
It should be fine, extra bees is great expansion and we definetly need it :)

**Comment by Bleuz** [comment]
Already running this mod with no issues

**Comment by mckulich** [comment]
ofc all binnies mods are cool especially extra tress. Really like the new way how many different wood plank i can create
