### ISSUE TITLE
Crashing started randomly again (same error).

### ISSUE THREAD

**Issue by Jasems** [The-1-7-10-Pack/The-1.7.10-Pack#703]
I will post the log tonight when I get home.  Just continuously crashes when a specific user logs in with nothing in the log that helps me determine the problem.

**remove SFM comment.

Thanks!

**Comment by The-1-7-10-Pack** [comment]
Crasg report?

**Comment by Jasems** [comment]
Here are links to crashlog and latest log.  Sorry for the delay, long day at work.

https://drive.google.com/file/d/0B8BGujAnlWVLZkFQT3d2ZE8yT1E/view?usp=sharing

https://drive.google.com/file/d/0B8BGujAnlWVLS0pmc2xHTGdCOFk/view?usp=sharing

The latest log was too large for pastebin so just posting them as attachments.  Thanks for the help!

**Comment by The-1-7-10-Pack** [comment]
I prefer it being online, try to use [this](http://paste.ubuntu.com/) paste-tool.

**Comment by Jasems** [comment]
Ok here is the latest log: http://paste.ubuntu.com/11767261/

and the crash log: http://paste.ubuntu.com/11767276/

Thanks for the help again and the paste-tool site. :)

**Comment by The-1-7-10-Pack** [comment]
Some NBT data in your save is corrupted and causes the crash. It doesn't say more, unfortunately, so it's really tricky.
I'd recommend you to try to get help at the [Forge Forums[(http://www.minecraftforge.net/forum/index.php?board=15.0), where they can try to locate the source for the problem.
Be sure to update me here about anything that you find!
