### ISSUE TITLE
Mod Request - Chunky Peripherals: Turtle chunkloaders! 

### ISSUE THREAD

**Issue by Smalfinn** [The-1-7-10-Pack/The-1.7.10-Pack#704]
With the fact that the ComputerCraft addon Misc Peripherals is now dead.

Can I request that you add Chunky Peripherals: Turtle chunkloaders! http://www.computercraft.info/forums2/index.php?/topic/18156-mc-17-cc-173-chunky-peripherals-turtle-chunkloaders-mining-chunkloaders-crmod/

Adds the ability to make mountable chunkloaders for computercraft turtles, meaning they can mine forever!

Now how cool would that be?

**Comment by The-1-7-10-Pack** [comment]
First of all, [Peripherals++](http://www.curse.com/mc-mods/minecraft/226687-peripherals) is the alternative for 1.7.10.
Now Chunky Peripherals are cool but there are moveable chunk loaders, also turtules are not the best way to mine forever.
The mod won't be added, but thanks for suggesting :)

**Comment by Smalfinn** [comment]
How do I aqquire a moveable chunkloader?
Also; what would you recommend for mass resources?

**Comment by The-1-7-10-Pack** [comment]
World Anchor in minecart :)
Quarry, and for later game Ender Quarry, or a Digital Miner. There are a lot of other options too :)

**Comment by Smalfinn** [comment]
WOW they look awesome!
Wasn't sure whether quarries and such needed chunk loaders?

**Comment by The-1-7-10-Pack** [comment]
They automatically chunk-load themselfs :)

**Comment by Smalfinn** [comment]
Awesome!
Thanks a million
