### ISSUE TITLE
Poor Performance & Recently Crashing 

### ISSUE THREAD

**Issue by ScytherDMC** [The-1-7-10-Pack/The-1.7.10-Pack#707]
I usually have around 20 - 30 FPS & at times it drops below 10, I have allocated 4-5 Gigs of Ram, Intel i7 2630QM processor & AMD Radeon HD 6870M GPU. Also it take 5 to 10 minutes to start the 1.7.10 pack. I linked my last crash report below. Any help or advice would be appreciated. 
http://paste.ubuntu.com/11776118/

**Comment by The-1-7-10-Pack** [comment]
Do you limit your fps, or have additional mods?
About the crash - when did it happen?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
