### ISSUE TITLE
Crashes in the nether

### ISSUE THREAD

**Issue by cshorty9** [The-1-7-10-Pack/The-1.7.10-Pack#708]
I went into the Nether and I started to explore around and then the game just crashed suddenly, now every time I load the world the game just crashes.

Latest Crash-Report: http://paste.ubuntu.com/11776801/
Latest Log: http://paste.ubuntu.com/11776808/

Thanks for any help!

**Comment by The-1-7-10-Pack** [comment]
When you try to go to the nether in a completely different place (build another portal far-far away), are you able to enter it?

**Comment by The-1-7-10-Pack** [comment]
It is, and there's nothing we can really do about it unfortunately. You can try to remove the chunk manually.
