### ISSUE TITLE
Low FPS for no reason: Any suggestions on optimizing?

### ISSUE THREAD

**Issue by Smalfinn** [The-1-7-10-Pack/The-1.7.10-Pack#709]
It is a very heavy modpack, even my machine has trouble giving me over 50fps with 8GB RAM allocated, i7-4790 CPU @ 3.60GHz Proessor and a MSI nVidia GeForce GTX 760. I'm running the server locally so upload and download speed shouldn't be a factor. Also, doesn't seem to matter if my graphics are set to fancy or fast, which is very weird.

Any way for me to get a stable 60FPS?

Internet speed for those who are curious: http://www.speedtest.net/my-result/4460909621

**Comment by The-1-7-10-Pack** [comment]
Do you limit your fps to 60?

**Comment by Smalfinn** [comment]
I tried limiting it to 60 but still doesn't stabilize. caps at about 53fps. Currently unlimited running between 40-50fps running around then the dynamic lights in a mine crashes my fps to around 20

**Comment by The-1-7-10-Pack** [comment]
Did you try to reset your video settings to default?
I'm able to get 200-300 fps with GTX 670.

**Comment by Smalfinn** [comment]
Apologies, I'm very new to minecraft; how do I reset all my settings?

**Comment by The-1-7-10-Pack** [comment]
You should try to install [Optifine](https://optifine.net/downloads) to get better performance, when you'll install it you'll also be able to reset the settings with one button click.
To install it download the latest ultra version to 1.7.10 and put the jar file inside the "mods" folder, in the modpack's folder.

**Comment by Smalfinn** [comment]
is that for both the server mods folder and the client mod folder?

**Comment by The-1-7-10-Pack** [comment]
Optifine is client only :)

**Comment by Smalfinn** [comment]
I will test when I get home and let you know how I get on (Y)

**Comment by Smalfinn** [comment]
Loaded up Optifine and played around with some settings and got upto 250fps now (Y)
Thanks a million!

**Comment by The-1-7-10-Pack** [comment]
:+1:
