### ISSUE TITLE
Chest and Invent Porblems

### ISSUE THREAD

**Issue by EnderFriend** [The-1-7-10-Pack/The-1.7.10-Pack#71]
I was crashing when trying to open a chest, EDIT Welp, it fixed itself, except for the chest opening part.
I need help please :( Also i cant open my invent. *sigh*
here ya go:    http://paste.ubuntu.com/9763580/

This is me consulting.

**Comment by The-1-7-10-Pack** [comment]
Please provide a crash report.

**Comment by EnderFriend** [comment]
i left one :3

**Comment by The-1-7-10-Pack** [comment]
It's a problem of the Thaumcraft NEI Plugin, very weird.
For now I can recommend you to uninstall the mod manually (just delete the thaumcraftneiplugin.jar file from the mods folder) - but you should report this bug to the mod author there: https://github.com/DjGiannuzz/Thaumcraft-NEI-Plugin/issues
Provide to him all the information you have, when did it start and the crash report.
