### ISSUE TITLE
Microblock Do not work

### ISSUE THREAD

**Issue by Linklog** [The-1-7-10-Pack/The-1.7.10-Pack#711]
I have been playing this game but i have a problem, microblocks do not work; 
![2015-06-26_16 40 37](https://cloud.githubusercontent.com/assets/13071471/8389247/2f19cb76-1c22-11e5-88f4-86e55238c260.png)

**Comment by The-1-7-10-Pack** [comment]
Just because they're not in NEI doesn't mean they don't work. We filter the micronblocks because we don't want them to flood NEI.
