### ISSUE TITLE
Won't Start!

### ISSUE THREAD

**Issue by Chocolate98282** [The-1-7-10-Pack/The-1.7.10-Pack#712]
I FINALLY got it downloaded, then when i hit play it loaded up everything and then the launcher closed as usual. About a second later, the launcher popped back up, no game. i updated my java to the latest version and tried again, still didn't work. If someone could tell me how to fix this i would be grateful, as i was looking forward to playing this modpack and it's the only one i could find the statues mod in.

**Comment by TheLegend714** [comment]
You need Java 8 64 Bit and if that does not work post your log with this http://paste.ubuntu.com/

**Comment by The-1-7-10-Pack** [comment]
Will reopen if needed.
