### ISSUE TITLE
Unable to download required libary - CB Deploader

### ISSUE THREAD

**Issue by faintedsquirtle** [The-1-7-10-Pack/The-1.7.10-Pack#713]
I tried installing the modpack but I keep getting the error "CB's DepLoader was unable to download required library vorbis-java-core-0.8-20150201.161816-1.jar Check your internet connection and try restarting or download it manually from http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar and put it in your mods folder" but the website link doesn't exist.

**Comment by RazorCWB** [comment]
i have the same problem

**Comment by The-1-7-10-Pack** [comment]
A mod's files host is down, should be fixed soon.

**Comment by faintedsquirtle** [comment]
So glad it's not on my end

**Comment by The-1-7-10-Pack** [comment]
In v0.7.9 we'll add those files with the modpack so problems like this won't happen again.

**Comment by faintedsquirtle** [comment]
when will that version be out? I am going to join a private server tomorrow and I was looking foward to play on it :/

**Comment by The-1-7-10-Pack** [comment]
The host of the mod files should be up soon.

**Comment by faintedsquirtle** [comment]
Still not up- The next day

**Comment by kirbeh87** [comment]
i found out if you right click the link http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar and chose save file as, you can manually download the jar file and place it in the mod folder, which fixes this issue however after the fix it then states it cant download the jar slick-util-0.0b9db0b2.jar so far i have found no way around this

**Comment by faintedsquirtle** [comment]
Kirbeh I tried but what browser are you using? It doesn't come up with the save as option.

**Comment by kirbeh87** [comment]
im using crome however i realized its save link as..  sorry

**Comment by kirbeh87** [comment]
I also foud out the issue seems to be coming from modular powersuits

**Comment by faintedsquirtle** [comment]
I tried uninstalling it but it didn't work anyways

**Comment by The-1-7-10-Pack** [comment]
Guys, just wait and don't panic. It's not the first time it happens - this mod's host for files is not that stable. We'll make sure it won't happen anymore in future updates, but for now waiting should be the easiest way.

**Comment by kirbeh87** [comment]
so i may have found a temporary work around untill the official fix however im using a low end laptop so i ran out of virtual memory when initializing the mods. what i did was completely uninstall and delete my .minecraft folder, then reinstalled it, installed the latest forge for 1.7.1o, then copied all the files for the 1.7.10 pack into my .minecraft folder and deleted the mods ModularPowersuitsAddons-0.11.0.7-QMX, ModularPowersuits-1.6.4-0.10.0-91, and Numina-0.4.0.87.  i then ran the game using the 1.7.10 forge from the original minecraft launcher. i made sure the launcher did not disappears so i could see the loading progress, everything seemed to be running smoothly, however for me at least it took a long time, before i ran out of memory. so if anyone has a faster comp that can try this method and see if it works and let me know. cant guarantee it will work but dosent hurt to try

**Comment by The-1-7-10-Pack** [comment]
As a temp fix for anyone that wants you can download the libary files from [here](http://solder.endermedia.com/repository/mods/qmx-files/qmx-files-1.0.zip), and put the in the modpack's folder as they are in the zip.

**Comment by faintedsquirtle** [comment]
Now the modpack won't even open o.o

**Comment by faintedsquirtle** [comment]
I press launch and it loads then it just refreshes and doesn't open

**Comment by Chocolate98282** [comment]
I got it to work by taking the two jar files from the zip folder and putting them directly into the mods folder for the pack.

**Comment by The-1-7-10-Pack** [comment]
Added the files as another mod in the solder - Should work. Try to reinstall so it'll detect the change, and confirm here.

**Comment by The-1-7-10-Pack** [comment]
It fixed it.

**Comment by BigAl607** [comment]
Just tried downloading and playing this pack.  Having the exact same issues with the latest and recommended packs.

**Comment by BigAl607** [comment]
I tried downloading the files as you stated in the post 6 days ago and the files are all ready in there.  When pressing play, still getting the same error message.  I really hope this gets fixed, as we'd like to get a server going with this pack.

**Comment by SUnRaysUV3** [comment]
Thank me later

https://web.archive.org/web/20150409134012/http://files.qmxtech.com/libs/vorbis-java-core-0.8-20150201.161816-1.jar

**Comment by assnicgegrs** [comment]
https://dl.dropboxusercontent.com/u/47135879//Baubles-1.7.10-1.0.1.10.jar
