### ISSUE TITLE
Unable to process Galacticraft Silicon Ore

### ISSUE THREAD

**Issue by ninjamckickass** [The-1-7-10-Pack/The-1.7.10-Pack#714]
1. I have an Ender IO quarry with silk touch. I'm getting no recipe to process to raw silicon without laying it on the floor and using a pickaxe.
2. When I mine it with the power glove from Modular Power suits it just disappears.

Regular, ruby and tinkers' pickaxes work fine. I am using EnderIO silicon as a work around.
Using v0.7.7b

**Comment by The-1-7-10-Pack** [comment]
- You mean you're having problems processing the silicon ore?
- Unfortunately there's no work arount, the support for the power suits is gone currently.

**Comment by ninjamckickass** [comment]
Yes, the Ore itself not the raw silicon. I can't cook or process it in anyway to get raw silicon.

**Comment by The-1-7-10-Pack** [comment]
Just put it on the ground and mine it manually.

**Comment by ninjamckickass** [comment]
Gotcha.
