### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by Voideon** [The-1-7-10-Pack/The-1.7.10-Pack#715]
Tropicraft

Advanced Genetics

**Comment by Voideon** [comment]
And Archaeology and Fossils reported

**Comment by mandm635** [comment]
These are good mods that I also enjoy, however tropicraft was just recently revived, and is missing a lot of features/has many bugs.

Advanced genetics has some severe balance issues although is fun. Perhaps with some changes it might be considered.

Its not my choice but I think these mods would be a good edition to the pack.

**Comment by The-1-7-10-Pack** [comment]
The mods are not going to be added but thanks again for suggesting :)
