### ISSUE TITLE
Cannot Download Modpack

### ISSUE THREAD

**Issue by mandm635** [The-1-7-10-Pack/The-1.7.10-Pack#716]
When I try to install the latest version of the pack I get an error saying: "The modpack The 1.7.10 Pack does not appear to be installed or is corrupt, and is not available for Offline Play." The pack is also marked as offline.

**Comment by mandm635** [comment]
Never mind, I restarted Technic and it worked. :P

**Comment by The-1-7-10-Pack** [comment]
:+1:
