### ISSUE TITLE
Dynamic Lights off/on

### ISSUE THREAD

**Issue by mandm635** [The-1-7-10-Pack/The-1.7.10-Pack#717]
When I joined a new world in the latest version of the pack, 0.7.8, I got a message saying dynamic lights globally off. Items such as the torch do not give off light. If this is an intended feature, the mod itself should be removed as that is the mod. Please tell me if im doing something wrong. I looked in the config and didn't see anything like that but im not good with that stuff.

**Comment by The-1-7-10-Pack** [comment]
There's a hotkey for turning it on/off, try 'K' or 'L', I don't remember. You can check in the controls menu.
