### ISSUE TITLE
Creative Ctrl Sprint While Flying Bug

### ISSUE THREAD

**Issue by mandm635** [The-1-7-10-Pack/The-1.7.10-Pack#718]
Using latest pack version, 0.7.8, I have set all my controls so that the only thing using Ctrl is sprint, however when flying in creative, It wont let me use the sprint with Ctrl. On the ground, I can use sprint, but it doesnt zoom my screen like normal but still sprints.

Also, I was wondering what the key.control option is/what mod adds it as it is always set to Ctrl, and disables sprint.

**Comment by The-1-7-10-Pack** [comment]
Sprinting while flying? doesn't make much sense. On the ground, in the modpack, the zoom is balanced so it won't be that annoying sometimes. It's not a bug, and there's nothing wrong with your system :)
