### ISSUE TITLE
Asking for help in the right place.  ;)

### ISSUE THREAD

**Issue by eliannawhm** [The-1-7-10-Pack/The-1.7.10-Pack#719]
Thank you for directing me here from the modpack page to get assistance. One of my favorite mods is Geocraft which allows you to customize your ore distribution.  I also love Metallurgy because it has so many ores.  Here is where I ran into difficulty.  Each time I added Metallurgy it would either dump me back to the launcher or give an error in MC.  I am not sure what I am doing wrong.
I will admit I have done a little tweaking to the modpack.  I have added:
Binnie-mods
CustomMobSpawner
Dr.Zharks MoCreatures
Enchiridion
extrabiomesxl
ExtraTiC
Geocraft
KeithyUtils (required for Metallurgy)
Mariculture-Deluxe
MetallurgyCore
MetallurgyMod
Pam's Clay Spawn
Pam's DesertCraft
Pam's Get all the Seeds
Pam's WeeeFlowers
RedGearCore (required to run Geocraft)
Ruins
SAPManPack
UndergroundBiomesConstructs
VarietyChests

If I take the Metallurgy out all is well.....add it back in and nothing works.
The thing is I have used all of these mods on a custom pack I did for myself in 1.6.4 so I know they should play nice together.  Perhaps I should be talking with the creators of Metallurgy?  Thought I would start here since this would be an awesome add in the modpack.  What exactly can I get for you, like logs and such, that might help sort this out?

btw....Geocraft is an amazing mod that gives the user control over the ore distribution including most of the added ores from other mods.  You can make them scarce or so bountiful you can barely go 10 blocks without running into some kind of ore.  It's a lot of fun to play with.  You may wish to consider adding it.  It runs just fine with everything else you already have.

**Comment by eliannawhm** [comment]
Please forgive me.  I feel really stupid right now.  Here I was bragging about Geocraft and that was in a different modpack.  It's been a really really long day.
I am starting over again now with a clean install of your modpack then will add each new mod one at a time like I am supposed to.  I was just so excited that I found such a great modpack for 1.8 that I let my enthusiasm get away with me.  If you would like I will keep you updated as to what works as I add things.  If not, I totally understand.

**Comment by The-1-7-10-Pack** [comment]
We have other ways to customize out ores, and Metallurgy adds a lot of contect that not everybody like. Thanks for the suggestions but all these mods are not in the pack for a reason, maybe except Binnie's Mods, that you can comment your opinion whether to add it or not [here](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/702). :)
