### ISSUE TITLE
Chococraft

### ISSUE THREAD

**Issue by clienthax** [The-1-7-10-Pack/The-1.7.10-Pack#72]
As the maintainer of chococraft i give you permission to use it in the pack if you want to,
http://minecraft.curseforge.com/mc-mods/225280-chococraft

**Comment by The-1-7-10-Pack** [comment]
Awesome!
Do you think it will fit good in the modpack?

**Comment by clienthax** [comment]
Its a pretty small mod, and the breeding offset makes it worth putting the effort in to get a flying chocobo, slightly improves travel speed but no op effects ;),
also would you mind adding me on skype "clienthax"

**Comment by The-1-7-10-Pack** [comment]
As I find the skype a bit too much personal l'd pefer you to contact me through a P.M in the MCF: http://www.minecraftforum.net/members/Jon

**Comment by Flukethoughts** [comment]
While I would enjoy it there are already far to many mobs on the map as it is. While I would suggest maybe some users try it in single player I don't see being able to hold any more mobs on the server.

**Comment by da404lewzer** [comment]
I just hope the amount of chocopedias you get from mob kills has been reduced. I'm not sure if the last version was bugged but we always had tons of them in our inventories after a good grind XD

**Comment by poetofsilence** [comment]
I feel like the pack could do without it. Just imo.

**Comment by DragonOfStendarr** [comment]
It would be awesome if we got this in the modpack! :3

**Comment by MrKRONIC** [comment]
put chococraft in for sure its an amazing mod and really adds something new to the animal system and breeding, also it goes well with the magic side as would dragon mounts mod  for warlocks and wizards style players, my self i play as a tech and redstone guy with guns and tech where alot of my pals take the magic route and having that dragon to fly on or that chocobo is a really good feature for this modpack

**Comment by DragonOfStendarr** [comment]
I too want chococraft :c

**Comment by MrKRONIC** [comment]
he aid he wont add it along with alot of other mods i requested, well fuck them man i will open a server withh all of the mods that people want adding to this pack and ill configure it myself, DRAGON your more then welcome to join myfriend.

**Comment by Flukethoughts** [comment]
wow sometimes people can be so ignorant. Grow up kids

**Comment by Voideon** [comment]
I don't really feel like writing a long explanation why I think it would be dumb to have it in....
But the thing about this modpack that I personally like is that it doesn't feel like any other modpacks.
I think chococraft would change that

**Comment by RetroJaro** [comment]
I'd like the option to use another riding mount besides horses, and chocobos are amazingly cute with the sphax texture pack. Plus you can breed them, which is always a nice little diversion.

**Comment by bfoxeh** [comment]
Please add chococraft to this pack! I will host a server if you do. 
Pros:
People love chococraft, and it is not in any big name modpack other than tolkiencraft,This will bring people who want chocobos to this modpack.

players that dislike chococraft can simply not use it.

server owners that dislike chococraft can simply disable it.

Cons:
The only con that I could derive with the mod is that the mod dev hasn't added spawn eggs for each type of chocobo yet. I added chococraft 4.1.5 to the 1.7.10pack 0.7.6c and there didn't appear to be any conflicts in recipes, chocobos spawned normally as did the greens.

**Comment by RetroJaro** [comment]
In response to bfoxeh:
I'm not Voideon obviously, but the only 1.7.10 pack I can recall that has chocopedia is the project flux branch of the resonant rise pack.

**Comment by CriticalRocket** [comment]
**Voideon: But the thing about this modpack that I personally like is that it doesn't feel like any other modpacks.
I think chococraft would change that**

He's not talking about the chococraft already being in a lot of modpacks. What he's saying is that the mod would ruin the feeling he gets from this modpack.


Not that I myself agree with that, but everyone is entitled to their opinion :p 
I just always like new stuff to explore, so chocobo's would be fun IMO :)
