### ISSUE TITLE
Ore Distribution Customization

### ISSUE THREAD

**Issue by eliannawhm** [The-1-7-10-Pack/The-1.7.10-Pack#720]
My favorite thing about MC is mining.  Start at the surface and find your way to bedrock.  ;)
So, in this pack how can you customize your ore distribution?  I just started using this pack yesterday so I have not even begun to scratch the surface of it's greatness.  I got my pick and I am ready to spelunk.

**Comment by The-1-7-10-Pack** [comment]
A lot of ores are disabled to have only one mod-ore from each type.
Some minor changes, didn't overhaul it too much; based on the default.
Still a lot of fun mining, even more when you have something doing it for you...
