### ISSUE TITLE
Hardcore Questing- Incomplete-able quest

### ISSUE THREAD

**Issue by Sovreign** [The-1-7-10-Pack/The-1.7.10-Pack#721]
Minor bug/ 

Grindem down quest requires 64 grinders in inventory, however, Grinders do not stack, and therefore you cannot hand the quest in, because standard invent size is too small.
Have tried in a party with inventories combined, and no luck.

unless I've overlooked something...

![javaw 2015-07-02 18-20-29-65](https://cloud.githubusercontent.com/assets/13147804/8472801/9fd1ad38-20e7-11e5-9d78-8ee118f4d30f.jpg)

**Comment by The-1-7-10-Pack** [comment]
Thanks for reporting!

**Comment by Sovreign** [comment]
but of course. 
Loving this pack, really nice work on it- well done sir.
I'm so impressed at how smooth its running.
