### ISSUE TITLE
Failed to login: The authentication are currently down for maintenance

### ISSUE THREAD

**Issue by Sapanator123** [The-1-7-10-Pack/The-1.7.10-Pack#722]
My friend and I are attempting to play on a LAN server, and it worked fine previously, but now whenever I attempt to join the server (He's hosting), it comes up with the error in the title. We're using Tunngle to connect to each other, and I have attempted every solution I could google. I've restarted my computer, reinstalled everything (Java, Technic Launcher, 1.7.10 pack), attempted to join in offline mode, restarted my router, changed my IPv4 DNS and nothing works. The servers aren't down because Mojang shows that they're up, and I can join unmodded public servers. Is there anything I can do?

**Comment by The-1-7-10-Pack** [comment]
Are you using cracked launchers?

**Comment by Sapanator123** [comment]
Nope, I purchased Minecraft back when it was in beta, and I downloaded the Technic Launcher from the technic website.

**Comment by The-1-7-10-Pack** [comment]
Can I get the full client log? please use a paste-tool

**Comment by Sapanator123** [comment]
http://pastebin.com/1921bgBv

There's nothing in there about the error, just connecting to the IP, which then doesn't work

**Comment by Sapanator123** [comment]
When I play a single player world, I don't have my skin, so I can't connect to the servers there either.

**Comment by The-1-7-10-Pack** [comment]
Are you able to find the error on the server log?

**Comment by The-1-7-10-Pack** [comment]
Closed due to inactivity.
