### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by djandy** [The-1-7-10-Pack/The-1.7.10-Pack#723]
hi ive tryed latest and reccomended versions but each time it says this is missing and to download it myself to which link is 404 not found so i googled around and found http://openeye.openmods.info/mod/mrtjpcoremod#files downloaded it from there and still the same issue also tryed deleting 1.7.10 pack and reinstalling to same issue again

**Comment by The-1-7-10-Pack** [comment]
You can try to launch without it, it may work. It's not the pack's fault, some mods require more files to be downloaded, and sometimes their hosts are down.

**Comment by xScoutx** [comment]
Yes it seems that we are also having the same issu, the solution is to just wait it out correct? 

Here is an image of the error:
http://gyazo.com/99eb18864e3fb6bf13121027c4510cf4

**Comment by The-1-7-10-Pack** [comment]
Are you guys able to download it manually?

**Comment by xScoutx** [comment]
no sadly

**Comment by MZDisaster** [comment]
http://www.curse.com/mc-mods/minecraft/229002-mrtjpcore/2236593

**Comment by xScoutx** [comment]
I am still receiving the same error and from looking at other mods i feel that there are sum missing when trying to download such as EJML which was located within a folder. This just seems to be a problem with downloading the folders.

**Comment by The-1-7-10-Pack** [comment]
The host for the needed file is down, that's all.

**Comment by xScoutx** [comment]
Thank you

**Comment by IceCookieHD** [comment]
Whe is it getting fixed?

**Comment by asapzzbosszz** [comment]
When will it be back online????
Plz Reply

**Comment by The-1-7-10-Pack** [comment]
It's not in our control currently.
For a manual fix, download [this](http://minecraft.curseforge.com/mc-mods/229002-mrtjpcore/files/2236593) and put it in the modpack's folder/mods/1.7.10.

**Comment by xScoutx** [comment]
Sadly this is now the new error we get: http://gyazo.com/b2bd2ad1f9f19420529c357faa1adec3

**Comment by djandy** [comment]
mine just deletes the file then says it cant find it i think ill give up for a few days

**Comment by The-1-7-10-Pack** [comment]
Just wait currently. It shouldn't take too long. Also there are some updates coming soon, they should fix it if the waiting wouldn't.

**Comment by juliang790** [comment]
i installed the MrTJPCore... no more CB DepLoader errors but i get a black screen on launch now, any solution for that or do i just have to wait for update?

**Comment by The-1-7-10-Pack** [comment]
@juliang790 Doesn't sound like a problem, just let it load :)

**Comment by The-1-7-10-Pack** [comment]
Guys try for a manual fix to download [this](http://minecraft.curseforge.com/mc-mods/229002-mrtjpcore/files/2240241) and put it in the modpack's folder/mods/1.7.10.

**Comment by jclarke8342** [comment]
I am no longer getting the CB's DepLoader error, however, now I cannot connect to the server that I play on. It  says it is incompatible FML modded server. I am using version: 0.7.7b. I can play single player though, so that is improvement. Thank you!

**Comment by The-1-7-10-Pack** [comment]
What server are you trying to connect? it may not be the same modpack version.

**Comment by jclarke8342** [comment]
It is a friends server. My wife and I play on it. I can get on without any problem. She cannot. I've made sure to set up everything up the same and it still says Incompatible FML modded server.

**Comment by The-1-7-10-Pack** [comment]
So she and the server aren't using the same version of the modpack. You can see the modpack's client version on the main menu and launcher settings, and the server's at the default MOTD.

**Comment by The-1-7-10-Pack** [comment]
**http://www.technicpack.net/status/242286**

**Comment by The-1-7-10-Pack** [comment]
Closing it.
