### ISSUE TITLE
Archimedes Ships Mod Sugestion

### ISSUE THREAD

**Issue by mandm635** [The-1-7-10-Pack/The-1.7.10-Pack#724]
I think that the Archimedes Ships mod would be a fun edition, to watch your creations fly!

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289952-archimedes-ships-v1-7-banking-ships

**Comment by The-1-7-10-Pack** [comment]
#140, #281, #533:
Please first look if the mod has been suggested.
Thanks anyway :)
