### ISSUE TITLE
Inventory Pets Suggestion

### ISSUE THREAD

**Issue by mandm635** [The-1-7-10-Pack/The-1.7.10-Pack#725]
I know I just suggested something but I remembered a mod I found a little bit ago. It adds items or "pets" that sit in your inventory and help with things. 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2402467-inventory-pets-animated-creatures-that-live-in

**Comment by The-1-7-10-Pack** [comment]
The mod doesn't really fit the pack, and won't be added.
Thanks anyway for suggesting!
