### ISSUE TITLE
Loading time 15min

### ISSUE THREAD

**Issue by MZDisaster** [The-1-7-10-Pack/The-1.7.10-Pack#726]
Java 8 update 45 64bit
Windows 8.1 64bit
Intel core i5 4200H 2.8GHz
6GB Ram
Nvidia GTX 850M

fml-client-latest.log / latest.log ( not sure which one you need )
https://mega.nz/#F!F0ZT1bJS!vFhIWTt-eVpjubbD8Iy4Mg

Hope this info helps

**Comment by The-1-7-10-Pack** [comment]
Can you post the log in [this](http://paste.ubuntu.com/) paste-tool? Thanks.

**Comment by MZDisaster** [comment]
fml-client-latest.log
http://paste.ubuntu.com/11815225/
--
latest.log
http://paste.ubuntu.com/11815272/

**Comment by The-1-7-10-Pack** [comment]
Try to load other modpacks for 1.7.10, does the same thing happens to you?

**Comment by MZDisaster** [comment]
Ok, I think i figured this out
The 1% who have this problem actually do other stuff than playing games on their PC
I've tested this on 2 other random 1.7.10 mods, Tekkit and Hexxit with only Google Chrome running and some other startup programs but they don't use much resources
Oh, and I actually restarted my PC

Times are approximates taken from the log file

The Diamond Dimensions pack: background 3min | foreground 1:30s
Tekkit Classic Reborn: background 5min | foreground 1min
The 1.7.10 pack: background 14min | foreground 3:40s
Tekkit: background 2:30s | foreground 50s
Hexxit: background 50s | foreground 26s

Moral of the story is: don't expect too much of minecraft.

**Comment by The-1-7-10-Pack** [comment]
@MZDisaster Think it is Minecraft, or Forge?

**Comment by MZDisaster** [comment]
If you consider Minecraft compared to the classic to be: nether realm mod, ender realm mod, mob mod which is ~25 mobs and bosses, ores mod ~8 ores, crafting mod ( alot ), mapgen mod, weather mod.
and it still loads in less than 5 seconds then it's Forge causing the long loading time not Minecraft in itself.
