### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by NemesisMc** [The-1-7-10-Pack/The-1.7.10-Pack#729]
This is the error i get:
CB's DepLoader was unable to download required library MrTJPCore-1.7.10-1.0.6.13-universal.jar Check your internet connection and try restarting or download it manually from http://projectredwiki.com/maven/mrtjp/MrTJPCore/1.7.10-1.0.6.13//MrTJPCore-1.7.10-1.0.6.13-universal.jar and put it in your mods folder
Tried the link and its invalid. Any help would be great.

**Comment by NemesisMc** [comment]
Sorry, duplicate post (Can't install #723)
Can Download it here;
http://www.curse.com/mc-mods/minecraft/229002-mrtjpcore/2236593

**Comment by The-1-7-10-Pack** [comment]
Did you try [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/723#issuecomment-118546787) manual fix?

**Comment by NemesisMc** [comment]
Yes, works just fine.
