### ISSUE TITLE
Crash before the game window even appears

### ISSUE THREAD

**Issue by SirSpart** [The-1-7-10-Pack/The-1.7.10-Pack#730]
I click play and game crashes before the game window or any window shows up. Here is the log: pastebin.com/9H7e8WWs

**Comment by The-1-7-10-Pack** [comment]
Your launcher libaries are not good, try to reinstall the launcher completely in order to reset them.

**Comment by SirSpart** [comment]
It worked with the legit launcher yeah. But not at all with the cracked ones.
