### ISSUE TITLE
Help needed? - End game mining ideas.

### ISSUE THREAD

**Issue by Smalfinn** [The-1-7-10-Pack/The-1.7.10-Pack#732]
I know it's a bit cheeky but is there anyway you guys can point me towards all the different end game mining options there are?

Quarry is draining my energy too much for the stupid amount of cobblestone it produces.

Any plans on a 1.7.10 pack wiki?

**Comment by The-1-7-10-Pack** [comment]
Is another wiki really needed, when there are so many out there?
For end games mining ideas, one of the tech quests are the mining lasers from MFR. You should look into that :)

**Comment by Smalfinn** [comment]
Was just a thought.

Mining lasers take alot of energy for not much return really. Might have to look into a less expensive digital miner.

**Comment by The-1-7-10-Pack** [comment]
If currently the mining lasers take too much power for you I wouldn't say you're in late game :)
They do give a lot in return when you give them the 40kRF/t they require.

**Comment by Smalfinn** [comment]
Okay so Big Reactors first (Y)

**Comment by The-1-7-10-Pack** [comment]
:+1:
