### ISSUE TITLE
Crash with start-up

### ISSUE THREAD

**Issue by Emperify** [The-1-7-10-Pack/The-1.7.10-Pack#733]
Whenever I start up the mod pack, my game instantly crashes back to the Technic Launcher, without any crash reports.

**Comment by Emperify** [comment]
Version : 0.7.7b
Add. Mods : None
Crash Report : None

**Comment by The-1-7-10-Pack** [comment]
99% you have the wrong Java version. You need Java 7/8 and 64 bit. Please check for that. If you do have the right version please post here your latest log and I'll reopen the issue.

**Comment by Emperify** [comment]
Will do.

**Comment by Emperify** [comment]
Version 8 Update 45, the newest one.

**Comment by The-1-7-10-Pack** [comment]
Check your launcher settings to see if you're using it, 64 bit.

**Comment by Emperify** [comment]
I am.

**Comment by The-1-7-10-Pack** [comment]
Can you launch now?

**Comment by Emperify** [comment]
Nope.

**Comment by The-1-7-10-Pack** [comment]
Please give me your latest client log, located in the modpack's folder/logs, the latest launcher log, located in the launcher's folder/logs and use a [paste-tool](http://paste.ubuntu.com/). :)

**Comment by Emperify** [comment]
Where do I find these logs?

**Comment by The-1-7-10-Pack** [comment]
They're all in the .technic folder, in %appdata%, search it in the start menu.

**Comment by Emperify** [comment]
Thank you

**Comment by Emperify** [comment]
Shoot, I messed up the log, I accidentally pressed Ctrl V instead of Ctrl V, because I had to do it in parts.

**Comment by Emperify** [comment]
I'm just going to try launching it again, maybe it will work this time, if not, I'll try to send the log again.

**Comment by Emperify** [comment]
http://paste.ubuntu.com/11831401/plain/

**Comment by The-1-7-10-Pack** [comment]
This long is not trying to launch The 1.7.10 Pack, I see different versions of Forge there.

**Comment by Emperify** [comment]
Maybe it's the other one I have down.

**Comment by Emperify** [comment]
http://paste.ubuntu.com/11831686/plain/

**Comment by The-1-7-10-Pack** [comment]
That log is also not the right one, it's another modpack.

**Comment by Emperify** [comment]
That's strange, because those are the only 2 logs that show.

**Comment by bkoelho** [comment]
I have the same problem with the mod and that's the log http://paste.ubuntu.com/11831954/

**Comment by The-1-7-10-Pack** [comment]
@bkoelho You have [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/730#issuecomment-118627281) problem.

**Comment by Emperify** [comment]
So yeah, those are the only 2 logs I have access too.

**Comment by The-1-7-10-Pack** [comment]
They're located in .technic/logs?

**Comment by Emperify** [comment]
Both of them, yes.

**Comment by Emperify** [comment]
:zzz:

**Comment by The-1-7-10-Pack** [comment]
Try to launch the pack again and see if another one is generating :)

**Comment by Emperify** [comment]
Kk

**Comment by Emperify** [comment]
Nope

**Comment by The-1-7-10-Pack** [comment]
Can you try to launch the modpack with the launcher console open and take a picture?

**Comment by Emperify** [comment]
Launcher console?

**Comment by Emperify** [comment]
I just got into this Technic mod-pack business yesterday, sorry.

**Comment by Emperify** [comment]
I'm going to have to use the snipping tool.

**Comment by Emperify** [comment]
![capture](https://cloud.githubusercontent.com/assets/13202889/8532065/af54f124-23f9-11e5-9e94-09ec73ed0a11.PNG)

**Comment by Emperify** [comment]
You mean this?

**Comment by The-1-7-10-Pack** [comment]
No, go to settings and show the console

**Comment by Emperify** [comment]
Oh

**Comment by Emperify** [comment]
![capture](https://cloud.githubusercontent.com/assets/13202889/8532481/561f8e54-23fc-11e5-9c95-b1b2befbb590.PNG)

**Comment by Emperify** [comment]
This is from start to end.

**Comment by bingy5016** [comment]
hi do you guys know where the help for code zero is because i wait like an hour after it launches for it to load an then it closes out i need help plz tell me

**Comment by Emperify** [comment]
...... :expressionless:

**Comment by bingy5016** [comment]
plz

**Comment by bingy5016** [comment]
**PLZ**

**Comment by bingy5016** [comment]
plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz plz

**Comment by bingy5016** [comment]
plz tell me

**Comment by bingy5016** [comment]
plz

**Comment by bingy5016** [comment]
plz

**Comment by bingy5016** [comment]
PLZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

**Comment by bingy5016** [comment]
**PLZ TELL ME**

**Comment by bingy5016** [comment]
plzzzzz

**Comment by Emperify** [comment]
Is there any way to kick him off this issue?

**Comment by bingy5016** [comment]
;(

**Comment by bingy5016** [comment]
dont kick me plz i just want help plz plz plz plz plzzzzzz

**Comment by Emperify** [comment]
I'm playing **Knights & Dragons** while I'm waiting.

**Comment by The-1-7-10-Pack** [comment]
@Emperify Your problem is that you're using Java 32 bit.

**Comment by Emperify** [comment]
.-.
