### ISSUE TITLE
Adding mods suggestion.

### ISSUE THREAD

**Issue by rapidfanatics** [The-1-7-10-Pack/The-1.7.10-Pack#734]
Hey Jon, 
Would you consider adding the following mods:
- Thaumic Energistics 
- Ars Magica 
- Rotary Craft 
- Random Things 
- Project E

I would have suggested Greg Tech also but a lot of people hate it so i'll leave it out on this one.

**Comment by sgdc3** [comment]
+1 for ArsMagica

**Comment by sgdc3** [comment]
Maybe BetterDungeons? ;)

**Comment by sgdc3** [comment]
Aether II?

**Comment by sgdc3** [comment]
Ore Sheep Mod

**Comment by mandm635** [comment]
He has already said no to rotary craft but im liking the others!

**Comment by The-1-7-10-Pack** [comment]
The mods won't be added, due to several reasons you can find in past suggestions. Instability, does't fit the pack, and more.
Thanks again for suggesting :)

**Comment by sgdc3** [comment]
@The-1-7-10-Pack Every mod in the list? O_o

**Comment by sgdc3** [comment]
At least Arsmagica2, ThermalRecycling and Ore Sheep Mod

**Comment by rapidfanatics** [comment]
All my mod fit the pack for sure, instability for Project E sure ill agree there and maybe Rotary craft but the rest are suitable perfect and fitting to the pack and i have tested by adding them to client and server to find no issues and all previous ID's stays the same from the previous configs form the pack.
