### ISSUE TITLE
Suggestions - Additional Tinkers Stuff

### ISSUE THREAD

**Issue by RedGoblin** [The-1-7-10-Pack/The-1.7.10-Pack#736]
Don't know how to add a tag of suggestion. Sorry.

Tried out on my end and seems to be having no problems so far, gives more uses of all the additional content/ores for Tinkers stuff. 

- ExtraTiC
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445212-extratic-tinkers-construct-mod-support-add-on

- Metallurgy 4
 http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1295123-metallurgy-4

**Comment by The-1-7-10-Pack** [comment]
Currently won't be added, it doesn't fit the pack. With so many types of metal, we really don't need more.
Thanks anyway for suggesting :)
