### ISSUE TITLE
Suggestion: add Storage Drawers to the ModPack

### ISSUE THREAD

**Issue by retrozool** [The-1-7-10-Pack/The-1.7.10-Pack#737]
Not sure it's the right place to submit a suggestion - anyhow:

would you consider adding Strorage Drawers to the ModPack?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2198533-storage-drawers-v1-5-10-v2-1-5-updated-jul-03-15

I think it would be a cool alternative for storage in early game :)

**Comment by The-1-7-10-Pack** [comment]
Not going to be added, thanks anyway for suggesting.

**Comment by retrozool** [comment]
any particular reason why not?

**Comment by The-1-7-10-Pack** [comment]
Mostly due to the other early game storage options, we really don't need more :)
Barrels, EnderIO filters with IronChests, and more.

**Comment by retrozool** [comment]
ok - your mod pack - your decision :) 
Still all the other options lack an "easy" and nice looking way of sorting your inventory by one click - and look good in a house decorated with Bibliocraft - Chest all over the place are just boring :)
Anyhow thanks for considering - I'll add it myself then most likely

**Comment by The-1-7-10-Pack** [comment]
:+1:

**Comment by retrozool** [comment]
maybe you want to watch this video https://www.youtube.com/watch?v=TJb7HeFsYCg starting around minute 29:30
It's Fireball1725 using the storage drawers with AE - really nice option :) Still hoping you reconsider your decision to not add storage drawers :D
