### ISSUE TITLE
Maximum RAM

### ISSUE THREAD

**Issue by cornytrace** [The-1-7-10-Pack/The-1.7.10-Pack#739]
Hey there,
I enjoy your pack really much, but when installed sphax 64x because this pack has the sphax patch, it ran out of memory everytime i tried to join a server.
Adjusting the memory options in the technic launcher changed nothing.
After searching for a long time the -Xmx3072M switch in version.json prevented me from allocating my own amount of memory through the technic launcher or by changing the java args.
Can you please remove the switch so people can allocate their own desired amounts of memory?
Thanks!

**Comment by The-1-7-10-Pack** [comment]
Currently it is set to this to prevent players with 1 RAM allocated to be able to even launch the modpack. It automatically allocates 3GB to your client. With Sphax 64x you shouldn't really run out of memory, I tried it myself and had no problems.

The good news is, that Technic is going to finish their new system soon which sets a minimum Java version and RAM amount, so as this new system comes, we will launch an update that removes these custom settings, also will remove the Java7Checker mod. :)

**Comment by The-1-7-10-Pack** [comment]
Indeed, [good news](http://bit.ly/1KXBMyi).
