### ISSUE TITLE
You should add in The weather2 mod  "suggestion"

### ISSUE THREAD

**Issue by snoutking** [The-1-7-10-Pack/The-1.7.10-Pack#741]
I think it would make this mod more hard and exciting. Also Me and my friends love tornadoes we o ways play on a different modpack but its not cool and it dose not have nearly as much mods as you do.       And there,s not anything to do on that other one accept doing the tornado thing. so i think the tornado would be way more better in this modpack. :)
 
Minecraft tornado photo below :)

![mincraft weather 2 mod](https://cloud.githubusercontent.com/assets/13246144/8585479/3bbd6990-25b0-11e5-83dd-cf786ead6775.png)

**Comment by The-1-7-10-Pack** [comment]
The mod is indeed awesome, but as I said it won't be added due to the reasons.
Thanks for suggesting, and I'd say that you should add in manually for you to enjoy :)

**Comment by snoutking** [comment]
Me and my friends and i bet a lot of other people think this mod is really awesome. :)
