### ISSUE TITLE
My server crashs every time I open my inventory in the 0.7.9, and 0.7.8

### ISSUE THREAD

**Issue by Distress323** [The-1-7-10-Pack/The-1.7.10-Pack#742]
Each time that i open my inventory in my server (Creative and Survival) my game freezes, and then closes itself.  It gives me no crash report, just closes and the console says that my character has left the game, and that it can't keep up.

**Comment by The-1-7-10-Pack** [comment]
I need the latest log then.

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
