### ISSUE TITLE
Suggestion - Add Ancient Warcraft 2

### ISSUE THREAD

**Issue by DanagaMoose** [The-1-7-10-Pack/The-1.7.10-Pack#745]
We have been having a lot of fun with Ancient Warfare 2. It has been taken over by gotolink and he is in the process of upgrading it and bringing it into the 1.7.10 arena. We have been adding it to our servers and playing it for a number of months now. 

I currently have it added to The 1.7.10 Pack (0.7.9) on a whitelisted server and it is working fine.

Thanks for the consideration.

DanagaMoose

**Comment by mandm635** [comment]
Seems cool, I personally haven't played with it but I'm liking the look of it.

**Comment by RedGoblin** [comment]
I got confused at first. Ancient Warcraft 2, then I saw Ancient Warfare 2.

**Comment by The-1-7-10-Pack** [comment]
The mod doesn't really fit the pack.
Thanks anyway for suggesting :)
