### ISSUE TITLE
Adding QCraft

### ISSUE THREAD

**Issue by rapidfanatics** [The-1-7-10-Pack/The-1.7.10-Pack#747]
My co thought about Bungee cord for connecting our server to another server running the pack, sadly Bungee will not work for a few reasons, so could you add QCraft, if you don't know what its about then check Direwolf20's tutorial on the mod, it allows connections between server and even optional to allow inventory's being transferred, although this may not be of interest to other servers we need this badly to handle our player load and balance it between servers.

As with every mod i request i have tested adding it to the pack to check for conflicts and bugs and everything was fine and worked the way it should, no world id mismatches as all previous configs are there and this mod was simply added on to generating its own set of new ID's that are not being used already, this mod is very small, i cant see any part of it creating lag and would strongly request that it would be added to help our server. Thanks

**Comment by The-1-7-10-Pack** [comment]
QCraft is indeed very cool. Unfortunately it didn't have too much support lately, and the latest release is for Minecraft 1.7.2. It may work, but it has problems.
It won't be added, currently, at least.
