### ISSUE TITLE
Unable to Load Modpack

### ISSUE THREAD

**Issue by NolerRobert** [The-1-7-10-Pack/The-1.7.10-Pack#748]
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion' has value '1.8', but value '1.7' is required.

Error: could not find java.dll

Error: Could not find Java SE Runtime Environment.

**Comment by TheLegend714** [comment]
You need Java 8 64 Bit. And or reinstall your java.

**Comment by The-1-7-10-Pack** [comment]
Your Java is a bit broken, uninstall all versions and install v8 64 bit.
