### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by ChaseIzKing** [The-1-7-10-Pack/The-1.7.10-Pack#749]
Minecraft Version:

1.7.10​

Modpack Version:

0.7.7b​

Log Link:

http://pastebin.com/WDDSkJ0i​

Details of the issue:

I have no idea why the server is broken. The worlds are not corrupted, and everything is the exact same as it was when the server was running fine. I have tried about 20 different remedies to fix the issue and really nothing at all has worked. As a side note, this is not an official FTB modpack, so I have replaced the launcher version with the version of minecraft it is running, as launchers are irrelevant when working with server-side issues.

**Comment by The-1-7-10-Pack** [comment]
> This paste has been removed!

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
