### ISSUE TITLE
draconic evolution mod and compact machines add suggestion 

### ISSUE THREAD

**Issue by darktrek** [The-1-7-10-Pack/The-1.7.10-Pack#75]
draconic evolation 

seems a good mod that would fit into the mod pack it adds more weapons and amour in two tiers, also adds some good features with a weather control block to stop the rain and a sunrise block it looks like a very good mod i have been playing with it for the past few hours 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2093099-draconic-evolution-1-0-0e

compact machines

Adds one simple game mechanic: Small rooms inside of blocks. It basically gives you the ability to build your contraptions inside of a single block.
Each side of a Compact Machine has a small buffer for items, fluids and Redstone Flux allowing the room to interact with the outside. Applied Energistics channels, ProjectRed bundled cables and OpenComputers cables are supported as well. The room has the corresponding counterparts on its walls.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2220422-compact-machines-v1-14

**Comment by The-1-7-10-Pack** [comment]
I know both mods but for now I won't add those mods, the modpack has more than 200 mods and I don't want to add mods just because they're cool. Thank you anyway.
