### ISSUE TITLE
Can't join my server

### ISSUE THREAD

**Issue by Ukelelechris** [The-1-7-10-Pack/The-1.7.10-Pack#750]
Downloaded the 0.7.7b version of the server and am using recommended version of 1.7.10 (technic says as of today it is 0.7.7b) but I cannot join my server. The error reads:

**EDITED: Please use a paste-tool: http://pastebin.com/pFK2fixS**

I'm aware it's saying there's a version mismatch but I've checked and both are the same. Even the server description reads as 0.7.7b. The only thing outside of the error log I can tell is that in the pack launcher it reads as version 0.7.7 instead of 0.7.7b if that means anything. Also, sorry about the long error log, dont know how to enclose it.

Please help!

**Comment by The-1-7-10-Pack** [comment]
In the launcher you see version 0.7.7? if so, you need to switch it to 0.7.7b.
Also you can use the latest version, 0.7.9a, it has a lot of bug fixes.
