### ISSUE TITLE
Modpack Installation Error

### ISSUE THREAD

**Issue by MrGoogleSearch** [The-1-7-10-Pack/The-1.7.10-Pack#752]
Trying to install the current 0.7.9a build and an error keeps popping up on the launcher stating

"Error unzipping a file for the following pack: The 1.7.10 Pack.
Attempting to extract file: The_1710-pack-0.7.9a.zip, but it did not exist.
Please consult the modpack author."

**Comment by The-1-7-10-Pack** [comment]
Technic is overloaded, as I see the error.
Try again later :)

**Comment by MrGoogleSearch** [comment]
Alright thanks for the input

**Comment by DiasZ** [comment]
hello, I was wondering when do you think that we will be able to download the modpack?

**Comment by PotatoSauceMC** [comment]
I've done a bit of searching and it looks like these people are having the same problem with a different modpack: https://github.com/TechnicPack/TechnicSolder/issues/240

**Comment by PotatoSauceMC** [comment]
Heres my console output when I click install: http://pastebin.com/raw.php?i=ByKqsuzb

**Comment by The-1-7-10-Pack** [comment]
@DiasZ I hope that soon.
"Too many connections" to our Solder.

**Comment by PotatoSauceMC** [comment]
It seems to be up now for me. :+1:

**Comment by The-1-7-10-Pack** [comment]
Should be okay now :)
