### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by Spectrel** [The-1-7-10-Pack/The-1.7.10-Pack#753]
You NEED to add thaumic energestic and thaumic horizons and maybe wiching gadgets to complete this pack it works perfectly with all of the thaumcraft mods.

**Comment by The-1-7-10-Pack** [comment]
Not all people want all the Thaumcraft addons and they don't really fit the pack.
We don't want too much magic (or tech, or adventure) mods.
Thanks anyway for suggesting!
