### ISSUE TITLE
Suggestions. Suggestions.

### ISSUE THREAD

**Issue by RedGoblin** [The-1-7-10-Pack/The-1.7.10-Pack#754]
Glenn's Gases
https://www.jamieswhiteshirt.com/minecraft/mods/gases/

Not sure if you have played with this mod- makes mining more interesting. Haven't seen in much modpacks. :(

===================================

Maybe if they manage to update to 1.7.10
Emashersmods
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290262-1-6-4-engineers-toolbox-customizable-modular

**Comment by The-1-7-10-Pack** [comment]
Both mods are cool, but won't be added.
Not all people like them and they don't really fit the modpack.
Thanks anyway for suggesting!
