### ISSUE TITLE
Tinker's Construct Help

### ISSUE THREAD

**Issue by jacobdono** [The-1-7-10-Pack/The-1.7.10-Pack#759]
I've been using tinkers for some time in other mod packs. I got the travellers gloves in the 1.7.10 pack today but haste doesnt seem to be working on it. Anybody have any suggestions why? Thanks !

**Comment by The-1-7-10-Pack** [comment]
What build are you using, of the modpack?
Recommended or Latest?

**Comment by jacobdono** [comment]
0.7.7b

**Comment by The-1-7-10-Pack** [comment]
Did you try using the latest?

**Comment by jacobdono** [comment]
Yeah I just tried then and no good with that either

**Comment by skittishtrigger** [comment]
Have you ever used tinkers construct Haste before? Not being derisive, but it takes quite a bit before you are going to notice the difference. spam that redstone and make sure the tool you made has a good mining modifier.

tool modifiers:  http://tinkers-construct.wikia.com/wiki/Modifiers
Material stats: http://tinkers-construct.wikia.com/wiki/Material_Stats

those are both good resources for getting a basic idea for what does what and how much.

**Comment by The-1-7-10-Pack** [comment]
I can confirm they're working in latest.
