### ISSUE TITLE
Closing the modpack

### ISSUE THREAD

**Issue by lordracalas** [The-1-7-10-Pack/The-1.7.10-Pack#760]
Hello everyone.

Firstly, I would like to compliment this modpack it is just awesome. And it works just fine.

My real problem is that when I close the game, my computer gets really, I mean, REALLY slow. I don't know if maybe you can help me with this, as it's not really a problem with the  modpack per se, I believe it's something to do with my computer. Any ideas?

Btw, my specs are:

Java 64bit (obviously)
FX6100 processor (piece of shit, hadn't had the $$$ to upgrade yet)
GTX960 (decent)
8GB RAM

**Comment by The-1-7-10-Pack** [comment]
How do you close the modpack? Using the windows x, or through the game menu?

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.

**Comment by lordracalas** [comment]
Hello.

I'm sorry for not responding I was expecting a mail from Github but it never came.

It was really weird, my problem only happened the first time I launched to modpack, from the second time and so on it works perfectly, and I'm playing the sheet out of it. Great modpack btw.

**Comment by The-1-7-10-Pack** [comment]
:+1:
