### ISSUE TITLE
Dropper Found in Mine

### ISSUE THREAD

**Issue by coreymason** [The-1-7-10-Pack/The-1.7.10-Pack#761]
A dropper (surrounded on all sides by stone) randomly spawned in a mine I was digging. I feel like an ore was supposed to spawn instead. I'm using the latest version, 0.7.9b

**Comment by The-1-7-10-Pack** [comment]
Open it. It's the weird (yet special) way of Factorization to give the player its menual. No bug.

**Comment by coreymason** [comment]
Ahh, thanks I would have never known
