### ISSUE TITLE
Wont let me get into the mod pack

### ISSUE THREAD

**Issue by bryson612** [The-1-7-10-Pack/The-1.7.10-Pack#762]
Every time i clicked play on the technic launcher it just loads up everything then just shuts down. I really wanna play this modpack so with someone please help me.

**Comment by skittishtrigger** [comment]
You need to post the logs using http://paste.ubuntu.com
There are two logs to look for.

log 1: Open technic launcher. Click launcher options, then logs at bottom left. They will need that one.
log 2: "C:\Users\username\AppData\Roaming\.technic\modpacks\The-1.7.10-Pack\logs\fml-client-latest.log"

Easiest way (in windows) is click on start button and in search box type {  %appdata%  }
then navigate from there.

**Comment by bryson612** [comment]
I cant find the second log you are talking about. I dont know how to upolad or put the log in there?

**Comment by skittishtrigger** [comment]
start with the one you have. just copy and paste the log into the big box in the link I gave you. type crash as a name then click the paste button. It will change the url at the top. copy and paste that url here.

**Comment by 3izzo** [comment]
try to increase you ram ,if the launcher is not allowing you to change it try to change your JAVA version. i had this problem after updating to JAVA 8 and this fixed it

**Comment by TheLegend714** [comment]
I've had the problem for quite awhile now and I've tried reinstalling my launcher libraries and I have Java 8 64 Bit Heres the Logs. If it reports library problem then I have no idea what to do
http://paste.ubuntu.com/11907425/

**Comment by skittishtrigger** [comment]
TheLegend714 you really should open a separate issue. At first glance your logs look like they are incomplete. (not fully pasted?) although you have the right idea of what to do.  
Here is a list of the basic info 
os
java version installed
java version used in launcher options (dbl check always)
ram used in java options (in launcher options)
Full versions of logs:
----launcher log (is the one you get when clicking log button in launcher options)
----the MOST recent  (and usually largest size log) in C:\Users\username\AppData\Roaming.technic\modpacks\The-1.7.10-Pack\logs\
---Also to help with info grab the latest log from crash-reports in C:\Users\username\AppData\Roaming.technic\modpacks\The-1.7.10-Pack\crash-reports/

**Comment by TheLegend714** [comment]
Alright

**Comment by TheLegend714** [comment]
I'll post tomorrow sorry been very busy lately.

**Comment by TheLegend714** [comment]
So heres the Launcher Log http://paste.ubuntu.com/11915157/
And the 'Most Recent Log" http://paste.ubuntu.com/11915177/
I could not find the crash reports folder because I cannot load the modpack lol

**Comment by The-1-7-10-Pack** [comment]
@TheLegend714 Are you able to launch other modpacks from the Technic Launcher with the latest version of Forge? Try [this](http://www.technicpack.net/modpack/rexxit-jurassic-pack.662762).

**Comment by TheLegend714** [comment]
Nope it did the same thing

**Comment by The-1-7-10-Pack** [comment]
Okay, now try a pack with an older version of Forge, pretty sure [this](http://www.technicpack.net/modpack/the-diamond-dimensions-mirror.505040) pack is using an outdated version of Forge.

**Comment by Nasif267** [comment]
the modpack wont open for me pls help

**Comment by TheLegend714** [comment]
It works, so its forge and how do I fix it ?

**Comment by The-1-7-10-Pack** [comment]
@Nasif267 Open your own issue please.
@TheLegend714 Possibly. Try to go to Forge's [GitHub](https://github.com/MinecraftForge/MinecraftForge/issues) and give them your latest log. Tell them how you're unable to launch with Forge v10.13.4 and how you are able to launch with Forge v10.13.2. Anyway, it's not the modpack issue. :)

**Comment by TheLegend714** [comment]
I see ok

**Comment by The-1-7-10-Pack** [comment]
@TheLegend714 Where did you download your launcher from?

**Comment by TheLegend714** [comment]
uxro.net sorry for late response

**Comment by xJon** [comment]
That's your problem, then.

**Comment by TheLegend714** [comment]
lol 8)

**Comment by TheLegend714** [comment]
Also i have contacted the owner of the site to fix the launcher too!

**Comment by ciak2009** [comment]
@xJon uxro.net isn't just a modified launcher it is a cracked one, you should probably add that cracked minecraft is strictly unsupported.

**Comment by xJon** [comment]
@ciak2009 :+1:
