### ISSUE TITLE
'CoreMod does not have a MCVersion annotation'

### ISSUE THREAD

**Issue by Sovreign** [The-1-7-10-Pack/The-1.7.10-Pack#763]
hey there,
Getting this while trying to update to 7.9c-

http://pastebin.com/1c5rZDNS

any suggestions here?

Sov

**Comment by The-1-7-10-Pack** [comment]
This isn't a bug, it's just missing info. This won't stop you from loading your client and not special for this version or modpack. Can you provide the latest launcher log?

**Comment by EngineerBean** [comment]
The pastebin link is all that comes from the launcher console, is the any other log file I should look at finding for you?

**Comment by The-1-7-10-Pack** [comment]
What is the actual problem? You can't launch the client?

**Comment by The-1-7-10-Pack** [comment]
Closed due to missing information.
