### ISSUE TITLE
Server Crashed While I was Away

### ISSUE THREAD

**Issue by Smalfinn** [The-1-7-10-Pack/The-1.7.10-Pack#765]
So I left my server running on my PC overnight because some friends wanted to finish up some stuff.

I'm running the latest version of Java - 1.8.0_51 (64-Bit).

I'm running version 0.7.9c of The 1.7.10 Pack Server with the addition of WorldEdit.

Crash-Report - http://paste.ubuntu.com/11913255/

ServerLauncher.bat - http://paste.ubuntu.com/11913286/

If you need any more information just let me know, server had never just crashed before...

**Comment by The-1-7-10-Pack** [comment]
It's a bug in Blood Magic. Are you able to reload your server?

**Comment by Smalfinn** [comment]
I'm unable to restart the server

Crash Report - http://paste.ubuntu.com/11913525/

On the blood magic forum post someone has said update forge? http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290532-1-7-10-2-1-6-4-blood-magic-v1-3-3-6-updated-jul?comment=4859

**Comment by The-1-7-10-Pack** [comment]
No, it's not the Forge version.
The [latest version of Blood Magi](http://minecraft.curseforge.com/mc-mods/224791-blood-magic/files)c _should_ fix it, can you test?

**Comment by Smalfinn** [comment]
Well the server booted up!

Just need to wait for my friend that crashed it the first time to login later today, but to me, looks fixed (Y)

Thanks a million for the help!

**Comment by The-1-7-10-Pack** [comment]
Hmm, might want to put this update in the pack. v0.7.9d?
Can you confirm that it did fix it? (go to your friend's chunks with all the blood magic things and see that they all work)

**Comment by Smalfinn** [comment]
I would put this fix in 0.7.9c or at least remove 0.7.9c from recommended.

No idea where he was when it crashed but I've gone to and around his base for blood magic and all seems okay to me. 

Will confirm when he replies to my message about his location.

**Comment by Smalfinn** [comment]
Oh found where he was summoning the demon. No demon but everything stayed loaded and didn't crash.

**Comment by The-1-7-10-Pack** [comment]
You can't just replace mod versions in the same update :)
I guess that we'll have to have another one to go for the recommended.
Shouldn't be a big update.

**Comment by Smalfinn** [comment]
#don't_blame_the_modpack

ahahahaha classic 8/8 m8

**Comment by The-1-7-10-Pack** [comment]
You can confirm that it is working okay with v0.7.9d?

**Comment by Smalfinn** [comment]
What is the correct way of updating a server?

I just create a new folder for the pack, move over the world folder and reload.

Server loaded up works but then proceeded to skip 59 ticks... I'll continue to monitor the lag

**Comment by The-1-7-10-Pack** [comment]
:+1:
