### ISSUE TITLE
Updating server question.

### ISSUE THREAD

**Issue by Sevario** [The-1-7-10-Pack/The-1.7.10-Pack#767]
So, the client updated the modpack for me but it won't let me log on the server, I downloaded the new server but I am not sure what I have to replace.
Do I just make a new folder and copy over the world?
Or do I just have to replace a file in my old one?

**Comment by The-1-7-10-Pack** [comment]
> You need to override all files that the server download include (mods folder, configs folder, forge jar, launch files, flan folder, libaries folder, etc). :)
