### ISSUE TITLE
EXTRA BEES (Addon for Forestry, similar to Magic Bees)

### ISSUE THREAD

**Issue by TheUnknownVariable** [The-1-7-10-Pack/The-1.7.10-Pack#768]
Extra bees is a great mod. It allows you to get almost anything from any tech mod from bees! You can make a gelid bee and create cyrotheum (excuse me if I spelt it wrong) dust and much much more, even ores! This mod is not "OP" whatsoever as, if you've had experience with bees, you would know how long it takes to get any progress with them. I think this would be a great addition to the pack! When the official server comes out, I look forward to teaching everybody all I can about the wonders of bees! Maybe you too will see that this mod is one of the best miss out there!

**Comment by TheUnknownVariable** [comment]
Best mods* sorry, autocorrect

**Comment by The-1-7-10-Pack** [comment]
"Extra Bees" Is a part from Binnie's Mods, and we have it in the pack already :)
