### ISSUE TITLE
Suggestion - Adding Lucky Blocks Mod

### ISSUE THREAD

**Issue by Smalfinn** [The-1-7-10-Pack/The-1.7.10-Pack#769]
Just saw someone post on the discussion feed on the modpack and thought I'd post a little more detail here.

Lucky Blocks looks fantastic... RNG gifting is something that I'd definitely like to play with.

http://www.minecraftascending.com/projects/lucky_block/lucky_block.html

**Comment by The-1-7-10-Pack** [comment]
The Lucky Blocks is a great mod, but it doesn't really fit the pack.
You can get lucky, although, sometimes - you can get very unlucky.

The Lucky Blocks isn't the real way of getting material so it should be kept to more adventures modpacks :)

**Comment by Smalfinn** [comment]
Fair enough :)
