### ISSUE TITLE
Reporting a problem

### ISSUE THREAD

**Issue by lordracalas** [The-1-7-10-Pack/The-1.7.10-Pack#770]
Hello, me again.

This time I got an acutal problem to report.

You know those big ass trees that spawn in the world, such as redwood? Once I got something called "rubber wood mega sapplings" or something like that. So I had no idea they would spawn a giant tree so I planted both of them in the middle of my base, and now I got that giant thing in my base.

"Just chop it", you say.

That's the problem I'm here to report. As soon as I right click it my frames drop really low. I mean, 10 fps low. So far it's the first time I got a frame drop playing minecraft, so I really doubt that has something to do with my computer.

Also, I cut once a redwood mega tree and I got no frame drops doing it. Only on the rubber wood mega tree Ithat I got it. And as soon as I give up doing it (release the right mouse button) the frame gets back to normal. So I must say it is something to do with this particular tree.

Anyways, I'm playing on the 0.7.9c version of the pack, and my specs are:

Processor FX6100
GPU Geforce GTX960
8 GB RAM (6 GB allocated to game via launcher)

PS: I apologize if my english is bad, it's not my native language.

**Comment by The-1-7-10-Pack** [comment]
Basically, the lag comes from the Treecapitator mod. When you try to cut down small trees everything should be fine, but when you get the mega trees, the client has to consider all the blocks that the tree is built from, which can be problematic.

The most simple way is to sneak while trying to chop (shift key): this will disable the Treecapitator mechanics.
The more advanced way would be to use a filler from Buildcraft to clean the blocks.

Your decision! :)

**Comment by lordracalas** [comment]
I see.

I just found it strange that when I chopped a redwood mega tree I didn't lag, only on the rubber mega tree.

Anyways thanks for the quick response, you are awesome! =)
