### ISSUE TITLE
Server crash with Advanced Machines

### ISSUE THREAD

**Issue by Baedel** [The-1-7-10-Pack/The-1.7.10-Pack#772]
after update from 0.7.9c to the newer 0.7.9d my server crash all times.

crash log: http://pastebin.com/0sn0jj7B

any ideas?

thx Baedel

**Comment by Baedel** [comment]
okay removing all centrifuge extractors fixed it. 

closed

**Comment by The-1-7-10-Pack** [comment]
Reported the bug to the mod author and he fixed it.
The next update of the pack will include the fix.

**Comment by Sovreign** [comment]
Ahh, perfect, had the same issue here with our Dedi. will either wait for pack update or remove extractors

Sov~
