### ISSUE TITLE
New AWSOME mods

### ISSUE THREAD

**Issue by romaoplys** [The-1-7-10-Pack/The-1.7.10-Pack#773]
"HI ITS ME", plz see if you can put the following mods on the modpack; RFtools, StorageDrawers and Thaumic Energistics !!!! (plzzz)

**Comment by mtcs** [comment]
I second the Thaumic Energistics!!!! IT is GREAT!

**Comment by The-1-7-10-Pack** [comment]
Currently the mods won't be added.
Also people suggested them already, so note that for future suggestions.
The don't really fit the pack, but you can add them manually for private use.
Thanks!
