### ISSUE TITLE
Gravisuit hover mode not working

### ISSUE THREAD

**Issue by mtcs** [The-1-7-10-Pack/The-1.7.10-Pack#774]
Hi, 

For some reason I cant get to turn hover mode on using Gravisuit's advanced nanosuit or advanced electric jetpack. I think this is a mod integration problem since I also used Gravisuit in an other server I set up with experimental Industrialcraft2. For me, Gravisuit is a very important mod to use in with IC2, please help me! 

Ps.: I am using pack 0.7.9d

Thanks!

**Comment by The-1-7-10-Pack** [comment]
It is working, you just need to switch its key in the controls manu so it won't conflict :)

**Comment by mtcs** [comment]
I already did switch it. All my key shortcuts are white (not in conflict). Also, I switched it from M to V or to C and nothing... I will try again.

**Comment by The-1-7-10-Pack** [comment]
You need to switch the keys for GraviSuit, and not for IC2

**Comment by Pandafuchs** [comment]
I don't have a Mode Switch Key in the Options under the Gravisuit tab :(

**Comment by xJon** [comment]
@Pandafuchs It's there, search for it good :)

**Comment by Pandafuchs** [comment]
![2015-09-09_17-08-46](https://cloud.githubusercontent.com/assets/9077076/9765629/7898dcc8-5715-11e5-9b2f-24f24b0ff3cc.png)

**Comment by xJon** [comment]
It's the "Fly Key".

**Comment by Pandafuchs** [comment]
When I press that I can toggle if I Fly or not, but I doesn't change the Hover Status of the Jetpack:
![2015-09-09_17-22-50](https://cloud.githubusercontent.com/assets/9077076/9766066/6cda6f08-5717-11e5-8fef-9cef273927ad.png)
The Hover Mode is always "off" regardless how of how often I press the Fly Key...

**Comment by xJon** [comment]
Just press it and you'll see you're in hover mode.
The tool-tips don't have to be accurate in order for it to be in hover mode.

**Comment by Pandafuchs** [comment]
When I press it, it disables the engine. If I am in mid-air and I press that key it turns the engine off and I  fall to the ground and get damage I don't think that is the hover mode :D And If I press it on the ground, it disables the engine too. If I press it again it enables the engine and I can fly again but I can never hover. I can just cycle between flying and not flying.

**Comment by xJon** [comment]
When I press it I can fly _and_ hover, are you sure you aren't able to?

**Comment by Pandafuchs** [comment]
I am VERY sure :D

**Comment by xJon** [comment]
Well that's weird. Anyway this bug should be reported directly to the mod author, unfortunately there's nothing I can do

**Comment by Pandafuchs** [comment]
Okay will do, thanks! :)

**Comment by TheCrimsonKing92** [comment]
Sorry to necro, but I stumbled across this thread in my Google search to solve the same issue, so perhaps the comment can help someone else. Hover mode is enabled via the mode change button but **only can be changed while flying up**. I also thought this was a bug until I found a reference on the Feed the Beast wiki.

**Comment by xJon** [comment]
Thank you for posting this!

**Comment by rjdelrio** [comment]
i did it, for my work the following configuration : i config the hotkey of the ic2 "the switch mode" and only can be activated if you are flying
