### ISSUE TITLE
(BC+BR)+MK RF transmission compatibility problems

### ISSUE THREAD

**Issue by mtcs** [The-1-7-10-Pack/The-1.7.10-Pack#775]
I had a problem with RF transmission using  Mekanism energy transmitters from a reactor from BigReactors to a Mekanism's energy cube and other stuff. For some reason the reactor didn't output the power. Then, I tested using BC kinesis pipes all the way to a machine that consumed energy and it DID work. So I had the idea of putting a  energy cube directly in the reactor output and use MK transmitters afterwards which also worked. Then I concluded that there is some in incompatibility with the new BC API and either BigReactors or Mekanism way of handling it. It is possible that this bug should be reported to the mods developers, but I just wanted you guys to know.

Ps.: I am using pack 0.7.9d

Thanks!

**Comment by The-1-7-10-Pack** [comment]
Currently nothing we can do about it, you can try to report it directly to the modders.
Thanks anyway for reporting :)
