### ISSUE TITLE
[Mods Suggestion] Auto Unification of Ores

### ISSUE THREAD

**Issue by rault-a** [The-1-7-10-Pack/The-1.7.10-Pack#777]
The mod AutoUnify from this page http://forum.minecraftuser.jp/viewtopic.php?f=13&t=19445 auto unify every ores/ingots/stuff when needed (either on generation, on drop, on loot, etc...), kinda useful considering the number of mods this modpack have. It seems that you can add it in the modpack (but as the page is in japanese, I just used google translate, so I cannot be sure)

**Comment by The-1-7-10-Pack** [comment]
The modpack disables in the config files all the different ore types but one already, so it's not really useful. Yet, it'd be useful for future projects, I didn't know that there's such a mod.
Thanks for suggesting!
