### ISSUE TITLE
Mod Suggestion. Metallurgy And ExtraTIC (Tinkers' Construct Mod Support Add-on)

### ISSUE THREAD

**Issue by Grimdeath** [The-1-7-10-Pack/The-1.7.10-Pack#779]
Don't know how to add a tag of suggestion. Sorry.

Metallurgy is a vast enhancement to the basic mining system, adding well over 48+ new metals (based on which submods you use). The goal is to create a balanced atmosphere for players to explore and enjoy mining. Metallurgy is also modular, configurable, and entirely tailoring for the player's experience.

ExtraTiC (Tinkers' Construct Mod Support Add-on) Makes more mods the ability to make Tools and tool parts. The mods are Natura, Mekanism, Applied Energistics, Biomes O' Plenty, Botania, Simpleores, Twilight forest, Thaumcraft, EnderIO, Better Storage, RotaryCraft, Gany's End, and Draconic Evolution

What is the modpack policy for Metallurgy?
You can add Metallurgy to your pack, just add credit to the team, and a link back to this page or the curse page, by Team Metallurgy

What is the modpack policy for ExtraTiC (Tinkers' Construct Mod Support Add-on)?
You can add this mod to your mod pack, public or private, just add a link to this forum page, by
- Slime Knights (Tinkers' Construct, Natura)
- Team Metallurgy (Metallurgy)
- RhinoKneel (Helped with textures of parts and tools)
- aidancbrady (Mekanism)
- AlgorithmX2 (Applied Energistics)
- Biomes O' Plenty team
- Toops (Tinkers' Steelworks)
- TheVikingWarrior (Italian Localization)
- Adaptivity (Russian Localization)
- Vifino (German Localization)

**Comment by The-1-7-10-Pack** [comment]
The mods doesn't really fit the pack, as they add a lot of contect that people won't really use normally.
They won't be added.
Thanks anyway for suggesting and adding all the information!
