### ISSUE TITLE
Replace Mystcraft with RFTools

### ISSUE THREAD

**Issue by TheUnknownVariable** [The-1-7-10-Pack/The-1.7.10-Pack#781]
Hello sirs! I think RFTools would be a great replacement for mystcraft for a couple of reasons:
1) RFTools requires lots more to create dimensions. This may not seems so great but it makes it harder and more fun.
2) RFTools adds more options. Instead of having pages, they have dimlets which can be found in dungeons or dropped by mobs. They include some Mystcraft things like eternal day but also have different dimensions such as SuperForest.
3) RFTools doesn't just add dimensions. It also adds a couple nifty machines like the environmental controller. This is a great machine and allows you to add modules to get potion effects like regeneration III
4) RFTools is a lot more stable. It doesn't crash you when it creates a dimension like mystcraft. I have a Titan X but I still crash with Mystcraft.

**Comment by The-1-7-10-Pack** [comment]
I do understand your point, and I'm sure that RFTools may indeed be better than Mystcraft in a lot of places.
But, Mystcraft fits the pack perfectly with the style of old-school gameplay experience that we try to provide. RFTools is a new mod and most importantly completely different in all its aspects.
For now, at least, it won't be added.
Thanks anyway for your time and your suggestion. :)

**Comment by bochen415** [comment]
Why won't you add rftools? :|

**Comment by xJon** [comment]
@bochen415 + RFTools = <3

**Comment by martinegui** [comment]
I know that this topic is dead, but i read evry single post about RFTOOLS here, and nobody said about the shield sytem that i think is nice to use to make doors that players can walk through but mob cant, looks very nice at cost of RF (energy), i know that there other mods that can do this but i think if you put every single thing that this mod can do would be considerable to add mod in future, i dont expect any answer here. I just want to put my vote here to show that there more people that would like this mod.
Thanks for reading and sorry about bad english ( Not natural speaker ).

**Comment by bochen415** [comment]
@xJon did you hear that? ^ It has  s h i n y   s h i e l d s !!

**Comment by xJon** [comment]
@bochen415 Modular Force Field Systems also had a shield system, which is really fancy. As I heard from the Voltz team, nobody wants this mod dead. I removed it not _too_ long ago, and I still hope to add it back :)
