### ISSUE TITLE
A quick question!

### ISSUE THREAD

**Issue by CoolKarateMan** [The-1-7-10-Pack/The-1.7.10-Pack#785]
Hey! I love the modpack (been keeping up with it for awhile now-- it got me back into Minecraft). I was wondering if you had an official server my friends and I could play on or if we should just keep doing our own private session. It you don't have an official server, are there currently any plans on getting one in the future? Thanks for everything, man. Keep on rockin'.

**Comment by The-1-7-10-Pack** [comment]
There isn't an official currently, but there are few community servers that you can play in :)
Here's a small list we made:
http://pastebin.com/8LR6WHXQ
