### ISSUE TITLE
There are two different oil fluids

### ISSUE THREAD

**Issue by cornytrace** [The-1-7-10-Pack/The-1.7.10-Pack#786]
When mining with the ender quarry with pump upgrade, it will sometimes mine fluid.oilgc. This looks like oil, except when you automatically import it into an AE system you will be unable to get it out with a bucket. If you do get it out of your me fluid storage cell using a galacticraft cannister, the oil inside the cannister becomes normal buildcraft oil, so you are stuck with two different kinds of oil, and are unable to automatically extract the oil from your AE system. 
Also, fluid.oilgc is not able to be refined by a buildcraft refinery.
A possible solution is to disable fluid.oilgc spawning through natural generation, or add a recipe such that fluid.oilgc can be extracted with a bucket and be able to be refined.
I dont know if a pack maintainer is able to fix this, if not where would i report this issue?

**Comment by The-1-7-10-Pack** [comment]
There shouldn't be any Galacticraft oil on the overworld.
Are you mining in the overworld?

**Comment by cornytrace** [comment]
That is correct.
The ender quarry also has a silk touch upgrade, if that matters.
The world has been generated at around 0.7.9a

**Comment by The-1-7-10-Pack** [comment]
Can you check your configuration file for galacticraft -> core.cfg?

**Comment by The-1-7-10-Pack** [comment]
I reported a bug about Galacticraft that some part of its configuration file resets after each update and I guess that this is still happening. Fixed the issue for future installs on client and server side (simply fixed the wrong config value), if you want you can update your client to v0.7.9e and it'd include it to you too.
Thanks for reporting!
