### ISSUE TITLE
AE2Stuff

### ISSUE THREAD

**Issue by p455w0rd** [The-1-7-10-Pack/The-1.7.10-Pack#787]
Adds Crystal growth chamber for faster crystal growth, also it takes the entities out of the world for reduced server lag. Also adds advanced inscribers that allow stacking of items

**Comment by The-1-7-10-Pack** [comment]
Some of the special things we can say about AE2 is the seeds that you have to drop in water, and the inscribers that you can automate but they'll always be a bit hard to use.
Some of the difficulty that the mod creates is a plus, and I don't think we should make it all easier.
Currently won't be added, thanks anyway for suggesting :)
