### ISSUE TITLE
Problem when updating the pack.

### ISSUE THREAD

**Issue by Melaa** [The-1-7-10-Pack/The-1.7.10-Pack#789]
So I updated the pack to the latest version by replacing all the downloaded files over the current server files but the server will not load.

I had a look through the log and it said something about duplicate field and class name. Was hoping you could help.

Log:
http://pastebin.com/cVj312MA

**Comment by The-1-7-10-Pack** [comment]
Did you replace the libaries folder too?

**Comment by The-1-7-10-Pack** [comment]
You did something wrong. Try to simply put the new updated server files in a new folder and put the "world" folder in them. Also be sure that you have the eula.txt file set to true, and try to launch.

**Comment by Melaa** [comment]
That's what I normally do but then it means all my waypoints get removed,

Just wanted to see if I could do it this way so it saves the hassle going to get them all again.

Thanks anyway.

**Comment by The-1-7-10-Pack** [comment]
Your waypoints are saved on your client, so it doesn't make much sense.
Anyway glad you figured it out.
