### ISSUE TITLE
When i press play just reopens

### ISSUE THREAD

**Issue by Jadababy** [The-1-7-10-Pack/The-1.7.10-Pack#79]
Help Crash Report  paste.ubuntu.com/9763867/

i have all the requirement 64-bit, Java 7 and 8, 4.00gb

**Comment by The-1-7-10-Pack** [comment]
Are you sure you have 64 bit Java? or only 64bit OS?

**Comment by Jadababy** [comment]
yes i ran minecraft and at the start it tell you i saw 64 and not 32

**Comment by Jadababy** [comment]
64 bit Operating System   can you explain the difference

**Comment by The-1-7-10-Pack** [comment]
You need your Java to be the 64 bit version.

**Comment by haaitje11** [comment]
I would recommend uninstalling Java 8 (and all other versions but 7 with it), this solved everything for me.

**Comment by Flukethoughts** [comment]
Seeing no more responce on this issue I close it.
