### ISSUE TITLE
Server no longer working

### ISSUE THREAD

**Issue by Geohazard** [The-1-7-10-Pack/The-1.7.10-Pack#794]
My server will start up like usual but when I or anyone else tries to connect to it this error shows up "The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED." Then the server immediately closes. I'm not quite sure what is causing this or how to go about fixing it.
Crash Report
http://paste.ubuntu.com/11960802/

**Comment by The-1-7-10-Pack** [comment]
You have a ticking entity in your world. You can delete it with NBTExplorer and it'd fix the issue on your side. See more information [here](https://www.youtube.com/watch?v=fWUUsdp3pJ8).
As for what did it occur, it looks like something between BiblioCraft and CoFH Core. When did the issue start?

**Comment by Geohazard** [comment]
Thanks for replying back with a solution. This issue happened a good while ago back when the current version of the mod pack was only at 0.7.7b. I was too busy with college  to even play anymore so didn't bother posting about it until now.
