### ISSUE TITLE
when crafting it wont let me receive the item crafted

### ISSUE THREAD

**Issue by MrSpoonHer** [The-1-7-10-Pack/The-1.7.10-Pack#80]
trying to craft a force hammer and an automated miner, i have the correct recipe and the crafted item will show up where it is meant to, but when i go to put it in my inventory or shift-click it the item wont move, it registers being in possession for a split second then snaps right back into the crafted item box of the crafting table.

**Comment by The-1-7-10-Pack** [comment]
I am not sure I fully understand your problem.

**Comment by MrSpoonHer** [comment]
you create the recipe for the force hammer within the crafting table. normally i would be able to shift click or drag the hammer out when im done crafting, but for some reason it rubber bands back to the finished crafting box when i do so. same thing happened with the automated miner from automated progression

**Comment by The-1-7-10-Pack** [comment]
Can you provide a picture?

**Comment by MrSpoonHer** [comment]
what isnt clear? tell me so i can elaborate. as for a picture, i cant access my server right now so i can supply one later

**Comment by The-1-7-10-Pack** [comment]
I'm just not too sure what items are you talking about. A picture can help

**Comment by MrSpoonHer** [comment]
![wooden miner](https://cloud.githubusercontent.com/assets/10576944/5790891/e230a198-9e74-11e4-93fd-405bb96bc368.jpg)

**Comment by MrSpoonHer** [comment]
![forge hammer](https://cloud.githubusercontent.com/assets/10576944/5790892/e927ac08-9e74-11e4-9a21-80bb2cb512b8.jpg)

**Comment by MrSpoonHer** [comment]
forge hammer and wooden hammer, sorry about the incorrect reference to the forge hammer earlier

**Comment by MrSpoonHer** [comment]
![openblocks tank](https://cloud.githubusercontent.com/assets/10576944/5790943/a5d315ca-9e77-11e4-9509-f2ba3b1b6efb.jpg)

**Comment by MrSpoonHer** [comment]
same for the openblocks tank

**Comment by MrSpoonHer** [comment]
i fooled around with the inventory and sorting settings, too (the three periods in the inventory screen). no luck there, i have no clue what is interfering with the crafting interface

**Comment by TwizzGribbly** [comment]
I am having the same issue when trying to create iron nuggets from an ingot.

I place the ingot in the crafting grid, the nuggets appear in the output box, when I go to take the nuggets with the cursor, they snap back into the output grid almost instantly.

If I try to shift click, to automatically empty them into my inventory, they briefly appear in my inventory as expected, but almost instantly disappear and the items are all back in the crafting grid.

**Comment by TwizzGribbly** [comment]
It might be worth mentioning that this only seems to be happening on a server, seemed to be fine in single player.

**Comment by The-1-7-10-Pack** [comment]
@MrSpoonHer Is it the same for you as @TwizzGribbly, Do you have this problem only on a server?

**Comment by TwizzGribbly** [comment]
I believe I have solved my problem. I had made my own .bat file which wasn't properly implementing the FML, so the mods, although appearing clientside, were not implemented on the server. I have since properly adjusted my .bat file to properly point to the FML.jar. All of this was in an attempt to allocate more ram. So my bad on my end, but my problem is now solved.

**Comment by The-1-7-10-Pack** [comment]
Okay, good, what about @MrSpoonHer, can you do what @TwizzGribbly said?

**Comment by MrSpoonHer** [comment]
I dont play single player but i can check when i get home

**Comment by MrSpoonHer** [comment]
it works on single player for me, so my buddy that runs our server must have messed with the .bat file. i'll talk to him and get back to you

**Comment by MrSpoonHer** [comment]
Twizz, can you supply a step by step solution?

**Comment by MrSpoonHer** [comment]
a screenshot of your .bat file would suffice

**Comment by TwizzGribbly** [comment]
![1 7 10bat](https://cloud.githubusercontent.com/assets/10617408/5833884/bcc70068-a14f-11e4-823b-51e5b764790e.png)

**Comment by TwizzGribbly** [comment]
That's the entirety of the .bat I'm using. The permsize and maxpermsize parts were necessary to get the server to boot up without running out of memory.

**Comment by The-1-7-10-Pack** [comment]
@MrSpoonHer You can also redownload at any time the server files and use the default launch file.

**Comment by TwizzGribbly** [comment]
The default launch file didn't work for me, I needed more ram allocated, which is why I ran into problems in the first place.

**Comment by MrSpoonHer** [comment]
Twizz is right, theres almost no possible way to use the default server file and also run multiple people using machines. I'll have my friend implement that .bat file and see if that solves the issue. I'll get back to you guys after school

**Comment by The-1-7-10-Pack** [comment]
It's super easy to edit the default one. there's text telling you exactly what to edit. You shouldn't make your own launch file.

**Comment by MrSpoonHer** [comment]
Thats a matter of opinion

**Comment by The-1-7-10-Pack** [comment]
Anyway, changing the launch file fixed your problem too @MrSpoonHer?

**Comment by TwizzGribbly** [comment]
It's probably worth noting that my .bat uses some rather large RAM values, you might not need that much allocated. I just have the RAM to spare and those numbers worked for me.

**Comment by MrSpoonHer** [comment]
this launch file did not fix the problem im having, did you do anything else that couldve fixed the problem Twizz?

**Comment by MrSpoonHer** [comment]
it seems to effect every mod, just tried crafting a mining turtle but couldnt

**Comment by MrSpoonHer** [comment]
i tried reinstalling the modpack and reinstalling the launcher itself. i cant seem to find whats causing this

**Comment by TwizzGribbly** [comment]
The only thing I did was change the .bat file for the one I posted above, nothing else was changed.

**Comment by MrSpoonHer** [comment]
my buddy is saying that launch file isnt working, but he easily couldve typed it in wrong, can you copy and paste the text in a comment here? that would be appreciated.

**Comment by TwizzGribbly** [comment]
My .bat is:-

@Echo off
"C:\Program Files\Java\jre7\bin\java.exe" -server -d64 -Xms2048M -Xmx8192M -XX:PermSize=256m -XX:MaxPermSize=512m  -jar forge-1.7.10-10.13.2.1277-universal.jar
pause

It's worth pointing out that the file path at the beginning should point to wherever your friend has java installed on his computer, which may not be the same place as mine. As I mentioned before, I use rather high RAM values, 8GB being the max, some rigs may not want to use so much RAM.

**Comment by The-1-7-10-Pack** [comment]
Guys, just use the default launch file and edit the number if you want to increase the RAM usage.
Playing with it will do only trouble.
![](http://i.imgur.com/h9J3TtR.png)

**Comment by TwizzGribbly** [comment]
Unfortunately the default launch file would not work for me, it would not launch the server.

**Comment by The-1-7-10-Pack** [comment]
Please open a new issue and mention why it is not working, show the latest server log.

**Comment by MrSpoonHer** [comment]
Default launch file had major lag for me on the server and the ram config was extremely touchy. Its so much easier with a different launch file

**Comment by TwizzGribbly** [comment]
I have started a new topic as requested.

**Comment by Flukethoughts** [comment]
closing as user indicated there fault in changing files.
this is an issue with FML When you change certain files things will not work please next time have the person running the server submit the ticket so we can work with him and have less hassle on the issue thank you.
