### ISSUE TITLE
Mod suggestion - MiscPeripherals

### ISSUE THREAD

**Issue by Jofkos** [The-1-7-10-Pack/The-1.7.10-Pack#81]
http://www.computercraft.info/forums2/index.php?/topic/20903-mc-1710cc-165-peripherals-v120beta4-miscperipherals-reimagined-now-includes-speakers/

Peripheral++ - MiscPeripherals for Minecraft 1.7.10. It don't has all the features MiscPeripherals had, but it has main features like the XP-Turtle, or the ProjectRed turtles.
Would be nice to add it :+1:

**Comment by The-1-7-10-Pack** [comment]
What do you think guys?

**Comment by Flukethoughts** [comment]
well it might be a good addon I can't say to much about it could come with alot of issues. At this current time the modpack is waiting on final version for alot of mods. Until 1.8. mods start being pushed i don't see adding to many more mods to the pact or even changing any out.

**Comment by The-1-7-10-Pack** [comment]
For now you can add it yourself, thanks for the suggestion anyway!
