### ISSUE TITLE
Pack will not install in Technic Launcher

### ISSUE THREAD

**Issue by Lowthreat** [The-1-7-10-Pack/The-1.7.10-Pack#82]
Pack is stuck at 0 percent when attempting to install.  After about 3 minutes a popup occurs that states,  "Failed to download https://onedrive.........."

**Comment by The-1-7-10-Pack** [comment]
Host doesn't like to work. Maybe overload. Let's give it some hours to fix it self, or I'll do something.

**Comment by Lowthreat** [comment]
Awesome. Thanks for the quick reply!

**Comment by Lowthreat** [comment]
It has already been down for about 4 hours.

**Comment by The-1-7-10-Pack** [comment]
You know what, I'll try to reupload client & server, it might help.

**Comment by Lowthreat** [comment]
You are amazing!  Thanks again for the great pack!

**Comment by The-1-7-10-Pack** [comment]
:wink:

**Comment by ReinasaurousRex** [comment]
I'm having this problem as well, any estimate when it'll be fixed?

**Comment by SomeRandomGamer** [comment]
same here aswell

**Comment by xJon** [comment]
Reupload didn't help: http://www.technicpack.net/status/33527
Let's play the waiting game. Did we reach the bandwith limits? good job guys [;

**Comment by xJon** [comment]
I can download it now myself, closing this one.

**Comment by The-1-7-10-Pack** [comment]
I can download it myself, closing this one.
