### ISSUE TITLE
Mod suggestion - PortalGun and GravityGun

### ISSUE THREAD

**Issue by Jofkos** [The-1-7-10-Pack/The-1.7.10-Pack#83]
PortalGun by iChun - http://www.minecraftdl.com/portal-gun-mod/
GravityGun by iChun - http://minecraftmods.io/gravity-gun-mod/

Especially for moving IndustrialCraft's rubber tree blocks together it's very usefull. One of them in this modpack would be nice :+1:

**Comment by The-1-7-10-Pack** [comment]
Both mods didn't update to 1.7.
"So why it says so in the download page?"
Please read this: http://stopmodreposts.org/
