### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by KLuebbert** [The-1-7-10-Pack/The-1.7.10-Pack#84]
From Friday, all the way to Sunday, the official server has been experiencing quite a few crashes. I'm not trying to complain, but I am curious if there is a way to find what causes these crashes, and maybe it could be fixed? I don't know what causes these crashes, but every hour or less, the server crashes, and sometimes it lasts for around a half an hour or more.

It crashed twice today, in the few hours I played, and the third time the server crashed, it didn't come back up. It's been well over a half hour since it has been down.

**Comment by The-1-7-10-Pack** [comment]
Hosting such a big server is not simple. Anyway Fluke may be able to answer more questions about the server.
@Flukethoughts

**Comment by KLuebbert** [comment]
Yes, hosting a server is not easy at all, small or large. My friend almost made a 24/7 modded server, and we were making plans for it. The plans easily became several pages long, and there were many missing details. Of course this server was never made because my friend started to not communicate, and he started ignoring me... But whatever.

**Comment by The-1-7-10-Pack** [comment]
NEI related crashes are because of missing mods on the server that you have on client: ComputerCraft, OpenPeripherals & EE3.
The latest crashes are related to the protection plugin for players. If we won't be able to find a fix for it we'll try to switch to another protection plugin.

**Comment by KLuebbert** [comment]
Crashes seem to have reduced, but these crashes were server crashes, not personal crashes. I have deleted the 2 mods, and I can now use my R key! =) But the U key is still a mystery.

**Comment by KLuebbert** [comment]
I was wrong, the server just crashed.

**Comment by Flukethoughts** [comment]
Sorry about the server crashing so much but it's due to plugin we think we are working hard on trying to get it fixed. But the issue with the keys ur using I can't help with client is johns devision

**Comment by The-1-7-10-Pack** [comment]
You need to delete **3** mods, and then the U key will also work. ComputerCraft, OpenPeripherals & EE3.

**Comment by KLuebbert** [comment]
EE3? ok THANKS, I hope that works, thanks so much Jon

**Comment by Nath742** [comment]
Hi Fluke is their a eta on when the server will be back up thanks

**Comment by Nath742** [comment]
Hi Fluke is their a eta on when the server will be back up thanks

**Comment by Nath742** [comment]
Hi Fluke is their a eta on when the server will be back up thanks

**Comment by KLuebbert** [comment]
When I try to join the server it says failed login session. Restart your game. So I restarted my game. I tried logging in and, failed login session. Restart your game. So I restarted my game. When I tried joining your server, this message popped up. Is it under maintenance???? There was only 3 players online, so that's what I assume.

**Comment by Flukethoughts** [comment]
Okay I can bring this into play now the server is so huge we need to move to a dedicated skynet server. So please look into the donation page on the website and look into chipping in. lol But seriously with a server this big we need extreme hardware to carry it.
