### ISSUE TITLE
Unable to build a Wind Mill

### ISSUE THREAD

**Issue by rdance364799** [The-1-7-10-Pack/The-1.7.10-Pack#85]
Hey guys,

Looks like the windmill is broken. The recipe comes up in the list on the right hand panel, but you are unable to click on it to check the materials needed. Also, when you place the correct materials in the right places, nothing is able to be created.

**Comment by The-1-7-10-Pack** [comment]
The windmill from what mod?

**Comment by rdance364799** [comment]
Heya,
It's the "Wind Mill" from IC2

Date: Mon, 19 Jan 2015 00:39:31 -0800

**Comment by The-1-7-10-Pack** [comment]
It is indeed a bug from IC2 and you should report it there: http://bt.industrial-craft.net/my_view_page.php
