### ISSUE TITLE
Smelting steel dust in a vanilla furnace creates refined iron instead of steel ingots.

### ISSUE THREAD

**Issue by thederpmachine** [The-1-7-10-Pack/The-1.7.10-Pack#86]
According to the wiki, smelting steel dust in a furnace will produce steel ingots, but in my game, it makes refined iron ingots. http://voltzwiki.com/wiki/Steel_Dust_%28Mekanism%29

**Comment by The-1-7-10-Pack** [comment]
Refined iron should be working as a steel ingot, because they're on the ore dictionary.
