### ISSUE TITLE
Personal Server

### ISSUE THREAD

**Issue by Quisani** [The-1-7-10-Pack/The-1.7.10-Pack#87]
Hello, 

I'm trying to set up a server using the download files from Tekkit, but after it loads about two or three dozen of mods, to just after Factorization, the gui freezes up and nothing happen. I tried changing the amount of memory allocated, but it didn't really help.

**Comment by Flukethoughts** [comment]
Hello this is a very common issue. I will explain it this way. This server is not for the faint hearted It takes alot of time and energy to try to get running. I wish you the best on your adventure. But as of now I can say It might be best to find the best cpu and ram for this operation even if it is for 5 or less players. 


Troubleshooting methods
look into what java you have installed.
Look into the memory your giving the server. For instance you may think u have 4gig ram free but where will the garbage collection happen?
Also look into the configs and eula to make sure it's all done right.

**Comment by Quisani** [comment]
Oh good. Thanks for getting back so quick. I have an i7-2600k and 16 gb of memory. 

Yeah haha, I've run a few servers and I have had more than one "gaming night" with my buddies that ended up me finding apocryphal help on the internet. 

Which version of Java is preferred. I know quite a few modpacks have issues with Java 8, so I have Java 7 update 71 installed currently, both 32-bit and 64-bit.

**Comment by The-1-7-10-Pack** [comment]
Why would you have more than one Java type installed on your system, may I ask?

**Comment by Quisani** [comment]
You may. I would attribute it mainly to ignorance and superstition and a healthy dose of cautiousness.

**Comment by The-1-7-10-Pack** [comment]
And how can you ensure which program uses the right version of Java?

**Comment by Quisani** [comment]
I dunno. I wouldn't say I'm an expert regarding Java by any stretch of the imagination. I'm just the guy who gets multiplayer to work.

**Comment by The-1-7-10-Pack** [comment]
Try to remove the 32bit version and have only the needed 64bit.

**Comment by Quisani** [comment]
Okay, It's still doing PreInitialization, and I'm seeing quite a high number [ServerThread/ERROR] instances, and I've seen a few instances of OutOfMemoryError, but it is still going. I'll update as soon as it is finished.

**Comment by Quisani** [comment]
It lagged out after getting to 
 "Holderlookup"

**Comment by The-1-7-10-Pack** [comment]
OutOfMemoryError: It can't allocate the 3GB RAM it needed: If your computer has 4+ RAM things SHOULD work: The computer uses the 32bit version which can allocates only up to 1GB of RAM.

**Comment by KLuebbert** [comment]
What is the IP of this server, may I ask?

**Comment by Quisani** [comment]
Alright. So I uninstalled Java 32 bit and Java 64 bit and reinstalled a clean 64 bit Java 7 Update 71. That seems to have cleared up the issues I was having. Thank you guys for your assistance.

Kluebbert, do you still want the IP? This server isn't going to be open all the time. I run it off my personal desktop as needed.
