### ISSUE TITLE
Server doesn't boot up

### ISSUE THREAD

**Issue by haaitje11** [The-1-7-10-Pack/The-1.7.10-Pack#88]
Hi!

I downloaded the server, but on booting up it crashes. It'll go for about a minute (maybe giving some errors, but too fast too see clearly), and then stop. Approximate error report:

[20:06:47] [Server thread/WARN] [EnderIO]: Failed to write Transciever Channels
on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException

[20:06:47] [Server thread/ERROR] [HatStand]: Skipping event FMLServerStoppedEven
t and marking errored mod HatStand since required dependency Hats has errored
[20:06:47] [Server thread/INFO] [FML]: The state engine was in incorrect state E
RRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[20:06:47] [Server thread/INFO] [FML]: The state engine was in incorrect state E
RRORED and forced into state AVAILABLE. Errors may have been discarded.
Press any key to continue . . .

I have no idea why this is happening. Any suggestions?
Specs:
Windows Vista
Java 7 update 71 64-bit
8GB RAM
Latest download server + Modpack

**Comment by The-1-7-10-Pack** [comment]
Did you set eula.txt to true?

**Comment by haaitje11** [comment]
No, I did not. Solved now! It should be more clearly stated that this is necessary, normally for minecraft servers it is not. Maybe a special posting somewhere?

Thanks for your help!

**Comment by Flukethoughts** [comment]
google.com how to start a minecraft server

**Comment by The-1-7-10-Pack** [comment]
"should be more clearly stated that this is necessary, normally for minecraft servers it is not. Maybe a special posting somewhere?"
Normally minecraft servers **DO** need to set eula.txt to true.
Also, I did post this line:
![](http://i.imgur.com/8kLD3S8.png)

**Comment by haaitje11** [comment]
Last time I started a Minecraft server this was not necessary. I have done it countless times.

**Comment by The-1-7-10-Pack** [comment]
MC version 1.7+.
You are welcome to try now :)

**Comment by haaitje11** [comment]
But thank you once again for your help. I only went to the TechnicNetwork site ;)

**Comment by haaitje11** [comment]
It's up and running and fully working right now. I must say that it has been a while since I last started one, before the EULA was added. I only updated it. Well, cheers!

**Comment by The-1-7-10-Pack** [comment]
:+1:
