### ISSUE TITLE
The 1.7.10 Pack

### ISSUE THREAD

**Issue by PhillyLover** [The-1-7-10-Pack/The-1.7.10-Pack#9]
Hello i installed the 1.7.10 pack and i had noticed that after it had installed all the mods and loaded it automatically closes out and im back at where i had downloaded the mod-pack. This has happened to a couple of other mod-packs and i don't know why. Can you please assist me and tell me how to fix this problem. Thank you and Happy New Year!

**Comment by BlackJackAres** [comment]
Additionally you can check your Java version here. https://www.java.com/en/download/installed.jsp

And I dedicate 4 of my 8 to the task and never have any problems. You could probably get away with 2-3 dedicated ram if you run everything on a lower tier of graphical settings via Optifine, which allows for a very very useful amount of detailed graphical changes.

Also to screen shot simply click CNTRL in the bottom left or right of your keyboard main keyset, and then at the very top right there's a group of three keys. While still holding down CNTRL click PRNT SC or print screen.

Example below.
![beautifully crafted image](https://cloud.githubusercontent.com/assets/10352736/5591738/452aecb2-9138-11e4-8646-53725d9f7dcb.png)

**Comment by PhillyLover** [comment]
Hey guys thanks for all the help! I found out what went wrong... i had downloaded the wrong version of java... it seems that i downloaded the 32 bit when i had a 64 bit laptop! Now i can enjoy the modpacks!

**Comment by BlackJackAres** [comment]
I am glad we were able to help! =D

**Comment by The-1-7-10-Pack** [comment]
This is the main issue, that people use 32bit of Java and then they can't even launch.
I'm happy to see we figured that out.
