### ISSUE TITLE
adding mod

### ISSUE THREAD

**Issue by bennygeorgiev** [The-1-7-10-Pack/The-1.7.10-Pack#91]
i want to know if you can to add all the thaumcraft addons specially Thaumic Energistics and another few mods:  
Minechem-http://minecraft-forum.net/minecraft-mods-downloads/1-7-10-minechem-5-mod-download/#.VL5ua0eUeim

thaumic energistics-http://mod-minecraft.net/thaumic-energistics-mod/

Adventure Backpack Mod-http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2252109-wip-adventure-backpack-mod-beta-0-7-5-updated

**Comment by The-1-7-10-Pack** [comment]
If you want to suggest a new mod do it like I asked to, here: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack
