### ISSUE TITLE
Client Suddenly Crashing with U recipe use

### ISSUE THREAD

**Issue by vvelvenvv** [The-1-7-10-Pack/The-1.7.10-Pack#92]
I've been playing for going on 2 weeks. A few days ago I built a Leadstone Jetpack showing as being part of Thermal Expansion. Something seemed to blip and then whenever I pressed U for what recipes an item is used for my client would crash. 

Upon restarting, R for recipes still functions but U will consistently crash on any item lookup. 

Now all items show "Unnamed" whenever shift is held. I can no longer see Energy levels in Flux Capacitors nor liquid levels in liquid containers. Jetpacks now show as Simple Jetpacks as a source mod. 

I've re-installed the client. I've deleted the client folder and reinstalled again. I've deleted NEI config files (the 3 I could find) on server and client. I've deleted all server files, restarted from the fresh zip  and copied the world folder and server.properties over.

Nothing seems to get it back. 

I seek thine Help!

I have not deleted/moved character files on the server.  The crashes were occurring before the resource pack was added. Client appears to run fine aside from these issues. 

Client Crash Report: http://paste.ubuntu.com/9798240/

**Comment by The-1-7-10-Pack** [comment]
**Please use a paste-tool**, be sure you read how to report a bug before you post here.
Anyway, the answer to this problem is just as the answer there:
https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/35#issuecomment-68635591

**Comment by vvelvenvv** [comment]
I saw the readme just after posting. My apologies, will do so on subsequent posts!
