### ISSUE TITLE
Missing essential library files

### ISSUE THREAD

**Issue by Phoenix0nFire** [The-1-7-10-Pack/The-1.7.10-Pack#93]
When i try to boot up my own server, the console window tells me i am missing essential library files (quite a few class loader files)

**Comment by The-1-7-10-Pack** [comment]
You probably deleted some libary files or somethin', just re-download the server files

**Comment by Phoenix0nFire** [comment]
have redownloaded the server files three time and deleted the old ones in between just in case, still the same issue. could you perhaps re upload the server file?

**Comment by The-1-7-10-Pack** [comment]
Why would I, it's working for everybody else - Also everything get tested before launching.
Can you provide the fml-server-latest.log file?

**Comment by Phoenix0nFire** [comment]
Where would i find this file? it's been a while since i last hosted a server.

**Comment by Phoenix0nFire** [comment]
This is the error i get in the cmd.exe anyway

OS is 64
We appear to be missing one or more essential library files.
You will need to add them to your server before FML and Forge will run successfu
lly.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:25)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Press any key to continue . . .

**Comment by Phoenix0nFire** [comment]
not quite sure what happened as i didnt change a single thng, but it seems to work when i run it from the jar file instead of the bat file

**Comment by bochen415** [comment]
@Phoenix0nFire How do you start the batch file? If on windows the current directory variable aka %CD% when running the file must be the servers directory, so running
c:\some_directory\servers_directory\LaunchServer.bat
will get you an error but running
cd c:\some_directory\servers_directory\
and then LaunchServer.bat it will work correctly.

**Comment by Phoenix0nFire** [comment]
The problem was that you can't run a minecraft server on the new Java 8, reinstalling 7 and deleting 8 fixed all issues.

**Comment by bochen415** [comment]
> The problem was that you can't run a minecraft server on the new Java 8, reinstalling 7 and deleting 8 fixed all issues.

Not true. Any java above 6 will do. I run a server everyday on 1.8u20 with no issues.

**Comment by The-1-7-10-Pack** [comment]
""Not true. Any java above 6 will do. I run a server everyday on 1.8u20 with no issues.""
Huh. Did you try to use my server files?

**Comment by bochen415** [comment]
Apart from a world leak caused by chicken chunks everything works well on 1.8_20 (that's why I don't use that mod any more)

**Comment by The-1-7-10-Pack** [comment]
That's for another time, but as I see it it's just a warning - but yes, ChickenChunks is not perfect.
