### ISSUE TITLE
Launch Server file not working

### ISSUE THREAD

**Issue by TwizzGribbly** [The-1-7-10-Pack/The-1.7.10-Pack#95]
As requested, I'm starting a fresh topic for this issue.

When trying to launch a server using the default Launch Server file, it attempted to launch, then almost immediately shut down, I believe this is due to memory allocation not being sufficient to boot the server, the log seems to back this up.
![logscreenie](https://cloud.githubusercontent.com/assets/10617408/5855638/6c830b72-a232-11e4-8042-9d5ddcb17153.png)

**Comment by The-1-7-10-Pack** [comment]
Can you provide more information about your system?

**Comment by TwizzGribbly** [comment]
I have:- 

Win 7 64bit
i7-3820 CPU @ 3.60GHz
32GB RAM
2X nVidia GeForce GTX 660 SLI

**Comment by The-1-7-10-Pack** [comment]
Can you provide a picture of your corrent launch file?
Also you're sure you have Java 64bit, right?

**Comment by TwizzGribbly** [comment]
Certainly using 64bit Java, otherwise I don't think I'd be able to allocate 8GB RAM to the server.
![1 7 10bat](https://cloud.githubusercontent.com/assets/10617408/5856813/6a5106f4-a23e-11e4-96ed-5cf77aea7709.png)

**Comment by The-1-7-10-Pack** [comment]
Okay. Some changes are going to be out next update for the server launch files.
I'd want to ask you to do the following:
Download the default launchfile and edit the whole line with the forge version to this:
https://gist.github.com/The-1-7-10-Pack/280645f6f1f628511407
Also change the line with the "3G" to "8G" (As you wanted)
Also if you wish you can change the 256 to 512.
Tell me if it's working.

**Comment by TwizzGribbly** [comment]
I'm not able to try this out as I'm currently hosting a server for me and my friends which is quite active, I won't be able to take the server down to try anything out for a while.

**Comment by The-1-7-10-Pack** [comment]
It can really help everyone that may have this problem. If you can find just 5 minutes to try it out I'll appreciate it. Also using this launch file (and hopefully it will work) will increase the server performance.

**Comment by TwizzGribbly** [comment]
I will give it a try later in the evening when the server gets quiet and get back to you, don't have the time at the moment unfortunately.

**Comment by The-1-7-10-Pack** [comment]
Update me here please.

**Comment by TwizzGribbly** [comment]
Since I'm running java 7, that new launch file doesn't work for me. I'm not willing to update java to try if it works, it will cause me too many issues with how my computer is currently running for it to be worth all the potential hassle, sorry.

Hopefully someone else will be able to test the file though.
Sorry I couldn't be of more help here.

**Comment by The-1-7-10-Pack** [comment]
It should run on Java 7. Why can't you use this file? do you get an error or what?

**Comment by Flukethoughts** [comment]
I will personally look into this issue if you contact me on skype message me if you want too.

**Comment by oowjh** [comment]
i have the same error :/

**Comment by TwizzGribbly** [comment]
When trying to boot up with that launch file, it gives me an error message in the console saying I don't have Java 8. I can't provide a screenshot because I can't try again at the moment, I'm hosting a server and can't shut it down right now to try the other. The error did not generate a log either, so I can't provide one.

**Comment by Flukethoughts** [comment]
skype name not_just_a_fluke

**Comment by The-1-7-10-Pack** [comment]
@oowjh I'd love you testing the launch file I provided.
@TwizzGribbly Please do try to provide a picture because I can't help you without more information.

**Comment by The-1-7-10-Pack** [comment]
Should work on the new files with v0.7.0, closing this one.
