### ISSUE TITLE
Flan's Mod Question

### ISSUE THREAD

**Issue by poetofsilence** [The-1-7-10-Pack/The-1.7.10-Pack#96]
Hey guys. There is no craft box for the Swat Team items in Flans mod. Is there a way to get these in survival? Also, What are the chances of you guys adding new flan's packs like cars, spaceships, nerf, etc. Thanks!

**Comment by Flukethoughts** [comment]
Flans mod is unstable as it is but you can add any mode you want to your modpack just be sure to readd it when the modpack updates.

**Comment by The-1-7-10-Pack** [comment]
More Flan's addons means more troubles. As Fluke said things are not 100% stable.
Still feel free to add it yourself.
