### ISSUE TITLE
When I make a server, not everything appears to be working.

### ISSUE THREAD

**Issue by iChilled** [The-1-7-10-Pack/The-1.7.10-Pack#97]
I'm not sure if I'm able to explain this well, but, whenever I try to create a server for me and my friend to play (portforwarded) it appears to work, but whenever I mine an ore which is modded (Dense ore, any modded ore) it breaks and nothing appears. Then, I assumed that not every mod loaded properly during the running of LaunchServer (batch file.)

Could it have anything to do with the LaunchServer Batch file? Whenever I load that some lines are Serverthread/Warn or main/Warn or even a complete Error (I am unsure if this is even the case, but I have suspicions)  so maybe it's not loading the mods properly? 

Do I need to set the amounted RAM to something specific in the server?

Sorry if I typed something pointless and stupid, and is actually an easy problem, I have poor expertise in running Minecraft servers. (It's just a private one for me and my friend.)

EDIT: After a long while, the line Serverthread/WARN: Can't keep up! appears. I didn't notice this at first.

Eventually, I managed to work it out. It was a big problem too, which had unfortunately costed me hours. Odd it worked out a few minutes after I posted this.

**Comment by Flukethoughts** [comment]
check ur pc stats and ask yourself can i run this server and play at the same time with the ram I have and cpu I have on this machine. Then think 4g here for os 4gig here for minecraft 4g here for server. do I have 16G of ram........... I know it doesn't add up because your forgetting a simple thing called GC garbage collection is ran in the ram also

**Comment by Flukethoughts** [comment]
seeing how you fixed your own issue I will close this
