### ISSUE TITLE
HELP ME PLZZZZ cant load 1.7.10 pack!

### ISSUE THREAD

**Issue by pophat31** [The-1-7-10-Pack/The-1.7.10-Pack#99]
I download the 1.7.10 pack on the technic launcher because my friend made a server but when I press play it does the loading thing then nothing happens after, no crash log or anything pops up. I tried downloading forge and copying the mods into my mods folder in Minecraft and it gets to like 95% of loading and stops and says Minecraft not responding because it to much for it to handle so I don't know what to do. HELLLLP PLZZZ

**Comment by Flukethoughts** [comment]
ok don't change anything inside of it because this is where we wont be able to help you. First off I need to know your system specs and What version of java you are currently trying to use.

**Comment by The-1-7-10-Pack** [comment]
Please provide the latest launcher log.

**Comment by pophat31** [comment]
How do I know what version of java im running and what do you mean by system specs

**Comment by pophat31** [comment]
and launcher log

**Comment by pophat31** [comment]
You go into launcher options and press open logs right? if so do I copy every thing in the notepads and give them to you?

**Comment by The-1-7-10-Pack** [comment]
Copy the latest log to there: http://paste.ubuntu.com/

**Comment by pophat31** [comment]
k I went there and pasted then clicked past now what

**Comment by The-1-7-10-Pack** [comment]
Post a link to there here

**Comment by The-1-7-10-Pack** [comment]
Closed due missing information.
